- app/Http/Controllers/ChallengeController.php
- resources/views/challenge/index.blade.php
DEV - Challenge Page in Greenfield Part 2
> DEV - Challenge Page in Greenfield Part 2

- app/Http/Controllers/ContactFaqController.php
- app/Http/Controllers/HomeController.php
- resources/views/contact/index.blade.php
- resources/views/home.blade.php
Dev - Updated Contact Page Visual (FAQs etc)
DEV - Challenge Page in Greenfield Part 2
> FAQ + Challenge

- app/Http/Controllers/ContactFaqController.php
- resources/views/contact/index.blade.php
Dev - Updated Contact Page Visual (FAQs etc)
> Dev - Updated Contact Page Visual (FAQs etc)

- app/Http/Controllers/BankDepositFormController.php
> Admin: Calendar Year missing in the Event Pledge List [jp-bugfix-0001]

- app/Models/PledgeHistorySummary.php
- database/seeders/SettingsSeeder.php
https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FS6Y8rfJc-0S_Jv1ltJodBWUAEH78%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D
> Volunteering dashboard gives Exception error when loaded

- app/Http/Requests/AnnualCampaignRequest.php
- app/Http/Requests/DonateNowPledgeRequest.php
- app/Http/Requests/DonateNowRequest.php
- app/Http/Requests/SpecialCampaignPledgeRequest.php
- app/Http/Requests/SpecialCampaignRequest.php
- app/Models/PledgeHistorySummary.php
https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FS6Y8rfJc-0S_Jv1ltJodBWUAEH78%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D
> Donations: CRA list - Change validation message for custom amount

- resources/views/donations/partials/pdf.blade.php
James you and I called about this ticket, format for pdf follows donation history
> S40(05) Donations: Missing charity names from Export Summary [PG-0001]

- app/Http/Controllers/BankDepositFormController.php
[Teams](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FhiTcoLTXY0ScNZY7EubR_GUAK505%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
[Image 1](https://bcgov.sharepoint.com/teams/02365/Shared%20Documents/Screenshot%202023-05-01%20at%205.56.31%20PM.png?web=1)
[Image 2](https://bcgov.sharepoint.com/teams/02365/Shared%20Documents/Screenshot%202023-05-01%20at%205.56.36%20PM.png?web=1)
Image missing from charity selector view details link
> Include image for fsps PG-bugfix-0006

- app/Console/Commands/ExportPledgesToPSFT.php
Since GF store the emplid with the pledges, so we should sent pledge with emplid to Peoplesoft via ODS instead of GUID.
> S40 Update the GF & PSFT integration -- use emplid instead of GUID [jp-bugfix-0007]

- app/Console/Commands/ExportPledgesToPSFT.php
the following bug fix is required for integration test, add env checking for allowing pass data in non-prod region.
[jp-bugfix-0008](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FIrKxbKC5N0K1adraESOD0GUAN6jL%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D) 
S40 Update the GF & PSFT integration -- use emplid instead of GUID (add env checking for passing data in non-prod region)
> Pull request for TEST region migration -Sprint40 May5-Release 0001 (part-2)

- app/Console/Commands/ExportPledgesToPSFT.php
Add env checking for passing data to Peoplesoft in non-prod region 
[jp-bugfix-0008](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FIrKxbKC5N0K1adraESOD0GUAN6jL%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
S40 Update the GF & PSFT integration -- use emplid instead of GUID (add env checking for passing data in non-prod region)
> S40 Update the GF & PSFT integration -- use emplid instead of GUID [jp-bugfix-0008]

- resources/views/annual-campaign/wizard.blade.php
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FLoMOv6zmH0eqgS13GU-SAmUAPido%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
Information bar missing beneath regional charity pool Step 2 selection.
> Donations FSP: Information Bar missing PG-bugfix-0015

- app/Http/Controllers/BankDepositFormController.php
- resources/views/volunteering/partials/add-event-js.blade.php
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FEvbvTRo5LkOBdg-5JV3hfWUABlw_%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D
Add File mask to controller validation. It is not possible to edit the formData object in js to remove files the user dropped and removed. Files that are not part of the submission need to be removed on the server.
[Why remove files on the server?](https://stackoverflow.com/questions/21443553/how-to-remove-value-from- …
> Volunteer: e-form File upload lets user attach all types of file

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
Additional change :  performance tuning on command UpdateEligibleEmployeeSnapshot
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d% …
> S40(09) DEV - Daily Campaign Update - Part 2 [jp-0001] 

- resources/views/annual-campaign/partials/choose-charity.blade.php
- resources/views/annual-campaign/partials/pools.blade.php
- resources/views/annual-campaign/wizard.blade.php
> Donations FSP: Information Bar missing

- app/Console/Commands/UpdateDailyCampaign.php
- database/migrations/2023_05_10_080840_modify_daily_campaign_view.php
Additional change : performance tuning on custom view 
> S40(09) DEV - Daily Campaign Update - Part 2 [jp-0001] Performance tuning

- app/Console/Commands/UpdateDailyCampaign.php
- app/Http/Controllers/ChallengeController.php
Additional change : update join statement
> S40(09) DEV - Daily Campaign Update - Part 2 [jp-0001]

- app/Console/Commands/UpdateDailyCampaign.php
- app/Exports/DailyCampaignByBUExport.php
- app/Exports/DailyCampaignByDeptExport.php
- app/Exports/DailyCampaignByRegionExport.php
- app/Http/Controllers/ChallengeController.php
- app/Models/DailyCampaignView.php
- database/migrations/2023_05_10_080840_modify_daily_campaign_view.php
**Since this project was partial mgrated by Paul's project accidentally on 2 days ago, I have to migrate the rest of the latest changes to TEST region otherwise, something could break.**
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboa …
> S40(09) DEV - Daily Campaign Update - Part 2 [jp-0001] - Test migration - May 12 Sprint 41

- resources/views/donations/index.blade.php
- resources/views/donations/partials/learn-more-modal.blade.php
Fixed the addition finding reported on May 12 -- I have seen one more issue here when we play the youtube video and close the PECSF slides modal, the video still keeps playing in the background.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FhEkLqcXZAUyjRO0zGXtYxmUAIQIQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> TEST migration -- s41(16) PECSF slides - Pause Youtube video when user navigate to next page [jp-bugfix-0011]

- resources/views/annual-campaign/wizard.blade.php
Issue: The pledge button is not responding sometimes: 
I also figured out that the issue has something to do with the distribution when changed 
If we wont change the distribution then the button is responding 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FBYII_4p8O0uzWkYv2ExmeGUAEQov%22%7D)
> Donations: Pledge button does not respond [jp-bugfix-0014]

- resources/views/donations/index.blade.php
Donations: Active campaign typo error
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FjA_DQUXxnk-qCpibhGXYXGUAPsyY%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> PG-bugfix-0024 | Donations: Active campaign typo error

- resources/views/donate/partials/choose-charity.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
[Ticket 1](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FEvbvTRo5LkOBdg-5JV3hfWUABlw_%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
[Ticket 2](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists …
> PG-bugfix-0022 | s41(13) Volunteer: e-form File upload lets user attach all types of file

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
[Maintain Event Pledges Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F3WzLf06FdECUqghkAYTZ7WUAIesb%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> S40(02) Dev - Maintain Event Pledges

- resources/views/annual-campaign/partials/pools.blade.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donate-now/partials/method-selection.blade.php
- resources/views/donate-now/partials/regional-pool.blade.php
- resources/views/donate/start.blade.php
- resources/views/special-campaign/partials/special-campaign.blade.php
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FAY-Sndhu4kaxXlMIx-zMKWUACERt%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
>  Donate now: Text alignment in blue banner

- resources/views/donate-now/wizard.blade.php
Ticket related to : s41(20) Browser Back button control on Annual Campaign page [jp-bugfix-0015]
We have added browser back button control to pages in annual campaign. 
Lets add the same logic to pages in the Donate now flow.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FrbmwQUkpA0Sif0qdwO2d22UAIMGK%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> Donate now: Browser Back button control [jp-bugfix-0016]

- app/Console/Commands/ExportDatabaseToBI.php
- app/Console/Commands/ExportPledgesToPSFT.php
- app/Console/Commands/ImportCities.php
- app/Console/Commands/ImportDepartments.php
- app/Console/Commands/ImportEmployeeJob.php
- app/Console/Commands/ImportNonGovPledgeHistory.php
- app/Console/Commands/ImportPayCalendar.php
- app/Console/Commands/ImportPledgeHistory.php
From MNP walkthrough of the interface process and the scheduled job run for the API call from ODS, the status of the job run is stored in Greenfield, and no notification is sent when the job run fails.
Schedule Job Audits logs cover import/export.
Additional changes for handling invalid user id and password exception.
[ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fixaf9A6LEkmA0OymF8HK8GUAFAIA%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D …
> Dev - System Notification in the Event of Data Interface Errors [jp-0002]

- app/Http/Requests/CRACharityRequest.php
- app/Imports/CharitiesImport.php
- app/Jobs/CharitiesExportJob.php
- app/Models/Charity.php
- app/Models/CharityStaging.php
- database/migrations/2023_05_31_080937_create_charity_stagings_table.php
- resources/views/admin-campaign/charities/index.blade.php
- resources/views/admin-campaign/charities/partials/model-edit.blade.php
Addition Improvements:
1) the export csv file should has created_at and updated_at columns
2) Allow administrator to update the charity status incluide the status 'No-CRA-match' or 'Pending-Dissolution'
3) during the import process, change the charity status to 'No-CRA-match' when not found in the inbound file
4) skip to update the status on the charity with status 'Pending-Dissolution'
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FGMcZ8107hECxLalIxZMjiWUAPivL%22%2C%22channe …
> s41(08) Testing - CRA list Upload [jp-bugfix-0009] additional chages

- app/Imports/CharitiesImport.php
Fix error "Exception: ErrorException: Attempt to read property "charity_status" on null in C:\Users\T904598\Sites\PECSF\app\Imports\CharitiesImport.php:80" 
> s41(08) Testing - CRA list Upload [jp-bugfix-0009] fix import error issue

- app/Exports/PledgeCharitiesExport.php
- app/Exports/PledgesExport.php
- app/Http/Controllers/Admin/CRACharityReportController.php
- app/Http/Controllers/Admin/PledgeCharityReportController.php
- app/Http/Controllers/Admin/PledgeReportController.php
- app/Jobs/CharitiesExportJob.php
Per test result, modify the "Annual and Event Pledges" export program. And also add the clean up procedure for clean up the  output file and taging tables.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FvWp7BiYVJEe5OqbQxIKZLWUAIT0p%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> S40 (01) DEV - Admin report list - Pledges and event [jp-bugfix-0018]

- resources/views/home.blade.php
Enhancement on the homepage, display the selection as a tiles.
Rewrite the home page, remove all non-standard and jaravscripts.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FQXp8DkhxVEKZWfWNb07dB2UAJf42%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> Dev - Homepage Alignment [jp-bugfix-0019] 2nd version

- app/Imports/CharitiesImport.php
Improve the program to assign created_by and updated_by info
> s41(08) Testing - CRA list Upload [jp-bugfix-0009] improve to assign created_by and updated_by info

- app/Imports/CharitiesImport.php
Improve the program to assign created_by and updated_by info
> Test Migration s41(08) Testing - CRA list Upload [jp-bugfix-0009]

- app/Models/Charity.php
Fix duplicate status 'No-CRA-match' on dropdown box.
> s41(08) Testing - CRA list Upload [jp-bugfix-0009] fix bug on duplicate status on dropdown box

- app/Http/Controllers/HomeController.php
- resources/views/donations/index.blade.php
- resources/views/donations/partials/learn-more-modal.blade.php
- resources/views/home.blade.php
Enhancement on the homepage, display the selection as a tiles.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FQXp8DkhxVEKZWfWNb07dB2UAJf42%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> TEST Region Migration - Homepage Alignment [jp-bugfix-0019] 3rd version 

- app/Http/Controllers/Admin/CharityListMaintenanceController.php
- resources/views/admin-campaign/charity-list-maintenance/index.blade.php
New column added 'submitted by' on Charity List Maintenance page
> s41(08) Testing - CRA list Upload [jp-bugfix-0009] new column added 'submitted by' on Charity List Maintenance page

- app/Http/Controllers/Admin/CampaignPledgeController.php
- app/Models/City.php
- app/Models/Pledge.php
- resources/views/admin-pledge/campaign/partials/profile.blade.php
- resources/views/admin-pledge/campaign/partials/summary.blade.php
- resources/views/admin-pledge/campaign/wizard.blade.php
- Use city to populate region
- Use org to populate BU for non-government orgs
[Ticket ](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FPR8E8PRCt0-hjaQYUISXS2UAG2S3%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> Dev - PECSF Admin - Maintain EE Enhancement - Non-gov [jp-bugfix-0021]

- app/Http/Controllers/HomeController.php
- public/css/app.css
- resources/sass/app.scss
- resources/views/donations/index.blade.php
- resources/views/donations/partials/learn-more-modal.blade.php
- resources/views/home.blade.php
- resources/views/volunteering/partials/organizations.blade.php
- resources/views/volunteering/partials/pagination.blade.php
CRA charities - Search results needs better indication of on what page the users is currently on 
Issue to be fixed at the following places: Donate Now, Donation flow, eForm 
[Ticket ](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FWuT3A2oniUuLMidi3MK48mUAKiap%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> CRA charities - Search results needs better indication of on what page the users is currently on [jp-bugfix-0022]

- public/css/app.css
- resources/sass/app.scss
- resources/views/volunteering/partials/organizations.blade.php
- resources/views/volunteering/partials/pagination.blade.php
CRA charities - Search results needs better indication of on what page the users is currently on
Issue to be fixed at the following places: Donate Now, Donation flow, eForm
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FWuT3A2oniUuLMidi3MK48mUAKiap%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [TEST migration] CRA charities - Search results needs better indication of on what page the users is currently on [jp-bugfix-0022] 

- app/Console/Commands/ExportDatabaseToBI.php
- app/Console/Commands/ExportPledgesToPSFT.php
- app/Console/Commands/ImportDepartments.php
- app/Console/Commands/ImportEmployeeJob.php
- app/Console/Commands/ImportNonGovPledgeHistory.php
- app/Console/Commands/ImportPayCalendar.php
- app/Console/Commands/ImportPledgeHistory.php
- app/Console/Commands/SyncUserProfile.php
- app/Console/Commands/UpdateDailyCampaign.php
- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Console/Kernel.php
Jun 20 - Daily batch was failed with the following error
SQLSTATE[HY000]: General error: 126 Incorrect key file for table './pecsf/non_gov_pledge_histories.MYI'; try to repair it (SQL: delete from non_gov_pledge_histories where yearcd = 2022)
This is cause by too many log data update on database.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F5gg98Ij0xEW-Glxp_QalKmUAHT_R%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [Test migration] Dev - Improve daily batch process to reduce database update [jp-bugfix-0025]

- resources/views/admin-pledge/event/index.blade.php
Discuss with FMO team, and should standardize the event pledge maintenance listimg page with better search and listing with pagination.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FGwHRjti1GUyNhtP2fENYFWUAFQ3x%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> Admin: Maintain Event Pledges Search Fields Enhancement [jp-bugfix-0026] 

- app/Http/Controllers/Admin/CharityListMaintenanceController.php
- app/Models/Charity.php
- resources/views/admin-campaign/charity-list-maintenance/index.blade.php
New column added 'submitted by' on Charity List Maintenance page
> [Test Migration] s41(08) Testing - CRA list Upload [jp-bugfix-0009] new column added 'submitted by' on Charity List Maintenance page

- resources/views/admin-pledge/event/partials/model-show.blade.php
Discuss with FMO team, and should standardize the event pledge maintenance listimg page with better search and listing with pagination.
Addition change: Left alignment on amount field
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FGwHRjti1GUyNhtP2fENYFWUAFQ3x%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> Admin: Maintain Event Pledges Search Fields Enhancement [jp-bugfix-0026] -- left alignment on amount field

- app/Http/Controllers/Admin/MaintainEventPledgeController.php
Discuss with FMO team, and should standardize the event pledge maintenance listimg page with better search and listing with pagination.
Addition Change: fix bug on the emplid search field
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FGwHRjti1GUyNhtP2fENYFWUAFQ3x%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> Admin: Maintain Event Pledges Search Fields Enhancement [jp-bugfix-0026]

- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- resources/views/admin-pledge/event/index.blade.php
- resources/views/admin-pledge/event/partials/model-show.blade.php
Discuss with FMO team, and should standardize the event pledge maintenance listimg page with better search and listing with pagination.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FGwHRjti1GUyNhtP2fENYFWUAFQ3x%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [Test Migration] Admin: Maintain Event Pledges Search Fields Enhancement [jp-bugfix-0026]

- app/Console/Commands/UpdateDailyCampaign.php
- app/Http/Controllers/ChallengeController.php
- app/Models/DailyCampaign.php
- app/Models/DailyCampaignView.php
- database/migrations/2023_06_27_104200_add_rank_in_daily_campaigns_table.php
- resources/views/challenge/index.blade.php
Additional change : performance improvement (require migrate after deployed)
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thr …
> S40(09) DEV - Daily Campaign Update - Part 2 (31 & 32 improvements)

- app/Http/Controllers/Admin/CampaignPledgeController.php
- resources/views/admin-pledge/campaign/index.blade.php
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F5DCmHERPDk6ETW7K6lo80mUAEphU%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [Test Migration] Admin: Create new pledge displays incorrect number for custom bi-weekly amount on summary page [jp-bugfix-0028]

- app/Console/Commands/UpdateDailyCampaign.php
- app/Http/Controllers/ChallengeController.php
Additional change : performance improvement
> S40(09) DEV - Daily Campaign Update - Part 2 (33 & 34 performance improvements)

- app/Imports/CharitiesImport.php
> [jp-bugfix-0030] Dev - Avoid too many log update during the import charities process

- app/Console/Commands/ImportEmployeeJob.php
- app/Console/Commands/UpdateDailyCampaign.php
- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Http/Controllers/ChallengeController.php
- app/Models/DailyCampaign.php
- app/Models/DailyCampaignView.php
- database/migrations/2023_06_23_133228_modify_4th_daily_campaign_view.php
- database/migrations/2023_06_26_135928_modify_5th_daily_campaign_view.php
- database/migrations/2023_06_27_104200_add_rank_in_daily_campaigns_table.php
- resources/views/challenge/index.blade.php
- resources/views/system-security/users/index.blade.php
To migrate the latest check of the challenge page to TEST region.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%2 …
> [Test Migration] S40(09) DEV - Daily Campaign Update - Part 2

- package.json
This is a adhoc deployment to verify the Laravel 9 upgrade on openshift platform.
Addition change:  resolve sweetalert2 security warning by cap the version"
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FmDwPcRcyo0OM3o1QFwDhYGUAGgDU%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [Adhoc Production Migration] Upgrade 883 to 952

- app/Console/Commands/SyncUserProfile.php
- app/Http/Controllers/System/UserMaintenanceController.php
Right now, any users who is not a part of the team can access the environment if they have the site of that environment which can become a threat due to security concerns. We want to limit the access of the environments to users from our team and the testing accounts only. Other users must not be able to login.
Environments to be blocked:
Dev
Test
Prod
Test accounts:
Name EmplID login ID Login Password idir
K Dunn 000422 [employee11@example.com](mailto:employee11@example.com) employee11@123 patdunn
Terry Jones - Admin 000413 [employee12@example.com](mailto:employee12@example.com) employee12@123 tejones
Wendy Vander Kuyl 000743 [employee13@example.com](mailto:employee13@example.com) employee13@123 wmvander
Helene Beauchesne 000749 [employee14@example.com](mailto:employee14@example.com) …
> [TEST migration] [jp-bugfix-0032] Lock users from using the environments

- app/Http/Controllers/System/SystemSettingController.php
- resources/views/vendor/adminlte/auth/login.blade.php
Right now, any users who is not a part of the team can access the environment if they have the site of that environment which can become a threat due to security concerns. We want to limit the access of the environments to users from our team and the testing accounts only. Other users must not be able to login.
Environments to be blocked:
Dev
Test
Prod
Test accounts:
Name EmplID login ID Login Password idir
K Dunn 000422 [employee11@example.com](mailto:employee11@example.com) employee11@123 patdunn
Terry Jones - Admin 000413 [employee12@example.com](mailto:employee12@example.com) employee12@123 tejones
Wendy Vander Kuyl 000743 [employee13@example.com](mailto:employee13@example.com) employee13@123 wmvander
Helene Beauchesne 000749 [employee14@example.com](mailto:employee14@example.com) …
> [jp-0005] Enable/Disable user signon during system maintenance (2nd minor changes)

- app/Http/Controllers/Auth/KeycloakLoginController.php
- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/System/SystemSettingController.php
- app/Models/Setting.php
- config/adminlte.php
- database/migrations/2023_06_29_140611_add_lockdown_fields_in_settings_table.php
- resources/views/errors/503.blade.php
- resources/views/system-security/lockdown/index.blade.php
- resources/views/system-security/partials/tabs.blade.php
- resources/views/system-security/settings/index.blade.php
- resources/views/vendor/adminlte/auth/auth-page.blade.php
- resources/views/vendor/adminlte/auth/login.blade.php
- resources/views/vendor/adminlte/master.blade.php
- routes/web.php
> [Test Migration] [jp-0005] Enable/Disable user signon during system maintenance

- resources/views/admin-pledge/campaign/wizard.blade.php
We need to add/manage the control on the browser Back button as the data can be lost so that when clicked must take the user to the previous page 
1. Maintain EE Pledges -> Create New Pledge: Ad1. d the browser button control to all the steps/pages of the create new pledge 
2. Maintain EE Pledges -> Edit any pledge: Add the browser button control to all the steps/pages of the create new pledge 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/bDqxx_5iJEiU-CxUycBe92UAAC6C?Type=TaskLink&Channel=Link&CreatedTime=638242526508730000)
> [jp-bugfix-0034] Admin: Browser Back Button Control

- composer.lock
- package-lock.json
- resources/views/admin-campaign/business-units/partials/model-create.blade.php
Additional change : Associated Business Unit Code is missing in the creation form.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d …
> S40(09) DEV - Daily Campaign Update - Part 2 (35 - fix business unit creation error) 

- app/Console/Commands/UpdateDailyCampaign.php
- app/Http/Controllers/Admin/ChallengeSummaryMaintenanceController.php
- app/Http/Controllers/ChallengeController.php
- app/Http/Requests/ChallengeSummaryMaintenanceRequest.php
- app/Models/DailyCampaignSummary.php
- app/Models/Setting.php
- database/migrations/2023_07_11_081217_create_daily_campaign_summaries_table.php
- resources/views/admin-campaign/challenge-summary/index.blade.php
- resources/views/admin-campaign/challenge-summary/partials/model-create.blade.php
- resources/views/admin-campaign/challenge-summary/partials/model-edit.blade.php
- resources/views/admin-campaign/challenge-summary/partials/model-show.blade.php
- resources/views/admin-campaign/partials/tabs.blade.php
- resources/views/challenge/daily_campaign.blade.php
- resources/views/challenge/index.blade.php
- routes/web.php
Additional changes : maintenance challenge page total donor and dollars)
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread. …
> S40(09) DEV - Daily Campaign Update - Part 2

- config/adminlte.php
- package-lock.json
- package.json
- public/css/app.css
- public/js/app.js.LICENSE.txt
- public/mix-manifest.json
- resources/views/components/bullet.blade.php
- webpack.mix.js
Laravel-mix-svg-sprite module should be decommissioned since PECSF application doesn't use teh feature -- "this webpack plugin generates a single SVG spritemap containing multiple <symbol> elements from all .svg files in a directory." and also avoid some security warning.
[ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/5lq5hmPvAkSQZx2BokxYH2UAOmsS?Type=TaskLink&Channel=Link&CreatedTime=638247993132880000)
> [jp-bugfix-0036] clean-up -- decommision old module Laravel-mix-svg-sprite

- app/Http/Controllers/System/UserMaintenanceController.php
- resources/views/system-security/users/index.blade.php
Purpose: Need to update the 'User Maintenance Page' to handle the user without emplid and org id
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/pwE8hc6j0ESBtdN0Z4mlZWUAMRGz?Type=TaskLink&Channel=Link&CreatedTime=638248870617070000)
> [jp-bugfix-0037] update 'User Maintenance Page' to handle user without emplid or org id

- app/Http/Controllers/System/UserMaintenanceController.php
- resources/views/system-security/users/index.blade.php
Purpose: Need to update the 'User Maintenance Page' to handle the user without emplid and org id (Special Account who are not PeopleSoft HCM record)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/pwE8hc6j0ESBtdN0Z4mlZWUAMRGz?Type=TaskLink&Channel=Link&CreatedTime=638248870617070000)
> [Test Migration] [jp-bugfix-0037] update 'User Maintenance Page' to handle user without emplid or org id

- app/Http/Controllers/ChallengeController.php
39th change -- search on Organzation name field should not be case sensitive
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thr …
> [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2 

- app/Http/Controllers/ChallengeController.php
- resources/views/challenge/daily_campaign.blade.php
- resources/views/challenge/index.blade.php
> [TEST Migration] [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2

- resources/views/vendor/adminlte/auth/login.blade.php
- routes/web.php
Need to have phpinfo page for troubleshooting and support purpose on difference regions. This is only accessible by admin.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/T1_F2EM6EEir4ftLqTm7fWUALa_K?Type=TaskLink&Channel=Link&CreatedTime=638253201246130000)
> [jp-bugfix-0040] phpinfo page

- resources/views/challenge/index.blade.php
Several area required to enhance for handling the session expiry
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ep8Ham4GKEm2v3yP7eibLmUAPXYg?Type=TaskLink&Channel=Link&CreatedTime=638253160730930000)
> [TEST Migration] [jp-bugfix-0039] S39(15) Manage Session Time out issue

- resources/views/admin-pledge/campaign/index.blade.php
- resources/views/admin-pledge/event/index.blade.php
Programming logic - default to Current year+1 for maintain ee and maintain event.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/whNNtQ8i9UKWpBuRJ_Ne3WUAFjy-?Type=TaskLink&Channel=Link&CreatedTime=638254886923740000)
> [jp-bugfix-0041] Dev - Maintain ee/event auto filters to the most current year

- resources/views/admin-pledge/campaign/index.blade.php
- resources/views/admin-pledge/event/index.blade.php
Programming logic - default to Current year+1 for maintain ee and maintain event.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/whNNtQ8i9UKWpBuRJ_Ne3WUAFjy-?Type=TaskLink&Channel=Link&CreatedTime=638254886923740000)
> (TEST MIGRATION) [jp-bugfix-0041] Dev - Maintain ee/event auto filters to the most current year

- app/AuditResolvers/UserAgentResolver.php
- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/AnnualCampaignController.php
- app/Http/Controllers/Auth/KeycloakLoginController.php
- app/Models/User.php
- composer.json
- composer.lock
- config/audit.php
- resources/views/system-security/auditing/index.blade.php
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/26imtcF-rUKeFAT_5AzigWUAKPbc?Type=TaskLink&Channel=Link&CreatedTime=638258088557360000)
> [jp-bugfix-0042] S39(01) Dev - Auditing capabilities for models, to keep track of changes made to records

- resources/views/admin-pledge/campaign/partials/profile.blade.php
- resources/views/admin-pledge/campaign/show.blade.php
- resources/views/admin-pledge/campaign/wizard.blade.php
Additional change:  show office region on Admin Maintain EE pledge page
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FvWp7BiYVJEe5OqbQxIKZLWUAIT0p%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [jp-bugfix-0018] S40 (01) DEV - Admin report list - Pledges and event pledges

- app/Http/Controllers/Admin/CityRegionInformationController.php
- resources/views/admin-campaign/cities/index.blade.php
- resources/views/admin-campaign/partials/tabs.blade.php
- routes/web.php
Ticket related to : [jp-bugfix-0018] S40 (01) DEV - Admin report list - Pledges and event 
As discussed with James, since region is based on the office city, we can add a foundation table that will display the relation between region and ciry.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/JTZ8O0Dsd06jzg_WjAJkQ2UAOo-h?Type=TaskLink&Channel=Link&CreatedTime=638258343025350000)
> [jp-bugfix-0043] Create a City foundation table to display the relation between city and region

- app/Http/Controllers/Admin/CityRegionInformationController.php
- resources/views/admin-campaign/cities/index.blade.php
- resources/views/admin-campaign/partials/tabs.blade.php
- routes/web.php
Ticket related to : [jp-bugfix-0018] S40 (01) DEV - Admin report list - Pledges and event
As discussed with James, since region is based on the office city, we can add a foundation table that will display the relation between region and ciry.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/JTZ8O0Dsd06jzg_WjAJkQ2UAOo-h?Type=TaskLink&Channel=Link&CreatedTime=638258343025350000)
> (TEST MIGRATION) [jp-bugfix-0043] Create a City foundation table to display the relationship between city and region

- database/seeders/EmployeeJobInactive2021_2023JSON.php
- database/seeders/EmployeeJobJSONSeeder.php
- database/seeders/EmployeeJobMissing.php
- database/seeders/EmployeeJobMissing255JSON.php
There are some missig employee job data from BI, they have Pledge History from BI. Justin provides the employee job data in excel spreadhseet format for loading into PECSF.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/tlbT8qvyck2LT6FpCGMjjWUAICSi?Type=TaskLink&Channel=Link&CreatedTime=638258341844310000)
> (TEST MIGRATION) [jp-bugfix-0044] Loading 2021-2023 Inactive employee job data into PECSF

- app/Http/Controllers/System/LogViewerController.php
- app/Http/Controllers/System/UploadFileController.php
- database/seeders/RolePermissionTableSeeder.php
- resources/views/system-security/log-files/index.blade.php
- routes/web.php
A new role called 'sysadmin' created to access some sensitive information.
> [jp-0007] New role sysadmin to exclude some functions from admin

- app/Exports/PledgesExport.php
- resources/views/admin-pledge/event/index.blade.php
Additional Change: Employee name missing on report and add it on the idnex page
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FvWp7BiYVJEe5OqbQxIKZLWUAIT0p%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [jp-bugfix-0018] S40 (01) DEV - Admin report list - Pledges and event pledges 

- app/Http/Controllers/ChallengeController.php
- app/Models/DailyCampaignView.php
- database/migrations/2023_07_31_200432_modify7th_daily_campaign_view.php
- storage/debugbar/.gitignore
(44th -- apply combine and split BU logic on pledges)
> [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2

- app/Http/Controllers/Admin/EligibleEmployeeReportController.php
- resources/views/admin-report/eligible-employee/index.blade.php
- resources/views/admin-report/pledge-charities/index.blade.php
- resources/views/admin-report/pledges/index.blade.php
Programming - Current year+1 for
Annual pledges and events
Amount by charity
Eligible employee
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/TlUnwxmo00aYo1MCdAilxWUAH2wW?Type=TaskLink&Channel=Link&CreatedTime=638264263598870000)
> (TEST MIGRATION) [jp-bugfix-0046] Dev - Reports - Calendar Year option auto filters to the most current year

- app/Console/Commands/SystemCleanUp.php
- app/Console/Kernel.php
Develop a new schedule process to clean up external files (log and import files)
1) Uploaded Charities import file and log files
2) Laravel Log file 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fe5A720iQTkKdFPJgLVluSmUAMnoU%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [jp-0009] Develope a new schedule process to clean up external files (log and import files)

- app/Console/Commands/SystemCleanUp.php
- app/Console/Kernel.php
Develop a new schedule process to clean up external files (log and import files)
Uploaded Charities import file and log files
Laravel Log file
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fe5A720iQTkKdFPJgLVluSmUAMnoU%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> (TEST MIGRATION) [jp-0009] Develope a new schedule process to clean up external files (log and import files)

- app/Http/Controllers/Admin/ChallengePageDataReportController.php
- resources/views/admin-report/challenge-page-data/index.blade.php
- resources/views/admin-report/partials/tabs.blade.php
- routes/web.php
New page build under administration > Reporting
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/SFLLYc_9Hk66emns4kBvRmUAN-UG?Type=TaskLink&Channel=Link&CreatedTime=638266732621250000)
> [jp-0011] Dev - Admin report list - Challenge page report

- app/Http/Controllers/Admin/ChallengePageDataReportController.php
- resources/views/admin-report/challenge-page-data/index.blade.php
Additional Change:  Column "Business Unit Code" added 
New page build under administration > Reporting
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/SFLLYc_9Hk66emns4kBvRmUAN-UG?Type=TaskLink&Channel=Link&CreatedTime=638266732621250000)
> [jp-0011] Dev - Admin report list - Challenge page report 

- app/Console/Commands/UpdateDailyCampaign.php
- app/Exports/DailyCampaignByBUExport.php
- app/Exports/DailyCampaignByDeptExport.php
- app/Exports/DailyCampaignByRegionExport.php
- app/Http/Controllers/Admin/ChallengeSettingsController.php
- app/Http/Controllers/ChallengeController.php
- app/Models/DailyCampaign.php
- app/Models/Setting.php
- database/migrations/2023_08_03_091830_add_processed_final_dates_in_settings_table.php
- database/migrations/2023_08_03_152933_modify_10th_daily_campaign_view.php
- resources/views/admin-campaign/challenge/index.blade.php
- routes/web.php
Changes from 47th & 48th (Fix Campaign Dept report issue)
>  [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2

- app/Http/Controllers/Admin/ChallengePageDataReportController.php
- resources/views/admin-report/challenge-page-data/index.blade.php
- resources/views/admin-report/partials/tabs.blade.php
- routes/web.php
New page build under administration > Reporting
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/SFLLYc_9Hk66emns4kBvRmUAN-UG?Type=TaskLink&Channel=Link&CreatedTime=638266732621250000)
> (TEST MIGRATION) [jp-0011] Dev - Admin report list - Challenge page report 

- app/Console/Commands/UpdateDailyCampaign.php
- app/Exports/DailyCampaignByBUExport.php
- app/Exports/DailyCampaignByDeptExport.php
- app/Exports/DailyCampaignByRegionExport.php
- app/Http/Controllers/Admin/ChallengeSettingsController.php
- app/Http/Controllers/ChallengeController.php
- app/Models/DailyCampaign.php
- app/Models/Setting.php
- database/migrations/2023_08_03_091830_add_processed_final_dates_in_settings_table.php
- database/migrations/2023_08_03_152933_modify_10th_daily_campaign_view.php
- resources/views/admin-campaign/challenge/index.blade.php
- resources/views/challenge/daily_campaign.blade.php
- routes/web.php
Changes 47 to 50th (multiple tickets)
> (TEST MIGRATION) [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2

- app/Http/Controllers/ChallengeController.php
51st change-- Fixed challenge page history didn't show issue)
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D …
> [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2 (

- app/Http/Controllers/ChallengeController.php
- resources/views/challenge/index.blade.php
Create a new "Participant Rate" Chart on Challenge page (user can select list or chart mode)
[ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Fk_dMJeg1kaWCLIkFcMY4WUAPY1M?Type=TaskLink&Channel=Link&CreatedTime=638267660046270000)
> [jp-0006] Participant Rate Chart on Challenge page 

- app/Http/Controllers/ChallengeController.php
changes : 50 & 51 including( Fixed challenge page history didn't show issue)
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thr …
> (TEST MIGRATION) [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2 

- app/Http/Controllers/System/UploadFileController.php
- resources/views/system-security/upload-files/index.blade.php
Tools for upload backup file on the adminer folder
> [jp-0010] Backup and Restore database on lower regions

- app/Http/Controllers/AnnualCampaignController.php
Change: update the program to handle the refresh button clicked scenario
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/TRPuqgiynEakSLKDIL0R9GUAFBcU?Type=TaskLink&Channel=Link&CreatedTime=638271920383460000)
> (TEST MIGRATION) [jp-bugfix-0049] Refreshing a page when duplicating pledge gives MethodNotAllowedHttpException error

- resources/views/annual-campaign/wizard.blade.php
Fix the program bug.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/MARGAY6YzEeUBbHeHqhIAmUAEXVA?Type=TaskLink&Channel=Link&CreatedTime=638272190532040000)
> [jp-bugfix-0051] Duplicating pledge displays a mix-up of step 2

- resources/views/annual-campaign/wizard.blade.php
Fix the program bug.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/MARGAY6YzEeUBbHeHqhIAmUAEXVA?Type=TaskLink&Channel=Link&CreatedTime=638272190532040000)
> (TEST MIGRATION) [jp-bugfix-0051] Duplicating pledge displays a mix-up of step 2

- database/seeders/SampleUsersSeeder.php
- database/seeders/UserTableSeeder.php
For security purpose,  reset the password value in the seed file with the hashed value (security purpose)
> [jp-bugfix-0052] reset the password value in the seed file with the hashed value (security purpose)

- env-dev
Action Required ASAP -- Credential information push by Paul on public Github
> [Test migration] remove sensitive data

- database/seeders/administratorSeeder.php
Addition change request -- assign 136308 to admin group in all regions
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/FRi2zr4KZUa07LqVNsy7oGUAK0vc?Type=TaskLink&Channel=Link&CreatedTime=638273711545340000)
> [jp-bugfix-0052] Reload test accounts on lower regions when clone from Production Backup

- app/Models/User.php
- config/audit.php
Avoid duplicatioin on the tracking, no audit log tracking on the login activites since we have a access log table.
Note: verified on DEV region.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/CgiyWlspgUqJ2hERoprEc2UAAeOl?Type=TaskLink&Channel=Link&CreatedTime=638273760008730000)
> (TEST MIGRATION) [jp-0012]  Exclude the login activities in the audit table

- database/seeders/SampleUsersSeeder.php
- database/seeders/UserTableSeeder.php
- database/seeders/administratorSeeder.php
Addition change request -- assign 136308 to admin group in all regions
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/FRi2zr4KZUa07LqVNsy7oGUAK0vc?Type=TaskLink&Channel=Link&CreatedTime=638273711545340000)
> (TEST MIGRATION) [jp-bugfix-0052] Reload test accounts on lower regions when clone from Production Backup

- public/css/app.css
- resources/sass/app.scss
- resources/views/volunteering/partials/organizations.blade.php
https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FhKeE-JaAn0WWxEXRLVQNm2UAN82I%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D
> (TEST MIGRATION) Center pagination

- app/Http/Controllers/ChallengeController.php
Challenge page: Update Daily campaign report names
> Challenge page: Update Daily campaign report names

- app/Console/Kernel.php
Develop a new schedule process to clean up external files (log and import files)
Additional change - fix typo on kernel.php file.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fe5A720iQTkKdFPJgLVluSmUAMnoU%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> [jp-0009] schedule process to clean up external files (log and import files) 

- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/annual-campaign/partials/choose-charity.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/choose-charity.blade.php
- resources/views/donate/partials/choose-charity-js.blade.php
- resources/views/donate/partials/choose-charity.blade.php
- resources/views/volunteering/partials/form.blade.php
Add a close button and title to the View details modal for the CRA charities and regional Pool of donation 
Reference to be taken from donation history - details modal 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/6skXGienb0-clRQw4VFCjGUAGxQa?Type=TaskLink&Channel=Link&CreatedTime=638284234589930000)
> [jp-0015] Add a close button to View details for CRA charities

- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/annual-campaign/partials/choose-charity.blade.php
- resources/views/annual-campaign/partials/pools.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/choose-charity.blade.php
- resources/views/donate-now/partials/regional-pool.blade.php
- resources/views/donate/partials/choose-charity-js.blade.php
- resources/views/donate/partials/choose-charity.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
Add a close button and title to the View details modal for the CRA charities and regional Pool of donation
Reference to be taken from donation history - details modal
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/6skXGienb0-clRQw4VFCjGUAGxQa?Type=TaskLink&Channel=Link&CreatedTime=638284234589930000)
> (TEST MIGRATION) [jp-0015] Add a close button to View details for CRA charities

- app/Http/Controllers/BankDepositFormController.php
Charity BN# could use for keyword search in the following self-service pages:
1. Annual Campaign pleges
2. Donate Now
3. Event pledges.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/vVucWWM3dk-Gz2cUQwY4XWUALb8O?Type=TaskLink&Channel=Link&CreatedTime=638285053281170000)
> (TEST MIGRATION) [jp-0016] Donations: Search CRA charities with BN#

- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/annual-campaign/partials/choose-charity.blade.php
- resources/views/annual-campaign/partials/pools.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/choose-charity.blade.php
- resources/views/donate-now/partials/regional-pool.blade.php
- resources/views/donate/partials/choose-charity-js.blade.php
- resources/views/donate/partials/choose-charity.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
Status: Ticket approved on MS Team 
Add a close button and title to the View details modal for the CRA charities and regional Pool of donation
Reference to be taken from donation history - details modal
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/6skXGienb0-clRQw4VFCjGUAGxQa?Type=TaskLink&Channel=Link&CreatedTime=638284234589930000)
> (MASTER) [jp-0015] Add a close button to View details for CRA charities 

- app/Http/Controllers/BankDepositFormController.php
Charity BN# could use for keyword search in the following self-service pages:
1. Annual Campaign pleges
2. Donate Now
3. Event pledges.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/vVucWWM3dk-Gz2cUQwY4XWUALb8O?Type=TaskLink&Channel=Link&CreatedTime=638285053281170000)
> (MASTER) [jp-0016] Donations: Search CRA charities with BN#

- app/Http/Controllers/ChallengeController.php
Challenge page: Update Daily campaign report names
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/PpE_LHePxEG9ZISwwEGhm2UAMI_g?Type=TaskLink&Channel=Link&CreatedTime=638285759904100000)
> (MASTER) [jz-bugfix-0001] Challenge page: Update Daily campaign report names

- app/Console/Kernel.php
Develop a new schedule process to clean up external files (log and import files)
Additional change - fix typo on kernel.php file.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fe5A720iQTkKdFPJgLVluSmUAMnoU%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> (MASTER) [jp-0009] Develop a new schedule process to clean up external files (log and import files)

- resources/views/vendor/adminlte/master.blade.php
Per DevOps Team request, implement GTX / Snowplow to track site visitors and provide analytics.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/jmdYB5bark60qCqCfbUuaGUAJ5Va?Type=TaskLink&Channel=Link&CreatedTime=638278028598910000)
> (MATSER) [jp-0014] Implement GTX / Snowplow to track site visitors and provide analytics per DevOps Team request

- app/Http/Controllers/BankDepositFormController.php
- resources/views/annual-campaign/partials/pools.blade.php
- resources/views/donations/partials/learn-more-modal.blade.php
- resources/views/donations/partials/pdf.blade.php
This is what Paul done so far to fix the pdf issue.
> pg-bugfix-0088 Export summary cuts off the last few charities to display out of 10

- resources/views/vendor/adminlte/auth/login.blade.php
Region:Test
Make the "login as administrator" hyperlink also enabled in TEST region to use test signin accouts for testing purpose
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Zq9k5zSB5kGi9TM-we6JA2UACdy6?Type=TaskLink&Channel=Link&CreatedTime=638290049601450000)
> (TEST MIGRATION) [jp-0022] Enable system administrator signon hyperlink for TEST region

- database/seeders/SampleUsersSeeder.php
- database/seeders/UserTableSeeder.php
To reset the test/dummy account password on lower region based on the env variables
SYNC_USER_PROFILE_SECRET=<password>
SYNC_ADMIN_PROFILE_SECRET=<password>
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/emjxdxcHoUmYKphMt7t7UGUADJpz?Type=TaskLink&Channel=Link&CreatedTime=638290072027860000)
> [jp-0023] Reset test user account password on lower regions

- database/seeders/SampleUsersSeeder.php
- database/seeders/UserTableSeeder.php
To reset the test/dummy account password on lower region based on the env variables
SYNC_USER_PROFILE_SECRET=
SYNC_ADMIN_PROFILE_SECRET=
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/emjxdxcHoUmYKphMt7t7UGUADJpz?Type=TaskLink&Channel=Link&CreatedTime=638290072027860000)
> (TEST MIGRATION) [jp-0023] Reset test user account password on lower regions

- app/Http/Controllers/BankDepositFormController.php
As reported by Kristina, the CRA charities list are not sorted. Can we keep the charities sorted at all times?
Aug 18 - Ticket validated on test.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/SpF6Sl1_KEacqbf55IILKGUAJVsv?Type=TaskLink&Channel=Link&CreatedTime=638290132702140000)
> (MASTER) [pg-bugfix-0078] Sort CRA charities

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/donate-now/create-edit.blade.php
- resources/views/annual-campaign/partials/choose-charity.blade.php
- resources/views/donate-now/partials/choose-charity.blade.php
- resources/views/donate/partials/choose-charity.blade.php
Three issues in this ticket
E-form: Choose option Donor choice -> Search by Fund Supported Pool field
1) The Capital FSP is not displaying any charities
2) If we choose FSP East Kootenay or Fraser Valley, we see a blank white screen
3) Choose the option Fund Supported Pool, notice that the Capital pool only shows 2 charities instead of 20 charities.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/hPLpt-5QjUmKpzPamwr_rmUAJ6Uc?Type=TaskLink&Channel=Link&CreatedTime=638290149426390000)
> (MASTER) pg-bugfix-0085 E-form: Search by Fund Supported Pool gives a white space when changing the FSP from the drop-down

- resources/views/vendor/adminlte/auth/login.blade.php
Region:Test
Make the "login as administrator" hyperlink also enabled in TEST region to use test signin accouts for testing purpose
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Zq9k5zSB5kGi9TM-we6JA2UACdy6?Type=TaskLink&Channel=Link&CreatedTime=638290049601450000)
> (MASTER) [jp-0022] Enable system administrator signon hyperlink for TEST region

- database/seeders/SampleUsersSeeder.php
- database/seeders/UserTableSeeder.php
To reset the test/dummy account password on lower region based on the env variables
SYNC_USER_PROFILE_SECRET=
SYNC_ADMIN_PROFILE_SECRET=
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/emjxdxcHoUmYKphMt7t7UGUADJpz?Type=TaskLink&Channel=Link&CreatedTime=638290072027860000)
> (MASTER) [jp-0023] Reset test user account password on lower regions

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/donate-now/partials/pool-detail.blade.php
- resources/views/volunteering/partials/form.blade.php
[dev migrate][jz-004] Admin: Edit e-form bug fixes and enhancements
> [dev migrate][jz-004] Admin: Edit e-form bug fixes and enhancements

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/donate-now/partials/pool-detail.blade.php
- resources/views/volunteering/partials/form.blade.php
[jz-004] Admin: Edit e-form bug fixes and enhancements
> [jz-004] Admin: Edit e-form bug fixes and enhancements

- resources/views/vendor/adminlte/auth/login.blade.php
[jz-005] align left for login content
> [jz-005] align left for login content

- resources/views/donations/index.blade.php
[jz-007](Need Number) Donation History - remove sentence in light blue area (how to update)
> [jz-007](Need Number) Donation History - remove sentence in light blue area (how to update)

- resources/views/annual-campaign/partials/pool-detail.blade.php
- resources/views/donate-now/partials/pool-detail.blade.php
- resources/views/donate/partials/pool-detail.blade.php
[jz-003]DEV - FSP description window - charity logo and name
> [jz-003]DEV - FSP description window - charity logo and name

- resources/views/admin-pledge/campaign/wizard.blade.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donate-now/wizard.blade.php
[jp-0026] Browser back button displays blank screen when clicked while modal is open
> [jp-0026] Browser back button displays blank screen when clicked while modal is open

- app/Exports/DailyCampaignByDeptExport.php
[jz-006] Daily Campaign Update - Dept report - Add organization subtotal row
> [jz-006] Daily Campaign Update - Dept report - Add organization subtotal row

- config/adminlte.php
[jz-005]PG-feature-0010 Update the PECSF logo
> [jz-005]PG-feature-0010 Update the PECSF logo

- app/Exports/DailyCampaignByDeptExport.php
- app/Http/Controllers/Admin/FundSupportedPoolController.php
- app/Http/Controllers/AnnualCampaignController.php
- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/campaign/wizard.blade.php
- resources/views/annual-campaign/partials/add-charity.blade.php
- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/annual-campaign/partials/choose-charity.blade.php
- resources/views/annual-campaign/partials/pool-detail.blade.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donate-now/partials/add-charity.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/choose-charity.blade.php
- resources/views/donate-now/partials/pool-detail.blade.php
- resources/views/donate-now/wizard.blade.php
- resources/views/donate/partials/choose-charity-js.blade.php
- resources/views/donate/partials/choose-charity.blade.php
- resources/views/donate/partials/pool-detail.blade.php
- resources/views/donations/index.blade.php
- resources/views/volunteering/partials/add-organization.blade.php
- resources/views/volunteering/partials/organizations.blade.php
[jz-008]CRA charity list option - FSP selection has program pre-filled
> [jz-008]CRA charity list option - FSP selection has program pre-filled

- app/Http/Controllers/BankDepositFormController.php
fix for the the test failed: Entered 2 one time donations for same employee.  No warning came up indicating there had been previous donations for that employee, nor did it force you to assign a unique PECSF ID.
> [TEST][jz-004] Admin: Edit e-form bug fixes and enhancements

- resources/views/donations/partials/learn-more-modal.blade.php
This changes are for 2 tickets :
[jp-0028] Dev - How to donate slide updates (UAT Feedback) | [Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FXyhCetbJ2k-CAO3ahxlJvmUAJmKV%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
[jp-0028] 'Why Donate to PECSF' slides enhancements | [Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1 …
> TEST MIGRATION [jp-0028] Dev - How to donate slide updates (UAT Feedback) 

- app/Http/Controllers/Admin/FundSupportedPoolController.php
- app/Http/Controllers/AnnualCampaignController.php
- app/Http/Controllers/DonateNowController.php
- resources/views/admin-campaign/fund-supported-pools/edit.blade.php
- resources/views/admin-campaign/fund-supported-pools/partials/edit-pool-charity.blade.php
- resources/views/admin-campaign/fund-supported-pools/show.blade.php
Pool detail in Annual Campaign
Summary Page in Annual Campaign
Pool detail in Donate Now
Pool detail in eForm
Pool detail in eForm (Administration)
Pool detail in submission Queue (Administration)
Fund Support Pool maintainenance page
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7BD5TafWSU-i7I6lzklcCWUAFjNl?Type=TaskLink&Channel=Link&CreatedTime=638320512603020000)
> TEST MIGRATION [jp-0030] Alphabetize FSP entries by charity name

- resources/views/donations/partials/learn-more-modal.blade.php
Oct 13 - Steffi and James discussed some improvements to the ticket (first slide especially) and decided to include the first slide numbering with other slides, so slide 1 of 9. And add a 'Cancel" or Back button so that the slide text can be displayed in the centre.
Putting ticket back to in progress
Oct-13 - Additional Changes :
a. Page start from 1 and up to line
b. Add 'close' button on the first page
c. the page index read 'Page n of 9'
This changes are for 2 tickets :
[jp-0028] Dev - How to donate slide updates (UAT Feedback) | [Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams …
> (TEST MIGRATION) [jp-0028] Dev - How to donate slide updates (UAT Feedback)

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/admin-pledge/submission-queue/partials/result_row.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
1.  removed hard code "checked" attribute from radio charity_selection_1
2. add "none" as default value of select.  to avoid undefined error.
> Jz 004 admin edit e form bug fixes and enhancements

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/admin-pledge/submission-queue/partials/result_row.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
1. removed hard code "checked" attribute from radio charity_selection_1
2. add "none" as default value of select. to avoid undefined error.
> [TEST MIGRAGE][Jz 004] admin edit e form bug fixes and enhancements

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/admin-pledge/submission-queue/partials/reginal-pool.blade.php
- resources/views/admin-pledge/submission-queue/partials/result_row.blade.php
- resources/views/donate-now/partials/pool-detail.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
1. removed hard code "checked" attribute from radio charity_selection_1
2. add "none" as default value of select. to avoid undefined error.
> [MATER MIGRATE][Jz-004] admin edit e form bug fixes and enhancements

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/partials/add-organization.blade.php
solve the following issues
1. charities can not be deleted and updated
2. Specific Community Or Initiative (Optional) can not be displayed and saved.
3. in some case form can not be submitted by error message "sub type" is required
> [jz-009]Admin -> Event Submission Queue issues

- resources/views/annual-campaign/partials/add-charity.blade.php
the root cause for this issue is the value used for display optional name is wrong
> [jz-010]When making changes to pledge with CRA charities, the Specific Community Or Initiative (Optional) field becomes disabled

- resources/views/annual-campaign/partials/add-charity.blade.php
the root cause for this issue is the value used for display optional name is wrong
> [TEST MIGRATE][jz-010]When making changes to pledge with CRA charities, the Specific Community Or Initiative (Optional) field becomes disabled

- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
added 'none' as default value for dropdown list sub type
> [TEST MIGRATE][jz-011]Volunteering -> E-form -> Changing event type from Fundraiser/Gaming to Cheque/Cheque throws error while submitting

- resources/views/admin-pledge/create/index.blade.php
- resources/views/volunteering/forms.blade.php
1. fix for closing modal in Volunteering -> e-form 
2. fix for closing modal in Admin -> Create new event pledge
> [jz-012]E-form -> FSP -> View details modal -> Close buttons not functioning

- resources/views/admin-pledge/create/index.blade.php
- resources/views/volunteering/forms.blade.php
1. fix for closing modal in Volunteering -> e-form
2. fix for closing modal in Admin -> Create new event pledge
> [TEST MIGRATION][jz-012]E-form -> FSP -> View details modal -> Close buttons not functioning

- resources/views/annual-campaign/partials/add-charity.blade.php
- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate/partials/choose-charity-js.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
1. Specific Community Or Initiative (Optional) is enabled for the flexibility
Annual campaign
Duplicate pledge
Donate now
E-form(create/edit)
2. Set default value for sub type to avoid undefined error
3. remove the readonly attribute from the input
> (MASTER) [jz-010]When making changes to pledge with CRA charities, the Specific Community Or Initiative (Optional) field becomes disabled 

- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
added 'none' as default value for dropdown list sub type
> (MASTER) [jz-011]Volunteering -> E-form -> Changing event type from Fundraiser/Gaming to Cheque/Cheque throws error while submitting 

- resources/views/admin-pledge/create/index.blade.php
- resources/views/volunteering/forms.blade.php
1) fix for closing modal in Volunteering -> e-form
2) fix for closing modal in Admin -> Create new event pledge
> (MASTER) [jz-012]E-form -> FSP -> View details modal -> Close buttons not functioning 

- app/Http/Controllers/BankDepositFormController.php
issue addressed.  root cause is when switch to fsp the charity items are not be cleaned.
> [jz-014]Event pledge: Admin editing the event pledge form CRA to FSP does not get saved

- app/Http/Controllers/BankDepositFormController.php
issue addressed. root cause is when switch to fsp the charity items are not be cleaned.
> [TEST MIGRATE][jz-014]Event pledge: Admin editing the event pledge form CRA to FSP does not get saved

- app/Console/Commands/ImportPledgeHistory.php
Per sugguestion from Patrick and Warren, to reduce the batch size and increase the timeout to test out
> [jp-0041] command:ImportPledgeHistory Failed with timeout issue

- app/Console/Commands/ImportPledgeHistory.php
Per sugguestion from Patrick and Warren, to reduce the batch size and increase the timeout to test out
> (TEST MIGRATION) [jp-0041] command:ImportPledgeHistory Failied with timeout issue

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
sorted the charities by donation percentage so that easy for checking.
> [jz-015]Event Pledge: Program name for entered charities disappears

- app/Models/CampaignYear.php
Oct 26 - confirmation from Nancy --
For the campaign pledges, the option for users to do updates should finish 11:59 November 30. We'll want pledges to be sent to PeopleSoft on December 1 (capturing all data entered as of 11:59 November 30).
Action required -- remove 14 days grace period rule
> [jp-0043] Update export to PSFT interface program, sent out the day after end date in campaign period

- app/Http/Controllers/Admin/CampaignPledgeController.php
Root cause: undefined variable for Non-Gov pledge. fixed by assign nul value on both variable deptid and dept_name,
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fb60NIdmwpkeHotKIZvqLI2UAPpJJ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
> (TEST MIGRATION) [jp-0042] Dev - Error admin entering LDB(Non-Gov) pledge

- app/Models/CampaignYear.php
Oct 26 - confirmation from Nancy --
For the campaign pledges, the option for users to do updates should finish 11:59 November 30. We'll want pledges to be sent to PeopleSoft on December 1 (capturing all data entered as of 11:59 November 30).
Action required -- remove 14 days grace period rule
> (TEST MIGRATION) [jp-0043] Update export to PSFT interface program, sent out the day after end date of the campaign period

- app/Console/Commands/ImportPledgeHistory.php
Per sugguestion from Patrick and Warren, to reduce the batch size and increase the timeout to test out
> (MASTER) [jp-0041] command:ImportPledgeHistory Failied with timeout issue

- app/Http/Controllers/BankDepositFormController.php
root cause is because of the wrong index using in the array looping for the form submit.
> (MASTER) [jz-013]All of the entered charities disappears when event pledge is edited and new CRA charities are added

- app/Http/Controllers/BankDepositFormController.php
1) disable the require validation for sub type and set a default value "false" for it
2) fix for the default error of sub types
> (MASTER) [jz-014]Event pledge: Admin editing the event pledge form CRA to FSP does not get saved

- app/Jobs/CharitiesExportJob.php
Reference ticket - DEV - PECSF Admin Section - Maintain Charity List - Part 3 - Sprint 28
Oct 5 - Meet with FMO team and the sample vendor file provided. 2 additional field require for storing phone# and fax#. Per Tara, the row with the vendor id equal to "remit vendor id" will used for update the fields
use_alt_address
alt_address1 // Column L -- Address 1
alt_address2 // Column M -- Address 2  
alt_city // Column P -- City       
alt_province // Column X -- State
alt_country  // Column K -- Country
alt_postal_code // Column Y -- postal
financial_contact_name // Column AB -- Name
financial_contact_title // Column AC -- Title
financial_contact_email // Column AH -- email
phone // Column AE -- Phone
fax // Column AF -- Fax
url // Column AI -- Fax
updated_by_id // always assigned to 999
To …
> (TEST MIGRATION) [jp-0032] Dev - Charity Mailing address and financial contact info upload

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/create/index.blade.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/volunteering/partials/form.blade.php
1.  modified the PECSF ID generation logic from details viewing to new donation creation step.
2. update the prefix code setting logic for "S", "F", "G", "R"
> [jz-016]eForm 'PECSF ID' to be populated for Gaming and Fundraising Events

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/create/index.blade.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/volunteering/partials/form.blade.php
1. modified the PECSF ID generation logic from details viewing to new donation creation step.
2. update the prefix code setting logic for "S", "F", "G", "R"
> [TEST][jz-016]eForm 'PECSF ID' to be populated for Gaming and Fundraising Events

- resources/views/settings/index.blade.php
- resources/views/settings/partials/tabs.blade.php
Nov 1 -- Upon to the clarification with Gillian and Nancy, the tabs under menu "Administration > Training , Communications and Engagement" are incorrect link to other pages. The clean up was required for avoiding confusion. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/SKkHbznwr0yXV8ijQ97h22UAIcaA?Type=TaskLink&Channel=Link&CreatedTime=638349054098500000)
> [jp-0046] Clean up on incorrect links under 'Training , Communications and Engagement' page

- resources/views/settings/index.blade.php
- resources/views/settings/partials/tabs.blade.php
Nov 1 -- Upon to the clarification with Gillian and Nancy, the tabs under menu "Administration > Training , Communications and Engagement" are incorrect link to other pages. The clean up was required for avoiding confusion.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/SKkHbznwr0yXV8ijQ97h22UAIcaA?Type=TaskLink&Channel=Link&CreatedTime=638349054098500000)
> (TEST MIGRATION) [jp-0046] Clean up on incorrect links under 'Training , Communications and Engagement' page 

- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/partials/form.blade.php
modify the drag and drop zone to extend the area and set a grey background color for user can find the working zone.
> [jz-17]Drag n drop or Browse files link not working in the e-form

- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/partials/form.blade.php
modify the drag and drop zone to extend the area and set a grey background color for user can find the working zone.
> [TEST][jz-17]Drag n drop or Browse files link not working in the e-form

- resources/views/home.blade.php
The carousel on the home page needs some changes according to the WCAG guidelines. Please refer to the link below and change the rotator according to the attributes mentioned. (FYI, Paul had worked on this feature before and made changes accordingly, but somehow when fixing things James had to remove the code while pushing to prod) 
Link to refer: 
[Auto-Rotating Image Carousel Example with Buttons for Slide Control | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/) 
Action: Rewritte this accessiblility feature since the previous work is not complete and function.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/frsNdCeXVkKIUVSNzXRyy2UALHWJ?Type=TaskLink&Channel=Link&CreatedTime=638350691713620000)
> [jp-0049] Home page: Change Slider Pattern

- resources/views/settings/index.blade.php
- resources/views/settings/partials/tabs.blade.php
Nov 1 -- Upon to the clarification with Gillian and Nancy, the tabs under menu "Administration > Training , Communications and Engagement" are incorrect link to other pages. The clean up was required for avoiding confusion.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/SKkHbznwr0yXV8ijQ97h22UAIcaA?Type=TaskLink&Channel=Link&CreatedTime=638349054098500000)
> (MASTER) [jp-0046] Clean up on incorrect links under 'Training , Communications and Engagement' page

- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
disable the drag & drop file feature from eForm
> (MASTER) [jz-17]Drag n drop or Browse files link not working in the e-form 

- resources/views/home.blade.php
The carousel on the home page needs some changes according to the WCAG guidelines. Please refer to the link below and change the rotator according to the attributes mentioned. (FYI, Paul had worked on this feature before and made changes accordingly, but somehow when fixing things James had to remove the code while pushing to prod) 
Link to refer: 
[Auto-Rotating Image Carousel Example with Buttons for Slide Control | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/) 
Action: Rewritte this accessiblility feature since the previous work is not complete and function.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/frsNdCeXVkKIUVSNzXRyy2UALHWJ?Type=TaskLink&Channel=Link&CreatedTime=638350691713620000)
> (TEST) [jp-0049] Home page: Change Slider Pattern

- app/Http/Controllers/Admin/CampaignPledgeController.php
- app/Http/Controllers/Admin/DonateNowPledgeController.php
- app/Http/Controllers/Admin/FundSupportedPoolController.php
- app/Http/Controllers/Admin/SpecialCampaignSetupController.php
- app/Http/Controllers/BankDepositFormController.php
- app/Http/Controllers/CharityController.php
- resources/views/home.blade.php
According to the application log, there are lots of SQL error caused by the single quote (‘) entered on the search value by users on charity search field.
`[2023-11-06 11:29:36] prod.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's%' or LOWER(registration_number) LIKE '%bc children's%') and `charity_status` =' at line 1 (SQL: select `id`, `charity_name`, `registration_number` from `charities` where (LOWER(charity_name) LIKE '%bc children's%' or LOWER(registration_number) LIKE '%bc children's%') and `charity_status` = Registered order by `charity_name` asc limit 100) 
`
Nov 8 -- fixed the following search fields:
a. charity 
b. user / …
> (TEST) [jp-0050] SQL error caused by the single quote () on the charity search string

- app/Console/Commands/ExportPledgesToPSFT.php
- app/Console/Kernel.php
- app/Models/Pledge.php
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Yu7_-ODvZkuYqTkthT2Cr2UAKNgh?Type=TaskLink&Channel=Link&CreatedTime=638352414795000000)
> [jp-0052] Admin updating/canceling gov pledges during campaign (2nd commit)

- app/Console/Commands/ExportPledgesToPSFT.php
- app/Console/Kernel.php
- app/Models/Pledge.php
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Yu7_-ODvZkuYqTkthT2Cr2UAKNgh?Type=TaskLink&Channel=Link&CreatedTime=638352414795000000)
> (TEST MIGRATION) [jp-0052] Admin updating/canceling gov pledges during campaign (2nd commit)

- resources/views/home.blade.php
The carousel on the home page needs some changes according to the WCAG guidelines. Please refer to the link below and change the rotator according to the attributes mentioned. (FYI, Paul had worked on this feature before and made changes accordingly, but somehow when fixing things James had to remove the code while pushing to prod) 
Link to refer: 
[Auto-Rotating Image Carousel Example with Buttons for Slide Control | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/) 
Action: Rewritte this accessiblility feature since the previous work is not complete and function.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/frsNdCeXVkKIUVSNzXRyy2UALHWJ?Type=TaskLink&Channel=Link&CreatedTime=638350691713620000)
> [jp-0049] Home page: Change Slider Pattern (reapply the change after resolve merge conflict)

- resources/views/home.blade.php
The carousel on the home page needs some changes according to the WCAG guidelines. Please refer to the link below and change the rotator according to the attributes mentioned. (FYI, Paul had worked on this feature before and made changes accordingly, but somehow when fixing things James had to remove the code while pushing to prod) 
Link to refer: 
[Auto-Rotating Image Carousel Example with Buttons for Slide Control | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/) 
Action: Rewritte this accessiblility feature since the previous work is not complete and function.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/frsNdCeXVkKIUVSNzXRyy2UALHWJ?Type=TaskLink&Channel=Link&CreatedTime=638350691713620000)
> (TEST MIGRATION) [jp-0049] Home page: Change Slider Pattern (reapply the change after resolved the conflict)

- resources/views/admin-pledge/campaign/wizard.blade.php
Nov 16 - Fix the blade error issue when create a new pledge (under admin menu)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Yu7_-ODvZkuYqTkthT2Cr2UAKNgh?Type=TaskLink&Channel=Link&CreatedTime=638352414795000000 …
> [jp-0052] Admin updating/canceling gov pledges during campaign (fix blade error when create new pledget)

- resources/views/admin-pledge/campaign/wizard.blade.php
Nov 16 - Fix the blade error issue when create a new pledge (under admin menu)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Yu7_-ODvZkuYqTkthT2Cr2UAKNgh?Type=TaskLink&Channel=Link&CreatedTime=638352414795000000 …
> (TEST) [jp-0052] Admin updating/canceling gov pledges during campaign (fix blade error when create new pledge)

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/create/index.blade.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/volunteering/forms.blade.php
- resources/views/volunteering/partials/form.blade.php
rule for "S" PECSF ids: S + year + sequence number. Sample: S23001
update id generate code from donation creation phase.
update sql statement for refresh existing PECSF IDs
> (MASTER)  [jz-016] eForm 'PECSF ID' to be populated for Gaming and Fundraising Events 

- app/Http/Controllers/Admin/CampaignPledgeController.php
- app/Http/Controllers/Admin/DonateNowPledgeController.php
- app/Http/Controllers/Admin/FundSupportedPoolController.php
- app/Http/Controllers/Admin/SpecialCampaignSetupController.php
- app/Http/Controllers/BankDepositFormController.php
- app/Http/Controllers/CharityController.php
- resources/views/home.blade.php
According to the application log, there are lots of SQL error caused by the single quote (‘) entered on the search value by users on charity search field.
`[2023-11-06 11:29:36] prod.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's%' or LOWER(registration_number) LIKE '%bc children's%') and `charity_status` =' at line 1 (SQL: select `id`, `charity_name`, `registration_number` from `charities` where (LOWER(charity_name) LIKE '%bc children's%' or LOWER(registration_number) LIKE '%bc children's%') and `charity_status` = Registered order by `charity_name` asc limit 100) 
`
Nov 8 -- fixed the following search fields:
a. charity 
b. user / …
> (MASTER) [jp-0050] SQL error caused by the single quote () on the charity search string 

- resources/views/donate-now/partials/amount.blade.php
Nov 14 - The title was was updated per request:
The Donate Now function is a one-time donation so lets change the title on Step 3 to ‘3. Decide on the amount’ from ‘3. Decide on the frequency and amount’ 
Fix must be applied to both flows: CRA charity and FSP 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Djg2pSMOBEqyRF1M4q5JUmUAClfj?Type=TaskLink&Channel=Link&CreatedTime=638356191619310000)
> (TEST MIGRATION) [jp-0059] Donate now: Change the title of Step 3 in the donation flow

- app/Console/Commands/ExportPledgesToPSFT.php
- app/Models/Pledge.php
Nov 16 - Fix the blade error issue when create a new pledge (under admin menu)
Nov 17 - Improve the batching process to send data to ODS
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Yu7_-ODvZkuYqTkthT2Cr2UAKNgh …
> [jp-0052] Admin updating/canceling gov pledges during campaign (improve batching)

- app/Console/Commands/ExportPledgesToPSFT.php
- app/Models/Pledge.php
Nov 16 - Fix the blade error issue when create a new pledge (under admin menu)
Nov 17 - Improve the batching process to send data to ODS
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Yu7_-ODvZkuYqTkthT2Cr2UAKNgh …
> (TEST MIGRATION) [jp-0052] Admin updating/canceling gov pledges during campaign

- resources/views/donate-now/partials/amount.blade.php
Nov 14 - The title was was updated per request:
The Donate Now function is a one-time donation so lets change the title on Step 3 to ‘3. Decide on the amount’ from ‘3. Decide on the frequency and amount’ 
Fix must be applied to both flows: CRA charity and FSP 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Djg2pSMOBEqyRF1M4q5JUmUAClfj?Type=TaskLink&Channel=Link&CreatedTime=638356191619310000)
> (MASTER) [jp-0059] Donate now: Change the title of Step 3 in the donation flow

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- app/Models/BankDepositForm.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/index.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
This branch contains multiple eForm related tickets
[jp-0066] eForm - Employee Name field does not get updated
[jp-0066] eForm - Pecsf Id is not generated when editing an event pledge
[jp-0066] Dev - eForm - Donation type options
[jp-0066] Dev - eForm - Allow EBC employees w/o eeIDs to make cash/cheque one-time donations
> (TEST) [jp-0066] Multiple eform tickets 

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/volunteering/forms.blade.php
To resolve the following error when try to locked the event pledge:
submission-queue:3046 Uncaught ReferenceError: formatState is not defined
at HTMLSelectElement.<anonymous> (submission-queue:3046:40)
at HTMLSelectElement.dispatch (jquery.js:5145:1)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/KYBXvbc0RkKm0pqLaWDgWmUAOwvq?Type=TaskLink&Channel=Link&CreatedTime=638368806756600000)
> [jp-0066] 4th commit -- Locked feature for Event Submission Queue not working

- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/volunteering/forms.blade.php
To resolve the following error when try to locked the event pledge:
submission-queue:3046 Uncaught ReferenceError: formatState is not defined
at HTMLSelectElement. (submission-queue:3046:40)
at HTMLSelectElement.dispatch (jquery.js:5145:1)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/KYBXvbc0RkKm0pqLaWDgWmUAOwvq?Type=TaskLink&Channel=Link&CreatedTime=638368806756600000)
> [jp-0066] 4th commit -- Locked feature for Event Submission Queue not working 

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- app/Models/BankDepositForm.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/forms.blade.php
- resources/views/volunteering/index.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
This branch includes the following tickets:
[jp-0066] eForm - Employee Name field does not get updated	
[jp-0066] eForm - Pecsf Id is not generated when editing an event pledge	
[jp-0066] Dev - eForm - Donation type options	
[jp-0066] Dev - eForm - Allow EBC employees w/o eeIDs to make cash/cheque one-time donations	
[jp-0066] e-Form - only show once eForm pop up instruction modal page
[jp-0066] Locked feature for Event Submission Queue not working
> (MASTER) [jp-0066] Multiple Fixes on eForm related programs

- app/Exports/PledgeCharitiesExport.php
> (TEST) [jp-0065] DEV - Admin report list - Charity Amount (Fixed issue 2 and 5)

- app/Http/Controllers/Admin/DonateNowPledgeController.php
- resources/views/admin-pledge/donate-now/create-edit.blade.php
- resources/views/admin-pledge/donate-now/show.blade.php
- routes/web.php
Additional change required to display the EE region based on their Office City.
> (TEST) [jp-0069] Donate Now pledges (admin) -- EE region should be based on EE office city

- app/Http/Controllers/Admin/DonateNowPledgeController.php
- resources/views/admin-pledge/donate-now/index.blade.php
Additional change required to display the EE region based on their Office City on the index page.
Issue:
User : 163106 | Jones,Jennifer
Admin added 2 donate now pledges for Jennifer, but in the Maintain Donate Now Pledge list the city is displayed with “,” and when clicked on Edit, the region field is empty
> [jp-0069] Donate Now pledges (admin) -- EE region should be based on EE office_city (additional change required)

- app/Http/Controllers/Admin/DonateNowPledgeController.php
- resources/views/admin-pledge/donate-now/index.blade.php
Additional change required to display the EE region based on their Office City on the index page.
Issue:
User : 163106 | Jones,Jennifer
Admin added 2 donate now pledges for Jennifer, but in the Maintain Donate Now Pledge list the city is displayed with “,” and when clicked on Edit, the region field is empty
> (TEST) [jp-0069] Donate Now pledges (admin) -- EE region should be based on EE office_city (additional change required)

- app/Http/Controllers/Admin/DonateNowPledgeController.php
- app/Models/DonateNowPledge.php
- resources/views/admin-pledge/donate-now/create-edit.blade.php
- resources/views/admin-pledge/donate-now/index.blade.php
- resources/views/admin-pledge/donate-now/show.blade.php
Dec 4 - Added. a small issue in the attachment.  Investigate: User with emp id 163106 has a missing Region?
Dec 4 - (JP) This is a good finding. The city on index (listing) page should be also based on the EE's employee city. The program was updated and deployed on both DEV & TEST region.
Dec 6 -
Replace City title with Region
Add City field on create and edit pledge
> [jp-0069] Donate Now pledges (admin) -- EE region should be based on EE office_city (additional change required to show correct city)

- app/Http/Controllers/Admin/DonateNowPledgeController.php
- app/Http/Controllers/DonateNowController.php
- app/Models/DonateNowPledge.php
- resources/views/admin-pledge/donate-now/create-edit.blade.php
- resources/views/admin-pledge/donate-now/index.blade.php
- resources/views/admin-pledge/donate-now/show.blade.php
- resources/views/donations/partials/donate-now-pledge-detail-modal.blade.php
- routes/web.php
For 2 tickets:
[jp-0069] Donate Now pledges displayed in 2023 instead of 2024
[jp-0069] Donate Now pledges (admin) -- EE region should be based on EE office city (additional Change)
> (MASTER) [jp-0069] Donate Now pledges (admin) -- EE region should be based on EE office_city (additional change required to show correct city)

- app/Exports/GamingAndFundrasingExport.php
- app/Exports/PledgeCharitiesExport.php
Dec 7 - per Nancy, this report is similar to Pledge Amount by Charity but for the event pledge with type Gaming and Fundrasing. mainly use by FMO team.
Additional changes - 
1. fixed prorated amount issue 
2. added Tran ID in report
> [jp-0071] Report - Gaming and Fundraising (2nd commit - fixed prorated d amount issue and added Tran ID)

- app/Exports/GamingAndFundrasingExport.php
- app/Exports/PledgeCharitiesExport.php
Dec 7 - per Nancy, this report is similar to Pledge Amount by Charity but for the event pledge with type Gaming and Fundrasing. mainly use by FMO team.
Additional changes -
fixed prorated amount issue
added Tran ID in report
> (TEST) [jp-0071] Report - Gaming and Fundraising (2nd commit - fixed prorated amount issue and added Tran ID)

- app/Http/Controllers/Admin/CampaignPledgeController.php
- app/Http/Requests/CampaignPledgeRequest.php
- app/Models/FSPoolCharity.php
- app/Models/Organization.php
- database/migrations/2023_12_19_132602_drop_foreign_in_pledge_charities_table.php
- resources/views/admin-pledge/campaign/partials/amount.blade.php
- resources/views/admin-pledge/campaign/wizard.blade.php
> [jp-0076] Dev - PECSF admin can edit charity choices outside campaign

- app/Http/Controllers/Admin/CampaignPledgeController.php
- app/Http/Requests/CampaignPledgeRequest.php
- app/Models/FSPoolCharity.php
- app/Models/Organization.php
- database/migrations/2023_12_19_132602_drop_foreign_in_pledge_charities_table.php
- resources/views/admin-pledge/campaign/partials/amount.blade.php
- resources/views/admin-pledge/campaign/wizard.blade.php
> (TEST) [jp-0076] Dev - PECSF admin can edit charity choices outside campaign

- app/Exports/DonationDataReportExport.php
- app/Http/Controllers/Admin/DonationDataReportController.php
- app/Jobs/DonationDataReportExportJob.php
- resources/views/admin-report/donation-report/index.blade.php
- resources/views/admin-report/partials/tabs.blade.php
- routes/web.php
Dec 18 - Per Leah, they need to export the Non-Gov EE donation data on excel spreadsheets for reconciliation and analysis purposes.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7zpNU6XoW0uqSwiUNKGpV2UAICdP?Type=TaskLink&Channel=Link&CreatedTime=638387789061870000)
> [jp-0077] Export Non-Gov donation data on excel spreadsheet

- app/Exports/DonationDataReportExport.php
- app/Http/Controllers/Admin/DonationDataReportController.php
- app/Jobs/DonationDataReportExportJob.php
- resources/views/admin-report/donation-report/index.blade.php
- resources/views/admin-report/partials/tabs.blade.php
- routes/web.php
Dec 18 - Per Leah, they need to export the Non-Gov EE donation data on excel spreadsheets for reconciliation and analysis purposes.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7zpNU6XoW0uqSwiUNKGpV2UAICdP?Type=TaskLink&Channel=Link&CreatedTime=638387789061870000)
> (TEST) [jp-0077] Export Non-Gov donation data on excel spreadsheet

- database/migrations/2023_12_22_104557_drop_foreign_in_volunteers_table.php
> [jp-0076] Dev - PECSF admin can edit charity choices outside campaign (2nd clean up -- foreigen key)

- database/migrations/2023_12_22_104557_drop_foreign_in_volunteers_table.php
> (TEST) [jp-0076] Dev - PECSF admin can edit charity choices outside campaign  (2nd clean up -- foreigen key)

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
> [jp-0080] eForm - Fundraiser BU list (remove LDB when Gov chosen) 

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
> (TEST) [jp-0080] eForm - Fundraiser BU list (remove LDB when Gov chosen)

- resources/views/annual-campaign/wizard.blade.php
Work Done:
Dec 28 - update the breadcrumb wording in "Annual Campaign" donation matching to "Donate Now" donation
> [jp-0081] Donations: Standardize the breadcrumb for in-campaign and donate now

- resources/views/annual-campaign/wizard.blade.php
Work Done:
Dec 28 - update the breadcrumb wording in "Annual Campaign" donation matching to "Donate Now" donation
> (TEST) [jp-0081] Donations: Standardize the breadcrumb for in-campaign and donate now

- app/Http/Controllers/BankDepositFormController.php
> [jp-0080] eForm - Fundraiser BU list (remove LDB when Gov chosen) - additional validation added

- app/Http/Controllers/BankDepositFormController.php
> (TEST) [jp-0080] eForm - Fundraiser BU list (remove LDB when Gov chosen) - additional validation added

- app/Http/Controllers/BankDepositFormController.php
> [jp-0080] eForm - Fundraiser BU list (remove LDB when Gov chosen) - additional validation added when editing

- app/Http/Controllers/BankDepositFormController.php
> (TEST) [jp-0080] eForm - Fundraiser BU list (remove LDB when Gov chosen) - additional validation added when editing

- app/Http/Controllers/Admin/CampaignPledgeController.php
- app/Http/Requests/CampaignPledgeRequest.php
- app/Models/FSPoolCharity.php
- app/Models/Organization.php
- database/migrations/2023_12_19_132602_drop_foreign_in_pledge_charities_table.php
- database/migrations/2023_12_22_104557_drop_foreign_in_volunteers_table.php
- resources/views/admin-pledge/campaign/partials/amount.blade.php
- resources/views/admin-pledge/campaign/wizard.blade.php
> (MASTER)  [jp-0076] Dev - PECSF admin can edit charity choices outside campaign 

- app/Exports/DonationDataReportExport.php
- app/Http/Controllers/Admin/DonationDataReportController.php
- app/Jobs/DonationDataReportExportJob.php
- resources/views/admin-report/donation-report/index.blade.php
- resources/views/admin-report/partials/tabs.blade.php
- routes/web.php
Dec 18 - Per Leah, they need to export the Non-Gov EE donation data on excel spreadsheets for reconciliation and analysis purposes.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7zpNU6XoW0uqSwiUNKGpV2UAICdP?Type=TaskLink&Channel=Link&CreatedTime=638387789061870000)
> (MASTER) [jp-0077] Export Non-Gov donation data on excel spreadsheet

- resources/views/admin-pledge/submission-queue/index.blade.php
> (MASTER) [jp-0078] Admin: eForm Submission Queue: Approval message

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/BankDepositFormController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
> (MASTER) [jp-0080] eForm - Fundraiser BU list (remove LDB when Gov chosen) - additional validation added when editing 

- resources/views/annual-campaign/wizard.blade.php
Work Done:
Dec 28 - update the breadcrumb wording in "Annual Campaign" donation matching to "Donate Now" donation
> (MASTER) [jp-0081] Donations: Standardize the breadcrumb for in-campaign and donate now

- app/Console/Commands/UpdateDailyCampaign.php
Work Done:
Dec 28 - update the breadcrumb wording in "Annual Campaign" donation matching to "Donate Now" donation
> (MASTER) [jp-0082] Challenge page data report - Stats cleared after new year

- app/Console/Commands/SystemQueueStatus.php
- app/Console/Kernel.php
- app/MicrosoftGraph/SendEmailNotification.php
> [jp-0088] pulse check process to monitor the background job (1st commit)

- app/Console/Commands/SystemQueueStatus.php
> [jp-0088] pulse check process to monitor the background job (3rd commit)

- app/Console/Kernel.php
> [jp-0088] pulse check process to monitor the background job (4th commit)

- app/Console/Kernel.php
> [jp-0088] pulse check process to monitor the background job (5th commit)

- app/Console/Commands/SystemQueueStatus.php
> [jp-0088] pulse check process to monitor the background job (6th commit)

- app/Console/Commands/SystemQueueStatus.php
- app/Console/Kernel.php
- app/MicrosoftGraph/SendEmailNotification.php
> [jp-0088] pulse check process to monitor the background job 

- app/Console/Commands/SystemQueueStatus.php
- app/Console/Kernel.php
- app/MicrosoftGraph/SendEmailNotification.php
> (MASTER) [jp-0088] pulse check process to monitor the background job

- app/Http/Controllers/BankDepositFormController.php
- database/migrations/2024_01_19_102829_change_deposit_date_in_bank_deposit_forms_table.php
Jan 25 - bug in the program to stop update the address_1 when the event_type is 'cheque one-time' Donation'.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/-a6e7j5eTkmJoSN3ljg_xGUAFupd?Type=TaskLink&Channel=Link&CreatedTime=638417959960330000)
> [jp-0087] Address line 1 missing from the Event Pledges in Submission Queue

- app/Http/Controllers/BankDepositFormController.php
- database/migrations/2024_01_19_102829_change_deposit_date_in_bank_deposit_forms_table.php
Jan 25 - bug in the program to stop update the address_1 when the event_type is 'cheque one-time' Donation'.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/-a6e7j5eTkmJoSN3ljg_xGUAFupd?Type=TaskLink&Channel=Link&CreatedTime=638417959960330000)
> (TEST) [jp-0087] Address line 1 missing from the Event Pledges in Submission Queue

- app/Http/Controllers/DonationController.php
Fix the bug in the donation history page.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/J4M3XdrSIE-3khFp2yGPpWUALYxN?Type=TaskLink&Channel=Link&CreatedTime=638418075552120000)
> [jp-0089] Receiving error when displaying Special campaign in Donation history

- app/Http/Controllers/DonationController.php
Fix the bug in the donation history page.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/J4M3XdrSIE-3khFp2yGPpWUALYxN?Type=TaskLink&Channel=Link&CreatedTime=638418075552120000)
> (TEST) [jp-0089] Receiving error when displaying Special campaign in Donation history

- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- app/Http/Controllers/BankDepositFormController.php
- database/migrations/2024_01_19_102829_change_deposit_date_in_bank_deposit_forms_table.php
- database/seeders/DataFixFor_jp_0087_reset_approval.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/vendor/adminlte/master.blade.php
Issue: 
When staying on one page, the special campaigns are displayed in the form of a rotating banner i.e One at a time, but when navigating for example from Home to donations page, for a second or two all the active Special campaigns are displayed. Refer to the screenshot attached.
Fix:  Hide the list before vertical slide start.  
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/MCtnnI8w9kaf6KKxVqi_bGUANsmR?Type=TaskLink&Channel=Link&CreatedTime=638418168979920000)
> [jp-0090] List of Special Campaigns displays when navigating from one page to another

- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- app/Http/Controllers/BankDepositFormController.php
- database/migrations/2024_01_19_102829_change_deposit_date_in_bank_deposit_forms_table.php
- database/seeders/DataFixFor_jp_0087_reset_approval.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/vendor/adminlte/master.blade.php
Issue:
When staying on one page, the special campaigns are displayed in the form of a rotating banner i.e One at a time, but when navigating for example from Home to donations page, for a second or two all the active Special campaigns are displayed. Refer to the screenshot attached.
Fix: Hide the list before vertical slide start.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/MCtnnI8w9kaf6KKxVqi_bGUANsmR?Type=TaskLink&Channel=Link&CreatedTime=638418168979920000)
> (TEST) [jp-0090] List of Special Campaigns displays when navigating from one page to another

- resources/views/special-campaign/partials/pdf.blade.php
- resources/views/special-campaign/partials/special-campaign.blade.php
> [jp-0092] Various improvements on Special Campaign Donation page

- resources/views/special-campaign/partials/pdf.blade.php
- resources/views/special-campaign/partials/special-campaign.blade.php
> (TEST) [jp-0092] Various improvements on Special Campaign Donation page

- resources/views/donations/partials/learn-more-modal.blade.php
Improve accessibility on the page "Why donate to PECSF and How to Donate": 
- Add a header to the modal
- Link identified only by color 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/YIjQx2x8pUeCMI4emBZpN2UAGNX6?Type=TaskLink&Channel=Link&CreatedTime=638422528005820000)
> [jp-0098] PECSF slides changes

- resources/views/donations/partials/learn-more-modal.blade.php
Improve accessibility on the page "Why donate to PECSF and How to Donate":
Add a header to the modal
Link identified only by color
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/YIjQx2x8pUeCMI4emBZpN2UAGNX6?Type=TaskLink&Channel=Link&CreatedTime=638422528005820000)
> (TEST) [jp-0098] PECSF slides changes

- resources/views/special-campaign/partials/special-campaign.blade.php
Additional change on List of Special campaigns (additional color change)
> [jp-0092] UI changes - List of Special campaigns (additional color change)

- resources/views/special-campaign/partials/special-campaign.blade.php
Additional change on List of Special campaigns (additional color change)
> (TEST) [jp-0092] UI changes - List of Special campaigns (additional color change)

- resources/views/vendor/adminlte/master.blade.php
The Special Campaign is displayed on the top bar of the user Dashboard/profile. Can we make the following changes to the display.
Make the background colour lighter to #FFE066
And the text: Make a donation to #C1201A
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mcBW8WgpVEeJy4RODcnFN2UAOvgY?Type=TaskLink&Channel=Link&CreatedTime=638419004720430000)
> (MASTER) [jp-0090] Special Campaign Display (change banner color)

- resources/views/special-campaign/partials/pdf.blade.php
- resources/views/special-campaign/partials/special-campaign.blade.php
> (MASTER) [jp-0092] Various improvements on Special Campaign Donation page

- resources/views/donations/partials/learn-more-modal.blade.php
Improve accessibility on the page "Why donate to PECSF and How to Donate":
Add a header to the modal
Link identified only by color
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/YIjQx2x8pUeCMI4emBZpN2UAGNX6?Type=TaskLink&Channel=Link&CreatedTime=638422528005820000)
> (MASTER) [jp-0098] PECSF slides changes

- tests/Feature/ChallengePageTest.php
- tests/Feature/DonationUploadTest.php
> [upgrade_952_to_103] Post-Implementation - Automated Testing (donations upload testing added)

- resources/views/donations/partials/history.blade.php
Feb 7 – James and Steffi had a discussion on the ticket and came up with the following solution. 
Add a column called Bi-weekly amount between the Frequency and Amount columns 
For Donate now, one-time and special campaigns, the Bi-weekly column will display ‘ - ‘ 
Change the Amount column name to ‘Total Amount’ 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/_nzgvwIUe0u94ixtjYQ2q2UAMttQ?Type=TaskLink&Channel=Link&CreatedTime=638430600574180000)
> [jp-0101] Dev - Donation history change amount to total amount

- resources/views/donations/partials/history.blade.php
Feb 7 – James and Steffi had a discussion on the ticket and came up with the following solution.
Add a column called Bi-weekly amount between the Frequency and Amount columns
For Donate now, one-time and special campaigns, the Bi-weekly column will display ‘ - ‘
Change the Amount column name to ‘Total Amount’
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/_nzgvwIUe0u94ixtjYQ2q2UAMttQ?Type=TaskLink&Channel=Link&CreatedTime=638430600574180000)
> (TEST) [jp-0101] Dev - Donation history change amount to total amount

- tests/Feature/SystemAccessLogsTest.php
- tests/Feature/SystemAuditingTest.php
- tests/Feature/SystemExportAuditsTest.php
- tests/Feature/SystemScheduleJobAuditsTest.php
- tests/Feature/SystemSettingsTest.php
- tests/Feature/SystemUsersTest.php
- tests/Feature/SystemadministratorsTest.php
> [upgrade_952_to_103] Post-Implementation - Automated Testing (system menu items testing added)

- tests/Feature/SystemAccessLogsTest.php
- tests/Feature/SystemAuditingTest.php
- tests/Feature/SystemExportAuditsTest.php
- tests/Feature/SystemScheduleJobAuditsTest.php
- tests/Feature/SystemSettingsTest.php
- tests/Feature/SystemUsersTest.php
- tests/Feature/SystemadministratorsTest.php
> (TEST) [upgrade_952_to_103] Post-Implementation - Automated Testing (system menu items testing added) 

- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
Various changes on Donations History and Annual compaign pledge pages
Branch jp-0100 -- Annual compaign pledge page
Branch jp-0101 -- Donation History page
[Tickets](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/fMUcKbdVsU6oB9vvo7Q6vmUAPf2R?Type=TaskLink&Channel=Link&CreatedTime=638432238175660000)
> [jp-0100+jp-0101] Dev - Donations Flow Style Changes (Donation History page)

- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
Various changes on Donations History and Annual compaign pledge pages
Branch jp-0100 -- Annual compaign pledge page
Branch jp-0101 -- Donation History page
[Tickets](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/fMUcKbdVsU6oB9vvo7Q6vmUAPf2R?Type=TaskLink&Channel=Link&CreatedTime=638432238175660000)
> (TEST) [jp-0100+jp-0101] Dev - Donations Flow Style Changes (jp-0101 Donation History page)

- database/factories/DonationFactory.php
- tests/Feature/ReportDonationReportTest.php
- tests/Feature/ReportDonationUploadTest.php
- tests/Feature/ReportPledgeReportTest.php
> [upgrade_952_to_103] Post-Implementation - Automated Testing (reporting added)

- database/factories/DonationFactory.php
- tests/Feature/ReportDonationReportTest.php
- tests/Feature/ReportDonationUploadTest.php
- tests/Feature/ReportPledgeReportTest.php
> (TEST) [upgrade_952_to_103] Post-Implementation - Automated Testing (reporting added)

- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
- resources/views/donations/partials/pdf.blade.php
Feb 7 – James and Steffi had a discussion on the ticket and came up with the following solution.
Add a column called Bi-weekly amount between the Frequency and Amount columns
For Donate now, one-time and special campaigns, the Bi-weekly column will display ‘ - ‘
Change the Amount column name to ‘Total Amount’
Feb 9 -- Migrated to DEV and Test. Ready for testing
Feb 12 - Steffi validated the test. Want to know if we should also include this change in the Donation Summary pdf only for the Bi-weekly donation?
Feb 13 - change applied on DEV and TEST. Please re-test.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/_nzgvwIUe0u94ixtjYQ2q2UAMttQ?Type=TaskLink&Channel=Link&CreatedTime=638430600574180000)
> (TEST) [jp-0101] Dev - Donation history change amount to total amount (add the Bi-weekly column on pdf)

- resources/views/donations/partials/learn-more-modal.blade.php
Feb 7 - James will need to look into it to see if we can achieve it
Feb 13 - Done some research and hetre is the findings
Issue 1: This is a "Live Text" on Mac, the special icon display for indicate that you can select the text from th image. "Interact with text in a photo using Live Text in Photos on Mac" https://support.apple.com/en-hk/guide/photos/pht6bc6bd5f5/mac
Issue 2: Play in fullscreen mode, since this is an embedded youtube video and the control is still under youtube domain. There is no way to control the full screen programmically. However, I enlarge the video window size and there are 3 ways to switch full mode from youtube player:
1. 'f' shortcut key
2. double click on the youtube player
3. click on full screen mode icon (bottom right corner) …
> [jp-0102] Dev - How to Donate - Remove Visual Search and Make Modal Full Screen - Possible?

- resources/views/donations/partials/learn-more-modal.blade.php
Feb 7 - James will need to look into it to see if we can achieve it
Feb 13 - Done some research and hetre is the findings
Issue 1: This is a "Live Text" on Mac, the special icon display for indicate that you can select the text from th image. "Interact with text in a photo using Live Text in Photos on Mac" https://support.apple.com/en-hk/guide/photos/pht6bc6bd5f5/mac
Issue 2: Play in fullscreen mode, since this is an embedded youtube video and the control is still under youtube domain. There is no way to control the full screen programmically. However, I enlarge the video window size and there are 3 ways to switch full mode from youtube player:
1. 'f' shortcut key
2. double click on the youtube player
3. click on full screen mode icon (bottom right corner) …
> (TEST) [jp-0102] Dev - How to Donate - Remove Visual Search and Make Modal Full Screen - Possible?

- tests/Feature/ReportGamingAndFundrasingReportTest.php
- tests/Feature/ReportPledgeCharityReportTest.php
> [upgrade_952_to_103] Post-Implementation - Automated Testing (more reporting added)

- tests/Feature/ReportGamingAndFundrasingReportTest.php
- tests/Feature/ReportPledgeCharityReportTest.php
> (TEST) [upgrade_952_to_103] Post-Implementation - Automated Testing (more reporting added) 

- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
The duplicate button does not function on the click of the button. No error is being received in the console.
Feb 13 -- Bug found and replicated on local review. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/PLU6c3fyYEaoDONbuvT5AGUAIUJj?Type=TaskLink&Channel=Link&CreatedTime=638434688193900000)
> [jp-0101] Duplicate this annual campaign pledge button not functioning

- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
The duplicate button does not function on the click of the button. No error is being received in the console.
Feb 13 -- Bug found and replicated on local review.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/PLU6c3fyYEaoDONbuvT5AGUAIUJj?Type=TaskLink&Channel=Link&CreatedTime=638434688193900000)
> (TEST) [jp-0101] Duplicate this annual campaign pledge button not functioning

- tests/Feature/ReportCRACharityReportTest.php
- tests/Feature/ReportChallengePageDataReportTest.php
- tests/Feature/ReportDonationReportTest.php
- tests/Feature/ReportEligibleEmployeesReportTest.php
- tests/Feature/ReportGamingAndFundrasingReportTest.php
- tests/Feature/ReportPledgeCharityReportTest.php
- tests/Feature/ReportPledgeReportTest.php
> [upgrade_952_to_103] Post-Implementation - Automated Testing (more test case on reporting area)

- tests/Feature/ReportCRACharityReportTest.php
- tests/Feature/ReportChallengePageDataReportTest.php
- tests/Feature/ReportDonationReportTest.php
- tests/Feature/ReportEligibleEmployeesReportTest.php
- tests/Feature/ReportGamingAndFundrasingReportTest.php
- tests/Feature/ReportPledgeCharityReportTest.php
- tests/Feature/ReportPledgeReportTest.php
> (TEST) [upgrade_952_to_103] Post-Implementation - Automated Testing (more test case on reporting area) 

- resources/views/volunteering/partials/form.blade.php
Various changes on Donations History and Annual compaign pledge pages
[jp-0100] Donation: Display Dollar Amount besides the % in Donations Distributions 
[jp-0100+jp-0101] Dev - Donations Flow Style Changes
[jp-0100] eForm - Volunteering changes
[jp-0100+jp-0101] All tabs remains highlighted when Donations page is open
[Tickets](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/fMUcKbdVsU6oB9vvo7Q6vmUAPf2R?Type=TaskLink&Channel=Link&CreatedTime=638432238175660000)
> [jp-0100] eForm - Volunteering changes

- resources/views/volunteering/partials/form.blade.php
Various changes on Donations History and Annual compaign pledge pages
[jp-0100] Donation: Display Dollar Amount besides the % in Donations Distributions
[jp-0100+jp-0101] Dev - Donations Flow Style Changes
[jp-0100] eForm - Volunteering changes
[jp-0100+jp-0101] All tabs remains highlighted when Donations page is open
[Tickets](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/fMUcKbdVsU6oB9vvo7Q6vmUAPf2R?Type=TaskLink&Channel=Link&CreatedTime=638432238175660000)
> (TEST) [jp-0100] eForm - Volunteering changes

- app/Http/Controllers/Admin/PayCalendarController.php
- app/Models/Pledge.php
- app/Models/PledgeCharity.php
Issue: The Pay Calendar Pay page under Admin - Settings can access by non-admin user.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FdRyyIRKpx0yKE16YPblJUGUAIFy8%22%7D)
> [jp-0103] SEC - authenicated user without admin role can access Pay Calendar page under Settings

- app/Http/Controllers/Admin/PayCalendarController.php
- app/Models/Pledge.php
- app/Models/PledgeCharity.php
Issue: The Pay Calendar Pay page under Admin - Settings can access by non-admin user.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FdRyyIRKpx0yKE16YPblJUGUAIFy8%22%7D)
> (TEST) [jp-0103] SEC - authenicated user without admin role can access Pay Calendar page under Settings

- resources/views/donations/partials/history.blade.php
When any other page example Home, Volunteering, Challenge are open, then they are highlighted in the right menu and other pages remain unhighlighted.
> (TEST) [jp-0101] Dev - Donation history change amount to total amount (update aria-label on expand/collapse icon when change) 

- composer.lock
This is to upgrade from Laravel 9 to Laravel 10 on openshift platform.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/j626_tGw9USLCiQkE-gqw2UAGc46?Type=TaskLink&Channel=Link&CreatedTime=638400871916850000)
Post upgrade steps:
php artisan optimize:clear
php artisan migrate
> [upgrade_952_103] Upgrade Laravel from 9.52 to 10.3 -- resolved dompdf critical patch

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- resources/views/admin-pledge/submission-queue/index.blade.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/admin-pledge/submission-queue/partials/form.blade.php
- resources/views/volunteering/forms.blade.php
- resources/views/volunteering/partials/add-event-js.blade.php
- resources/views/volunteering/partials/form.blade.php
Update  Fund Support Pool selection UI on pages under self-service event pledge (eForm) and event submission queue, make it similiar to "Annual campaign pledge" page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/algcnP8GiEOfHdWZA3CfKmUANQt-?Type=TaskLink&Channel=Link&CreatedTime=638442393333690000)
> [jp-0100] E-form FSP - Pools are not organized

- tests/Feature/ChallengePageTest.php
- tests/Feature/NotifyMailTest.php
> [upgrade_952_to_103] Post-Implementation - Automated Testing (add notify mail test)

- composer.lock
- tests/Feature/ChallengePageTest.php
- tests/Feature/NotifyMailTest.php
> (TEST) [upgrade_952_to_103] Post-Implementation - Automated Testing (add notify mail test)

- tests/Feature/DonateNowTest.php
> [upgrade_952_to_103] Post-Implementation - Automated Testing (add download pdf in DaonteNow)

- tests/Feature/AnnualCampaignTest.php
- tests/Feature/DonateNowTest.php
- tests/Feature/DonationsPageTest.php
> (TEST) [upgrade_952_to_103] Post-Implementation - Automated Testing (add download pdf in DaonteNow)

- resources/views/donations/partials/learn-more-modal.blade.php
Feb 7 - James will need to look into it to see if we can achieve it
Feb 13 - Done some research and hetre is the findings
Issue 1: This is a "Live Text" on Mac, the special icon display for indicate that you can select the text from th image. "Interact with text in a photo using Live Text in Photos on Mac" https://support.apple.com/en-hk/guide/photos/pht6bc6bd5f5/mac
Issue 2: Play in fullscreen mode, since this is an embedded youtube video and the control is still under youtube domain. There is no way to control the full screen programmically. However, I enlarge the video window size and there are 3 ways to switch full mode from youtube player:
- 'f' shortcut key
- double click on the youtube player
- click on full screen mode icon (bottom right corner) …
> (MASTER) [jp-0102] Dev - How to Donate - Remove Visual Search and Make Modal Full Screen - Possible?

- app/Http/Requests/CampaignPledgeRequest.php
- resources/views/admin-pledge/campaign/wizard.blade.php
> [jp-0108] Various changes on Admin - Annual Campaign 

- app/Http/Requests/CampaignPledgeRequest.php
- resources/views/admin-pledge/campaign/wizard.blade.php
> (TEST) [jp-0108] Various changes on Admin - Annual Campaign

- app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
- app/Http/Controllers/DonationController.php
- app/Http/Controllers/SpecialCampaignController.php
- resources/views/admin-pledge/special-campaign/create-edit.blade.php
- resources/views/donations/partials/special-campaign-pledge-detail-modal.blade.php
- resources/views/special-campaign/partials/pdf.blade.php
- resources/views/special-campaign/partials/special-campaign.blade.php
- resources/views/special-campaign/partials/summary.blade.php
- resources/views/special-campaign/wizard.blade.php
This branch contains various changes related to Special Campaign:
[jp-0109] Incorrect Special Campaigns list displayed for Admin - Maintain Special Campaign Pledge ([ticket)](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ACw_m_SthUCEwbKvj7OP3WUANMgW?Type=TaskLink&Channel=Link&CreatedTime=638455156856870000)
[jp-0109] Special campaign - Change the Back button UI to copy from the donation flow ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/219KGHygvUCQAtZo3F-pQWUAEAlh?Type=TaskLink&Channel=Link&CreatedTime=638455156615660000))
[jp-0109] Rename Special Campaign donation summary pdf ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/kmjjbUtVuE2lh9Op9dazR2UADfYj?Type=TaskLink&Channel=Link&CreatedTime=638455156463050000))
[jp-0109] Remove the …
> [jp-0109] Various changes related to Special Campaign 

- app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
- app/Http/Controllers/DonationController.php
- app/Http/Controllers/SpecialCampaignController.php
- resources/views/admin-pledge/special-campaign/create-edit.blade.php
- resources/views/donations/partials/special-campaign-pledge-detail-modal.blade.php
- resources/views/special-campaign/partials/pdf.blade.php
- resources/views/special-campaign/partials/special-campaign.blade.php
- resources/views/special-campaign/partials/summary.blade.php
- resources/views/special-campaign/wizard.blade.php
This branch contains various changes related to Special Campaign:
[jp-0109] Incorrect Special Campaigns list displayed for Admin - Maintain Special Campaign Pledge ([ticket)](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ACw_m_SthUCEwbKvj7OP3WUANMgW?Type=TaskLink&Channel=Link&CreatedTime=638455156856870000)
[jp-0109] Special campaign - Change the Back button UI to copy from the donation flow ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/219KGHygvUCQAtZo3F-pQWUAEAlh?Type=TaskLink&Channel=Link&CreatedTime=638455156615660000))
[jp-0109] Rename Special Campaign donation summary pdf ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/kmjjbUtVuE2lh9Op9dazR2UADfYj?Type=TaskLink&Channel=Link&CreatedTime=638455156463050000))
[jp-0109] Remove the …
> (TEST) [jp-0109] Various changes related to Special Campaign

- composer.lock
- tests/Feature/ChallengePageTest.php
March 2 - 2 HIGH vulnerabilities reported on Github.
phpseclib does not properly limit the ASN1 OID length High
#83 opened last week • Detected in phpseclib/phpseclib (Composer) • composer.lock
phpseclib a large prime can cause a denial of service High
#82 opened last week • Detected in phpseclib/phpseclib (Composer) • composer.lock
Found 2 security vulnerability advisories affecting 1 package:
| Package           | phpseclib/phpseclib                                                              |
| CVE               | CVE-2024-27354                                                                   |
| Title             | phpseclib a large prime can cause a denial of service …
> [jp-0111] Security update required -- 2 security vulnerability

- composer.lock
- tests/Feature/ChallengePageTest.php
March 2 - 2 HIGH vulnerabilities reported on Github.
phpseclib does not properly limit the ASN1 OID length High
#83 opened last week • Detected in phpseclib/phpseclib (Composer) • composer.lock
phpseclib a large prime can cause a denial of service High
#82 opened last week • Detected in phpseclib/phpseclib (Composer) • composer.lock
Found 2 security vulnerability advisories affecting 1 package:
> +-------------------+----------------------------------------------------------------------------------+
> | Package           | phpseclib/phpseclib                                                              |
> | CVE               | CVE-2024-27354                                                                   |
> | Title             | phpseclib a large prime can cause a denial of service …
> (TEST) [jp-0111] Security update required -- 2 security vulnerability

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Exports/OrgPartipationTrackersExport.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
- app/Jobs/OrgPartipationTrackersExportJob.php
- app/Models/BusinessUnit.php
- app/Models/EligibleEmployeeByBU.php
- resources/views/admin-report/org-partipation-tracker/index.blade.php
- resources/views/admin-report/partials/tabs.blade.php
- routes/web.php
- tests/Feature/ReportOrgPartipationTrackersTest.php
Background 
Each year on October 15, the PECSF HQ team downloads the eligible employee numbers it will use for the campaign. Using these Organization Participation Trackers are pre-populated and sent to each organization’s Lead Coordinator. The Lead Coordinator uses the Daily Campaign Update (view by department) to fill in their organization tracker. Theoretically, the Lead Coordinator can fill this out once or every day if they wish.  
Lead Coordinator will fill it in Oct 15 – to see progress 
Lead Coordinator will fill it in last day after campign – 
Lead Coordinator’s whose organization’s have 2/3 or 100% participation can submit their tracker and be awarded a participation certificate. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UlV69hNR0kGmxX3X2j2SvWUAGcdN?Type= …
> [jp-0110] PMVP (00) DEV - Organization Participation Trackers

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Exports/OrgPartipationTrackersExport.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
- app/Jobs/OrgPartipationTrackersExportJob.php
- app/Models/BusinessUnit.php
- app/Models/EligibleEmployeeByBU.php
- resources/views/admin-report/org-partipation-tracker/index.blade.php
- resources/views/admin-report/partials/tabs.blade.php
- routes/web.php
- tests/Feature/ReportOrgPartipationTrackersTest.php
Background 
Each year on October 15, the PECSF HQ team downloads the eligible employee numbers it will use for the campaign. Using these Organization Participation Trackers are pre-populated and sent to each organization’s Lead Coordinator. The Lead Coordinator uses the Daily Campaign Update (view by department) to fill in their organization tracker. Theoretically, the Lead Coordinator can fill this out once or every day if they wish.  
Lead Coordinator will fill it in Oct 15 – to see progress 
Lead Coordinator will fill it in last day after campign – 
Lead Coordinator’s whose organization’s have 2/3 or 100% participation can submit their tracker and be awarded a participation certificate. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UlV69hNR0kGmxX3X2j2SvWUAGcdN?Type= …
> (TEST) [jp-0110] PMVP (00) DEV - Organization Participation Trackers

- app/Http/Controllers/Admin/EligibleEmployeeSummaryMaintenanceController.php
- app/Http/Requests/EligibleEmployeeSummaryMaintenanceRequest.php
- app/Models/DailyCampaignView.php
- app/Models/EligibleEmployeeByBU.php
- database/migrations/2024_03_12_081003_add_audit_user_fields_eligible_eligible_employee_by_bus_table.php
- resources/views/admin-campaign/eligible-employee-summary/index.blade.php
- resources/views/admin-campaign/eligible-employee-summary/partials/model-create.blade.php
- resources/views/admin-campaign/eligible-employee-summary/partials/model-edit.blade.php
- resources/views/admin-campaign/eligible-employee-summary/partials/model-show.blade.php
- resources/views/admin-campaign/partials/tabs.blade.php
- routes/web.php
- [jp-0110] PMVP (00) DEV - Organization Participation Trackers ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UlV69hNR0kGmxX3X2j2SvWUAGcdN?Type=TaskLink&Channel=Link&CreatedTime=638458899361620000))
- [jp-0110] Dev - Add non-gov eligible ees manually and add to challenge page ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/kmXtcH6JbUmkE8zxGogk82UAMCKs?Type=TaskLink&Channel=Link&CreatedTime=638458898866330000))
> [jp-0110] Dev - Add non-gov eligible ees manually and add to challenge page

- app/Http/Controllers/Admin/EligibleEmployeeSummaryMaintenanceController.php
- app/Http/Requests/EligibleEmployeeSummaryMaintenanceRequest.php
- app/Models/DailyCampaignView.php
- app/Models/EligibleEmployeeByBU.php
- database/migrations/2024_03_12_081003_add_audit_user_fields_eligible_eligible_employee_by_bus_table.php
- resources/views/admin-campaign/eligible-employee-summary/index.blade.php
- resources/views/admin-campaign/eligible-employee-summary/partials/model-create.blade.php
- resources/views/admin-campaign/eligible-employee-summary/partials/model-edit.blade.php
- resources/views/admin-campaign/eligible-employee-summary/partials/model-show.blade.php
- resources/views/admin-campaign/partials/tabs.blade.php
- routes/web.php
- [jp-0110] PMVP (00) DEV - Organization Participation Trackers ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UlV69hNR0kGmxX3X2j2SvWUAGcdN?Type=TaskLink&Channel=Link&CreatedTime=638458899361620000))
- [jp-0110] Dev - Add non-gov eligible ees manually and add to challenge page ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/kmXtcH6JbUmkE8zxGogk82UAMCKs?Type=TaskLink&Channel=Link&CreatedTime=638458898866330000))
> (TEST) [jp-0110] Dev - Add non-gov eligible ees manually and add to challenge page

- app/Http/Requests/CampaignPledgeRequest.php
- resources/views/admin-pledge/campaign/wizard.blade.php
> (MASTER) [jp-0108] Various changes on Admin - Annual Campaign

- composer.lock
- tests/Feature/ChallengePageTest.php
March 2 - 2 HIGH vulnerabilities reported on Github.
phpseclib does not properly limit the ASN1 OID length High
#83 opened last week • Detected in phpseclib/phpseclib (Composer) • composer.lock
phpseclib a large prime can cause a denial of service High
#82 opened last week • Detected in phpseclib/phpseclib (Composer) • composer.lock
Found 2 security vulnerability advisories affecting 1 package:
> +-------------------+----------------------------------------------------------------------------------+
> | Package           | phpseclib/phpseclib                                                              |
> | CVE               | CVE-2024-27354                                                                   |
> | Title             | phpseclib a large prime can cause a denial of service …
> (MASTER) [jp-0111] Security update required -- 2 security vulnerability

- tests/Feature/EligibleEmployeeSummaryMaintenanceTest.php
> [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation

- tests/Feature/EligibleEmployeeSummaryMaintenanceTest.php
- [jp-0110] PMVP (00) DEV - Organization Participation Trackers ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UlV69hNR0kGmxX3X2j2SvWUAGcdN?Type=TaskLink&Channel=Link&CreatedTime=638458899361620000))
- [jp-0110] Dev - Add non-gov eligible ees manually and add to challenge page ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/kmXtcH6JbUmkE8zxGogk82UAMCKs?Type=TaskLink&Channel=Link&CreatedTime=638458898866330000))
> (TEST) [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation

- app/Http/Controllers/Api/SystemStatusController.php
- app/Http/Kernel.php
- app/Http/Middleware/ApiToken.php
- routes/api.php
To monitor the status of queues and task scheduling within a system or application, this task involves regularly checking the status of queues to ensure they are functioning properly and monitoring the scheduling of tasks to ensure they are being executed as intended. 
> [jp-0116] To monitor Queue and Task Scheduling Status

- app/Console/Kernel.php
- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0116] To monitor Queue and Task Scheduling Status (additional changes)

- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0116] To monitor Queue and Task Scheduling Status (fix typo and missing to include model class)

- app/Console/Kernel.php
- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0116] To monitor Queue and Task Scheduling Status (include queue job information)

- app/Console/Kernel.php
- app/Http/Controllers/Api/SystemStatusController.php
> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (include queue job information)

- app/Console/Commands/CopySpecialCampaignImagesInPublicFolder.php
- app/Http/Controllers/Admin/SpecialCampaignSetupController.php
- app/Models/SpecialCampaign.php
- database/migrations/2024_03_20_080537_add_file_in_special_campaigns_table.php
- database/seeders/SpecialCampaignImagesSeeder.php
Save the Special Campaign logo image to the database, ensuring benefits such as efficient storage and backup, and optionally move it to the public folder for recovery purpose.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/lXf9zK-V_ky6qN9R7yoIYGUAOELY?Type=TaskLink&Channel=Link&CreatedTime=638466420697850000)
> (TEST) [jp-0114] Special Campaign Setup -- store and retreive logo image onto/from database

- app/Console/Kernel.php
- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0116] To monitor Queue and Task Scheduling Status (add grace period when checking the job)

- app/Console/Kernel.php
- app/Http/Controllers/Api/SystemStatusController.php
> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (add grace period when checking the job)

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
- resources/views/admin-report/org-partipation-tracker/index.blade.php
> [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation (schedule task added)

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
- resources/views/admin-report/org-partipation-tracker/index.blade.php
> (TEST) [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation (schedule task added)

- app/Http/Controllers/Api/SystemStatusController.php
- routes/api.php
> [jp-0116] To monitor Queue and Task Scheduling Status (add for checking database status)

- app/Http/Controllers/Api/SystemStatusController.php
- routes/api.php
> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (add for checking database status)

- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0116] To monitor Database, Queue and Task Scheduling Status (always print in pretty format)

- app/Console/Commands/CopySpecialCampaignImagesInPublicFolder.php
- app/Http/Controllers/Admin/SpecialCampaignSetupController.php
- app/Models/SpecialCampaign.php
- database/migrations/2024_03_20_080537_add_file_in_special_campaigns_table.php
- database/seeders/SpecialCampaignImagesSeeder.php
Save the Special Campaign logo image to the database, ensuring benefits such as efficient storage and backup, and optionally move it to the public folder for recovery purpose.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/lXf9zK-V_ky6qN9R7yoIYGUAOELY?Type=TaskLink&Channel=Link&CreatedTime=638466420697850000)
> (MASTER) [jp-0114] Special Campaign Setup -- store and retreive logo image onto/from database

- tests/Feature/CharityListMaintenanceTest.php
- tests/Feature/ReportDonationUploadTest.php
> [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation (update feature test)

- tests/Feature/CharityListMaintenanceTest.php
- tests/Feature/ReportDonationUploadTest.php
> (TEST) [jp-0110] Dev - Add non-gov eligible ees manually and add to challenge page (update feature test)

- resources/views/admin/dashboard/index.blade.php
Isses:
1. The options on the page are read 2 times by the screen reader(SR). Issue for all the 4 options 
2. Links for buttons do not function on the click of Spacebar but only on Enter key. Issue for all the 4 options 
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/MkVDEIzryEaxVyB_op9xm2UADnUQ?Type=TaskLink&Channel=Link&CreatedTime=638475822593230000)
> [jp-0118] Pledge Administration Landing Page enhancement

- resources/views/admin/dashboard/index.blade.php
Isses:
1. The options on the page are read 2 times by the screen reader(SR). Issue for all the 4 options 
2. Links for buttons do not function on the click of Spacebar but only on Enter key. Issue for all the 4 options 
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/MkVDEIzryEaxVyB_op9xm2UADnUQ?Type=TaskLink&Channel=Link&CreatedTime=638475822593230000)
> (TEST) [jp-0118] Pledge Administration Landing Page enhancement

- resources/views/contact/index.blade.php
Issue:
The + button is read as +.  
Add an aria-label to the ‘+’ and ‘-’ buttons is it possible? 
> [jp-0119] FAQ page enhancement

- app/Console/Commands/CopyFSPoolCharityImagesInPublicFolder.php
- app/Console/Commands/CopySpecialCampaignImagesInPublicFolder.php
- app/Http/Controllers/Admin/FundSupportedPoolController.php
- app/Http/Controllers/Admin/SpecialCampaignSetupController.php
- app/Models/FSPoolCharity.php
- app/Models/SpecialCampaign.php
- database/migrations/2024_03_20_080537_add_file_in_special_campaigns_table.php
- database/migrations/2024_03_21_075257_add_file_in_f_s_pool_charities_table.php
- database/seeders/FSPoolCharityImagesSeeder.php
- database/seeders/SpecialCampaignImagesSeeder.php
> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (Merge branch 'master' into jp-0116)

- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0116] To monitor Queue and Task Scheduling Status (show UpTime info on database status)

- resources/views/donate-now/partials/amount.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/method-selection.blade.php
- resources/views/donate-now/partials/regional-pool.blade.php
- resources/views/donate-now/wizard.blade.php
> (TEST) [jp-0120] Copy the Donations Flow Style Changes to the Donate Now flow

- resources/views/donate-now/partials/amount.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/method-selection.blade.php
- resources/views/donate-now/partials/regional-pool.blade.php
- resources/views/donate-now/wizard.blade.php
> [jp-0120] Copy the Donations Flow Style Changes to the Donate Now flow

- resources/views/system-security/auditing/index.blade.php
- resources/views/system-security/export-audit-log/index.blade.php
To add a checkbox option to dynamically show/hide row detail information to make the table simply and clean look.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/tb4uaJqglUKTjVMv_6qNPGUALAHD?Type=TaskLink&Channel=Link&CreatedTime=638477567970330000)
> (TEST) [jp-0121] Auditing pages -- checkbox to dynamically show/hide detail value column

- resources/views/system-security/auditing/index.blade.php
- resources/views/system-security/export-audit-log/index.blade.php
To add a checkbox option to dynamically show/hide row detail information to make the table simply and clean look. 
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/tb4uaJqglUKTjVMv_6qNPGUALAHD?Type=TaskLink&Channel=Link&CreatedTime=638477567970330000)
> [jp-0121] Auditing pages -- checkbox to dynamically show/hide detail value column

- app/Exports/OrgPartipationTrackersExport.php
- app/Http/Controllers/ChallengeController.php
- resources/views/challenge/daily_campaign.blade.php
- resources/views/challenge/index.blade.php
- resources/views/challenge/org_participation_tracker.blade.php
- resources/views/challenge/partials/tabs.blade.php
- routes/web.php
- tests/Feature/ChallengePageTest.php
>  [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation (org tracker self-service)

- app/Exports/OrgPartipationTrackersExport.php
- app/Http/Controllers/ChallengeController.php
- resources/views/challenge/daily_campaign.blade.php
- resources/views/challenge/index.blade.php
- resources/views/challenge/org_participation_tracker.blade.php
- resources/views/challenge/partials/tabs.blade.php
- routes/web.php
- tests/Feature/ChallengePageTest.php
> (TEST) [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation (org tracker self-service) 

- resources/views/contact/index.blade.php
> [jp-0119] FAQ page enhancement (Merge branch 'master' )

- resources/views/contact/index.blade.php
> (TEST) [jp-0119] FAQ page enhancement (Merge branch 'master' )

- resources/views/contact/index.blade.php
> [jp-0119] FAQ page enhancement (additional change on element focus)

- resources/views/contact/index.blade.php
> (TEST) [jp-0119] FAQ page enhancement (additional change on element focus)

- app/Http/Controllers/Api/SystemStatusController.php
- package-lock.json
> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (Merge branch 'master') 

- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
> [jp-0120] Copy the Donations Flow Style Changes to the Donate Now flow (additional fix on 3, 5, 10)

- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
> (TEST) [jp-0120] Copy the Donations Flow Style Changes to the Donate Now flow (additional fix on 3, 5, 10)

- resources/views/donate-now/wizard.blade.php
- resources/views/donations/partials/history.blade.php
> [jp-0120] Copy the Donations Flow Style Changes to the Donate Now flow (2nd fix on item 3, 5, 10)

- resources/views/donations/partials/history.blade.php
> (TEST) [jp-0120] Copy the Donations Flow Style Changes to the Donate Now flow (2nd fix on item 3, 5, 10)

- resources/views/admin/dashboard/index.blade.php
Issues:
1. The options on the page are read 2 times by the screen reader(SR). Issue for all the 4 options 
2. Links for buttons do not function on the click of Spacebar but only on Enter key. Issue for all the 4 options 
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/MkVDEIzryEaxVyB_op9xm2UADnUQ?Type=TaskLink&Channel=Link&CreatedTime=638475822593230000)
> (MASTER) [jp-0118] Pledge Administration Landing Page enhancement

- resources/views/contact/index.blade.php
> (MASTER) [jp-0119] FAQ page enhancement

- resources/views/donate-now/partials/amount.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/partials/method-selection.blade.php
- resources/views/donate-now/partials/regional-pool.blade.php
- resources/views/donate-now/wizard.blade.php
- resources/views/donations/index.blade.php
- resources/views/donations/partials/history.blade.php
> (MASTER) [jp-0120] Copy the Donations Flow Style Changes to the Donate Now flow

- resources/views/system-security/auditing/index.blade.php
- resources/views/system-security/export-audit-log/index.blade.php
To add a checkbox option to dynamically show/hide row detail information to make the table simply and clean look.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/tb4uaJqglUKTjVMv_6qNPGUALAHD?Type=TaskLink&Channel=Link&CreatedTime=638477567970330000)
> (MASTER) [jp-0121] Auditing pages -- checkbox to dynamically show/hide detail value column

- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0116] To monitor Queue and Task Scheduling Status (6th add server name)

- app/Http/Controllers/Api/SystemStatusController.php
> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (6th add server name)

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Exports/OrgPartipationTrackersExport.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
- app/Http/Controllers/ChallengeController.php
- resources/views/admin-report/org-partipation-tracker/index.blade.php
- resources/views/challenge/daily_campaign.blade.php
- resources/views/challenge/index.blade.php
- resources/views/challenge/org_participation_tracker.blade.php
- resources/views/challenge/partials/tabs.blade.php
- routes/web.php
- tests/Feature/ChallengePageTest.php
- tests/Feature/CharityListMaintenanceTest.php
- tests/Feature/ReportDonationUploadTest.php
> [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation (merge with master)

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Exports/OrgPartipationTrackersExport.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
- app/Http/Controllers/ChallengeController.php
- resources/views/admin-report/org-partipation-tracker/index.blade.php
- resources/views/challenge/daily_campaign.blade.php
- resources/views/challenge/index.blade.php
- resources/views/challenge/org_participation_tracker.blade.php
- resources/views/challenge/partials/tabs.blade.php
- routes/web.php
- tests/Feature/ChallengePageTest.php
- tests/Feature/CharityListMaintenanceTest.php
- tests/Feature/ReportDonationUploadTest.php
> (TEST) [jp-0110] 2 tickets related to Maintenance Eligible Employee Summary and report generation (merge with master)

- app/Http/Controllers/Api/SystemStatusController.php
> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (7th fix the time for checking 2 conditionally run process)

- app/Console/Kernel.php
- app/Http/Controllers/Api/SystemStatusController.php
- app/Http/Kernel.php
- app/Http/Middleware/ApiToken.php
- routes/api.php
> (MASTER) [jp-0116] To monitor Queue, Database and Task Scheduling Status

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
> [jp-0110] PMVP (00) DEV - Organization Participation Trackers (use new field 'acronym' in business_units as report file name)

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Http/Controllers/Admin/OrgPartipationTractorReportController.php
> (TEST) [jp-0110] PMVP (00) DEV - Organization Participation Trackers (use new field 'acronym' in business_units as report file name)

- resources/views/admin-pledge/campaign/partials/amount.blade.php
- resources/views/admin-pledge/campaign/partials/charities.blade.php
- resources/views/admin-pledge/campaign/partials/method-selection.blade.php
- resources/views/admin-pledge/campaign/partials/profile.blade.php
- resources/views/admin-pledge/campaign/wizard.blade.php
Most of the issues was addressed and fixed except iItem 4 & 10, due to incompaible accessibility issue on the 3rd party library (select2), we need to do some research on how to address that, by replacing with difference library or dig into the library to investigate.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/c6NSaay76k6q6m1JAY_Q7mUAHT5n?Type=TaskLink&Channel=Link&CreatedTime=638490495677720000)
> [jp-0122] Admin - Create new annual pledge (improve issue 6, 7 and 16)

- resources/views/admin-pledge/campaign/partials/amount.blade.php
- resources/views/admin-pledge/campaign/partials/charities.blade.php
- resources/views/admin-pledge/campaign/partials/method-selection.blade.php
- resources/views/admin-pledge/campaign/partials/profile.blade.php
- resources/views/admin-pledge/campaign/wizard.blade.php
Most of the issues was addressed and fixed except iItem 4 & 10, due to incompaible accessibility issue on the 3rd party library (select2), we need to do some research on how to address that, by replacing with difference library or dig into the library to investigate.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/c6NSaay76k6q6m1JAY_Q7mUAHT5n?Type=TaskLink&Channel=Link&CreatedTime=638490495677720000)
> (TEST) [jp-0122] Admin - Create new annual pledge (improve issue 6, 7 and 16)

- app/Models/EligibleEmployeeByBU.php
> [jp-0110] PMVP (00) DEV - Organization Participation Trackers (add auditing on table eligible_employee_by_bu)

- resources/views/volunteer-profile/show.blade.php
- resources/views/volunteering/partials/training-guide-modal.blade.php
> (TEST) [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) (fix some typo)

- resources/views/volunteer-profile/show.blade.php
- resources/views/volunteering/partials/training-guide-modal.blade.php
> [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) (fix some typo)

- resources/views/volunteering/comminucation.blade.php
> [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) - Communications/Resources

- resources/views/volunteering/comminucation.blade.php
> (TEST) [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) - Communications/Resources

- app/Exports/VolunteerProfilesExport.php
- app/Http/Controllers/Admin/MaintainVolunteerProfileController.php
- app/Http/Controllers/VolunteerProfileController.php
- app/Http/Requests/MaintainVolunteerProfileRequest.php
- app/Models/EmployeeJob.php
- app/Models/VolunteerProfile.php
- database/factories/VolunteerProfileFactory.php
- resources/views/admin-volunteering/profile/create-edit.blade.php
- resources/views/volunteering/index.blade.php
- resources/views/volunteering/partials/communication-guide-modal.blade.php
- resources/views/volunteering/partials/learn-more-modal.blade.php
- resources/views/volunteering/partials/training-guide-modal.blade.php
- tests/Feature/AdminDonateNowPledgeTest.php
- tests/Feature/AdminVolunteerProfileTest.php
- tests/Feature/BusinessUnitTest.php
- tests/Feature/CampaignYearTest.php
- tests/Feature/VolunteerProfileTest.php
> (TEST) [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) - Update Training & Communication

- app/Exports/VolunteerProfilesExport.php
- app/Http/Controllers/Admin/MaintainVolunteerProfileController.php
- app/Http/Controllers/VolunteerProfileController.php
- app/Http/Requests/MaintainVolunteerProfileRequest.php
- app/Models/EmployeeJob.php
- app/Models/VolunteerProfile.php
- database/factories/VolunteerProfileFactory.php
- resources/views/admin-volunteering/profile/create-edit.blade.php
- resources/views/volunteering/index.blade.php
- resources/views/volunteering/partials/communication-guide-modal.blade.php
- resources/views/volunteering/partials/learn-more-modal.blade.php
- resources/views/volunteering/partials/training-guide-modal.blade.php
- tests/Feature/AdminDonateNowPledgeTest.php
- tests/Feature/AdminVolunteerProfileTest.php
- tests/Feature/BusinessUnitTest.php
- tests/Feature/CampaignYearTest.php
- tests/Feature/VolunteerProfileTest.php
> [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) - Update Training & Communication

- app/Http/Controllers/VolunteeringController.php
- resources/views/volunteering/index.blade.php
- resources/views/volunteering/partials/communication-guide-modal.blade.php
- resources/views/volunteering/partials/learn-more-modal.blade.php
- resources/views/volunteering/partials/training-guide-modal.blade.php
> [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) 

- app/Http/Controllers/VolunteeringController.php
- resources/views/volunteering/index.blade.php
- resources/views/volunteering/partials/communication-guide-modal.blade.php
- resources/views/volunteering/partials/learn-more-modal.blade.php
- resources/views/volunteering/partials/training-guide-modal.blade.php
This pull request is related to multiple changes on May 22. 
- [jp-0125d] Volunteering - Training [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7CkAU5t …
> (TEST) [jp-0125] Rewrite Volunteering Area (self-service and maintain by Admin + reporting) 

- resources/views/volunteering/partials/communication-guide-modal.blade.php
- resources/views/volunteering/partials/learn-more-modal.blade.php
- resources/views/volunteering/partials/training-guide-modal.blade.php
[jp-0125a] Volunteer landing page [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mnZ1m7eQMEKAyaC_ydw5DmUAFplk?Type=TaskLink&Channel=Link&CreatedTime=638500935244270000)]
[jp-0125b] Volunteer Admin Part 1 [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Q4b0rRcOC0-WsonJV3Uhx2UAFlnm?Type=TaskLink&Channel=Link&CreatedTime=638500935966650000)]
[jp-0125c] Volunteering - Learning [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2VI05lLGK0GOhgdOEAAWnmUAP23k?Type=TaskLink&Channel=Link&CreatedTime=638500936118130000)]
[jp-0125d] Volunteering - Training [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7CkAU5tef0GmG5O_bHZ562UALwSX?Type=TaskLink&Channel=Link&CreatedTime=638500936 …
> [jp-0125i] Volunteering: Slide number does not display correctly

- resources/views/volunteering/partials/learn-more-modal.blade.php
[jp-0125a] Volunteer landing page [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mnZ1m7eQMEKAyaC_ydw5DmUAFplk?Type=TaskLink&Channel=Link&CreatedTime=638500935244270000)]
[jp-0125b] Volunteer Admin Part 1 [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Q4b0rRcOC0-WsonJV3Uhx2UAFlnm?Type=TaskLink&Channel=Link&CreatedTime=638500935966650000)]
[jp-0125c] Volunteering - Learning [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2VI05lLGK0GOhgdOEAAWnmUAP23k?Type=TaskLink&Channel=Link&CreatedTime=638500936118130000)]
[jp-0125d] Volunteering - Training [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7CkAU5tef0GmG5O_bHZ562UALwSX?Type=TaskLink&Channel=Link&CreatedTime=638500936 …
> [jp-0125c] Volunteering -  Learning (additional changes on May 28 part 2)

- resources/views/volunteering/partials/communication-guide-modal.blade.php
[jp-0125a] Volunteer landing page [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mnZ1m7eQMEKAyaC_ydw5DmUAFplk?Type=TaskLink&Channel=Link&CreatedTime=638500935244270000)]
[jp-0125b] Volunteer Admin Part 1 [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Q4b0rRcOC0-WsonJV3Uhx2UAFlnm?Type=TaskLink&Channel=Link&CreatedTime=638500935966650000)]
[jp-0125c] Volunteering - Learning [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2VI05lLGK0GOhgdOEAAWnmUAP23k?Type=TaskLink&Channel=Link&CreatedTime=638500936118130000)]
[jp-0125d] Volunteering - Training [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7CkAU5tef0GmG5O_bHZ562UALwSX?Type=TaskLink&Channel=Link&CreatedTime=638500936 …
> [jp-0125e] Volunteering - Communications/Resources (additional changes on May 28 part 2)

- resources/views/volunteering/partials/communication-guide-modal.blade.php
[jp-0125a] Volunteer landing page [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mnZ1m7eQMEKAyaC_ydw5DmUAFplk?Type=TaskLink&Channel=Link&CreatedTime=638500935244270000)]
[jp-0125b] Volunteer Admin Part 1 [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Q4b0rRcOC0-WsonJV3Uhx2UAFlnm?Type=TaskLink&Channel=Link&CreatedTime=638500935966650000)]
[jp-0125c] Volunteering - Learning [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2VI05lLGK0GOhgdOEAAWnmUAP23k?Type=TaskLink&Channel=Link&CreatedTime=638500936118130000)]
[jp-0125d] Volunteering - Training [[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7CkAU5tef0GmG5O_bHZ562UALwSX?Type=TaskLink&Channel=Link&CreatedTime=638500936 …
> (TEST) [jp-0125e] Volunteering - Communications/Resources (additional changes on May 28 part 2)

- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0128] Improve the Task Scheduling Status Monitoring to conditionally skip checking based on the local env configuration (additional enhancement)

- resources/views/admin-volunteering/profile/create-edit.blade.php
- resources/views/volunteer-profile/partials/volunteer-details.blade.php
- [jp-0135] Volunteer Registration – First year [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Hb0f4qN9nUyHMOXxj5wa8WUANPEE?Type=TaskLink&Channel=Link&CreatedTime=638526991734370000)
- [jp-0135] Volunteer Registration - Profile  - Number of years [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/I5M2bdnDakGwbU2_PQ-cv2UAGObS?Type=TaskLink&Channel=Link&CreatedTime=638526992427850000)
> [jp-0135] Volunteer Registration  First year

- resources/views/admin-volunteering/profile/create-edit.blade.php
- resources/views/volunteer-profile/partials/volunteer-details.blade.php
[jp-0135] Volunteer Registration – First year [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Hb0f4qN9nUyHMOXxj5wa8WUANPEE?Type=TaskLink&Channel=Link&CreatedTime=638526991734370000)
[jp-0135] Volunteer Registration - Profile - Number of years [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/I5M2bdnDakGwbU2_PQ-cv2UAGObS?Type=TaskLink&Channel=Link&CreatedTime=638526992427850000)
> (TEST) [jp-0135] Volunteer Registration  First year

- resources/views/volunteer-profile/wizard.blade.php
Change the button from "register" to "update" on the last screen for updating the volunteer profile. Update the confirmation page for the volunteer profile (changes in attached document). 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/D9eA-6a1zk2UBA1t7teDXWUAA5J9?Type=TaskLink&Channel=Link&CreatedTime=638527013689670000)
> [jp-0136] Volunteering Profile - update

- resources/views/volunteer-profile/wizard.blade.php
Change the button from "register" to "update" on the last screen for updating the volunteer profile. Update the confirmation page for the volunteer profile (changes in attached document).
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/D9eA-6a1zk2UBA1t7teDXWUAA5J9?Type=TaskLink&Channel=Link&CreatedTime=638527013689670000)
> (TEST) [jp-0136] Volunteering Profile - update

- app/Http/Requests/MaintainVolunteerProfileRequest.php
- tests/Feature/AdminVolunteerProfileTest.php
- tests/Feature/VolunteerProfileTest.php
The validation messages were updated per request.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UoEnTR2UCEGVbF9P9eYjbGUAL1Z9?Type=TaskLink&Channel=Link&CreatedTime=638526801390630000)
> [jp-0133] Volunteering: Update validation message (additional changes and update feature test case)

- app/Http/Requests/MaintainVolunteerProfileRequest.php
- tests/Feature/AdminVolunteerProfileTest.php
- tests/Feature/VolunteerProfileTest.php
The validation messages were updated per request.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UoEnTR2UCEGVbF9P9eYjbGUAL1Z9?Type=TaskLink&Channel=Link&CreatedTime=638526801390630000)
> (TEST) [jp-0133] Volunteering: Update validation message (additional changes and update feature test case)

- resources/views/admin-volunteering/profile/create-edit.blade.php
- resources/views/volunteer-profile/partials/volunteer-details.blade.php
- resources/views/volunteer-profile/show.blade.php
[jp-0135] Volunteer Registration – First year [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Hb0f4qN9nUyHMOXxj5wa8WUANPEE?Type=TaskLink&Channel=Link&CreatedTime=638526991734370000)
[jp-0135] Volunteer Registration - Profile - Number of years [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/I5M2bdnDakGwbU2_PQ-cv2UAGObS?Type=TaskLink&Channel=Link&CreatedTime=638526992427850000)
> [jp-0135] Volunteer Registration  First year (fix bug on edit mode)

- resources/views/admin-volunteering/profile/create-edit.blade.php
- resources/views/volunteer-profile/partials/volunteer-details.blade.php
- resources/views/volunteer-profile/show.blade.php
[jp-0135] Volunteer Registration – First year [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Hb0f4qN9nUyHMOXxj5wa8WUANPEE?Type=TaskLink&Channel=Link&CreatedTime=638526991734370000)
[jp-0135] Volunteer Registration - Profile - Number of years [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/I5M2bdnDakGwbU2_PQ-cv2UAGObS?Type=TaskLink&Channel=Link&CreatedTime=638526992427850000)
> (TEST) [jp-0135] Volunteer Registration  First year (fix bug on edit mode)

- app/Http/Controllers/Admin/MaintainVolunteerProfileController.php
- resources/views/volunteer-profile/partials/recognition-items.blade.php
Remove the GAL option in step 2 of the volunteering registration (image in the document attached). Remove the radial button in front of "Use the following address:" Located: Volunteering > Register tile
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/nnEK4nKIW0KNkGMUEU5k9mUADBKV?Type=TaskLink&Channel=Link&CreatedTime=638526140667890000)
> (MASTER) [jp-0129] Volunteering Registration - address (remove debug statement)

- app/Models/VolunteerProfile.php
Remove "Out of Canada" as an option in the volunteer registration
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/hcwHTX_PX0qusDxiJEHPr2UAH6CU?Type=TaskLink&Channel=Link&CreatedTime=638526139581170000)
> (MASTER) [jp-0130] Volunteering Registration - address

- app/Http/Requests/MaintainVolunteerProfileRequest.php
- app/Http/Requests/VolunteerProfileRequest.php
- tests/Feature/AdminVolunteerProfileTest.php
- tests/Feature/VolunteerProfileTest.php
The validation messages were updated per request.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UoEnTR2UCEGVbF9P9eYjbGUAL1Z9?Type=TaskLink&Channel=Link&CreatedTime=638526801390630000)
> (MASTER) [jp-0133] Volunteering: Update validation message (additional changes and update feature test case)

- resources/views/admin-volunteering/profile/create-edit.blade.php
- resources/views/volunteer-profile/partials/volunteer-details.blade.php
- resources/views/volunteer-profile/show.blade.php
[jp-0135] Volunteer Registration – First year [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Hb0f4qN9nUyHMOXxj5wa8WUANPEE?Type=TaskLink&Channel=Link&CreatedTime=638526991734370000)
[jp-0135] Volunteer Registration - Profile - Number of years [ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/I5M2bdnDakGwbU2_PQ-cv2UAGObS?Type=TaskLink&Channel=Link&CreatedTime=638526992427850000)
> (MASTER) [jp-0135] Volunteer Registration First year

- app/Http/Controllers/ChallengeController.php
- resources/views/challenge/index.blade.php
Serveral enhancement on Statistic (Challenge) Page:
[jp-0137a] Enhancement - Daily Campaign Stats - Final Stats [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/T_dTCzJqVkuFqO0pzhBQWGUALT5B?Type=TaskLink&Channel=Link&CreatedTime=638533030443900000)
[jp-0137b] Enhancement - Challenge Page Export for end users [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ntd_9k4HD0eXVRmABfNNKGUAJtWa?Type=TaskLink&Channel=Link&CreatedTime=638533030776710000)
[jp-0137c] Enhancement - Org Tracker - availability requirements [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aJ72fFrt1UavEam3ITiNEGUAHxK5?Type=TaskLink&Channel=Link&CreatedTime=638533030953040000)
[jp-0137d] Challenge Page rename – to “Statistics Page Data” (back-end/admin) …
>  [jp-0137] Enhancement on Statistic (Challenge) Page (only final year output to pdf)

- app/Http/Controllers/ChallengeController.php
- resources/views/challenge/index.blade.php
Serveral enhancement on Statistic (Challenge) Page:
[jp-0137a] Enhancement - Daily Campaign Stats - Final Stats [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/T_dTCzJqVkuFqO0pzhBQWGUALT5B?Type=TaskLink&Channel=Link&CreatedTime=638533030443900000)
[jp-0137b] Enhancement - Challenge Page Export for end users [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ntd_9k4HD0eXVRmABfNNKGUAJtWa?Type=TaskLink&Channel=Link&CreatedTime=638533030776710000)
[jp-0137c] Enhancement - Org Tracker - availability requirements [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aJ72fFrt1UavEam3ITiNEGUAHxK5?Type=TaskLink&Channel=Link&CreatedTime=638533030953040000)
[jp-0137d] Challenge Page rename – to “Statistics Page Data” (back-end/admin) …
> (TEST)  [jp-0137] Enhancement on Statistic (Challenge) Page (only final year can export to pdf)

- database/seeders/DataFixFor_jp_0143_EE195765.php
EE 195765 
Pledge# 271
One-Time: 50 -->  0 
> [jp-0143] EE195765 Pledge# 271 -- Data Fix bi-weekly amount through backend

- database/seeders/DataFixFor_jp_0143_EE195765.php
EE 195765
Pledge# 271
One-Time: 50 --> 0
> (TEST) [jp-0143] EE195765 Pledge# 271 -- Data Fix bi-weekly amount through backend

- database/seeders/DataFixFor_jp_0143_EE195765.php
EE 195765
Pledge# 271
One-Time: NO Change
> [jp-0143] EE195765 Pledge# 271 -- Data Fix bi-weekly amount through backend (keep one-time CAD 50)

- database/seeders/DataFixFor_jp_0143_EE195765.php
EE 195765
Pledge# 271
One-Time: 50 --> 0
> (TEST) [jp-0143] EE195765 Pledge# 271 -- Data Fix bi-weekly amount through backend (keep one-time CAD 50)

- database/seeders/DataFixFor_jp_0143_EE195765.php
EE 195765
Pledge# 271
One-Time: NO Change
> (MASTER) [jp-0143] EE195765 Pledge# 271 -- Data Fix bi-weekly amount through backend 

- database/seeders/DataFixFor_jp_0150_EE185747.php
June 24 - Job require the change on pledge# 6184
EE 185747
Pledge# 6184
Biweekly : 0 --> 73.84
One-Time: 73.84 --> 0
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0AUZHZcvik-PxCpDEEYqwmUAOzr5?Type=TaskLink&Channel=Link&CreatedTime=638549237760650000)
> (TEST) [jp-0150] EE185747 Pledge# 6184 -- Data Fix bi-weekly amount through backend

- database/seeders/DataFixFor_jp_0150_EE185747.php
June 24 - Job require the change on pledge# 6184
EE 185747
Pledge# 6184
Biweekly :  0 --> 73.84 
One-Time:  73.84  --> 0 
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0AUZHZcvik-PxCpDEEYqwmUAOzr5?Type=TaskLink&Channel=Link&CreatedTime=638549237760650000)
> [jp-0150] EE185747 Pledge# 6184 -- Data Fix bi-weekly amount through backend

- database/seeders/DataFixFor_jp_0150_EE185747.php
June 24 - Job require the change on pledge# 6184
EE 185747
Pledge# 6184
Biweekly : 0 --> 73.84
One-Time: 73.84 --> 0
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0AUZHZcvik-PxCpDEEYqwmUAOzr5?Type=TaskLink&Channel=Link&CreatedTime=638549237760650000)
> (MASTER) [jp-0150] EE185747 Pledge# 6184 -- Data Fix bi-weekly amount through backend

- resources/views/volunteering/partials/training-guide-modal.blade.php
New link to PECSF 101 Video -  needs updating before August 1 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/xptvjYgmU0m_LI9xxPo4IWUAIyaM?Type=TaskLink&Channel=Link&CreatedTime=638569113933980000)
> [jp-0161] Update PECSF 101 Video in Volunteering /Training 

- resources/views/volunteering/partials/training-guide-modal.blade.php
New link to PECSF 101 Video - needs updating before August 1
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/xptvjYgmU0m_LI9xxPo4IWUAIyaM?Type=TaskLink&Channel=Link&CreatedTime=638569113933980000)
> (TEST) [jp-0161] Update PECSF 101 Video in Volunteering /Training 

- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/wizard.blade.php
Under Annual Campaign Pledge and Donate Now Pledge self service pages, make sure not to include charity on the list if it goes beyond the maximum limit
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/RKH6Gc4_NEaJNDFM5Eg6XGUAPF8k?Type=TaskLink&Channel=Link&CreatedTime=638569107225400000)
> [jp-0160] Avoid charity add on the list when beyond the maximum limit

- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/wizard.blade.php
Under Annual Campaign Pledge and Donate Now Pledge self service pages, make sure not to include charity on the list if it goes beyond the maximum limit
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/RKH6Gc4_NEaJNDFM5Eg6XGUAPF8k?Type=TaskLink&Channel=Link&CreatedTime=638569107225400000)
> (TEST) [jp-0160] Avoid charity add on the list when beyond the maximum limit

- resources/views/volunteering/partials/training-guide-modal.blade.php
New link to PECSF 101 Video - needs updating before August 1
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/xptvjYgmU0m_LI9xxPo4IWUAIyaM?Type=TaskLink&Channel=Link&CreatedTime=638569113933980000)
> (MASTER) [jp-0161] Update PECSF 101 Video in Volunteering /Training

- database/seeders/HistoricalChallengePageData_2023.php
- database/seeds/2023_final.csv
As per discussion update highlighted groups.
Jul 30 - see attached excel spreadsheet "2023_final_statictics_comparison_JP.xlsx" for the final figures which confirmed with Gillian.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/51q73bsTSkGBjhbivfAACWUAPRwu?Type=TaskLink&Channel=Link&CreatedTime=638579673899360000)
> [jp-0165] Challenge Page 2023 Data Update

- resources/views/annual-campaign/partials/choose-charity-js.blade.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donate-now/partials/choose-charity-js.blade.php
- resources/views/donate-now/wizard.blade.php
Under Annual Campaign Pledge and Donate Now Pledge self service pages, make sure not to include charity on the list if it goes beyond the maximum limit
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/RKH6Gc4_NEaJNDFM5Eg6XGUAPF8k?Type=TaskLink&Channel=Link&CreatedTime=638569107225400000)
> (MASTER) [jp-0160] Avoid charity add on the list when beyond the maximum limit 

- database/seeders/HistoricalChallengePageData_2023.php
- database/seeds/2023_final.csv
As per discussion update highlighted groups.
Jul 30 - see attached excel spreadsheet "2023_final_statictics_comparison_JP.xlsx" for the final figures which confirmed with Gillian.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/51q73bsTSkGBjhbivfAACWUAPRwu?Type=TaskLink&Channel=Link&CreatedTime=638579673899360000)
> (MASTER) jp-0165] Challenge Page 2023 Data Update

- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- app/Http/Controllers/ChallengeController.php
- app/Models/BankDepositForm.php
- resources/views/admin-pledge/event/edit.blade.php
- resources/views/admin-pledge/event/partials/form.blade.php
- resources/views/donate/partials/choose-charity.blade.php
- resources/views/volunteering/partials/add-organization.blade.php
- routes/web.php
- tests/Feature/AdminBankDepositFormTest.php
- tests/Feature/AdminSubmissionQueueTest.php
- tests/Feature/BankDepositFormTest.php
- tests/Feature/VolunteerProfileTest.php
[jp-0162a] Admin -- Enable administrators to modify the selected charities for the approved Event pledge  ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aFfCuJ4XUU6PNELH9UfyJ2UAEnsr?Type=TaskLink&Channel=Link&CreatedTime=638582085615650000))
[jp-0162b] Region appears blank when viewing an approved event ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/haRx1fxyj0S-0Y711KVf5mUACD_j?Type=TaskLink&Channel=Link&CreatedTime=638582085494090000))
> [jp-0162] Admin -- Enable administrators to modify the selected charities for the approved Event pledge

- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- app/Http/Controllers/ChallengeController.php
- app/Models/BankDepositForm.php
- resources/views/admin-pledge/event/edit.blade.php
- resources/views/admin-pledge/event/partials/form.blade.php
- resources/views/donate/partials/choose-charity.blade.php
- resources/views/volunteering/partials/add-organization.blade.php
- routes/web.php
- tests/Feature/AdminBankDepositFormTest.php
- tests/Feature/AdminSubmissionQueueTest.php
- tests/Feature/BankDepositFormTest.php
- tests/Feature/VolunteerProfileTest.php
[jp-0162a] Admin -- Enable administrators to modify the selected charities for the approved Event pledge ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aFfCuJ4XUU6PNELH9UfyJ2UAEnsr?Type=TaskLink&Channel=Link&CreatedTime=638582085615650000))
[jp-0162b] Region appears blank when viewing an approved event ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/haRx1fxyj0S-0Y711KVf5mUACD_j?Type=TaskLink&Channel=Link&CreatedTime=638582085494090000))
> (TEST) [jp-0162] Admin -- Enable administrators to modify the selected charities for the approved Event pledge

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- app/Http/Controllers/BankDepositFormController.php
Some of the BU's in the drop-down of the eform are duplicated.
The list:
Ministry of Citizens' Services
Ministry of Education and Child Care
Ministry of Finance
Ministry of Transportation and Infrastructure
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/_-dtlbZcyEWuYNRA_A4mNmUABlan?Type=TaskLink&Channel=Link&CreatedTime=638587254307990000)
> [jp-0162c] eForm - Duplicate BU in the drop-down list

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- app/Http/Controllers/BankDepositFormController.php
Some of the BU's in the drop-down of the eform are duplicated.
The list:
- Ministry of Citizens' Services
- Ministry of Education and Child Care
- Ministry of Finance
- Ministry of Transportation and Infrastructure
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/_-dtlbZcyEWuYNRA_A4mNmUABlan?Type=TaskLink&Channel=Link&CreatedTime=638587254307990000)
> (TEST) [jp-0162c] eForm - Duplicate BU in the drop-down list

- resources/views/admin-pledge/event/partials/form.blade.php
[jp-0162a] Admin -- Enable administrators to modify the selected charities for the approved Event pledge ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aFfCuJ4XUU6PNELH9UfyJ2UAEnsr?Type=TaskLink&Channel=Link&CreatedTime=638582085615650000))
> [jp-0162a] Admin -- Enable administrators to modify the selected charities for the approved Event pledge (additional change)

- resources/views/admin-pledge/event/partials/form.blade.php
[jp-0162a] Admin -- Enable administrators to modify the selected charities for the approved Event pledge ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aFfCuJ4XUU6PNELH9UfyJ2UAEnsr?Type=TaskLink&Channel=Link&CreatedTime=638582085615650000))
> (TEST) [jp-0162a] Admin -- Enable administrators to modify the selected charities for the approved Event pledge (additional change)

- app/Http/Controllers/Admin/EventSubmissionQueueController.php
- app/Http/Controllers/Admin/MaintainEventPledgeController.php
- app/Http/Controllers/BankDepositFormController.php
- app/Http/Controllers/ChallengeController.php
- app/Models/BankDepositForm.php
- resources/views/admin-pledge/event/edit.blade.php
- resources/views/admin-pledge/event/partials/form.blade.php
- resources/views/donate/partials/choose-charity.blade.php
- resources/views/volunteering/partials/add-organization.blade.php
- routes/web.php
- tests/Feature/AdminBankDepositFormTest.php
- tests/Feature/AdminSubmissionQueueTest.php
- tests/Feature/BankDepositFormTest.php
- tests/Feature/VolunteerProfileTest.php
[jp-0162a] Admin -- Enable administrators to modify the selected charities for the approved Event pledge ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aFfCuJ4XUU6PNELH9UfyJ2UAEnsr?Type=TaskLink&Channel=Link&CreatedTime=638582085615650000))
[jp-0162b] Region appears blank when viewing an approved event ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/haRx1fxyj0S-0Y711KVf5mUACD_j?Type=TaskLink&Channel=Link&CreatedTime=638582085494090000))
[jp-0162c] eForm - Duplicate BU in the drop-down list  ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/_-dtlbZcyEWuYNRA_A4mNmUABlan?Type=TaskLink&Channel=Link&CreatedTime=638587254307990000))
> (MASTER) [jp-0162] Admin -- Enable administrators to modify the selected charities for the approved Event pledge

- app/Console/Commands/UpdateEligibleEmployeeSnapshot.php
- app/Http/Controllers/Admin/ChallengeSettingsController.php
- app/Http/Controllers/ChallengeController.php
- app/Models/Setting.php
- database/migrations/2024_08_01_101435_add_snap_shot_date_in_settings_table.php
- resources/views/admin-campaign/challenge/index.blade.php
- resources/views/challenge/partials/tabs.blade.php
Add new fields for Eligible Employee Snapshot date 1 and date 2 added. Those fields will be used for determine when generate Eligible Employee snapshot and make the Org Participation Tracker report availability.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/1sJEqPKXAk-oFMOCHAEUkWUAFmwH?Type=TaskLink&Channel=Link&CreatedTime=638581416337480000)
> (MASTER) [jp-0168] Organization Participation Tracker must function on custom dates 

- resources/views/annual-campaign/wizard.blade.php
Change the text:
You can distribute your contributions to each charity here. Start from the top and specify the amount of percentage so that together they are total 100%.
To
You can distribute your contributions to each charity listed here. Start from the top and specify either the amount or percentage for each so that the total adds up to 100%
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/h170tdPtsEC9LJ9Le5c2Z2UAKmIu?Type=TaskLink&Channel=Link&CreatedTime=638603777945380000)
> (TEST) [jp-0174] Content error on Amount distribution page

- resources/views/annual-campaign/wizard.blade.php
Change the text: 
You can distribute your contributions to each charity here. Start from the top and specify the amount of percentage so that together they are total 100%.
To
You can distribute your contributions to each charity listed here. Start from the top and specify either the amount or percentage for each so that the total adds up to 100%
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/h170tdPtsEC9LJ9Le5c2Z2UAKmIu?Type=TaskLink&Channel=Link&CreatedTime=638603777945380000)
> [jp-0174] Content error on Amount distribution page

- resources/views/annual-campaign/wizard.blade.php
Change the text:
You can distribute your contributions to each charity here. Start from the top and specify the amount of percentage so that together they are total 100%.
To
You can distribute your contributions to each charity listed here. Start from the top and specify either the amount or percentage for each so that the total adds up to 100%
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/h170tdPtsEC9LJ9Le5c2Z2UAKmIu?Type=TaskLink&Channel=Link&CreatedTime=638603777945380000)
> (MASTER) [jp-0174] Content error on Amount distribution page

- app/Http/Controllers/BankDepositFormController.php
- app/Models/BankDepositForm.php
- app/Models/BusinessUnit.php
- app/Models/EmployeeJob.php
- app/Models/Pledge.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donations/index.blade.php
- tests/Feature/AdminBankDepositFormTest.php
- tests/Feature/AdminCampaignPledgeTest.php
- tests/Feature/AdminSubmissionQueueTest.php
- tests/Feature/AdminVolunteerProfileTest.php
- tests/Feature/AnnualCampaignTest.php
- tests/Feature/BankDepositFormTest.php
- tests/Feature/ChallengePageTest.php
- tests/Feature/ChallengeSettingsTest.php
Employee103 - emp id 013238 had a 2025 annual pledge, which admin cancelled. The amounts on the donation history page and the volunteer profile page now differ. Not able to find the root cause.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/rVjfXqgFzEarpWXxUXV7UGUAMLSK?Type=TaskLink&Channel=Link&CreatedTime=638604641010020000)
> [jp-0179] Inconsistency in the numbers on the volunteer profile and donation history page

- app/Http/Controllers/BankDepositFormController.php
- app/Models/BankDepositForm.php
- app/Models/BusinessUnit.php
- app/Models/EmployeeJob.php
- app/Models/Pledge.php
- resources/views/annual-campaign/wizard.blade.php
- resources/views/donations/index.blade.php
- tests/Feature/AdminBankDepositFormTest.php
- tests/Feature/AdminCampaignPledgeTest.php
- tests/Feature/AdminSubmissionQueueTest.php
- tests/Feature/AdminVolunteerProfileTest.php
- tests/Feature/AnnualCampaignTest.php
- tests/Feature/BankDepositFormTest.php
- tests/Feature/ChallengePageTest.php
- tests/Feature/ChallengeSettingsTest.php
Employee103 - emp id 013238 had a 2025 annual pledge, which admin cancelled. The amounts on the donation history page and the volunteer profile page now differ. Not able to find the root cause.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/rVjfXqgFzEarpWXxUXV7UGUAMLSK?Type=TaskLink&Channel=Link&CreatedTime=638604641010020000)
> (TEST) [jp-0179] Inconsistency in the numbers on the volunteer profile and donation history page

- database/seeders/DuplicateBCPCampaignPledgesSeeder.php
> [jp-0192] 40C Creation for BCPS (create organization BCP in seeder)

- Dockerfile
- composer.json
- composer.lock
- package-lock.json
> [upgrade_10_to_11] Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3

- app/Exports/OrgPartipationTrackersExport.php
Scenario
Menu: Administration > Reporting > Program Reports > Organization Participation Trackers
1. Select 2024  and click 'Generate' to generate the Organization Participation Trackers Report 
2. click any filename (except first row) to download and got the following error message 
Unable to retrieve the file_size for file at location: OrgPartipationTracker_2024_DBC_2024-09-01.xlsx.
Root cause: bug in the program, the files were deleted too quickly by the cleanup function. 
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/gchoig6lwkamH6FY0COqRmUAP9f7?Type=TaskLink&Channel=Link&CreatedTime=638641873710090000)
> [jp-0199] Organization Tracker Report -- Unable to retrieve the file size for file at location

- app/Exports/OrgPartipationTrackersExport.php
Scenario
Menu: Administration > Reporting > Program Reports > Organization Participation Trackers
1. Select 2024  and click 'Generate' to generate the Organization Participation Trackers Report 
2. click any filename (except first row) to download and got the following error message 
Unable to retrieve the file_size for file at location: OrgPartipationTracker_2024_DBC_2024-09-01.xlsx.
Root cause: bug in the program, the files were deleted too quickly by the cleanup function. 
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/gchoig6lwkamH6FY0COqRmUAP9f7?Type=TaskLink&Channel=Link&CreatedTime=638641873710090000)
> (TEST) [jp-0199] Organization Tracker Report -- Unable to retrieve the file size for file at location

- app/Console/Kernel.php
> [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error

- app/Console/Kernel.php
> (TEST) [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error

- app/Exports/OrgPartipationTrackersExport.php
Scenario
Menu: Administration > Reporting > Program Reports > Organization Participation Trackers
1. Select 2024  and click 'Generate' to generate the Organization Participation Trackers Report 
2. click any filename (except first row) to download and got the following error message 
Unable to retrieve the file_size for file at location: OrgPartipationTracker_2024_DBC_2024-09-01.xlsx.
Root cause: bug in the program, the files were deleted too quickly by the cleanup function. 
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/gchoig6lwkamH6FY0COqRmUAP9f7?Type=TaskLink&Channel=Link&CreatedTime=638641873710090000)
> (MASTER) [jp-0199] Organization Tracker Report -- Unable to retrieve the file_size for file at location

- Dockerfile
- composer.json
- composer.lock
- package-lock.json
> [upgrade_10_to_11] Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (merge master)

- app/Console/Commands/ExportDatabaseToBI.php
- app/Exports/OrgPartipationTrackersExport.php
>  [jp-0192] 40C Creation for BCPS (merge with the latest master Oct 16) 

- database/seeders/DuplicateBCPCampaignPledgesSeeder.php
> (TEST)  [jp-0192] 40C Creation for BCPS (merge with the latest master Oct 16) 

- app/Console/Commands/ExportDatabaseToBI.php
- app/Exports/OrgPartipationTrackersExport.php
> [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error (update schedule time)

- app/Console/Kernel.php
> (TEST) [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error (update schedule time)

- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
Add a pop-up message (to say that the number will change upon submission) when the 'type' of eForm changes as a result of editing by admin.
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/wq6HZh2keUuVEs64hNZqemUAGiFG?Type=TaskLink&Channel=Link&CreatedTime=638652098064930000)
> [jp-0202] Admin eForm - pop-up message appears when changing the event type 

- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
Add a pop-up message (to say that the number will change upon submission) when the 'type' of eForm changes as a result of editing by admin.
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/wq6HZh2keUuVEs64hNZqemUAGiFG?Type=TaskLink&Channel=Link&CreatedTime=638652098064930000)
> (TEST)  [jp-0202] Admin eForm - pop-up message appears when changing the event type

- app/Console/Kernel.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/contact/index.blade.php
- server_files/php.ini
> [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3

- app/Console/Kernel.php
Root Cause:
Important: noticed that the ImportJobData is taking longer (more than 20 mins) in Production, need to adjust the start time of some tasks.
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/MCn4Pv0iPkypbAL5wgjvP2UAAFHP?Type=TaskLink&Channel=Link&CreatedTime=638658992156280000)
> (MASTER) [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error & reschedule some tasks 

- app/Http/Controllers/BankDepositFormController.php
Resolve 2 issues reported on the laravel.log files:
[jp-0203a] eForm - Attempt to assign property 'business_unit_id' on null ([ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/YnnZtj6zNEKDAXiiCdwj_WUAN7WW?Type=TaskLink&Channel=Link&CreatedTime=638664212203970000))
[jp-0203b] eForm - count(): Argument https://github.com/bcgov/PECSF/issues/1 ($value) must be of type Countable|array, null given ([ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/X9m6KGy6QEa2dKSEiqMvc2UAH6Mn?Type=TaskLink&Channel=Link&CreatedTime=638664212513860000))
> (TEST) [jp-0203] eForm - resolve the issues reported on the log files

- app/Http/Controllers/BankDepositFormController.php
Resolve 2 issues  reported on the laravel.log files:
[jp-0203a] eForm - Attempt to assign property 'business_unit_id' on null  ([ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/YnnZtj6zNEKDAXiiCdwj_WUAN7WW?Type=TaskLink&Channel=Link&CreatedTime=638664212203970000))
[jp-0203b] eForm -  count(): Argument #1 ($value) must be of type Countable|array, null given ([ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/X9m6KGy6QEa2dKSEiqMvc2UAH6Mn?Type=TaskLink&Channel=Link&CreatedTime=638664212513860000))
> [jp-0203] eForm - resolve the issues reported on the log files

- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
Add a pop-up message (to say that the number will change upon submission) when the 'type' of eForm changes as a result of editing by admin.
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/wq6HZh2keUuVEs64hNZqemUAGiFG?Type=TaskLink&Channel=Link&CreatedTime=638652098064930000)
> (MASTER) [jp-0202] Admin eForm - pop-up message appears when changing the event type

- Dockerfile
- composer.json
- composer.lock
- package-lock.json
- server_files/php.ini
Dependabot alerts (Github) reported HIGH vulnerabilities. Run composer audit and npm audit, a couple of packages required update:
[ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/PLvpkEk1NkWbbNmfV_P6MWUAANE2?Type=TaskLink&Channel=Link&CreatedTime=638665269908590000)
> [jp-0205] Security update required -- HIGH security vulnerability

- app/Console/Kernel.php
- database/seeders/DuplicateBCPCampaignPledgesSeederForCalendarYear2025.php
- database/seeders/DuplicateBCPEventPledgesSeederForCalendarYear2025.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/contact/index.blade.php
> [jp-0192] 40C Creation for BCPS (new seeder for calendar year 2025)

- app/Console/Kernel.php
- database/seeders/DuplicateBCPCampaignPledgesSeederForCalendarYear2025.php
- database/seeders/DuplicateBCPEventPledgesSeederForCalendarYear2025.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/contact/index.blade.php
> (TEST) [jp-0192] 40C Creation for BCPS  (new seeder for calendar year 2025)

- app/Console/Kernel.php
Since Nov 8, the scheduled process 'ImportEmployeeJob' has not been triggered or run in the Production region, and we have had to run it manually."
Modified the kernel.php file to adjust the environment checking by APP::environment statement.
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/jmAXKyUKEkys64NwdQtDbGUAGIcR?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> (TEST) [jp-0206] Scheduler - ImportEmployeeJob process was not triggered in the Production region 

- app/Console/Kernel.php
Since Nov 8, the scheduled process 'ImportEmployeeJob' has not been triggered or run in the Production region, and we have had to run it manually."
Modified the kernel.php file to adjust the environment checking by APP::environment statement.  
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/jmAXKyUKEkys64NwdQtDbGUAGIcR?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> [jp-0206] Scheduler - ImportEmployeeJob process was not triggered in the Production region

- composer.lock
Found 1 security vulnerability advisory affecting 1 package:
| Severity          | high                                                                             |
| CVE               | CVE-2024-52301                                                                   |
| Title             | Laravel environment manipulation via query string                                |
| URL               | https://github.com/advisories/GHSA-gv7v-rgg6-548h                                |
| Affected versions | >=11.0.0,<11.31.0|>=10.0.0,<10.48.23|>=9.0.0,<9.52.17|>=8.0.0,<8.83.28 …
> [jp-0205] Security update required -- HIGH security vulnerability (laravel/framework from 10.48.22 to 10.48.23)

- composer.lock
composer audit
Found 1 security vulnerability advisory affecting 1 package:
| Package | laravel/framework |
| Severity | high |
| CVE | https://github.com/advisories/GHSA-gv7v-rgg6-548h |
| Title | Laravel environment manipulation via query string |
| URL | https://github.com/advisories/GHSA-gv7v-rgg6-548h |
| Affected versions | >=11.0.0,<11.31.0|>=10.0.0,<10.48.23|>=9.0.0,<9.52.17|>=8.0.0,<8.83.28|>=7.0.0,< |
| | 7.30.7|<6.20.45 |
| Reported at | 2024-11-12T22:08:42+00:00 |
Found 1 abandoned package:
+------------------------+-------------------------------------------------------- …
> (TEST) [jp-0205] Security update required -- HIGH security vulnerability (laravel/framework from 10.48.22 to 10.48.23)

- app/Console/Kernel.php
Since Nov 8, the scheduled process 'ImportEmployeeJob' has not been triggered or run in the Production region, and we have had to run it manually."
Modified the kernel.php file to adjust the environment checking by APP::environment statement.
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/jmAXKyUKEkys64NwdQtDbGUAGIcR?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> (MASTER) [jp-0206] Scheduler - ImportEmployeeJob process was not triggered in the Production region

- app/Console/Kernel.php
- database/seeders/DuplicateBCPCampaignPledgesSeederForCalendarYear2025.php
- database/seeders/DuplicateBCPEventPledgesSeederForCalendarYear2025.php
- resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
- resources/views/contact/index.blade.php
> (MASTER) [jp-0192] 40C Creation for BC Pension Corporation (BCP)

- config/mail.php
Release and Support: Regular updates till August 2024 and security patches until February 2025.
Why Upgrade?:
Faster performance due to improved routing and caching.
Enhanced security features.
New [developer tools](https://daily.dev/blog/firefox-enhancements-for-developers) and simplified upgrade process.
Full compatibility with [PHP 8.2](https://daily.dev/blog/php-trends-for-2024).
New Features:
Simplified project structure with fewer preset directories.
Configuration and settings streamlined into .env files.
Enhanced data handling and …
> (TEST) [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (Fix Laravel 11 with symfony/mailer v7.2.0 issue)

- app/Http/Controllers/Api/SystemStatusController.php
> [jp-0211] Improve the Task Scheduling Status Monitoring for lower regions)

- tests/Browser/ExampleTest.php
> [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (UPDATE ExampleTest.php)

- database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "135016"
>  [jp-0212] Non-gov Pledge Updates (BCS 080964 / LA135016) revised

- database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "135016"
>  (TEST) [jp-0212] Non-gov Pledge Updates (BCS 081027/ LA135016) revised

- app/Http/Requests/CampaignPledgeRequest.php
- app/Http/Requests/DonateNowPledgeRequest.php
- app/Http/Requests/MaintainVolunteerProfileRequest.php
- app/Http/Requests/SpecialCampaignPledgeRequest.php
BC Pension Employee Katherine S. Betts name needs the . removed from the first name box. Only letters, hyphens, spaces are allowed. It is preventing any further updates to the pledges being made.
PECSF ID 147846
Transaction ID: 12078 and 12293
Feb 5 - Adjust the validation rule and allow the name contain letters, periods and spaces on 4 areas:
Administration > Pledge Administration > Maintain EE Pledges
Administration > Pledge Administration > Maintain Donate Now Pledges
Administration > Pledge Administration > Maintain Special Campaign Pledges
Administration > Volunteering > Maintain Volunteer
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/pOnNQZv0ak6YvWY8j2sVrGUABWsO?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> (MASTER) [jp-0216] Update First Name for BCP EE

- app/Http/Requests/CampaignPledgeRequest.php
- app/Http/Requests/DonateNowPledgeRequest.php
- app/Http/Requests/MaintainVolunteerProfileRequest.php
- app/Http/Requests/SpecialCampaignPledgeRequest.php
- resources/views/vendor/adminlte/auth/login.blade.php
- resources/views/volunteering/partials/learn-more-modal.blade.php
>  [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (demo env added)

- Dockerfile
This Production migration have 1 tickets (1 branch) 
[jp-0217] Fix Production Deployment error -- unable to resolve host address 'packages.sury.org' on 
**Pre Migration Steps:**
1. Request User to setup planned maintenance schedule timeframe in Production.
**Post Migration Steps:**
1. php artisan optimize:clear
2. make sure all POD must be restarted 
3. make background queue process started on each POD (command: ps -eF )
> Production Migration on Feb 8, 2025 16:30 (Urgent fix Production Deployment error) 

- Dockerfile
>  [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (merge jp-0217)

- app/Http/Controllers/Admin/VolunteerProfileUploadController.php
- app/Imports/VolunteerProfilesGovImport.php
- app/Imports/VolunteerProfilesNonGovImport.php
- app/Jobs/VolunteerProfilesImportJob.php
- app/Models/VolunteerProfile.php
- resources/views/admin-volunteering/partials/tabs.blade.php
- resources/views/admin-volunteering/upload-profile/index.blade.php
- routes/web.php
At the end of each campaign a list of volunteers (see attached spreadsheet) will need to be uploaded into the system.  This year will be the first upload into the system.  Once the upload is complete, a template for the data will need to be created next to make it easier to upload volunteer data.  
Questions
Will this always be a developer task? 
Is there a way for PECSF HQ staff to upload the information in a batch?  …
> [jp-0215] Admin - Reporting - Program Reports - Volunteer Profile - Upload Campaign 2024 list of volunteers

- app/Http/Controllers/Admin/VolunteerProfileUploadController.php
- app/Imports/VolunteerProfilesGovImport.php
- app/Imports/VolunteerProfilesNonGovImport.php
- app/Jobs/VolunteerProfilesImportJob.php
- app/Models/VolunteerProfile.php
- resources/views/admin-volunteering/partials/tabs.blade.php
- resources/views/admin-volunteering/upload-profile/index.blade.php
- routes/web.php
At the end of each campaign a list of volunteers (see attached spreadsheet) will need to be uploaded into the system. This year will be the first upload into the system. Once the upload is complete, a template for the data will need to be created next to make it easier to upload volunteer data.
Questions
Will this always be a developer task?
Is there a way for PECSF HQ staff to upload the information in a batch?
> (TEST) [jp-0215] Admin - Reporting - Program Reports - Volunteer Profile - Upload Campaign 2024 list of volunteers

- Dockerfile
Update Dockerfile on line 23
FROM php:8.3-apache-bulleye to  FROM php:8.3-apache
> (TEST) [jp-0217] Fix Production Deployment error -- unable to resolve host address 'packages.sury.org'

- Dockerfile
Update Dockerfile on line 23
FROM php:8.3-apache-bulleyes to  FROM php:8.3-apache
> (MASTER)  [jp-0217] Fix Production Deployment error -- unable to resolve host address 'packages.sury.org'

- database/seeders/UserTableSeeder.php
Release and Support: Regular updates till August 2024 and security patches until February 2025.
Why Upgrade?:
Faster performance due to improved routing and caching.
Enhanced security features.
New [developer tools](https://daily.dev/blog/firefox-enhancements-for-developers) and simplified upgrade process.
Full compatibility with [PHP 8.2](https://daily.dev/blog/php-trends-for-2024).
New Features:
Simplified project structure with fewer preset directories.
Configuration and settings streamlined into .env files.
Enhanced data handling and …
> [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (remove User::trunate in UserTableSeeder file)

- database/seeders/UserTableSeeder.php
Release and Support: Regular updates till August 2024 and security patches until February 2025.
Why Upgrade?:
Faster performance due to improved routing and caching.
Enhanced security features.
New [developer tools](https://daily.dev/blog/firefox-enhancements-for-developers) and simplified upgrade process.
Full compatibility with [PHP 8.2](https://daily.dev/blog/php-trends-for-2024).
New Features:
Simplified project structure with fewer preset directories.
Configuration and settings streamlined into .env files.
Enhanced data handling and …
> (TEST) [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (remove User::trunate in UserTableSeeder file)

- app/Imports/VolunteerProfilesGovImport.php
- resources/views/admin-volunteering/upload-profile/index.blade.php
- routes/web.php
At the end of each campaign a list of volunteers (see attached spreadsheet) will need to be uploaded into the system. This year will be the first upload into the system. Once the upload is complete, a template for the data will need to be created next to make it easier to upload volunteer data.
Questions
Will this always be a developer task?
Is there a way for PECSF HQ staff to upload the information in a batch?
> [jp-0215] Admin - Reporting - Program Reports - Volunteer Profile - Upload Campaign 2024 list of volunteers (merge to latest master)

- app/Imports/VolunteerProfilesGovImport.php
- resources/views/admin-volunteering/upload-profile/index.blade.php
- routes/web.php
At the end of each campaign a list of volunteers (see attached spreadsheet) will need to be uploaded into the system. This year will be the first upload into the system. Once the upload is complete, a template for the data will need to be created next to make it easier to upload volunteer data.
Questions
Will this always be a developer task?
Is there a way for PECSF HQ staff to upload the information in a batch?
> (TEST)  [jp-0215] Admin - Reporting - Program Reports - Volunteer Profile - Upload Campaign 2024 list of volunteers (merge to latest master)

- Dockerfile
--> 6ee56ade8303
[2/2] STEP 9/33: RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
--2025-03-07 03:17:58-- https://packages.sury.org/php/apt.gpg
> Update Dockerfile for resolving the failed: Temporary failure in name resolution issue

- composer.json
- composer.lock
- database/seeders/DataFixFor_jp_0218_DonateNowPledges_298_299.php
- package-lock.json
> (TEST) [jp-0220] Security update required -- HIGH security vulnerability 

- composer.json
- composer.lock
- database/seeders/DataFixFor_jp_0218_DonateNowPledges_298_299.php
- package-lock.json
> [jp-0220] Security update required -- HIGH security vulnerability 

- database/migrations/2023_07_22_230401_create_visits_monitoring_table.php
- database/migrations/2023_07_23_145723_create_actions_monitoring_table.php
- database/migrations/2023_07_25_132642_create_authentications_monitoring_table.php
> [jp-0220] Security update required -- HIGH security vulnerability (additional migration files required)

- database/migrations/2023_07_22_230401_create_visits_monitoring_table.php
- database/migrations/2023_07_23_145723_create_actions_monitoring_table.php
- database/migrations/2023_07_25_132642_create_authentications_monitoring_table.php
> (TEST) [jp-0220] Security update required -- HIGH security vulnerability (additional migration files required)

- config/user-monitoring.php
> [jp-0220] Security update required -- HIGH security vulnerability (cfg file also required)

- app/Http/Kernel.php
- app/Http/Middleware/VisitMonitoringMiddleware.php
> [jp-0220] Security update required -- HIGH security vulnerability (additional changes)

- composer.lock
- database/migrations/2023_07_22_230401_create_visits_monitoring_table.php
- database/migrations/2023_07_23_145723_create_actions_monitoring_table.php
- database/migrations/2023_07_25_132642_create_authentications_monitoring_table.php
> (TEST) [jp-0220] Security update required -- HIGH security vulnerability (package data structure changed)

- app/Http/Kernel.php
- app/Http/Middleware/VisitMonitoringMiddleware.php
- composer.lock
- database/migrations/2023_07_22_230401_create_visits_monitoring_table.php
- database/migrations/2023_07_23_145723_create_actions_monitoring_table.php
- database/migrations/2023_07_25_132642_create_authentications_monitoring_table.php
> (TEST) [jp-0220] Security update required -- HIGH security vulnerability (additional changes)

- app/Http/Middleware/VisitMonitoringMiddleware.php
> [jp-0220] Security update required -- HIGH security vulnerability (update middleware)

- app/Http/Middleware/VisitMonitoringMiddleware.php
> (TEST) [jp-0220] Security update required -- HIGH security vulnerability (update middleware)

- app/Http/Controllers/Admin/VolunteerProfileUploadController.php
- app/Imports/VolunteerProfilesGovImport.php
- app/Imports/VolunteerProfilesNonGovImport.php
- app/Jobs/VolunteerProfilesImportJob.php
- app/Models/VolunteerProfile.php
- resources/views/admin-volunteering/partials/tabs.blade.php
- resources/views/admin-volunteering/upload-profile/index.blade.php
- routes/web.php
At the end of each campaign a list of volunteers (see attached spreadsheet) will need to be uploaded into the system. This year will be the first upload into the system. Once the upload is complete, a template for the data will need to be created next to make it easier to upload volunteer data.
Questions
Will this always be a developer task?
Is there a way for PECSF HQ staff to upload the information in a batch?
> (MASTER) [jp-0215] Admin - Reporting - Program Reports - Volunteer Profile - Upload Campaign 2024 list of volunteers

- app/Http/Kernel.php
- app/Http/Middleware/VisitMonitoringMiddleware.php
- composer.json
- composer.lock
- config/user-monitoring.php
- database/migrations/2023_07_22_230401_create_visits_monitoring_table.php
- database/migrations/2023_07_23_145723_create_actions_monitoring_table.php
- database/migrations/2023_07_25_132642_create_authentications_monitoring_table.php
- package-lock.json
> (MASTER) [jp-0220] Security update required -- HIGH security vulnerability 

- app/Http/Controllers/Auth/KeycloakLoginController.php
> (TEST) [jp-0222] Keycloak 26 upgrade -- legacy redirect_url parameter is no longer supported (additional parameter required by keycloak)

- app/Console/Kernel.php
- app/Http/Controllers/Auth/KeycloakLoginController.php
- app/Listeners/LogFailedLogin.php
- app/Providers/EventServiceProvider.php
**Issue**
On Production, the ImportEmployeeJob wasn't triggered couple of time without any issue. would like to try difference time to see any improvement. 
"name": "command:ImportEmployeeJob",
"cron": "0 4 * * 1-5",
"previous schedule time": "2025-03-25 04:00:00",
"last completed start time": "2025-03-24 04:00:27",
"last completed end time": "2025-03-24 04:10:58",
"next schedule time": "2025-03-26 04:00:00"
**Action**
Reschedule ImportEmployeeJob from 4:00am to 4:05am
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/JGj5EDIuqEu_kasUhEOuMWUAAHki?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> (TEST) [jp-0224] Reschedule ImportEmployeeJob from 4:00am to 4:05am

- app/Console/Kernel.php
- app/Http/Controllers/Auth/KeycloakLoginController.php
- app/Listeners/LogFailedLogin.php
- app/Providers/EventServiceProvider.php
**Issue**
On Production, the ImportEmployeeJob wasn't triggered couple of time without any issue. would like to try difference time to see any improvement. 
"name": "command:ImportEmployeeJob",
"cron": "0 4 * * 1-5",
"previous schedule time": "2025-03-25 04:00:00",
"last completed start time": "2025-03-24 04:00:27",
"last completed end time": "2025-03-24 04:10:58",
"next schedule time": "2025-03-26 04:00:00"
**Action**
Reschedule ImportEmployeeJob from 4:00am to 4:05am
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/JGj5EDIuqEu_kasUhEOuMWUAAHki?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> [jp-0224]  Reschedule ImportEmployeeJob from 4:00am to 4:05am

- app/Http/Controllers/System/UserActivityController.php
Need to create an area in the administrative side of the PECSF application to view donor and volunteer analytics.
For example:
How many users access the application?
How many users set up a pledge?
How long did it take to set up a donation?
How many users visit the volunteering section?
What is the traffic on each volunteering page?
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/YduahGL_R02M1OR4rYu4E2UAOwGI?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> [jp-0221] Donor and Volunteer Analytics (part 6 - update access for admin)

- app/Http/Controllers/System/UserActivityController.php
Need to create an area in the administrative side of the PECSF application to view donor and volunteer analytics.
For example:
How many users access the application?
How many users set up a pledge?
How long did it take to set up a donation?
How many users visit the volunteering section?
What is the traffic on each volunteering page?
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/YduahGL_R02M1OR4rYu4E2UAOwGI?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> (TEST) [jp-0221] Donor and Volunteer Analytics (part 6 - update access for admin)

- resources/views/admin-campaign/campaignyears/index.blade.php
- resources/views/volunteer-profile/wizard.blade.php
2025
May 13 - James & Kristina - review and re-test Volunteer Renewal process, and a couple minor enhancement suggested for avoid confusion.
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/A_0G_ClUP0uxmZB_F_6zuWUAIUKC?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> (TEST) [jp-0228] PMVP (00) Dev -  Volunteer registration - Annual Cycle - Renewal

- resources/views/admin-campaign/campaignyears/index.blade.php
- resources/views/volunteer-profile/wizard.blade.php
2025
May 13 - James & Kristina - review and re-test Volunteer Renewal process, and a couple minor enhancement suggested for avoid confusion. 
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/A_0G_ClUP0uxmZB_F_6zuWUAIUKC?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> [jp-0228] PMVP (00) Dev -  Volunteer registration - Annual Cycle - Renewal

- resources/views/admin-campaign/campaignyears/index.blade.php
- resources/views/volunteer-profile/wizard.blade.php
2025
May 13 - James & Kristina - review and re-test Volunteer Renewal process, and a couple minor enhancement suggested for avoid confusion.
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/A_0G_ClUP0uxmZB_F_6zuWUAIUKC?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
> (MASTER) [jp-0228] PMVP (00) Dev -  Volunteer registration - Annual Cycle - Renewal

- composer.lock
- package-lock.json
- package.json
as of June 10, 2025, there are security more than 10 security patch request
Found 1 security vulnerability advisory affecting 1 package:
Found 1 security vulnerability advisory affecting 1 package:
| Package | league/commonmark |
| Severity | medium |
| CVE | CVE-2025-46734 |
| Title | league/commonmark contains a XSS vulnerability in Attributes extension |
| URL | https://github.com/advisories/GHSA-3527-qv2q-pfvx |
| Affected versions | <2.7.0 |
| Reported at | 2025-05-05T20:40:36+00:00 |
>npm audit
:
:
12 vulnerabilities (2 low, 10 moderate)
Step 1 …
> [jp-0233] Security update required (June, 2025)
