app/Http/Controllers/ContactFaqController.php
Dev - Updated Contact Page Visual (FAQs etc)  typo for "vary my role" change to "vary by role"
=> typo fixing for faqs

resources/views/donations/index.blade.php
Issue: 
User does not see the ‘Why Donate to PECSF’ button when there is no donation history.  Can we add that button regardless of the donations.  
Also, I’m ready to donate button in the Why Donate to PECSF flow when clicked, must navigate user to the first page/step of the donation flow.  
**Enhancement done**
1. Always display "‘Why Donate to PECSF’ button on the right side
2. Always start from the first page after click on "Why Donate to PECSF" page.
=> Donations: Missing 'Why Donate to PECSF' button when there is no donation history

app/Http/Controllers/AnnualCampaignController.php
Bug found by Steffi,  
In the donation page, when duplicate a pledge from history, the Dollar amount gives an error as it expects the total amount to be the one selected in the previous step. 
Root cause analysis: the BI history data is stored in annual amount basis, the biweekly distribution amount expected in annual pledge page is pledge amount. 
Solution: the amount should be divided by 26 period.
=> Duplicate Donor Choice charities gives error in Amount distribution page

app/Models/PledgeHistorySummary.php
The Donation History is needed to Duplicate the Pledge. Chances are that the charities and FSP might not be active anymore. So, when the Duplicate Pledge button is clicked, the user gets a pop-up message saying that the charity or FSP is not active anymore. And when continue is clicked, user must be navigated to the First step of the donations flow.  
**Root cause**: Issue caused by the recent change on the BI summary data, the summary transaction is now storing region code instead of region name, need to update this program to use 'region code'.
**Resolution**: For BI summary data, in model class, use regioin code instead of region name for lookup Region instance.
=> Duplicate pledge gives error when the FSP or charities are active and inactive [jp-bugfix-0004]

resources/views/donations/partials/learn-more-modal.blade.php
Additional change request:
Conditionally jump to difference page when th user click on the "I'm ready to Donate!" button. depend on the annual campiagn is open or not.
=> Donations: Missing 'Why Donate to PECSF' button when there is no donation history [jp-bugfix-0003]

resources/views/annual-campaign/partials/distribution-js.blade.php
Additional found on duplicate Donor Choice charities gives error in Amount distribution page, the incorrect distribute amount when percentage change. 
Root cause: varibale 'current' didn't initialize before calculation.
=> Duplicate Donor Choice charities gives error in Amount distribution [jp-bugfix-0002]

app/Http/Controllers/Admin/EventSubmissionQueueController.php
[TEAMS](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F3WzLf06FdECUqghkAYTZ7WUAIesb%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
[TICKET](https://bcgov.sharepoint.com/:w:/r/teams/02365/Shared%20Documents/Greenfield%20-%20Maintain%20Event%20Pledges.docx?d=w80cf2bea391545f2af48a931ef32b6d0&csf=1&web=1&e=H1ctUN)
Employee ID should only be 6 numbers. S shouldn’t be in front of Employee IDs. PECSF ID are F, S, R, G numbers.   
Verified on the …
=> Store locked Status - PG-bugfix-0008

app/Http/Requests/AnnualCampaignRequest.php
[Doc 1](https://bcgov.sharepoint.com/:w:/r/teams/02365/_layouts/15/Doc.aspx?action=editNew&sourcedoc=%7Bb7e42418-0742-4ed0-b9d6-bbaa386212fe%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1682352480664&web=1&cid=57e64ede-eb02-45c9-9bb6-e207fc80cfa0)
Some inconsistencies between one-time and bi-weekly messages needed to be fixed. Steffi's Notes are below. 
May 2 
I still see an inconsistency in some of the messages 
For zero – Bi-weekly message is perfect, but the one-time is not 
For alphabets: Can we change the message to ‘The Bi-weekly custom amount must be a number’ 
Can we have the same general message for all other cases? Here 2 messages are different for the same scenario
=> S40(23) Donations: CRA list - Change validation message for custom amount PG-bugfix-0010

resources/views/admin-pledge/campaign/wizard.blade.php
[Issue Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FGkbV4oAxFkqNduBZo0KcL2UADqz8%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
Root Cause:
Mixed Content: The page at 'https://pecsf-new-test.apps.silver.devops.gov.bc.ca/admin-pledge/campaign/create' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://pecsf-new-test.apps.silver.devops.gov.bc.ca/admin-pledge/campaign'. This request has been blocked; the …
=> Admin: Next button doesn't work for Create/edit campaign pledge [jp-bugfix-0010]

resources/views/admin-pledge/campaign/wizard.blade.php
[Issue Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FGkbV4oAxFkqNduBZo0KcL2UADqz8%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
Root Cause:
Mixed Content: The page at 'https://pecsf-new-test.apps.silver.devops.gov.bc.ca/admin-pledge/campaign/create' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://pecsf-new-test.apps.silver.devops.gov.bc.ca/admin-pledge/campaign'. This request has been blocked; the …
=> Test migration - Admin: Next button doesn't work for Create/edit campaign pledge [jp-bugfix-0010]

resources/views/donations/index.blade.php, resources/views/donations/partials/learn-more-modal.blade.php
The PECSF slides displayed on the click of ‘Why Donate to PECSF’ button has a Youtube video on the first page.  
The video can be played by clicking the play button. 
While the video is playing, user can click on ‘Learn more about how to donate’ button. When button is clicked, user navigates to the next page, but the YouTube video keeps on playing in the background 
Expected result: Can we pause the video when user clicks on Why Donate to PECSF button 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ft …
=> PECSF slides - Pause Youtube video when user navigate to next page [jp-bugfix-0011]

app/Http/Controllers/ChallengeController.php
Additional change : update challenege page to display BU based on the count of eligible employee over 5
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df …
=> S40(09) DEV - Daily Campaign Update - Part 2 [jp-0001] chane on challenge controller

app/Console/Commands/UpdateDailyCampaign.php
Additional change : remove debug statement
=> S40(09) DEV - Daily Campaign Update - Part 2 [jp-0001]

app/Console/Commands/ExportPledgesToPSFT.php
For allow sending transaction on lower region, update the program, allow to send transactions to PSFT immediately on the lower region conditionally with a flag called --now=1
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FdvBz8hF1MEO5dAWWe7t0tWUAI956%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> DEV - PSFT integration -- conditionally allow send transaction immediately to PSFT [jp-bugfix-0012]

app/Console/Commands/ExportPledgesToPSFT.php
For allow sending transaction on lower region, update the program, allow to send transactions to PSFT immediately on the lower region conditionally with a flag called --now=1
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FdvBz8hF1MEO5dAWWe7t0tWUAI956%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> DEV - PSFT integration -- conditionally allow send transaction immediately to PSFT [jp-bugfix-0012] - Test migration - May 12 Sprint 41

resources/views/donations/index.blade.php, resources/views/donations/partials/learn-more-modal.blade.php
Fixed the addition finding reported on May 12 -- I have seen one more issue here when we play the youtube video and close the PECSF slides modal, the video still keeps playing in the background. 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FhEkLqcXZAUyjRO0zGXtYxmUAIQIQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> s41(16) PECSF slides - Pause Youtube video when user navigate to next page [jp-bugfix-0011] 

resources/views/annual-campaign/wizard.blade.php
The ‘Back’ button from the browser when clicked in the Donations flow, leaves the user on the home page.  
We are hoping to find a solution so that the browser back button behaves the same way as the Back button in the donation flow.  
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FafY-XLDot0yuiHi5r862FGUAE2zN%22%7D)
=> Browser Back button control on Annual Campaign page [jp-bugfix-0015]

resources/views/donations/partials/learn-more-modal.blade.php
Enhancement received from UAT: "for accessiblity those who cannot hear would need closed captioning, can this be added to videos?"
Right now, when the Youtube link is played, the CC option is turned off. Is there any way to turn on and make the setting as default?
[Ticket ](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FTttqFlKUY0yP043KbipcUWUAA4gR%22%7D)
=> S41(16) PECSF slides - PECSF Youtube link: Make the Closed captioning setting turned on by default [jp-bugfix-0011]

resources/views/donations/partials/learn-more-modal.blade.php
Enhancement received from UAT: "for accessiblity those who cannot hear would need closed captioning, can this be added to videos?"
Right now, when the Youtube link is played, the CC option is turned off. Is there any way to turn on and make the setting as default?
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FTttqFlKUY0yP043KbipcUWUAA4gR%22%7D)
=> TEST migration - S41(16) PECSF slides - PECSF Youtube link: Make the Closed captioning setting turned on by default [jp-bugfix-0011] 

resources/views/annual-campaign/wizard.blade.php
The ‘Back’ button from the browser when clicked in the Donations flow, leaves the user on the home page.
We are hoping to find a solution so that the browser back button behaves the same way as the Back button in the donation flow.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FafY-XLDot0yuiHi5r862FGUAE2zN%22%7D)
=> Test migration -- Browser Back button control on Annual Campaign page [jp-bugfix-0015]

app/Console/Commands/ExportDatabaseToBI.php, app/Console/Commands/ExportPledgesToPSFT.php, app/Console/Commands/ImportCities.php, app/Console/Commands/ImportDepartments.php, app/Console/Commands/ImportEmployeeJob.php, app/Console/Commands/ImportNonGovPledgeHistory.php, app/Console/Commands/ImportPayCalendar.php, app/Console/Commands/ImportPledgeHistory.php, app/Console/Commands/SyncUserProfile.php, app/Console/Commands/UpdateDailyCampaign.php, app/Console/Commands/UpdateEligibleEmployeeSnapshot.php, app/Mail/NotifyMail.php, app/MicrosoftGraph/SendEmailNotification.php, config/logging.php, resources/views/emails/notification-template.blade.php
From MNP walkthrough of the interface process and the scheduled job run for the API call from ODS, the status of the job run is stored in Greenfield, and no notification is sent when the job run fails.
Schedule Job Audits logs cover import/export.
[ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fixaf9A6LEkmA0OymF8HK8GUAFAIA%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> Dev - System Notification in the Event of Data Interface Errors [jp-0002]

app/Console/Commands/ExportDatabaseToBI.php, app/Console/Commands/ExportPledgesToPSFT.php, app/Console/Commands/ImportCities.php, app/Console/Commands/ImportDepartments.php, app/Console/Commands/ImportEmployeeJob.php, app/Console/Commands/ImportNonGovPledgeHistory.php, app/Console/Commands/ImportPayCalendar.php, app/Console/Commands/ImportPledgeHistory.php, app/Console/Commands/SyncUserProfile.php, app/Console/Commands/UpdateDailyCampaign.php, app/Console/Commands/UpdateEligibleEmployeeSnapshot.php, app/Mail/NotifyMail.php, app/MicrosoftGraph/SendEmailNotification.php, config/logging.php, resources/views/emails/notification-template.blade.php
From MNP walkthrough of the interface process and the scheduled job run for the API call from ODS, the status of the job run is stored in Greenfield, and no notification is sent when the job run fails.
Schedule Job Audits logs cover import/export.
Work done: send out email notification when the schedule process was failed.
[ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fixaf9A6LEkmA0OymF8HK8GUAFAIA%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2% …
=> TEST migration -- Dev - System Notification in the Event of Data Interface Errors [jp-0002]

app/Http/Controllers/Admin/EventSubmissionQueueController.php
MNP auditor observed that there was no eForm change log, which could lead to unauthorized/erroneous changes being made without being identified.
Question
-Should we create an eForm audit log similar to existing audit logs that tracks changes from the eForm queue?
Are our current audit logs and the Maintain Events table/process enough to meet the need and I just need to document.
We may not need to do more work on this and just focus on Nancy documenting.
April 28 - This is currently captured in the PECSF admin>system security section>Auditing> filter for Bank Deposit event form. James recommends to enhance with user/date stamp for create update details in PECSF Admin>Pledge Admin>Maintain Events (details). This note has been added to the FRCR audit tracking table.
Dev has suggested a …
=> S40(24) Dev - eForm change log [jp-0003]

app/Console/Commands/ExportPledgesToPSFT.php
For allow sending transaction on lower region, update the program, allow to send transactions to PSFT immediately on the lower region conditionally with a flag called --now=1
Addition change: Fix a bug -- the cancelled pledge still sent out to PSFT. 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FdvBz8hF1MEO5dAWWe7t0tWUAI956%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> s41(19) DEV - PSFT integration -- conditionally allow send transaction immediately to PSFT [jp-bugfix-0012]

app/Console/Commands/ExportPledgesToPSFT.php
For allow sending transaction on lower region, update the program, allow to send transactions to PSFT immediately on the lower region conditionally with a flag called --now=1
Fix the bug which sent cancelled pledge to PSFT.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FdvBz8hF1MEO5dAWWe7t0tWUAI956%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> TEST migration -- s41(19) DEV - PSFT integration -- fix bug [jp-bugfix-0012]

resources/views/home.blade.php
Enhancement on the homepage, display the selection as a tiles.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FQXp8DkhxVEKZWfWNb07dB2UAJf42%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> Dev - Homepage Alignment [jp-bugfix-0019] 3rd version

app/Http/Controllers/ChallengeController.php, resources/views/challenge/index.blade.php
Additional Change: Display order on historial challenge data, e.g. change rate is lower than GCPE so SDPR should come before GCPE.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FGYHfdec1HkGX68ealYy0jWUAI3ks%22%7D)
=> S40(09) DEV - Daily Campaign Update - Part 2 (24th -- s41(17) Challenge page historical ordering)

database/migrations/2023_06_14_120840_modify_2nd_daily_campaign_view.php, database/migrations/2023_06_14_132007_add_campaign_year_id_index_in_pledge.php, database/migrations/2023_06_14_132052_add_campaign_year_id_index_in_bank_deposit_form.php, database/migrations/2023_06_14_133953_add_name_index_in_department.php, database/migrations/2023_06_14_134027_add_empl_id_index_in_eligible_employee_detail.php
Additional change : Fix the eForm data doesn't has the correct business unit 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40th …
=> S40(09) DEV - Daily Campaign Update - Part 2 (26th -- fix GPCE not found in eForm data

database/migrations/2023_06_15_122828_modify_3rd_daily_campaign_view.php, database/migrations/2023_06_15_130313_add_city_index_in_cities_table.php
Additional change : For non-gov EE pledges, get the region code from the pledges.city 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58 …
=> S40(09) DEV - Daily Campaign Update - Part 2 (27th -- for non-gov ee pledges, get the region based on cities)

resources/views/admin-pledge/campaign/show.blade.php
Use city to populate region
Use org to populate BU for non-government orgs
2nd change: update 'show' page to display BU and region
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FPR8E8PRCt0-hjaQYUISXS2UAG2S3%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> Dev - PECSF Admin - Maintain EE Enhancement - Non-gov [jp-bugfix-0021] update 'show' page to display BU and region

app/Http/Controllers/Admin/AdministratorController.php, config/adminlte.php, resources/views/admin-campaign/partials/tabs.blade.php, resources/views/system-security/administrators/index.blade.php, resources/views/system-security/partials/tabs.blade.php, routes/web.php
Per agreed, submenu 'Security - PECSF Administrators' should be grouped under 'System Security' menu
@[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FZwUZUA-mu0O0dBAbnl0wgWUAA8zE%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> S43 Dev - reposition submenu 'Security - PECSF Administrators' [jp-bugfix-0023]

app/Http/Controllers/Admin/AdministratorController.php, config/adminlte.php, resources/views/admin-campaign/partials/tabs.blade.php, resources/views/system-security/administrators/index.blade.php, resources/views/system-security/partials/tabs.blade.php, routes/web.php
Per agreed, submenu 'Security - PECSF Administrators' should be grouped under 'System Security' menu
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FZwUZUA-mu0O0dBAbnl0wgWUAA8zE%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> [Test migration] S43 Dev - reposition submenu 'Security - PECSF Administrators' [jp-bugfix-0023]

resources/views/vendor/adminlte/partials/navbar/menu-item-dropdown-user-menu.blade.php
we must display something like a label on the environments so that the users can differentiate them looking at the screen instead of the URL
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F_Su9IaUAe0qDM31dQ7OSOmUAE3K_%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> Differentiate the environments for users [jp-bugfix-0024]

composer.json
Root Cause: 
On server, the PHP version 8.0.29 and not compatilible with updated ZipStream packge per the vendor website information: https://github.com/PHPOffice/PhpSpreadsheet/issues/3616
Resolution: 
Force the dependency back to v2 which is compatible with PHP 8.0 by requiring "maennchen/zipstream-php": "^2.4".
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2Fto9FMHaEb0qOp03-dFYYBGUABWqY%22%7D)
=> DEV - Pledges and event report issue [jp-bugfix-0027]

composer.json
Root Cause:
On server, the PHP version 8.0.29 and not compatilible with updated ZipStream packge per the vendor website information: https://github.com/PHPOffice/PhpSpreadsheet/issues/3616
Resolution:
Force the dependency back to v2 which is compatible with PHP 8.0 by requiring "maennchen/zipstream-php": "^2.4".
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2Fto9FMHaEb0qOp03-dFYYBGUABWqY%22%7D)
=> Pledges and event report issue [jp-bugfix-0027]

app/Console/Commands/UpdateEligibleEmployeeSnapshot.php, database/migrations/2023_06_23_133228_modify_4th_daily_campaign_view.php, resources/views/system-security/users/index.blade.php
Additional change : improvement on displaying more employee status information for trobleshooting purpose
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15 …
=> S40(09) DEV - Daily Campaign Update - Part 2 (28th -- improvement)

app/Console/Commands/ImportEmployeeJob.php, app/Console/Commands/UpdateEligibleEmployeeSnapshot.php, database/migrations/2023_06_26_135928_modify_5th_daily_campaign_view.php
Additional change : use employee_jobs for identify the BU instead of eligible employee table
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb0 …
=> S40(09) DEV - Daily Campaign Update - Part 2 (30th -- improvement)

resources/views/admin-pledge/donate-now/create-edit.blade.php, resources/views/admin-pledge/special-campaign/create-edit.blade.php
During performing some high-level unit tests, the '301 Moved Permanently' error happened when creating on Donate Now and Special Campaign pledges under administration area
[ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FabmbPT6q2kulakC1wtz-yWUANl3D%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> [jp-bugfix-0029] '301 Moved Permanently' error happened on Admin Donate Now and Sepcial Campaign Pledges

app/Http/Controllers/Admin/DonateNowPledgeController.php, app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
During performing some high-level unit tests, the '301 Moved Permanently' error happened when creating on Donate Now and Special Campaign pledges under administration area
Addition change: fix bug related to non-Gov users can't create a new pledge
[ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FabmbPT6q2kulakC1wtz-yWUANl3D%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> [jp-bugfix-0029] '301 Moved Permanently' error happened on Admin Donate Now and Sepcial Campaign Pledges 

app/Imports/CharitiesImport.php
Reduce the log update from 30 sec to 1 min
=> [jp-bugfix-0030] Dev - Avoid too many log update during the import charities process

resources/views/admin-campaign/campaignyears/show.blade.php
Bug 
When open a campaign years setting display page (show) to review the auditing information, the error message displayed, those are record contain invalid created_by_id from initial setup.
Jun 30 - Fix the program to aviod the error on the transaction contains bad data .
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/h22vdUMQSUylloJhYzND32UAAudX?Type=TaskLink&Channel=Link&CreatedTime=638237849658280000)
=> [jp-bugfix-0031] Fix error when display campaign year record with invalid created_by_id

app/Console/Commands/SyncUserProfile.php, app/Http/Controllers/System/UserMaintenanceController.php
Right now, any users who is not a part of the team can access the environment if they have the site of that environment which can become a threat due to security concerns. We want to limit the access of the environments to users from our team and the testing accounts only. Other users must not be able to login. 
Environments to be blocked: 
- Dev
- Test
- Prod
Test accounts: 
Name	EmplID	login ID	Login Password	idir
1) K Dunn	000422	employee11@example.com	employee11@123	patdunn
2) Terry Jones - Admin	000413	employee12@example.com	employee12@123	tejones
3) Wendy Vander Kuyl	000743	employee13@example.com	employee13@123	wmvander
4) Helene Beauchesne	000749	employee14@example.com	employee14@123	hbeauche
5) Anthony Button	000754	employee15@example.com	employee15@123	tbutton
6) Harinder Gill …
=> [jp-bugfix-0032] Lock users from using the environments

app/Http/Controllers/Admin/CharityListMaintenanceController.php, app/Imports/CharitiesImport.php, resources/views/admin-campaign/charity-list-maintenance/index.blade.php
=> [Test migration] [jp-bugfix-0030] Dev - Avoid too many log update during the import charities process

app/Http/Controllers/System/SystemSettingController.php, resources/views/system-security/settings/index.blade.php
Additional change: fix minor bugs
Scenario
=> [jp-0005] Enable/Disable user signon during system maintenance

app/Http/Controllers/System/SystemSettingController.php, resources/views/system-security/settings/index.blade.php
Additional change: minor bug fix
Scenario
=> [TEST Migration] [jp-0005] Enable/Disable user signon during system maintenance

app/Http/Controllers/System/SystemSettingController.php, resources/views/system-security/lockdown/index.blade.php, resources/views/system-security/settings/index.blade.php
Additional change: accessibility support on the hidden button
Scenario
=> [jp-0005] Enable/Disable user signon during system maintenance 

app/Http/Controllers/DonationController.php
Scenario
For those special iDir account (not a employee in PeopleSoft), their user profile with organization_id and emplid always assigned to null, so that they should not have any transaction in the Donation History page. Those special account login for supporting purpose and shouldn't have any transactions.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/bLZiedffw02qn6NHE6mNyGUAD1L8?Type=TaskLink&Channel=Link&CreatedTime=638243588934860000)
=> [TEST Migration] [jp-bugfix-0035] organization must be checked for display Donation History

app/Http/Controllers/Admin/CharityListMaintenanceController.php, app/Imports/CharitiesImport.php, config/filesystems.php
Addition change: store the log file in logs folder.
=> [jp-bugfix-0030] Dev - Avoid too many log update during the import charities process 

app/Http/Controllers/Admin/CharityListMaintenanceController.php, app/Imports/CharitiesImport.php, config/filesystems.php
Addition change: store the log file in logs folder
=> [jp-bugfix-0030] Dev - Avoid too many log update during the import charity process

resources/views/challenge/daily_campaign.blade.php, resources/views/challenge/index.blade.php
38th change -- Challenge page : Leaderboard tab does not highlight when changing the campaign year
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390 …
=> S40(09) DEV - Daily Campaign Update - Part 2 

resources/views/vendor/adminlte/partials/sidebar/menu-item-link.blade.php
Laravel-mix-svg-sprite module should be decommissioned since PECSF application doesn't use teh feature -- "this webpack plugin generates a single SVG spritemap containing multiple elements from all .svg files in a directory." and also avoid some security warning.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/5lq5hmPvAkSQZx2BokxYH2UAOmsS?Type=TaskLink&Channel=Link&CreatedTime=638247993132880000)
=> [jp-bugfix-0036] clean-up -- decommision old module Laravel-mix-svg-sprite

app/Http/Controllers/System/UserMaintenanceController.php
Purpose: Need to update the 'User Maintenance Page' to handle the user without emplid and org id (sql need to join with oragnization_id)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/pwE8hc6j0ESBtdN0Z4mlZWUAMRGz?Type=TaskLink&Channel=Link&CreatedTime=638248870617070000)
=> [jp-bugfix-0037] update 'User Maintenance Page' to handle user without emplid or org id 

resources/views/challenge/daily_campaign.blade.php, resources/views/challenge/index.blade.php
40th change -- reverse the tabs design on Challenge and Daily Campiagn pages 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2F2lqkNB58wEuqiMkpBLGjtWUANfWQ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40th …
=> [jp-0001] S40(09) DEV - Daily Campaign Update - Part 2 

.gitignore, app/Console/Commands/DownloadImageFiles.php, app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Http/Controllers/Admin/SpecialCampaignSetupController.php, resources/views/admin-campaign/fund-supported-pools/partials/edit-pool-charity.blade.php, resources/views/admin-campaign/fund-supported-pools/partials/show-pool-charity.blade.php, resources/views/admin-campaign/special-campaigns/index.blade.php, resources/views/admin-pledge/special-campaign/create-edit.blade.php, resources/views/annual-campaign/partials/pool-detail.blade.php, resources/views/donate-now/partials/pool-detail.blade.php, resources/views/donate/partials/pool-detail.blade.php, resources/views/special-campaign/partials/special-campaign.blade.php
July 14 - The uploaded FSPool and Special Campaign image files by admin, should be stored in the stoarge folder instead of public. This could share to multiple application servers and better security control.
Old location: public/img/uploads
new location: storage/app/public
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/W9l6V9vVOUKQvG4_XmPBAGUAGB2W?Type=TaskLink&Channel=Link&CreatedTime=638249755758110000)
=> [jp-bugfix-0038] relocate the uploaded image folder (avoid to use public)

.gitignore, app/Console/Commands/DownloadImageFiles.php, app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Http/Controllers/Admin/SpecialCampaignSetupController.php, resources/views/admin-campaign/fund-supported-pools/partials/edit-pool-charity.blade.php, resources/views/admin-campaign/fund-supported-pools/partials/show-pool-charity.blade.php, resources/views/admin-campaign/special-campaigns/index.blade.php, resources/views/admin-pledge/special-campaign/create-edit.blade.php, resources/views/annual-campaign/partials/pool-detail.blade.php, resources/views/donate-now/partials/pool-detail.blade.php, resources/views/donate/partials/pool-detail.blade.php, resources/views/special-campaign/partials/special-campaign.blade.php
Rollback change on the directory but still fix old image doesn't delete issue when update by user.
July 14 - The uploaded FSPool and Special Campaign image files by admin, should be stored in the stoarge folder instead of public. This could share to multiple application servers and better security control.
Old location: public/img/uploads
new location: storage/app/public
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/W9l6V9vVOUKQvG4_XmPBAGUAGB2W?Type=TaskLink&Channel=Link&CreatedTime=638249755758110000)
=> [jp-bugfix-0038] relocate the uploaded image folder (ROLLBACK)

app/Console/Kernel.php
In order to have individual control on the schedule process, 2 seperate flag setting in .env to control out inbound and outbound schedule process.
TASK_SCHEDULING_INBOUND_ENABLED=true
TASK_SCHEDULING_OUTBOUND_PSFT_ENABLED=false
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UymKl8yKR02JEk3cUVBBtmUAFxsT?Type=TaskLink&Channel=Link&CreatedTime=638265981829070000)
=> [jp-bugfix-0047] Indiviudal flag to enable/disable inbound/outbound schedule process

app/Console/Kernel.php
In order to have individual control on the schedule process, 2 seperate flag setting in .env to control out inbound and outbound schedule process.
TASK_SCHEDULING_INBOUND_ENABLED=true
TASK_SCHEDULING_OUTBOUND_PSFT_ENABLED=false
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UymKl8yKR02JEk3cUVBBtmUAFxsT?Type=TaskLink&Channel=Link&CreatedTime=638265981829070000)
=> (TEST MIGRATION) [jp-bugfix-0047] Indiviudal flag to enable/disable inbound/outbound schedule process 

app/Http/Controllers/System/SystemSettingController.php
Additional change: remove validation on the start date not allow before today
Scenario
=> (TEST MIGRATION) [jp-0005] Enable/Disable user signon during system maintenance 

app/Console/Commands/UpdateDailyCampaign.php, app/Http/Controllers/Admin/ChallengeSettingsController.php, database/seeds/2020.csv
2 additional changes: 
**Update the process for updating the daily campaign summary only today date between the start & end date or final date. (included minor fix the 2020.csv seed data)**
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GYHfdec1HkGX68ealYy0jWUAI3ks?Type=TaskLink&Channel=Link&CreatedTime=638272957859890000)
=> [jp-0001] s41(24) Challenge Page - Controls (update summary logic)

app/Console/Kernel.php
Database backup was changed from 9:00am to 0:00 everyday now. The 1st schedule process have to move to 1:00am instead.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/5R_RgS8mlEC2FS2aJyrThWUAJpJE?Type=TaskLink&Channel=Link&CreatedTime=638273882386890000)
=> (TEST MIGRATION) [jp-0013] Adjust the schedule process start time

app/Console/Commands/UpdateDailyCampaign.php, app/Http/Controllers/Admin/ChallengeSettingsController.php, database/seeds/2020.csv
Changes:
1) Update summary page logic
2) Update the process for updating the daily campaign summary only today date between the start & end date or final date. (included minor fix the 2020.csv seed data)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GYHfdec1HkGX68ealYy0jWUAI3ks?Type=TaskLink&Channel=Link&CreatedTime=638272957859890000)
=> (TEST MIGRATION) [jp-0001] s41(24) Challenge Page - Controls (update summary logic) 

app/Http/Controllers/ChallengeController.php, resources/views/challenge/daily_campaign.blade.php
To fix the default last date that a user can download a daily campaign update report for “By Department” should be the “end” date.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Brq3tMzJ7kecCsu325AhwmUANT6S?Type=TaskLink&Channel=Link&CreatedTime=638285757563800000)
=> [jp-0017] Daily Campaign Update – Able to Download Dept after end date

app/Http/Controllers/ChallengeController.php, resources/views/challenge/daily_campaign.blade.php
To fix the default last date that a user can download a daily campaign update report for “By Department” should be the “end” date.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Brq3tMzJ7kecCsu325AhwmUANT6S?Type=TaskLink&Channel=Link&CreatedTime=638285757563800000)
=> (TEST MIGRATION) [jp-0017] Daily Campaign Update – Able to Download Dept after end date

resources/views/vendor/adminlte/master.blade.php
Per DevOps Team request, seperate the GTX / Snowplow to track site visitors and provide analytics  for lower and production regions.
To make an adjustment to the dev / test Snowplow code. They want us to use the dev pipeline in dev/test to verify, then implement on prod after. What we need to ajust is just 
"spt" (prod) to "spm" (dev): 
var collector = 'spm.apps.gov.bc.ca';
Note: new environment variable were added in .env file and the program will get from there per region
SNOWPLOW_COLLECTOR=spm.apps.gov.bc.ca
On openshift, all region was added the new configuration
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ZzYnm6WimU6p1LFUXTPGqmUAGy5a?Type=TaskLink&Channel=Link&CreatedTime=638285950474650000)
=> [jp-0018]  GTX / Snowplow -- separate collector for lower and Production regions

resources/views/annual-campaign/partials/pools.blade.php
Root cause: this bug was introduced by the change "Fix wrong pools showing in donation flow" made by techmusicmoney on August 25th, 2023 4:30 PM The wrong variable used.
Reapply: In some reason, the code for fixing doesn't appear after merged with dev by using the merge resolve. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/WsV8QxmakE2snMx8XK7LIWUAMk_T?Type=TaskLink&Channel=Link&CreatedTime=638289605199590000)
=> [jp-0021] Duplicate pledge for FSP issue (Reapply the fix due to merge conflict)

resources/views/vendor/adminlte/auth/login.blade.php
Region:Test  
Make the "login as administrator" hyperlink also enabled in TEST region to use test signin accouts for testing purpose
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Zq9k5zSB5kGi9TM-we6JA2UACdy6?Type=TaskLink&Channel=Link&CreatedTime=638290049601450000)
=> [jp-0022] Enable system administrator signon hyperlink for TEST region

app/Http/Controllers/ChallengeController.php, resources/views/challenge/daily_campaign.blade.php
To fix the default last date that a user can download a daily campaign update report for “By Department” should be the “end” date.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Brq3tMzJ7kecCsu325AhwmUANT6S?Type=TaskLink&Channel=Link&CreatedTime=638285757563800000)
=> (MASTER) [jp-0017] Daily Campaign Update – Able to Download Dept after end date

app/Http/Controllers/Admin/FundSupportedPoolController.php
Root cause: Bug found in the SQL statement , when the user search by name, the non-registrated charities also returns in the select2 and also need to add validation rule for checking charity when submit.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/xPvm9DGTwkmoWmasshqtCGUADATx?Type=TaskLink&Channel=Link&CreatedTime=638295214876310000)
=> [jp-0025] Dev - Only registered status charities can be selected for Fund Supported Pool

resources/views/admin-pledge/campaign/wizard.blade.php, resources/views/annual-campaign/wizard.blade.php, resources/views/donate-now/wizard.blade.php
Issue if for all the modals that opens - 
- View details (CRA charities)
- info icon for FSP
Steps to reproduce: 
- Open the modal
- Click the browser back button
- Notice that the black screen remains on the screen until the refresh button is clicked
Sept 5 - enhancement done on programs, close all modal box when the browser back button triggered
-- Annual Campaign (Self service)
-- Donate Now (Self-Service)
-- Annual Campaign (Admin)
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/-HSeEvzf0kKOaqn3h2TlcWUAO8dK?Type=TaskLink&Channel=Link&CreatedTime=638295257267390000)
=> [jp-0026] Browser back button displays blank screen when clicked while modal is open

app/Console/Commands/ImportEmployeeJob.php, app/Models/EmployeeJobStaging.php, database/migrations/2023_09_05_160415_create_employee_job_stagings_table.php
Issues
Eligible employee numbers in challenge page and eligible ee report are:
Missing entries with Sept 1 eft dates
Missing entries with future layoffs
Includes entries for terminated/retired ees
Sept 5 -- Couple of issues:
a) for data conversion, the old employee job carried forward but no longer exists in BI interface data anymore. Those job record should be marked as 'Terminated'.
b) Per audit, the couple of business units were update on Sept 1 after the eligible employee snapshot took on 4:30am
c) some new or recent update job data doesn't pass to Greenfield until Sept 5, 2023. That why eligible doesn't has those records.
Changes
New staging table created for temporialy storing  the BI job data for comparing purpose, use it for comparing whether the job data is exists or not, If no …
=> [jp-0027] Test eligible employee numbers in PROD (fixed employee job data issues)

resources/views/admin-pledge/campaign/wizard.blade.php, resources/views/annual-campaign/wizard.blade.php, resources/views/donate-now/wizard.blade.php
Issue if for all the modals that opens -
View details (CRA charities)
info icon for FSP
Steps to reproduce:
Open the modal
Click the browser back button
Notice that the black screen remains on the screen until the refresh button is clicked
Sept 5 - enhancement done on programs, close all modal box when the browser back button triggered
-- Annual Campaign (Self service)
-- Donate Now (Self-Service)
-- Annual Campaign (Admin)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/-HSeEvzf0kKOaqn3h2TlcWUAO8dK?Type=TaskLink&Channel=Link&CreatedTime=638295257267390000)
=> (TEST MIGRATION) [jp-0026] Browser back button displays blank screen when clicked while modal is open

app/Console/Commands/ImportEmployeeJob.php, app/Models/EmployeeJobStaging.php, database/migrations/2023_09_05_160415_create_employee_job_stagings_table.php
Issues
Eligible employee numbers in challenge page and eligible ee report are:
Missing entries with Sept 1 eft dates
Missing entries with future layoffs
Includes entries for terminated/retired ees
Sept 5 -- Couple of issues:
a) for data conversion, the old employee job carried forward but no longer exists in BI interface data anymore. Those job record should be marked as 'Terminated'.
b) Per audit, the couple of business units were update on Sept 1 after the eligible employee snapshot took on 4:30am
c) some new or recent update job data doesn't pass to Greenfield until Sept 5, 2023. That why eligible doesn't has those records.
Changes
New staging table created for temporialy storing the BI job data for comparing purpose, use it for comparing whether the job data is exists or not, If no …
=> (TEST MIGRATINO) [jp-0027] Test eligible employee numbers in PROD (fixed employee job data issues) 

app/Console/Commands/ImportEmployeeJob.php, app/Models/EmployeeJobStaging.php, database/migrations/2023_09_05_160415_create_employee_job_stagings_table.php
Issues
Eligible employee numbers in challenge page and eligible ee report are:
Missing entries with Sept 1 eft dates
Missing entries with future layoffs
Includes entries for terminated/retired ees
Sept 5 -- Couple of issues:
a) for data conversion, the old employee job carried forward but no longer exists in BI interface data anymore. Those job record should be marked as 'Terminated'.
b) Per audit, the couple of business units were update on Sept 1 after the eligible employee snapshot took on 4:30am
c) some new or recent update job data doesn't pass to Greenfield until Sept 5, 2023. That why eligible doesn't has those records.
Changes
New staging table created for temporialy storing the BI job data for comparing purpose, use it for comparing whether the job data is exists or not, If no …
=> (MASTER) [jp-0027] Test eligible employee numbers in PROD (fixed employee job data issues)

resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php, resources/views/admin-pledge/submission-queue/partials/reginal-pool.blade.php
1.  replace the Thumps-down button with ‘Maybe later’ 
2.  When the thumps-down button is clicked, it gives a blank white page
3. After the white screen is displayed, if we close the modal and again click on the View details button for any pledge, it still gives the white screen
4. Click on view details -> Edit -> View details for the FSP -> When the FSP details open up -> Close it -> Now if we scroll up and down, the edit form page does not scroll and the background scrolls up and down 
5. For gov cash and cheque only, please add the PECSF id field besides the employee name so that user can enter the PECSF id 
6. Nice to have: It will be nice to have if we can store the emp id and name field locally so that for any event, if we change the event from cash/cheque to gaming/fundraiser and …
=> [jz-004] Admin: Edit e-form bug fixes and enhancements

app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Http/Controllers/AnnualCampaignController.php, app/Http/Controllers/DonateNowController.php, resources/views/admin-campaign/fund-supported-pools/edit.blade.php, resources/views/admin-campaign/fund-supported-pools/partials/edit-pool-charity.blade.php, resources/views/admin-campaign/fund-supported-pools/show.blade.php
1. Pool detail in Annual Campaign
2. Summary Page in Annual Campaign
3. Pool detail in Donate Now
4. Pool detail in eForm
5. Pool detail in eForm (Administration)
6. Pool detail in submission Queue (Administration)
7. Fund Support Pool maintainenance page
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7BD5TafWSU-i7I6lzklcCWUAFjNl?Type=TaskLink&Channel=Link&CreatedTime=638320512603020000)
=> [jp-0030] Alphabetize FSP entries by charity name

resources/views/annual-campaign/wizard.blade.php
There is an extra line showing up at the bottom of all pages of the donations flow as / Page 2 -- charities // Page 4 -- distribution
The screenshot is attached for reference
Oct 5 - fix wrong comment line on HTML area. 
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2F03El3lk-LE65UWddZU87LWUANZfY%22%7D)
=> [jp-0031] Remove the extra line showing up in the donations flow

resources/views/annual-campaign/wizard.blade.php
There is an extra line showing up at the bottom of all pages of the donations flow as / Page 2 -- charities // Page 4 -- distribution
The screenshot is attached for reference
Oct 5 - fix wrong comment line on HTML area.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2F03El3lk-LE65UWddZU87LWUANZfY%22%7D)
=> TEST MIGRATION [jp-0031] Remove the extra line showing up in the donations flow

app/Exports/PledgesExport.php, app/Http/Controllers/Admin/CampaignPledgeController.php, app/Http/Controllers/AnnualCampaignController.php, app/Http/Controllers/BankDepositFormController.php, app/Models/BankDepositForm.php, app/Models/Pledge.php, database/migrations/2023_10_09_202426_add_dept_fields_in_table_pledges.php, database/migrations/2023_10_09_210528_add_dept_fields_in_table_bank_deposit_forms.php, database/migrations/2023_10_09_221933_modify_11th_daily_campaign_view.php
Root Cause
Solution
[jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/141GZwePI0alr7agMNtLNGUAFcUG?Type=TaskLink&Channel=Link&CreatedTime=638325520128010000))
[jp-0033] Admin Pledges report - …
=> TEST MIGRATION [jp-0033] Daily Campaign Update report - Employees that move show und…er correct org, but dept ID description is wrong

app/Console/Commands/SyncUserProfile.php
Feedback from a user:
Employee changed their name in July. Update is not reflected in the PECSF system. 
Impacted user: 
Beaumont, Bambi (ID - 132987). Showing as Bambi Spyker.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FppZZdGGmJEuXhs0n18cb3WUAJMG1%22%7D)
Oct 10 - UserProfile Sync process doesn't update the user name when changed in employee job. As of today, there are about 210 EE's name wasn't updated. 
select A.emplid, A.name, B.first_name, B.last_name from users A, employee_jobs B …
=> [jp-0034] Employee name field is pulling outdated information

app/Console/Commands/SyncUserProfile.php
Feedback from a user:
Employee changed their name in July. Update is not reflected in the PECSF system.
Impacted user:
Beaumont, Bambi (ID - 132987). Showing as Bambi Spyker.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2FppZZdGGmJEuXhs0n18cb3WUAJMG1%22%7D)
Oct 10 - UserProfile Sync process doesn't update the user name when changed in employee job. As of today, there are about 210 EE's name wasn't updated.
select A.emplid, A.name, B.first_name, B.last_name from users A, employee_jobs B
where …
=> TEST MIGRATION [jp-0034] Employee name field is pulling outdated information

resources/views/donations/partials/pledge-detail-modal.blade.php
Root cause:
Chat with Nancy and found out that the inconsistent figure show on donation page and the annual campaign pledge entry page. Fixed the program to display inconsistently.   
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/742X46xpBk2b7s2eBZGi8WUAFHXQ?Type=TaskLink&Channel=Link&CreatedTime=638326393288860000)
=> [jp-0035] Donation history shows % even if users select $ for distribution

resources/views/donations/partials/pledge-detail-modal.blade.php
Root cause:
Chat with Nancy and found out that the inconsistent figure show on donation page and the annual campaign pledge entry page. Fixed the program to display inconsistently.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/742X46xpBk2b7s2eBZGi8WUAFHXQ?Type=TaskLink&Channel=Link&CreatedTime=638326393288860000)
=> TEST MIGRATION [jp-0035] Donation history shows % even if users select $ for distribution

app/Http/Controllers/AnnualCampaignController.php
Root cause:
Disucss with Nancy and found the issue when click on the duplicate pledge button, the root cuase related to the recent change in "[jz-008]CRA charity list option - FSP selection has program pre-filled", the changes for in the "create" section is not workibng for old BI data (campiagn year 2022 or before). 
Solution: rollback this portioin of the change to the original for now. And also there is no need to prefill the program name for the dupliucated pledge.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/5N5SMLck0EW95RLPa-oPt2UAB-nE?Type=TaskLink&Channel=Link&CreatedTime=638326540675220000)
=> [jp-0036] Duplicate a pledge - match not found

app/Http/Controllers/AnnualCampaignController.php
Root cause:
Disucss with Nancy and found the issue when click on the duplicate pledge button, the root cuase related to the recent change in "[jz-008]CRA charity list option - FSP selection has program pre-filled", the changes for in the "create" section is not workibng for old BI data (campiagn year 2022 or before).
Solution: rollback this portioin of the change to the original for now. And also there is no need to prefill the program name for the dupliucated pledge.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/5N5SMLck0EW95RLPa-oPt2UAB-nE?Type=TaskLink&Channel=Link&CreatedTime=638326540675220000)
=> (TEST MIGRATION) [jp-0036] Duplicate a pledge - match not found

resources/views/admin-pledge/campaign/index.blade.php, resources/views/admin-pledge/event/index.blade.php
Addition Change:  add deptid and name column on Admin Annual Campaign and Event Pledges index pages
Root Cause
Solution
[jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/141GZwePI0alr7agMNtLNGUAFcUG?T …
=> [jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong 

resources/views/admin-pledge/campaign/index.blade.php, resources/views/admin-pledge/event/index.blade.php
Addition Change: add deptid and name column on Admin Annual Campaign and Event Pledges index pages
Root Cause
Solution
[jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/141GZwePI0alr7agMNtLNGUAFcUG?Ty …
=> TEST MIGARTION [jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong

app/Http/Controllers/Admin/CampaignPledgeController.php
Additional Change (2nd): typo on the variable name caused failure on the new pledge creation under admin section
Root Cause
Solution
[jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/141GZwePI0alr7agM …
=> (TEST MIGRATION) [jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong

resources/views/annual-campaign/wizard.blade.php
There is an extra line showing up at the bottom of all pages of the donations flow as / Page 2 -- charities // Page 4 -- distribution
The screenshot is attached for reference
Oct 5 - fix wrong comment line on HTML area.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2FtaskListType%2FsmartList%2FSL_AssignedToMe%2Fplan%2FZOb3bFXcakWu8Gl2Zd_PuGUAFIJt%2Ftask%2F03El3lk-LE65UWddZU87LWUANZfY%22%7D)
=> (MASTER) [jp-0031] Remove the extra line showing up in the donations flow

app/Http/Controllers/AnnualCampaignController.php
Root cause:
Disucss with Nancy and found the issue when click on the duplicate pledge button, the root cuase related to the recent change in "[jz-008]CRA charity list option - FSP selection has program pre-filled", the changes for in the "create" section is not workibng for old BI data (campiagn year 2022 or before).
Solution: rollback this portioin of the change to the original for now. And also there is no need to prefill the program name for the dupliucated pledge.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/5N5SMLck0EW95RLPa-oPt2UAB-nE?Type=TaskLink&Channel=Link&CreatedTime=638326540675220000)
=> (MASTER) [jp-0036] Duplicate a pledge - match not found

app/Http/Controllers/Admin/CampaignPledgeController.php, resources/views/admin-pledge/campaign/partials/summary.blade.php, resources/views/donations/partials/pledge-detail-modal.blade.php
Additional changes on Oct 12: 
Three more pages also need to be changed for display in alphabetical order 
8. Admin Annual Campaign -- summary page
9. Admin Annual Campaign -- show 
10. Donation Page 
1. Pool detail in Annual Campaign
2. Summary Page in Annual Campaign
3. Pool detail in Donate Now
4. Pool detail in eForm
5. Pool detail in eForm (Administration)
6. Pool detail in submission Queue (Administration)
7. Fund Support Pool maintainenance page
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7BD5TafWSU-i7I6lzklcCWUAFjNl?Type=TaskLink&Channel=Link&CreatedTime=638320512603020000)
=> [jp-0030] Alphabetize FSP entries by charity name (3 more pages needs to be changed also)

app/Http/Controllers/Admin/CampaignPledgeController.php, resources/views/admin-pledge/campaign/partials/summary.blade.php, resources/views/donations/partials/pledge-detail-modal.blade.php
Additional changes on Oct 12:
Three more pages also need to be changed for display in alphabetical order
8. Admin Annual Campaign -- summary page
9. Admin Annual Campaign -- show
10. Donation Page
Pool detail in Annual Campaign
Summary Page in Annual Campaign
Pool detail in Donate Now
Pool detail in eForm
Pool detail in eForm (Administration)
Pool detail in submission Queue (Administration)
Fund Support Pool maintainenance page
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7BD5TafWSU-i7I6lzklcCWUAFjNl?Type=TaskLink&Channel=Link&CreatedTime=638320512603020000)
=> (TEST MIGRATION) [jp-0030] Alphabetize FSP entries by charity name (3 more pages needs to change also)

resources/views/volunteering/forms.blade.php
If user navigates from Home page to Volunteering -> e-form -> FSP -> info icon. Once modal is opened, click the browser back button.
Issue: User is navigated to the Home page
Expected: User must be left of the Volunteering -> eform
Keeping this ticket for future as James will work on it after coming back from vacation
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fl_Hubfx3EEq1bcL1jV70TWUALGo_%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D …
=> (MASTER) [jp-0029] Browser back button when clicked while e-form modal is opened leaves user to the previous page

app/Exports/PledgesExport.php, app/Http/Controllers/Admin/CampaignPledgeController.php, app/Http/Controllers/AnnualCampaignController.php, app/Http/Controllers/BankDepositFormController.php, app/Models/BankDepositForm.php, app/Models/Pledge.php, database/migrations/2023_10_09_202426_add_dept_fields_in_table_pledges.php, database/migrations/2023_10_09_210528_add_dept_fields_in_table_bank_deposit_forms.php, database/migrations/2023_10_09_221933_modify_11th_daily_campaign_view.php, resources/views/admin-pledge/campaign/index.blade.php, resources/views/admin-pledge/event/index.blade.php
Additional Change (2nd): typo on the variable name caused failure on the new pledge creation under admin section
Root Cause
Solution
[jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong ([ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/141GZwePI0alr7agM …
=> (MASTER) [jp-0033] Daily Campaign Update report - Employees that move show under correct org, but dept ID description is wrong

resources/views/donations/partials/pledge-detail-modal.blade.php
Root cause:
Chat with Nancy and found out that the inconsistent figure show on donation page and the annual campaign pledge entry page. Fixed the program to display inconsistently.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/742X46xpBk2b7s2eBZGi8WUAFHXQ?Type=TaskLink&Channel=Link&CreatedTime=638326393288860000)
=> (MASTER) [jp-0035] Donation history shows % even if users select $ for distribution

app/Http/Controllers/BankDepositFormController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/result_row.blade.php, resources/views/volunteering/partials/add-event-js.blade.php
Oct 13 - During the investigation on the ticket "View details in Event submission queue displays incorrect Charity selections and distribution", the current program was unable to save the user selected charity into the database. This is a high priority issue.
Root cause:
Incomplete code found in controller
bug in the form submission when re-submit again after validation
Affected areas
a. eForm submission (self service) - create
b. Admin Event Pledge -- create
c. Additional Columns added onto the submission queue listing page for easy identify the transaction including tran ID, emplid, pecsf ID, business unit, deptid and name etc.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUA …
=> (TEST MIGRATION) [jp-0038] eForm -- doesn't update charity information into database when save

resources/views/annual-campaign/partials/summary-distribution.blade.php, resources/views/annual-campaign/partials/summary.blade.php
Req1 - In the donation summary page, when the option Percentage is selected, the column title must be changed from "Amount" to "Percentage". 
Req2 - Can we make the data in column Percentage/Amount to not bold, since the text in other columns are not bold.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/X2MZDq39aEupPaQ3DWogRWUAP6YM?Type=TaskLink&Channel=Link&CreatedTime=638328289702680000)
=> [jp-0039] Change the text from Amount to Percentage on Summary Page

app/Http/Controllers/BankDepositFormController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/result_row.blade.php, resources/views/volunteering/partials/add-event-js.blade.php
Oct 13 - During the investigation on the ticket "View details in Event submission queue displays incorrect Charity selections and distribution", the current program was unable to save the user selected charity into the database. This is a high priority issue.
Root cause:
a. Incomplete code found in controller
b. bug in the form submission when re-submit again after validation
Affected areas
a. eForm submission (self service) - create
b. Admin Event Pledge -- create
c. Additional Columns added onto the submission queue listing page for easy identify the transaction including tran ID, emplid, pecsf ID, business unit, deptid and name etc.
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd …
=> (MASTER) [jp-0038] eForm -- doesn't update charity information into database when save

resources/views/donations/partials/learn-more-modal.blade.php, resources/views/home.blade.php
Oct 13 - Steffi and James discussed some improvements to the ticket (first slide especially) and decided to include the first slide numbering with other slides, so slide 1 of 9. And add a 'Cancel" or Back button so that the slide text can be displayed in the centre.
Oct-13 - Additional Changes :
a. Page start from 1 and up to line
b. Add 'close' button on the first page
c. the page index read 'Page n of 9'
Oct 17 - additional change for fixing 2 issues
The text Slide 1 of 9 does not look centered
I know that we have auto rotate for the slides ON, but the issue is the that the slide x of 9 does not change hence resulting in the following kind of scenarios. The button ‘Learn more’ and text Slide 1 of9 does not change
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.p …
=> (TEST MIGRATION) [jp-0028] Dev - How to donate slide updates (UAT Feedback)

app/Http/Controllers/BankDepositFormController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php, resources/views/donate/partials/choose-charity.blade.php, resources/views/volunteering/partials/add-attachment.blade.php, resources/views/volunteering/partials/add-organization.blade.php, routes/web.php
fix for the following detected issues:
The submit button does not function on edit: For any type of event pledge, if admin clicks on edit, and tries saving the form by the Submit button without even changing anything on the form. Hence this results in not saving any charities.
The donation percent is required error is not displayed accurately.
For any FSP CRA charities, can we keep the Specific Community Or Initiative (Optional): field always disabled?
Added a Fundraiser pledge to Metro Vancouver FSP -> Click on Edit Pledge -> Change the FSP from Metro Vancouver to Cariboo -> Click on Submit button An error is displayed on the Submit button
Can we remove the text ‘You have not chosen any charities’ when viewing the pledge
The file section in edit pledge does not let user add/remove/drag …
=> [TEST MIGRATE][jz-009]Admin -> Event Submission Queue issues

app/Http/Controllers/Admin/CampaignPledgeController.php, app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Http/Controllers/AnnualCampaignController.php, app/Http/Controllers/DonateNowController.php, resources/views/admin-campaign/fund-supported-pools/edit.blade.php, resources/views/admin-campaign/fund-supported-pools/partials/edit-pool-charity.blade.php, resources/views/admin-campaign/fund-supported-pools/show.blade.php, resources/views/admin-pledge/campaign/partials/summary.blade.php, resources/views/donations/partials/event-detail-modal.blade.php, resources/views/donations/partials/pledge-detail-modal.blade.php
Pool detail in Annual Campaign
Summary Page in Annual Campaign
Pool detail in Donate Now
Pool detail in eForm
Pool detail in eForm (Administration)
Pool detail in submission Queue (Administration)
Fund Support Pool maintenance page
Donation Page (changes on Oct 12 also)
Oct 11 - Test validated. Assigning the ticket back to James to add the change to the following places as well.
1)Admin->Create a campaign pledge (Summary page)
2)Admin->View campaign pledge
Oct 12: Three more pages are changed for display in alphabetical order (ready for re-test)
8. Admin Annual Campaign -- summary page
9. Admin Annual Campaign -- show
10. Donation Page
Oct 13 - Steffi validated. The following places still …
=> (MASTER) [jp-0030] Alphabetize FSP entries by charity name (1 more page needs

app/Http/Controllers/Admin/CampaignPledgeController.php, app/Http/Controllers/Admin/DonateNowPledgeController.php, app/Http/Controllers/Admin/DonationDataController.php, app/Http/Controllers/Admin/SpecialCampaignPledgeController.php, app/Http/Controllers/System/UserMaintenanceController.php
Oct 12 - Investigation and findings:
Root Cause: typo on the datetime format characters. It should be format('Y-m-d H:i:s') instead of format('Y-m-d HⓂ️s'). The following areas are updated:
a. Admin -- Annual Campaign Pledge (index page)
b. Admin -- Donation Now Pledge (index page)
c. Admin -- Special Campaign Pledge (index page)
d: System -- User Maintenance (index page)
e. Reportng -- Review Donation Data (index page)
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2_nCQXel20uVbFL3RLJScmUAOAWc?Type=TaskLink&Channel=Link&CreatedTime=638327399329180000)
=> (MASTER) [jp-0037] Maintain ee table - minutes are wrong for created and updated at

resources/views/annual-campaign/partials/summary-distribution.blade.php, resources/views/annual-campaign/partials/summary.blade.php
Req1 - In the donation summary page, when the option Percentage is selected, the column title must be changed from "Amount" to "Percentage".
Req2 - Can we make the data in column Percentage/Amount to not bold, since the text in other columns are not bold.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/X2MZDq39aEupPaQ3DWogRWUAP6YM?Type=TaskLink&Channel=Link&CreatedTime=638328289702680000)
=> (MASTER) [jp-0039] Change the text from Amount to Percentage on Summary Page

app/Http/Controllers/Admin/CampaignPledgeController.php
Root cause: undefined variable for Non-Gov pledge.  fixed by assign nul value on both variable deptid and dept_name,
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fb60NIdmwpkeHotKIZvqLI2UAPpJJ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> [jp-0042] Dev - Error admin entering LDB(Non-Gov) pledge

app/Console/Kernel.php
Oct 26 -- Confirmation from Nancy 
"We can stop the scheduled jobs for donation history. Assuming that if a change is made between now and the end of the year, we COULD do a one-time refresh, if needed. We would, of course, let you know."
Action Required:
Stop scheduling both "ImportPledgeHistory" and "ImportNonGovPledgeHistory" from the daily process in all regions.
The process could run per adhoc rqeuest basis.
And also additional cleanup:
1. adjust the process, no BI import process running daily the weekend.
2. excluded some process from the conditional branch (configuration file flag "env('TASK_SCHEDULING_INBOUND_ENABLED')"
=> [jp-0044] Stop scheduling both import Gov and Non-gov pledge history from BI process

app/Console/Kernel.php
Oct 26 -- Confirmation from Nancy
"We can stop the scheduled jobs for donation history. Assuming that if a change is made between now and the end of the year, we COULD do a one-time refresh, if needed. We would, of course, let you know."
Action Required:
Stop scheduling both "ImportPledgeHistory" and "ImportNonGovPledgeHistory" from the daily process in all regions.
The process could run per adhoc rqeuest basis.
And also additional cleanup:
adjust the process, no BI import process running daily the weekend.
excluded some process from the conditional branch (configuration file flag "env('TASK_SCHEDULING_INBOUND_ENABLED')"
=> (TEST MIGRATION) [jp-0044] Stop scheduling both import Gov and Non-gov pledge history from BI process

app/Http/Controllers/Admin/CampaignPledgeController.php
Root cause: undefined variable for Non-Gov pledge. fixed by assign nul value on both variable deptid and dept_name,
[Ticket](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:68ee6eb15df44390b85fb02cac58153d@thread.tacv2_p_ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt_h_1611165472107?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fb60NIdmwpkeHotKIZvqLI2UAPpJJ%22%2C%22channelId%22%3A%2219%3A68ee6eb15df44390b85fb02cac58153d%40thread.tacv2%22%7D)
=> (MASTER) [jp-0042] Dev - Error admin entering LDB(Non-Gov) pledge

app/Jobs/CharitiesExportJob.php
Reference ticket - DEV - PECSF Admin Section - Maintain Charity List - Part 3 - Sprint 28
Oct 5 - Meet with FMO team and the sample vendor file provided. 2 additional field require for storing phone# and fax#. Per Tara, the row with the vendor id equal to "remit vendor id" will used for update the fields
use_alt_address
alt_address1 // Column L -- Address 1
alt_address2 // Column M -- Address 2  
alt_city // Column P -- City       
alt_province // Column X -- State
alt_country  // Column K -- Country
alt_postal_code // Column Y -- postal
financial_contact_name // Column AB -- Name
financial_contact_title // Column AC -- Title
financial_contact_email // Column AH -- email
phone // Column AE -- Phone
fax // Column AF -- Fax
url // Column AI -- Fax
updated_by_id // always assigned to 999
To …
=> [jp-0032] Dev - Charity Mailing address and financial contact info upload (add 2 fields (phone & fax) in export output file)

package-lock.json
Nov 1 - 2 critical vulnerabilities reported based on npm audit report and required to fix ASAP.
PS> composer audit --format=summary
No security vulnerability advisories found
PS> npm audit report
8 vulnerabilities (1 low, 4 moderate, 1 high, 2 critical)
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
node_modules/@babel/traverse
crypto-js  <4.2.0
Severity: critical
crypto-js PBKDF2 1,000 times weaker than specified in 1993 and 1.3M times weaker than current standard - https://github.com/advisories/GHSA-xwcq-pm8m-c4vf
node_modules/crypto-js
=> [jp-0045] Security update required -- 2 critical vulnerabilities

package-lock.json
Nov 1 - 2 critical vulnerabilities reported based on npm audit report and required to fix ASAP.
PS> composer audit --format=summary
No security vulnerability advisories found
PS> npm audit report
8 vulnerabilities (1 low, 4 moderate, 1 high, 2 critical)
@babel/traverse <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via npm audit fix
node_modules/@babel/traverse
crypto-js <4.2.0
Severity: critical
crypto-js PBKDF2 1,000 times weaker than specified in 1993 and 1.3M times weaker than current standard - https://github.com/advisories/GHSA-xwcq-pm8m-c4vf
fix available via npm audit fix
node_modules/crypto-js
=> (MASTER) [jp-0045] Security update required -- 2 critical vulnerabilities

resources/views/donations/partials/history.blade.php
Issue:
Employees have submitted 3 cash/cheque e-forms which are displayed in the donation history. Since these entries are not a pledge donation for calendar year 2024, the Duplicate Pledge button must still be displayed in the years of donation history.  
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UgKwXU8dn0O8BZbmqBAiO2UABuJ3?Type=TaskLink&Channel=Link&CreatedTime=638349684102380000)
=> [jp-0047] Duplicate pledge button disappears when a cash/cheque is added to donation history

app/Http/Controllers/DonationController.php
Issue:
User details: [employee54@example.com](mailto:employee54@example.com), emp id: 190429
User Lee Gu submitted a Cash event form to the Capital FSP.  
Event was approved by admin.  
Now the event is displayed in the donation history, but with the incorrect benefitting charity.  
Here, the expected charity must display ‘Capital’ but is displaying ‘Central Kootenay ‘instead 
Nov 6 -- (JP) Reassign to myself and start the investigation
Nov 7 -  replicated this scenario on local and fixed the logic of the program.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Mn0zH18LmUy8Peod7O1BnWUAG70n?Type=TaskLink&Channel=Link&CreatedTime=638349703375890000)
=> [jp-0048] Incorrect Benefiting charity displayed in donation history

resources/views/donations/partials/history.blade.php
Issue:
Employees have submitted 3 cash/cheque e-forms which are displayed in the donation history. Since these entries are not a pledge donation for calendar year 2024, the Duplicate Pledge button must still be displayed in the years of donation history.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UgKwXU8dn0O8BZbmqBAiO2UABuJ3?Type=TaskLink&Channel=Link&CreatedTime=638349684102380000)
=> (TEST MIGRATION) [jp-0047] Duplicate pledge button disappears when a cash/cheque is added to donation history 

app/Http/Controllers/DonationController.php
Issue:
User details: [employee54@example.com](mailto:employee54@example.com), emp id: 190429
User Lee Gu submitted a Cash event form to the Capital FSP.
Event was approved by admin.
Now the event is displayed in the donation history, but with the incorrect benefitting charity.
Here, the expected charity must display ‘Capital’ but is displaying ‘Central Kootenay ‘instead
Nov 6 -- (JP) Reassign to myself and start the investigation
Nov 7 - replicated this scenario on local and fixed the logic of the program.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Mn0zH18LmUy8Peod7O1BnWUAG70n?Type=TaskLink&Channel=Link&CreatedTime=638349703375890000)
=> (TEST MIGRATION) [jp-0048] Incorrect Benefiting charity displayed in donation history 

resources/views/admin-pledge/submission-queue/index.blade.php
remove the tabindex="-1" from modal to enable keyword searching of select2 plugin
=> [jz-18]Edit event pledge -> Drop down fields does not let admin type and search an option

resources/views/admin-pledge/submission-queue/index.blade.php
remove the tabindex="-1" from modal to enable keyword searching of select2 plugin
=> [TEST][jz-18]Edit event pledge -> Drop down fields does not let admin type and search an option

app/Http/Controllers/Admin/CampaignPledgeController.php, app/Http/Controllers/Admin/DonateNowPledgeController.php, app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Http/Controllers/Admin/SpecialCampaignSetupController.php, app/Http/Controllers/BankDepositFormController.php, app/Http/Controllers/CharityController.php
According to the application log, there are lots of SQL error caused by the single quote (‘) entered on the search value by users on charity search field.
`[2023-11-06 11:29:36] prod.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's%' or LOWER(registration_number) LIKE '%bc children's%') and `charity_status` =' at line 1 (SQL: select `id`, `charity_name`, `registration_number` from `charities` where (LOWER(charity_name) LIKE '%bc children's%' or LOWER(registration_number) LIKE '%bc children's%') and `charity_status` = Registered order by `charity_name` asc limit 100) 
`
Nov 8 -- fixed the following search fields:
a. charity 
b. user / …
=> [jp-0050] SQL error caused by the single quote () on the charity search string

resources/views/donations/partials/history.blade.php
Issue:
Employees have submitted 3 cash/cheque e-forms which are displayed in the donation history. Since these entries are not a pledge donation for calendar year 2024, the Duplicate Pledge button must still be displayed in the years of donation history.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UgKwXU8dn0O8BZbmqBAiO2UABuJ3?Type=TaskLink&Channel=Link&CreatedTime=638349684102380000)
=> (MASTER) [jp-0047] Duplicate pledge button disappears when a cash/cheque is added to donation history

app/Http/Controllers/DonationController.php
Issue:
User details: [employee54@example.com](mailto:employee54@example.com), emp id: 190429
User Lee Gu submitted a Cash event form to the Capital FSP.
Event was approved by admin.
Now the event is displayed in the donation history, but with the incorrect benefitting charity.
Here, the expected charity must display ‘Capital’ but is displaying ‘Central Kootenay ‘instead
Nov 6 -- (JP) Reassign to myself and start the investigation
Nov 7 - replicated this scenario on local and fixed the logic of the program.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Mn0zH18LmUy8Peod7O1BnWUAG70n?Type=TaskLink&Channel=Link&CreatedTime=638349703375890000)
=> (MASTER) [jp-0048] Incorrect Benefiting charity displayed in donation history

resources/views/admin-pledge/submission-queue/index.blade.php
remove the tabindex="-1" from modal to enable keyword searching of select2 plugin
=> (MASTER) [jz-18]Edit event pledge -> Drop down fields does not let admin type and search an option 

resources/views/annual-campaign/partials/summary-distribution.blade.php
Nov 14 - located the reported issue and fixed the issue:
In the pdf’s the Percentage title in the donation disbursement table must be changed to Amount, since the data displayed within is in $$ 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2a_sFVCdpkmVdP_O1uuirWUAJflb?Type=TaskLink&Channel=Link&CreatedTime=638355831277690000)
=> [jp-0053] Incorrect header in the pdf - Change Percentage to Amount

app/Http/Controllers/BankDepositFormController.php
Nov 14 - the reported issue was located and fixed:
For all the drop-down fields, there is an option to search the menu by typing it. This feature is not working in the Organization field in the e-form 
Places to be fixed: 
1. Volunteering -> e-form 
2. Admin - > Create new event pledge 
3. Admin -> Event submission queue -> Edit pledge 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/VqO5Ojtnuk260U4i09puKGUAGXw4?Type=TaskLink&Channel=Link&CreatedTime=638355832260340000)
=> [jp-0054] E-form: Search function in the Org drop-down list does not work

app/Http/Controllers/Admin/EventSubmissionQueueController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php
Nov 8 - Ticket created / screenshots added (GH)
Nov 9 - Steffi confirmed the issue.
Nov 14 - The reported issue was located and fixed:
In production environment 
When user goes to Event Submission Queue 
When choosing an eForm and viewing details – the name of the submitter changes from the volunteer, to the admin name… 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/WAUYvDiShkqT04JYhDZtBGUAA8HU?Type=TaskLink&Channel=Link&CreatedTime=638355887650870000)
=> [jp-0055] Employee name does not get stored when editing an Gov event pledge

app/Http/Controllers/BankDepositFormController.php
Nov 14 - the reported issue was located and fixed:
For all the drop-down fields, there is an option to search the menu by typing it. This feature is not working in the Organization field in the e-form 
Places to be fixed: 
1. Volunteering -> e-form 
2. Admin - > Create new event pledge 
3. Admin -> Event submission queue -> Edit pledge 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/VqO5Ojtnuk260U4i09puKGUAGXw4?Type=TaskLink&Channel=Link&CreatedTime=638355832260340000)
=> (TEST MIGRATION) [jp-0054] E-form: Search function in the Org drop-down list does not work

app/Http/Controllers/BankDepositFormController.php
Nov 14 - The reported issues was replicated and fixed 
For admin -> Event pledge -> Edit pledge -> The employee name and employee id field are not mandatory when Cheque or Cheque is selected.    
For gov org, Changed the event type from gaming/fundraiser to cash/cheque, without entering the emp id and name, clicked the submit button.  
Expected result: The emp id and emp name field must be validated as shown in the following screenshot 
Actual result: Fields are not validated 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/3rzCDqikbk66AwRU3XCEEGUAPwuu?Type=TaskLink&Channel=Link&CreatedTime=638355945507220000)
=> [jp-0056] Emp Id and name in Admin -> Event submission queue are not mandatory

resources/views/admin-pledge/submission-queue/index.blade.php
Nov 14 - The reported issue was replicated and fixed
Issue: Event Pledge: Editing a Retiree form, lets admin change the event type to Fundraiser/Gaming 
When submitting an e-form, if org is selected as ‘Retirees’ then Donation or event type list is modified to disable the options Fundraiser and Gaming. So, the user cannot select any of these options.  
But when editing the pledge made to Retirees with event type cash or cheque, admin can see the options Fundraiser and Gaming in Event type.  
Expected result: Keep the 2 options disabled when Retiree is selected 
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mSras7_0_UeP-C8J9EGAV2UAAWu6?Type=TaskLink&Channel=Link&CreatedTime=638356043225370000)
=> [jp-0057] Event Pledge: Editing a Retiree form, lets admin change the event type to Fundraiser/Gaming

app/Http/Controllers/Admin/EventSubmissionQueueController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php
Nov 8 - Ticket created / screenshots added (GH)
Nov 9 - Steffi confirmed the issue.
Nov 14 - The reported issue was located and fixed:
In production environment 
When user goes to Event Submission Queue 
When choosing an eForm and viewing details – the name of the submitter changes from the volunteer, to the admin name… 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/WAUYvDiShkqT04JYhDZtBGUAA8HU?Type=TaskLink&Channel=Link&CreatedTime=638355887650870000)
=> (TEST MIGRATION) [jp-0055] Employee name does not get stored when editing an Gov event pledge

app/Http/Controllers/BankDepositFormController.php
Nov 14 - The reported issues was replicated and fixed 
For admin -> Event pledge -> Edit pledge -> The employee name and employee id field are not mandatory when Cheque or Cheque is selected.    
For gov org, Changed the event type from gaming/fundraiser to cash/cheque, without entering the emp id and name, clicked the submit button.  
Expected result: The emp id and emp name field must be validated as shown in the following screenshot 
Actual result: Fields are not validated 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/3rzCDqikbk66AwRU3XCEEGUAPwuu?Type=TaskLink&Channel=Link&CreatedTime=638355945507220000)
=> (TEST MIGRATION) [jp-0056] Emp Id and name in Admin -> Event submission queue are not mandatory

resources/views/donate-now/partials/choose-charity-js.blade.php
As we know the donate now feature only lets user select one charity, we have added a pop-up message which is displayed when user adds more than the allowed number of charities.  
Expected result: The message must be displayed when adding the 2nd charity 
Actual result: The message is displayed when adding the 3rd charity
=> [jp-0058] Donate now - Maximum charity reached message displayed while adding the 3rd charity

app/Http/Controllers/DonateNowController.php
In the Donate now summary pdf, there is an extra line below the title ‘One-time total disbursement’ that displays the charity name and the text ‘Fund supported pool’. Can we please remove that line when a pledge is made to a CRA charity as it does not make sense. 
Note: That line must remain present when donation is made to a FSP so that we can display the name of the FSP.  
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/DoJGk0eZXkGc9qMNuMRuQGUAEkKW?Type=TaskLink&Channel=Link&CreatedTime=638356192057890000)
=> [jp-0060] Donate now: Remove an extra line form the Donate now summary pdf

app/Http/Controllers/DonateNowController.php
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/u9JFAhNEFkSPhaqcuSIyb2UAOmlK?Type=TaskLink&Channel=Link&CreatedTime=638356231547330000)
=> [jp-0062] Donate now - Program name for a FSP - CRA charity is not displayed in the pdf and donation history

resources/views/admin-pledge/submission-queue/index.blade.php
Nov 14 - The reported issue was replicated and fixed
Nov 15 - Required to merge with jz-016 and required additional logic fix.
Issue: Event Pledge: Editing a Retiree form, lets admin change the event type to Fundraiser/Gaming 
When submitting an e-form, if org is selected as ‘Retirees’ then Donation or event type list is modified to disable the options Fundraiser and Gaming. So, the user cannot select any of these options.  
But when editing the pledge made to Retirees with event type cash or cheque, admin can see the options Fundraiser and Gaming in Event type.  
Expected result: Keep the 2 options disabled when Retiree is selected 
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mSras7_0_UeP-C8J9EGAV2UAAWu6?Type=TaskLink&Channel=Link&CreatedTime=638356043225370000)
=> [jp-0057] Event Pledge: Editing a Retiree form, lets admin change the event type to Fundraiser/Gaming (reapply the fix)

resources/views/admin-pledge/submission-queue/index.blade.php
Nov 14 - The reported issue was replicated and fixed
Nov 15 - Required to merge with jz-016 and required additional logic fix.
Issue: Event Pledge: Editing a Retiree form, lets admin change the event type to Fundraiser/Gaming 
When submitting an e-form, if org is selected as ‘Retirees’ then Donation or event type list is modified to disable the options Fundraiser and Gaming. So, the user cannot select any of these options.  
But when editing the pledge made to Retirees with event type cash or cheque, admin can see the options Fundraiser and Gaming in Event type.  
Expected result: Keep the 2 options disabled when Retiree is selected 
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mSras7_0_UeP-C8J9EGAV2UAAWu6?Type=TaskLink&Channel=Link&CreatedTime=638356043225370000)
=> (TEST MIGRATION) [jp-0057] Event Pledge: Editing a Retiree form, lets admin change the event type to Fundraiser/Gaming

app/Http/Controllers/ChallengeController.php
Issue: 
When users try to download the (Organization/Region) Daily Campaign Update for November 13, 2023, it downloads and the date at the end of the file name for the Excel spreadsheet shows 2024-02-01. When it is opened, the report is empty. 
Nov 15 - the reported issue was replicated and fix
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/h-IBhrMu9kyH-1ZUnLRj12UAIYdJ?Type=TaskLink&Channel=Link&CreatedTime=638356878233090000)
=> [jp-0063] Daily Campaign Update - Org/Region report error

app/Http/Controllers/ChallengeController.php
Issue: 
When users try to download the (Organization/Region) Daily Campaign Update for November 13, 2023, it downloads and the date at the end of the file name for the Excel spreadsheet shows 2024-02-01. When it is opened, the report is empty. 
Nov 15 - the reported issue was replicated and fix
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/h-IBhrMu9kyH-1ZUnLRj12UAIYdJ?Type=TaskLink&Channel=Link&CreatedTime=638356878233090000)
=> (TEST MIGRATION) [jp-0063] Daily Campaign Update - Org/Region report error

resources/views/annual-campaign/partials/summary-distribution.blade.php
Nov 14 - located the reported issue and fixed the issue:
In the pdf’s the Percentage title in the donation disbursement table must be changed to Amount, since the data displayed within is in $$ 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2a_sFVCdpkmVdP_O1uuirWUAJflb?Type=TaskLink&Channel=Link&CreatedTime=638355831277690000)
=> (MASTER) [jp-0053] Incorrect header in the pdf - Change Percentage to Amount

app/Http/Controllers/BankDepositFormController.php
Nov 14 - the reported issue was located and fixed:
For all the drop-down fields, there is an option to search the menu by typing it. This feature is not working in the Organization field in the e-form 
Places to be fixed: 
1. Volunteering -> e-form 
2. Admin - > Create new event pledge 
3. Admin -> Event submission queue -> Edit pledge 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/VqO5Ojtnuk260U4i09puKGUAGXw4?Type=TaskLink&Channel=Link&CreatedTime=638355832260340000)
=> (MASTER) [jp-0054] E-form: Search function in the Org drop-down list does not work 

app/Http/Controllers/Admin/EventSubmissionQueueController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php
Nov 8 - Ticket created / screenshots added (GH)
Nov 9 - Steffi confirmed the issue.
Nov 14 - The reported issue was located and fixed:
In production environment 
When user goes to Event Submission Queue 
When choosing an eForm and viewing details – the name of the submitter changes from the volunteer, to the admin name… 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/WAUYvDiShkqT04JYhDZtBGUAA8HU?Type=TaskLink&Channel=Link&CreatedTime=638355887650870000)
=> (MASTER) [jp-0055] Employee name does not get stored when editing an Gov event pledge 

app/Http/Controllers/BankDepositFormController.php
Nov 14 - The reported issues was replicated and fixed 
For admin -> Event pledge -> Edit pledge -> The employee name and employee id field are not mandatory when Cheque or Cheque is selected.    
For gov org, Changed the event type from gaming/fundraiser to cash/cheque, without entering the emp id and name, clicked the submit button.  
Expected result: The emp id and emp name field must be validated as shown in the following screenshot 
Actual result: Fields are not validated 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/3rzCDqikbk66AwRU3XCEEGUAPwuu?Type=TaskLink&Channel=Link&CreatedTime=638355945507220000)
=> (MASTER)  [jp-0056] Emp Id and name in Admin -> Event submission queue are not mandatory 

app/Http/Controllers/ChallengeController.php
Issue:
When users try to download the (Organization/Region) Daily Campaign Update for November 13, 2023, it downloads and the date at the end of the file name for the Excel spreadsheet shows 2024-02-01. When it is opened, the report is empty.
Nov 15 - the reported issue was replicated and fix
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/h-IBhrMu9kyH-1ZUnLRj12UAIYdJ?Type=TaskLink&Channel=Link&CreatedTime=638356878233090000)
=> (MASTER) [jp-0063] Daily Campaign Update - Org/Region report error

resources/views/donate-now/partials/choose-charity-js.blade.php
As we know the donate now feature only lets user select one charity, we have added a pop-up message which is displayed when user adds more than the allowed number of charities.  
Expected result: The message must be displayed when adding the 2nd charity 
Actual result: The message is displayed when adding the 3rd charity
=> (TEST MIGRATION) [jp-0058] Donate now - Maximum charity reached message displayed while adding the 3rd charity

app/Http/Controllers/DonateNowController.php
In the Donate now summary pdf, there is an extra line below the title ‘One-time total disbursement’ that displays the charity name and the text ‘Fund supported pool’. Can we please remove that line when a pledge is made to a CRA charity as it does not make sense. 
Note: That line must remain present when donation is made to a FSP so that we can display the name of the FSP.  
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/DoJGk0eZXkGc9qMNuMRuQGUAEkKW?Type=TaskLink&Channel=Link&CreatedTime=638356192057890000)
=> (TEST MIGRATION) [jp-0060] Donate now: Remove an extra line form the Donate now summary pdf

resources/views/admin-pledge/donate-now/create-edit.blade.php
Issue: Admin Donate now - When editing, changes are being saved without clicking on the Save button 
- Go to admin -> Maintain donate now pledge 
- Edit the pledge made to CRA charity 
- Go to the ‘Donate to charity’ section 
- Change the charity from the drop-down section 
- Click on the ‘Cancel’ button 
Notice that the transaction is being updated with the newly selected charity without hitting the Save button 
Expected result: Can we only save the changes if user clicks on the Save button 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Chw4gNwkfkeEemeYEM7xGmUACmz1?Type=TaskLink&Channel=Link&CreatedTime=638356198793910000)
Nov 14 - The reported issues was replicated and fixed.
=> (TEST MIGRATION) [jp-0061] Admin Donate now - When editing, changes are being saved without clicking on the Save button

resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
When editing a event pledge from the Event submission queue, if user changes the org from Non-gov to gov, then Business unit does not populate.  
Pick any bank deposit form submitted to Gov and must be Cash/cheque from the event submission queue
Click on View details
Click on edit
The BU will be populated for now based on the employee id entered
Now change the Org to any of the Non-Gov organization
Now again change the org back to ‘Gov’
The BU field now remains empty
Expected result: Since there is already a employee id present in the e-form. Is it possible to populate the BU based on the employee id.  
Nov 15 - WIP, have to wait for jz-016 and jp-0057 tickets move to master and production (otherwise code merge conflict)
Nov 17 - Fix the issue and move forward
=> [jp-0064] Edit event pledge -> Business unit does not populate when org is changed to Gov

app/Http/Controllers/DonateNowController.php
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/u9JFAhNEFkSPhaqcuSIyb2UAOmlK?Type=TaskLink&Channel=Link&CreatedTime=638356231547330000)
=> (TEST MIGRATION) [jp-0062] Donate now - Program name for a FSP - CRA charity is not displayed in the pdf and donation history

resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
When editing a event pledge from the Event submission queue, if user changes the org from Non-gov to gov, then Business unit does not populate.  
Pick any bank deposit form submitted to Gov and must be Cash/cheque from the event submission queue
Click on View details
Click on edit
The BU will be populated for now based on the employee id entered
Now change the Org to any of the Non-Gov organization
Now again change the org back to ‘Gov’
The BU field now remains empty
Expected result: Since there is already a employee id present in the e-form. Is it possible to populate the BU based on the employee id.  
Nov 15 - WIP, have to wait for jz-016 and jp-0057 tickets move to master and production (otherwise code merge conflict)
Nov 17 - Fix the issue and move forward
=> (TEST MIGRATION) [jp-0064] Edit event pledge -> Business unit does not populate when org is changed to Gov

app/Exports/PledgeCharitiesExport.php, app/Http/Controllers/Admin/PledgeCharityReportController.php, app/Models/PledgeCharityStaging.php, database/migrations/2023_11_17_132642_add_f_s_pool_id_field_in_pledge_charity_staging_table.php
=> [jp-0065] DEV - Admin report list - Charity Amount

app/Exports/PledgeCharitiesExport.php, app/Http/Controllers/Admin/PledgeCharityReportController.php, app/Models/PledgeCharityStaging.php, database/migrations/2023_11_17_132642_add_f_s_pool_id_field_in_pledge_charity_staging_table.php
=> (TEST MIGRATION) [jp-0065] DEV - Admin report list - Charity Amount

app/Http/Controllers/DonateNowController.php, resources/views/donations/partials/donate-now-pledge-detail-modal.blade.php
Nov 17 - Fixed and ready for retest
Nov 20 - Test failed. Cannot see the program name in the Donate now pdf nor in the View details modal in donation history
Nov 21 - Missing to display the "Donate Now" special program on donation history and the Donate Today summary in PDF format.
=> [jp-0062] Donate now - Program name for a FSP - CRA charity is not displayed in the pdf and donation history (additiona changes)

app/Http/Controllers/DonateNowController.php, resources/views/donations/partials/donate-now-pledge-detail-modal.blade.php
Nov 17 - Fixed and ready for retest
Nov 20 - Test failed. Cannot see the program name in the Donate now pdf nor in the View details modal in donation history
Nov 21 - Missing to display the "Donate Now" special program on donation history and the Donate Today summary in PDF format.
=> (TEST MIGRATION) [jp-0062] Donate now - Program name for a FSP - CRA charity is not displayed in the pdf and donation history (additiona changes) 

resources/views/donate-now/partials/choose-charity-js.blade.php
As we know the donate now feature only lets user select one charity, we have added a pop-up message which is displayed when user adds more than the allowed number of charities.  
Expected result: The message must be displayed when adding the 2nd charity 
Actual result: The message is displayed when adding the 3rd charity
=> (MASTER) [jp-0058] Donate now - Maximum charity reached message displayed while adding the 3rd charity 

app/Http/Controllers/DonateNowController.php
In the Donate now summary pdf, there is an extra line below the title ‘One-time total disbursement’ that displays the charity name and the text ‘Fund supported pool’. Can we please remove that line when a pledge is made to a CRA charity as it does not make sense. 
Note: That line must remain present when donation is made to a FSP so that we can display the name of the FSP.  
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/DoJGk0eZXkGc9qMNuMRuQGUAEkKW?Type=TaskLink&Channel=Link&CreatedTime=638356192057890000)
=> (MASTER) [jp-0060] Donate now: Remove an extra line form the Donate now summary pdf

resources/views/admin-pledge/donate-now/create-edit.blade.php
Issue: Admin Donate now - When editing, changes are being saved without clicking on the Save button 
- Go to admin -> Maintain donate now pledge 
- Edit the pledge made to CRA charity 
- Go to the ‘Donate to charity’ section 
- Change the charity from the drop-down section 
- Click on the ‘Cancel’ button 
Notice that the transaction is being updated with the newly selected charity without hitting the Save button 
Expected result: Can we only save the changes if user clicks on the Save button 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Chw4gNwkfkeEemeYEM7xGmUACmz1?Type=TaskLink&Channel=Link&CreatedTime=638356198793910000)
Nov 14 - The reported issues was replicated and fixed.
=> (MASTER) [jp-0061] Admin Donate now - When editing, changes are being saved without clicking on the Save button

app/Http/Controllers/DonateNowController.php, resources/views/donations/partials/donate-now-pledge-detail-modal.blade.php
Nov 17 - Fixed and ready for retest
Nov 20 - Test failed. Cannot see the program name in the Donate now pdf nor in the View details modal in donation history
Nov 21 - Missing to display the "Donate Now" special program on donation history and the Donate Today summary in PDF format.
=> (MASTER) [jp-0062] Donate now - Program name for a FSP - CRA charity is not displayed in the pdf and donation history (additiona changes)

resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
When editing a event pledge from the Event submission queue, if user changes the org from Non-gov to gov, then Business unit does not populate.  
Pick any bank deposit form submitted to Gov and must be Cash/cheque from the event submission queue
Click on View details
Click on edit
The BU will be populated for now based on the employee id entered
Now change the Org to any of the Non-Gov organization
Now again change the org back to ‘Gov’
The BU field now remains empty
Expected result: Since there is already a employee id present in the e-form. Is it possible to populate the BU based on the employee id.  
Nov 15 - WIP, have to wait for jz-016 and jp-0057 tickets move to master and production (otherwise code merge conflict)
Nov 17 - Fix the issue and move forward
=> (MASTER) [jp-0064] Edit event pledge -> Business unit does not populate when org is changed to Gov 

app/Http/Requests/DonateNowRequest.php, resources/views/donate-now/partials/choose-charity-js.blade.php
As we know the donate now feature only lets user select one charity, we have added a pop-up message which is displayed when user adds more than the allowed number of charities.  
The error message needs an update. See attached.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/bLFzO-7YT0SMlKAWCpA7KmUAOpPs?Type=TaskLink&Channel=Link&CreatedTime=638363563818170000)
=> (TEST) [0068] Donate now - Maximum charity reached message update

resources/views/admin-pledge/donate-now/create-edit.blade.php
Issue: When editing a Donate now pledge to a FSP – incorrect FSP is assigned to the pledge.
Nov 23 - The reported issue was replciated and fixed
=> (MASTER) [jp-0067] Admin Editing a Donate now pledge' FSP does not assign the selected FSP

database/seeders/BankDepositFormAttachmentsSeeder.php
This pull request contains 2 tickets:
[jp-0066] eForm - When user attaches Multiple files to eform, some of the files are missing in admin-event pledge,
[jp-0066] eForm - store eForm Attachments in Database instead of system folder
Additional fix on seeder file.
=> [jp-0066] 6th commit -- eform attachment functionality (wrong criteria on the seeder file)

app/Http/Controllers/Admin/DonateNowPledgeController.php, app/Http/Controllers/DonateNowController.php, resources/views/admin-pledge/donate-now/create-edit.blade.php, resources/views/admin-pledge/donate-now/index.blade.php, resources/views/donations/partials/donate-now-pledge-detail-modal.blade.php
Nov 30 - The year on the Donate Pledges should be based on the year of pay deduction date. The following area should be changed:
1) The donations made in Donate now after Nov 23, must be displayed in the year 2024 of the users' donation history page
2) For admin ‘Maintain Donate Now Pledge’ -> Create new pledge -> Make the calendar year non editable field and change it to 2024 (Deduction yr)
3) On the Maintain Donate Now Pledge -> Search criteria -> Change the default Calendar yr to 2024
4) The donations must be displayed in 2024
=> [jp-0069] Donate Now pledges displayed in 2023 instead of 2024 (based on year of pay deduction date)

app/Http/Controllers/Admin/DonateNowPledgeController.php, app/Http/Controllers/DonateNowController.php, resources/views/admin-pledge/donate-now/create-edit.blade.php, resources/views/admin-pledge/donate-now/index.blade.php, resources/views/donations/partials/donate-now-pledge-detail-modal.blade.php
Nov 30 - The year on the Donate Pledges should be based on the year of pay deduction date. The following area should be changed:
1) The donations made in Donate now after Nov 23, must be displayed in the year 2024 of the users' donation history page
2) For admin ‘Maintain Donate Now Pledge’ -> Create new pledge -> Make the calendar year non editable field and change it to 2024 (Deduction yr)
3) On the Maintain Donate Now Pledge -> Search criteria -> Change the default Calendar yr to 2024
4) The donations must be displayed in 2024
=> (TEST) [jp-0069] Donate Now pledges displayed in 2023 instead of 2024 (based on year of pay deduction date) 

resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php, resources/views/volunteering/partials/add-event-js.blade.php, resources/views/volunteering/partials/form.blade.php
Merged with jp-0066 and avoid code conflict.
This pull request contains 2 tickets:
[jp-0070 <-- jp-0066] eForm - When user attaches Multiple files to eform, some of the files are missing in admin-event pledge,
[jp-0070 <-- jp-0066] eForm - store eForm Attachments in Database instead of system folder
Additional change required -- display error message when submit
=> [jp-0070][<--jp-0066] 7th commit -- eform attachment functionality (display error message when submit)

app/Http/Controllers/BankDepositFormController.php, resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php, resources/views/volunteering/partials/add-event-js.blade.php, resources/views/volunteering/partials/dropzone-js.blade.php, resources/views/volunteering/partials/form.blade.php
Merged with jp-0066 and avoid code conflict.
This pull request contains 2 tickets:
[jp-0070 <-- jp-0066] eForm - When user attaches Multiple files to eform, some of the files are missing in admin-event pledge,
[jp-0070 <-- jp-0066] eForm - store eForm Attachments in Database instead of system folder
Additional change required -- max upload files is 3
=> [jp-0070][<--jp-0066] 8th commit -- eform attachment functionality (max attachemnt is 3)

app/Exports/PledgeCharitiesExport.php
=> [jp-0065] DEV - Admin report list - Charity Amount (issue 5 on FSP event pledge no breakdown)

app/Exports/PledgeCharitiesExport.php
=> (TEST) [jp-0065] DEV - Admin report list - Charity Amount (issue 5 on FSP event pledge no breakdown)

app/Exports/PledgeCharitiesExport.php
=> [jp-0065] DEV - Admin report list - Charity Amount (incorrect calendar year in event pledge)

app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php
=> [jp-0072] eForm - Matching eForms to campaigns

app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php
=> (TEST) [jp-0072] eForm - Matching eForms to campaigns

routes/web.php
Issue: Fatal error when access ‘create’ action on Special Campaign Setup
http://domain:port/settings/special-campaigns/create
Action Required:
When declaring a resource route, have to specify a subset of actions the controller should handle instead of the full set of default actions.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7BujhHc_YE2M0Inr47FXT2UAF2B-?Type=TaskLink&Channel=Link&CreatedTime=638381657894160000)
=> (TEST) [jp-0074] Fatal Error when access ‘create’ action on Special Campaign Setup (Admin)

app/Http/Controllers/Admin/EventSubmissionQueueController.php, resources/views/admin-pledge/submission-queue/index.blade.php
=>  [jp-0072] eForm - Matching eForms to campaigns

app/Http/Controllers/Admin/EventSubmissionQueueController.php, resources/views/admin-pledge/submission-queue/index.blade.php
=> [jp-0072] eForm - Matching eForms to campaigns (fix issue on campaign year on the detail view under submission queue)

app/Http/Controllers/Admin/EventSubmissionQueueController.php, app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php, resources/views/admin-pledge/submission-queue/index.blade.php, resources/views/admin-pledge/submission-queue/partials/form.blade.php
=> (MASTER) [jp-0072] eForm - Matching eForms to campaigns (fix issue on campaign year on the detail view under submission queue) 

routes/web.php
Issue: Fatal error when access ‘create’ action on Special Campaign Setup
http://domain:port/settings/special-campaigns/create
Action Required:
When declaring a resource route, have to specify a subset of actions the controller should handle instead of the full set of default actions.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7BujhHc_YE2M0Inr47FXT2UAF2B-?Type=TaskLink&Channel=Link&CreatedTime=638381657894160000)
=> (MASTER) [jp-0074] Fatal Error when access ‘create’ action on Special Campaign Setup (Admin)

app/Console/Kernel.php
Dec 13 - Confirmed with Nancy
Cities and departments should update with the same timeline as Business Unit. If this data updates at different times, it could cause data issues for our reports. Currently, this is daily, I believe. This works for campaign! If you're asking to improve efficiency, these items could be updated weekly outside of campaign. The pay calendar could go weekly at any time.
Import Pay Calendar (every Monday)
ImportCities (every Monday or every weekday during campaign period)
ImportDepartments (every Monday or every weekday during campaign period)
=> [jp-0075] To arrange the several schedule processes from daily to weekly (fix checking logic)

app/Console/Kernel.php
Dec 13 - Confirmed with Nancy
Cities and departments should update with the same timeline as Business Unit. If this data updates at different times, it could cause data issues for our reports. Currently, this is daily, I believe. This works for campaign! If you're asking to improve efficiency, these items could be updated weekly outside of campaign. The pay calendar could go weekly at any time.
Import Pay Calendar (every Monday)
ImportCities (every Monday or every weekday during campaign period)
ImportDepartments (every Monday or every weekday during campaign period)
=> (TEST) [jp-0075] To arrange the several schedule processes from daily to weekly 

app/Http/Controllers/Admin/ChallengePageDataReportController.php
BC0601 is inactive and doesn't need to show in the report
BC006 is inactive and doesn't need to show in the report
Confirm with Gillian/FMO - What is the use case for having BC000 - Government of B.C. as a BU?
Dec 27 -- exclude the inactive business unit on the challenge data report
=> [jp-0079] Challenge page - Report - Only show "active" Business Units

app/Http/Controllers/Admin/ChallengePageDataReportController.php
BC0601 is inactive and doesn't need to show in the report
BC006 is inactive and doesn't need to show in the report
Confirm with Gillian/FMO - What is the use case for having BC000 - Government of B.C. as a BU?
Dec 27 -- exclude the inactive business unit on the challenge data report
=> (TEST) [jp-0079] Challenge page - Report - Only show 'active' Business Units

app/Console/Commands/UpdateDailyCampaign.php
Issue - Challenge page stats should "freeze" when the campaign is finalized and should only reset on September 1st.
Jan 4 - bug in the Daily UpdateDailyCampaign process caused the progress try to create 2024 campaign year data.
=> [jp-0082] Challenge page data report - Stats cleared after new year

app/Console/Commands/UpdateDailyCampaign.php
Issue - Challenge page stats should "freeze" when the campaign is finalized and should only reset on September 1st.
Jan 4 - bug in the Daily UpdateDailyCampaign process caused the progress try to create 2024 campaign year data.
=> (TEST) [jp-0082] Challenge page data report - Stats cleared after new year

app/Console/Kernel.php
Dec 13 - Confirmed with Nancy
Cities and departments should update with the same timeline as Business Unit. If this data updates at different times, it could cause data issues for our reports. Currently, this is daily, I believe. This works for campaign! If you're asking to improve efficiency, these items could be updated weekly outside of campaign. The pay calendar could go weekly at any time.
Import Pay Calendar (every Monday)
ImportCities (every Monday or every weekday during campaign period)
ImportDepartments (every Monday or every weekday during campaign period)
=> (MASTER) [jp-0075] To arrange the several schedule processes from daily to weekly 

app/Http/Controllers/Admin/ChallengePageDataReportController.php
BC0601 is inactive and doesn't need to show in the report
BC006 is inactive and doesn't need to show in the report
Confirm with Gillian/FMO - What is the use case for having BC000 - Government of B.C. as a BU?
Dec 27 -- exclude the inactive business unit on the challenge data report
=> (MASTER) [jp-0079] Challenge page - Report - Only show 'active' Business Units

database/seeders/DataFixFor_jp_0083.php
7 events show under BU0000. This has been deactivated and shouldn't have any entries. 7 current entries need BU updated. See attached spreadsheet.
Jan 8  -- per request, create a seeder file to run the following SQL scripts 
update bank_deposit_forms set business_unit = 29, updated_at = now() where id in (85,93,150,151,152,153);
update bank_deposit_forms set business_unit = 13, updated_at = now() where id = 97;
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/zeFSeQwe_ECek68mJsnmu2UAA287?Type=TaskLink&Channel=Link&CreatedTime=638403375869050000)
=> [jp-0083] BC0000 - Clean up and re-assignment

app/Console/Commands/ExportPledgesToPSFT.php
Jan 10 - Per Jon's request. the start date on the Annual Campaign pledge transactions should the next pay check date, with 8 days grace period (pay check date - 8 days) comparing to the current date of the export process.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/KYb_wCwY5EKW7cD4yUOL2GUALWUY?Type=TaskLink&Channel=Link&CreatedTime=638405130548880000)
=> [jp-0085] For PS interface, the start date on 'Annual Campaign pledge is the next upcoming check date

app/Console/Commands/ExportPledgesToPSFT.php
Jan 10 - Per Jon's request. the start date on the Annual Campaign pledge transactions should the next pay check date, with 8 days grace period (pay check date - 8 days) comparing to the current date of the export process.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/KYb_wCwY5EKW7cD4yUOL2GUALWUY?Type=TaskLink&Channel=Link&CreatedTime=638405130548880000)
=> (TEST) [jp-0085] For PS interface, the start date on 'Annual Campaign pledge is the next upcoming check date

database/seeders/DataFixFor_jp_0083.php
7 events show under BU0000. This has been deactivated and shouldn't have any entries. 7 current entries need BU updated. See attached spreadsheet.
Jan 8 -- per request, create a seeder file to run the following SQL scripts
update bank_deposit_forms set business_unit = 29, updated_at = now() where id in (85,93,150,151,152,153);
update bank_deposit_forms set business_unit = 13, updated_at = now() where id = 97;
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/zeFSeQwe_ECek68mJsnmu2UAA287?Type=TaskLink&Channel=Link&CreatedTime=638403375869050000)
=> (MASTER) [jp-0083] BC0000 - Clean up and re-assignment

app/Console/Commands/ExportPledgesToPSFT.php
Jan 10 - Per Jon's request. the start date on the Annual Campaign pledge transactions should the next pay check date, with 8 days grace period (pay check date - 8 days) comparing to the current date of the export process.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/KYb_wCwY5EKW7cD4yUOL2GUALWUY?Type=TaskLink&Channel=Link&CreatedTime=638405130548880000)
=> (MASTER) [jp-0085] For PS interface, the start date on 'Annual Campaign pledge is the next upcoming check date 

app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php, database/seeders/DataFixFor_jp_0087_reset_approval.php, resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
Jan 16 - Campaign years need to overlap with calendar years. E.g. Campaign 2023 opened on September 1, 2023, and will continue through til next campaign opens on September 1, 2024. Any funds reported using eForm should continue to be labelled as Campaign 2023 until that time.
Jan 16 - The previous ticket "[jp-0072] eForm - Matching eForms to campaigns" already take care the campaign year logic based on the open date of the campaign year setting to determine the campaign year. This ticket issue is mainly on PECSF_ID assignment, the year should be the campaign year instead of current year.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/B24UAhvGnUiayiRz_h9fo2UAKulm?Type=TaskLink&Channel=Link&CreatedTime=638410294883270000)
=> (TEST) [jp-0087] eform -- Fix PECSF_ID assignment with correct campaign year and Campaign years need to overlap with calendar years 

app/Console/Commands/ExportPledgesToPSFT.php
Jan 16 -- The "updated_at" value should not be changed when the pledge was successfully sent to PS. The schedule process "ExportPledgesToPSFT.php" need to revise.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/pMxt1Hbjy0yTCwgtcMtNH2UAKJnu?Type=TaskLink&Channel=Link&CreatedTime=638410201570380000)
=> (MASTER) [jp-0086] Avoid to change 'updated_at' when the pledge scucessfully sent to PS

app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php, database/migrations/2024_01_19_102829_change_deposit_date_in_bank_deposit_forms_table.php, database/seeders/DataFixFor_jp_0087_reset_approval.php, resources/views/admin-campaign/special-campaigns/index.blade.php, resources/views/admin-pledge/submission-queue/partials/add-event-js.blade.php
Issue: The confirmation modal displays the message but does not display the campaign name and rather displays “” 
Fix: the program was missed to get the name for display in javascript.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GLbd3yg6QUOJDzsp3XDf42UABD1I?Type=TaskLink&Channel=Link&CreatedTime=638418184582360000)
=> [jp-0091] Edit Special campaign confirmation modal is missing the Campaign name

resources/views/admin-campaign/special-campaigns/index.blade.php
Issue: The confirmation modal displays the message but does not display the campaign name and rather displays “”
Fix: the program was missed to get the name for display in javascript.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GLbd3yg6QUOJDzsp3XDf42UABD1I?Type=TaskLink&Channel=Link&CreatedTime=638418184582360000)
=> [jp-0091] Edit Special campaign confirmation modal is missing the Cpaign name

resources/views/vendor/adminlte/master.blade.php
The Special Campaign is displayed on the top bar of the user Dashboard/profile. Can we make the following changes to the display.
Make the background colour lighter to #FFE066
And the text: Make a donation to #C1201A
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mcBW8WgpVEeJy4RODcnFN2UAOvgY?Type=TaskLink&Channel=Link&CreatedTime=638419004720430000)
=> [jp-0090] Special Campaign Display (change banner color)

resources/views/vendor/adminlte/master.blade.php
The Special Campaign is displayed on the top bar of the user Dashboard/profile. Can we make the following changes to the display.
Make the background colour lighter to #FFE066
And the text: Make a donation to #C1201A
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mcBW8WgpVEeJy4RODcnFN2UAOvgY?Type=TaskLink&Channel=Link&CreatedTime=638419004720430000)
=> (TEST) [jp-0090] Special Campaign Display (change banner color)

app/Http/Controllers/Admin/DonateNowPledgeController.php
As we have cleaned up the list of FSP in donations, we need to do that clean up in the FSP option in Donate Now
Admin -> Maintain Donate Now Pledge -> Create New Pledge ->FSP
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GqKA8TCIWkSDRG3yzV1YAWUAJkFR?Type=TaskLink&Channel=Link&CreatedTime=638419022253440000)
=> [jp-0093] Admin: Donate Now - FSP field needs clean up

app/Http/Controllers/Admin/DonateNowPledgeController.php
As we have cleaned up the list of FSP in donations, we need to do that clean up in the FSP option in Donate Now
Admin -> Maintain Donate Now Pledge -> Create New Pledge ->FSP
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GqKA8TCIWkSDRG3yzV1YAWUAJkFR?Type=TaskLink&Channel=Link&CreatedTime=638419022253440000)
=> (TEST) [jp-0093] Admin: Donate Now - FSP field needs clean up

app/Http/Controllers/Admin/CampaignPledgeController.php
As we have cleaned up the list of FSP in donations, we need to do that clean up in the FSP option in Annual Campaign Pledges. 
Admin -> Maintain EE Pledge -> Create/Edit  New Pledge ->FSP
https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/NAUcyODuekKur5WlU9mpZmUAAeKM?Type=TaskLink&Channel=Link&CreatedTime=638421440144700000
=> [jp-0094] Admin - Maintain EE pledges - Clean up FSP options to only show active

app/Http/Controllers/Admin/CampaignPledgeController.php
As we have cleaned up the list of FSP in donations, we need to do that clean up in the FSP option in Annual Campaign Pledges.
Admin -> Maintain EE Pledge -> Create/Edit New Pledge ->FSP
https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/NAUcyODuekKur5WlU9mpZmUAAeKM?Type=TaskLink&Channel=Link&CreatedTime=638421440144700000
=> (TEST) [jp-0094] Admin - Maintain EE pledges - Clean up FSP options to only show active

app/Http/Controllers/AnnualCampaignController.php
For Duplicate pledge, If any of the charity/FSP is not available then user receives the following message in the confirmation dialog box: 
One or more charity(ies) you've selected is not available in the current campaign. Click here to see available charities, or alternatively you can select a different years choices from your donor history
Can we replace the msg by: 
One or more charity(ies) you've selected is not available in the current campaign. Click 'Continue' to see available charities, or alternatively you can select a different years choices from your donor history
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/vSXgF_BQ3Eqn4YFW211D6GUABaCI?Type=TaskLink&Channel=Link&CreatedTime=638422470998850000)
=> [jp-0095] Minor change to Duplicate Pledge confirmation message

resources/views/donations/partials/special-campaign-pledge-detail-modal.blade.php
Remove the time stamp portion on field "Deduct pay from" in Special campaign donation history.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ug_ZVn8xA0eUvo4prQpgn2UAHZBI?Type=TaskLink&Channel=Link&CreatedTime=638422475439520000)
=> [jp-0096] Remove the time stamp from Special campaign donation history

resources/views/donations/partials/special-campaign-pledge-detail-modal.blade.php
Remove the time stamp portion on field "Deduct pay from" in Special campaign donation history.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ug_ZVn8xA0eUvo4prQpgn2UAHZBI?Type=TaskLink&Channel=Link&CreatedTime=638422475439520000)
=> (TEST) [jp-0096] Remove the time stamp from Special campaign donation history

resources/views/special-campaign/wizard.blade.php
=> [jp-0097] Breadcrumb in Special Campaign is not clickable

resources/views/special-campaign/wizard.blade.php
=> (TEST) [jp-0097] Breadcrumb in Special Campaign is not clickable

resources/views/special-campaign/wizard.blade.php
Additional change: A little fix is still needed. The breadcrumb is working good, but the cursor does not change to hand when hovered over.
=> [jp-0097] Breadcrumb in Special Campaign is not clickable (2nd commit - change cursor to pointer when hover)

resources/views/special-campaign/wizard.blade.php
Additional change: A little fix is still needed. The breadcrumb is working good, but the cursor does not change to hand when hovered over.
=> (TEST) [jp-0097] Breadcrumb in Special Campaign is not clickable (2nd commit - change cursor to pointer when hover)

resources/views/donations/partials/history.blade.php
Root cause: the wrong id assign on the duplicate button, it should be the id of the 'Annual' instead of 'Event' type on BI history data. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/z_5aZNNMs0ejg6IWG6qxIGUAOD0d?Type=TaskLink&Channel=Link&CreatedTime=638423338678600000)
=> [jp-0090] Error 'The is not an Annual Campaign pledge!' received when duplicating

resources/views/donations/partials/history.blade.php
Root cause: the wrong id assign on the duplicate button, it should be the id of the 'Annual' instead of 'Event' type on BI history data.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/z_5aZNNMs0ejg6IWG6qxIGUAOD0d?Type=TaskLink&Channel=Link&CreatedTime=638423338678600000)
=> (TEST) [jp-0090] Error 'The is not an Annual Campaign pledge!' received when duplicating

resources/views/admin-campaign/special-campaigns/index.blade.php
Issue: The confirmation modal displays the message but does not display the campaign name and rather displays “”
Fix: the program was missed to get the name for display in javascript.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GLbd3yg6QUOJDzsp3XDf42UABD1I?Type=TaskLink&Channel=Link&CreatedTime=638418184582360000)
=> (MASTER) [jp-0091] Edit Special campaign confirmation modal is missing the Campaign name

app/Http/Controllers/Admin/DonateNowPledgeController.php
As we have cleaned up the list of FSP in donations, we need to do that clean up in the FSP option in Donate Now
Admin -> Maintain Donate Now Pledge -> Create New Pledge ->FSP
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/GqKA8TCIWkSDRG3yzV1YAWUAJkFR?Type=TaskLink&Channel=Link&CreatedTime=638419022253440000)
=> (MASTER) [jp-0093] Admin: Donate Now - FSP field needs clean up

app/Http/Controllers/Admin/CampaignPledgeController.php
As we have cleaned up the list of FSP in donations, we need to do that clean up in the FSP option in Annual Campaign Pledges.
Admin -> Maintain EE Pledge -> Create/Edit New Pledge ->FSP
https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/NAUcyODuekKur5WlU9mpZmUAAeKM?Type=TaskLink&Channel=Link&CreatedTime=638421440144700000
=> (MASTER) [jp-0094] Admin - Maintain EE pledges - Clean up FSP options to only show active

app/Http/Controllers/AnnualCampaignController.php
For Duplicate pledge, If any of the charity/FSP is not available then user receives the following message in the confirmation dialog box:
One or more charity(ies) you've selected is not available in the current campaign. Click here to see available charities, or alternatively you can select a different years choices from your donor history
Can we replace the msg by:
One or more charity(ies) you've selected is not available in the current campaign. Click 'Continue' to see available charities, or alternatively you can select a different years choices from your donor history
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/vSXgF_BQ3Eqn4YFW211D6GUABaCI?Type=TaskLink&Channel=Link&CreatedTime=638422470998850000)
=> (MASTER) [jp-0095] Minor change to Duplicate Pledge confirmation message

resources/views/special-campaign/wizard.blade.php
=> (MASTER) [jp-0097] Breadcrumb in Special Campaign is not clickable

resources/views/donations/partials/history.blade.php
Root cause: the wrong id assign on the duplicate button, it should be the id of the 'Annual' instead of 'Event' type on BI history data.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/z_5aZNNMs0ejg6IWG6qxIGUAOD0d?Type=TaskLink&Channel=Link&CreatedTime=638423338678600000)
=> (MASTER) [jp-0099] Error 'The is not an Annual Campaign pledge!' received when duplicating

resources/views/annual-campaign/partials/amount-distribution.blade.php, resources/views/annual-campaign/partials/distribution-js.blade.php
The Donation Distributions on Step 4 right now gives user 2options ‘Percentage’ and ‘Dollar Amount’ to enter or distribute the amount.  
This causes an issue to calculate the amount and percentage every time the user tries to switch the tabs or the user has to keep on switching if they want to see the figures of amount when they are in the Percentage section or vice versa 
We can add a Dollar Amount label to view beside the Percentage for each charity.  
And add a Percentage label to view beside the Dollar amount field for each charity 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/YM1kZknYVUq7gUrrOU3kyGUAG8X0?Type=TaskLink&Channel=Link&CreatedTime=638430574296180000)
=> [jp-0100] Donation: Display Dollar Amount besides the % in Donationn Distributions

resources/views/annual-campaign/partials/amount-distribution.blade.php, resources/views/annual-campaign/partials/distribution-js.blade.php
The Donation Distributions on Step 4 right now gives user 2options ‘Percentage’ and ‘Dollar Amount’ to enter or distribute the amount.
This causes an issue to calculate the amount and percentage every time the user tries to switch the tabs or the user has to keep on switching if they want to see the figures of amount when they are in the Percentage section or vice versa
We can add a Dollar Amount label to view beside the Percentage for each charity.
And add a Percentage label to view beside the Dollar amount field for each charity
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/YM1kZknYVUq7gUrrOU3kyGUAG8X0?Type=TaskLink&Channel=Link&CreatedTime=638430574296180000)
=> (TEST) [jp-0100] Donation: Display Dollar Amount besides the % in Donationn Distributions

resources/views/donations/index.blade.php, resources/views/donations/partials/history.blade.php, resources/views/donations/partials/pdf.blade.php
Feb 7 – James and Steffi had a discussion on the ticket and came up with the following solution.
Add a column called Bi-weekly amount between the Frequency and Amount columns
For Donate now, one-time and special campaigns, the Bi-weekly column will display ‘ - ‘
Change the Amount column name to ‘Total Amount’
Feb 9 -- Migrated to DEV and Test. Ready for testing
Feb 12 - Steffi validated the test. Want to know if we should also include this change in the Donation Summary pdf only for the Bi-weekly donation?
Feb 13 - change applied on DEV and TEST. Please re-test.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/_nzgvwIUe0u94ixtjYQ2q2UAMttQ?Type=TaskLink&Channel=Link&CreatedTime=638430600574180000)
=> [jp-0101] Dev - Donation history change amount to total amount (add the Bi-weekly column on pdf)

resources/views/donations/index.blade.php
When any other page example Home, Volunteering, Challenge are open, then they are highlighted in the right menu and other pages remain unhighlighted.  
=> [jp-0101] All tabs remains highlighted when Donations page is open

resources/views/donations/index.blade.php
When any other page example Home, Volunteering, Challenge are open, then they are highlighted in the right menu and other pages remain unhighlighted.
=> (TEST) [jp-0101] All tabs remains highlighted when Donations page is open

resources/views/volunteering/forms.blade.php, resources/views/volunteering/index.blade.php
When any other page example Home, Volunteering, Challenge are open, then they are highlighted in the right menu and other pages remain unhighlighted.  
Feb 14 - Bug fixed. Deployed on DEV and TEST, ready for testing
Feb 14 - The donations page issue is fixed now. But The same issue is happening for Volunteering -> Dashboard and Form page. Can we please fix that in this ticket itself?
=> [jp-0100+jp-0101] All tabs remains highlighted when Donations page is open (remove underline on nav link when on  Volunteering pages)

resources/views/donations/partials/history.blade.php
When any other page example Home, Volunteering, Challenge are open, then they are highlighted in the right menu and other pages remain unhighlighted.
=>  [jp-0101] Dev - Donation history change amount to total amount (update aria-label on expand/collapse icon when change)

resources/views/admin-pledge/submission-queue/partials/form.blade.php, resources/views/volunteering/partials/form.blade.php
Update Fund Support Pool selection UI on pages under self-service event pledge (eForm) and event submission queue, make it similiar to "Annual campaign pledge" page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/algcnP8GiEOfHdWZA3CfKmUANQt-?Type=TaskLink&Channel=Link&CreatedTime=638442393333690000)
=> [jp-0100] E-form FSP - Pools are not organized (add aria-labels)

resources/views/admin-pledge/submission-queue/partials/form.blade.php, resources/views/volunteering/partials/form.blade.php
Update Fund Support Pool selection UI on pages under self-service event pledge (eForm) and event submission queue, make it similiar to "Annual campaign pledge" page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/algcnP8GiEOfHdWZA3CfKmUANQt-?Type=TaskLink&Channel=Link&CreatedTime=638442393333690000)
=> (TEST) [jp-0100] E-form FSP - Pools are not organized (add aria-labels)

app/Http/Controllers/Admin/FundSupportedPoolController.php
The regions drop-down list for Admin -> Campaign Setup -> Core Setup -> Fund Supported Pools -> Add New Fund Supported Pool -> Region list is not sorted from A-z
Resolution: define a sorting order for regions.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/BnMtUlxVrU2tZyX9URATZGUAKX5Y?Type=TaskLink&Channel=Link&CreatedTime=638449366717530000)
=> [jp-0106] Sort Region list in Admin - Core Setup - FSP - Create new FSP

app/Http/Controllers/Admin/FundSupportedPoolController.php
The regions drop-down list for Admin -> Campaign Setup -> Core Setup -> Fund Supported Pools -> Add New Fund Supported Pool -> Region list is not sorted from A-z
Resolution: define a sorting order for regions.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/BnMtUlxVrU2tZyX9URATZGUAKX5Y?Type=TaskLink&Channel=Link&CreatedTime=638449366717530000)
=> (TEST) [jp-0106] Sort Region list in Admin - Core Setup - FSP - Create new FSP

app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
To standardize the number of special Campaign choices on both Self-Service and Administration pages. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ACw_m_SthUCEwbKvj7OP3WUANMgW?Type=TaskLink&Channel=Link&CreatedTime=638451856828830000)
=> [jp-0109] Incorrect Special Campaigns list displayed for Admin - Maintain Special Campaign Pledge

app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
To standardize the number of special Campaign choices on both Self-Service and Administration pages.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ACw_m_SthUCEwbKvj7OP3WUANMgW?Type=TaskLink&Channel=Link&CreatedTime=638451856828830000)
=> (TEST) [jp-0109] Incorrect Special Campaigns list displayed for Admin - Maintain Special Campaign Pledge

app/Console/Kernel.php
Issue: The "UpdateEligibleEmployeeSnapshot" schedule process was setup to run once at 4:30am. However, this schedule process
was always run 2 times, one at 4:30am and other one 4:45am
Resolution: Adjust the following job timing to test out.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/M-j2xuGlnkqIJvb2ouwJ02UAEyqw?Type=TaskLink&Channel=Link&CreatedTime=638451752804360000)
=> [jp-0107] Schedule process 'UpdateEligibleEmployeeSnapshot' ran 2 times daily at 4:30 and 4:45 on all regions (2nd change)

app/Console/Kernel.php
Issue: The "UpdateEligibleEmployeeSnapshot" schedule process was setup to run once at 4:30am. However, this schedule process
was always run 2 times, one at 4:30am and other one 4:45am
Resolution: Adjust the following job timing to test out.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/M-j2xuGlnkqIJvb2ouwJ02UAEyqw?Type=TaskLink&Channel=Link&CreatedTime=638451752804360000)
=> (TEST) [jp-0107] Schedule process 'UpdateEligibleEmployeeSnapshot' ran 2 times daily at 4:30 and 4:45 on all regions

app/Console/Kernel.php
Issue: The "UpdateEligibleEmployeeSnapshot" schedule process was setup to run once at 4:30am. However, this schedule process
was always run 2 times, one at 4:30am and other one 4:45am
Resolution: Adjust the following job timing to test out.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/M-j2xuGlnkqIJvb2ouwJ02UAEyqw?Type=TaskLink&Channel=Link&CreatedTime=638451752804360000)
=> [jp-0107] Schedule process 'UpdateEligibleEmployeeSnapshot' ran 2 times daily at 4:30 and 4:45 on all regions (3rd change)

app/Console/Kernel.php
Issue: The "UpdateEligibleEmployeeSnapshot" schedule process was setup to run once at 4:30am. However, this schedule process
was always run 2 times, one at 4:30am and other one 4:45am
Resolution: Adjust the following job timing to test out.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/M-j2xuGlnkqIJvb2ouwJ02UAEyqw?Type=TaskLink&Channel=Link&CreatedTime=638451752804360000)
=> (TEST) [jp-0107] Schedule process 'UpdateEligibleEmployeeSnapshot' ran 2 times daily at 4:30 and 4:45 on all regions (3rd change)

app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
To standardize the number of special Campaign choices on both Self-Service and Administration pages.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ACw_m_SthUCEwbKvj7OP3WUANMgW?Type=TaskLink&Channel=Link&CreatedTime=638451856828830000)
=> [jp-0109] Incorrect Special Campaigns list displayed for Admin - Maintain Special Campaign Pledge (changes on the edit mode also)

app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
To standardize the number of special Campaign choices on both Self-Service and Administration pages.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ACw_m_SthUCEwbKvj7OP3WUANMgW?Type=TaskLink&Channel=Link&CreatedTime=638451856828830000)
=> (TEST) [jp-0109] Incorrect Special Campaigns list displayed for Admin - Maintain Special Campaign Pledge (changes on the edit mode also)

app/Http/Requests/CampaignPledgeRequest.php
=> [jp-0108] Various changes on Admin - Annual Campaign

app/Http/Requests/CampaignPledgeRequest.php
=> (TEST) [jp-0108] Various changes on Admin - Annual Campaign

config/adminlte.php, resources/views/annual-campaign/wizard.blade.php
Two change on Self-service Annual Campaign Pledge page
1. the menu item all underline on the sidebar 
2. donation should be "active" when entering annual campaign pledge.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/9RPYCczm9UaI5Zp53YNN2GUAA7yc?Type=TaskLink&Channel=Link&CreatedTime=638449194165830000)
=> (MASTER) [jp-0104] Donation tab does not remain highlighted when user is in th Annual Campaign donations flow

app/Http/Controllers/Admin/FundSupportedPoolController.php
The regions drop-down list for Admin -> Campaign Setup -> Core Setup -> Fund Supported Pools -> Add New Fund Supported Pool -> Region list is not sorted from A-z
Resolution: define a sorting order for regions.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/BnMtUlxVrU2tZyX9URATZGUAKX5Y?Type=TaskLink&Channel=Link&CreatedTime=638449366717530000)
=> MASTER) [jp-0106] Sort Region list in Admin - Core Setup - FSP - Create new FSP

app/Console/Commands/SendDailyNotification.php
=> [jp-0113] No hardcoded email addresses in Daily email notification process

app/Console/Commands/SendDailyNotification.php
=> (TEST) [jp-0113] No hardcoded email addresses in Daily email notification process

app/Console/Commands/SendDailyNotification.php
=> [jp-0113] No hardcoded email addresses in Daily email notification process (string to array on ToAddresses)

app/Console/Commands/SendDailyNotification.php
=> (TEST) [jp-0113] No hardcoded email addresses in Daily email notification process (string to array on ToAddresses)

app/Console/Commands/SendDailyNotification.php
=> (MASTER) [jp-0113] No hardcoded email addresses in Daily email notification process (string to array on ToAddresses)

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0116] To monitor Queue and Task Scheduling Status (excluded queue Status and notify:daily)

app/Console/Commands/CopyFSPoolCharityImagesInPublicFolder.php, app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Models/FSPoolCharity.php, database/migrations/2024_03_21_075257_add_file_in_f_s_pool_charities_table.php, database/seeders/FSPoolCharityImagesSeeder.php
Save the Fund Support Pool logo image to the database, ensuring benefits such as efficient storage and backup, and optionally move it to the public folder for recovery purpose.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/H-G4tJCCdUqj26nchQAIGWUABTS_?Type=TaskLink&Channel=Link&CreatedTime=638466425422540000)
=> [jp-0115] Fund Support Pool Setup -- store and retreive logo image onto/from database

app/Console/Commands/CopyFSPoolCharityImagesInPublicFolder.php, app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Models/FSPoolCharity.php, database/migrations/2024_03_21_075257_add_file_in_f_s_pool_charities_table.php, database/seeders/FSPoolCharityImagesSeeder.php
Save the Fund Support Pool logo image to the database, ensuring benefits such as efficient storage and backup, and optionally move it to the public folder for recovery purpose.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/H-G4tJCCdUqj26nchQAIGWUABTS_?Type=TaskLink&Channel=Link&CreatedTime=638466425422540000)
=> (TEST) [jp-0115] Fund Support Pool Setup -- store and retreive logo image onto/from database

app/Console/Commands/CopyFSPoolCharityImagesInPublicFolder.php, app/Http/Controllers/Admin/FundSupportedPoolController.php, app/Models/FSPoolCharity.php, database/migrations/2024_03_21_075257_add_file_in_f_s_pool_charities_table.php, database/seeders/FSPoolCharityImagesSeeder.php
Save the Fund Support Pool logo image to the database, ensuring benefits such as efficient storage and backup, and optionally move it to the public folder for recovery purpose.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/H-G4tJCCdUqj26nchQAIGWUABTS_?Type=TaskLink&Channel=Link&CreatedTime=638466425422540000)
=> (MASTER) [jp-0115] Fund Support Pool Setup -- store and retreive logo image onto/from database

package-lock.json
March 27 - 1 HIGH vulnerabilities reported on Github.
https://github.com/bcgov/PECSF/pull/1167   "Bump webpack-dev-middleware from 5.3.3 to 5.3.4"
> npm audit    
express  <4.19.2
Express.js Open Redirect in malformed URLs - https://github.com/advisories/GHSA-rv95-896h-c2vc
sweetalert2  >=10.16.10 <11.0.0
sweetalert2 v10.16.10 and above contains hidden functionality - https://github.com/advisories/GHSA-457r-cqc8-9vj9
node_modules/sweetalert2
webpack-dev-middleware  <=5.3.3
Severity: high
Path traversal in webpack-dev-middleware - https://github.com/advisories/GHSA-wr3j-pwj9-hqq6
node_modules/webpack-dev-middleware
3 vulnerabilities (1 low, 1 …
=> [jp-0117] Security update required -- 1 HIGH security vulnerability

package-lock.json
March 27 - 1 HIGH vulnerabilities reported on Github.
https://github.com/bcgov/PECSF/pull/1167   "Bump webpack-dev-middleware from 5.3.3 to 5.3.4"
> npm audit    
express  <4.19.2
Express.js Open Redirect in malformed URLs - https://github.com/advisories/GHSA-rv95-896h-c2vc
sweetalert2  >=10.16.10 <11.0.0
sweetalert2 v10.16.10 and above contains hidden functionality - https://github.com/advisories/GHSA-457r-cqc8-9vj9
node_modules/sweetalert2
webpack-dev-middleware  <=5.3.3
Severity: high
Path traversal in webpack-dev-middleware - https://github.com/advisories/GHSA-wr3j-pwj9-hqq6
node_modules/webpack-dev-middleware
3 vulnerabilities (1 low, 1 …
=> (TEST) [jp-0117] Security update required -- 1 HIGH security vulnerability

package-lock.json
March 27 - 1 HIGH vulnerabilities reported on Github.
https://github.com/bcgov/PECSF/pull/1167   "Bump webpack-dev-middleware from 5.3.3 to 5.3.4"
> npm audit    
express  <4.19.2
Express.js Open Redirect in malformed URLs - https://github.com/advisories/GHSA-rv95-896h-c2vc
sweetalert2  >=10.16.10 <11.0.0
sweetalert2 v10.16.10 and above contains hidden functionality - https://github.com/advisories/GHSA-457r-cqc8-9vj9
node_modules/sweetalert2
webpack-dev-middleware  <=5.3.3
Severity: high
Path traversal in webpack-dev-middleware - https://github.com/advisories/GHSA-wr3j-pwj9-hqq6
node_modules/webpack-dev-middleware
3 vulnerabilities (1 low, 1 …
=> (MASTER) [jp-0117] Security update required -- 1 HIGH security vulnerability

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0116] To monitor Queue and Task Scheduling Status (fix hours calculation on database uptime)

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (fix hours calculation on database uptime)

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0116] To monitor Queue and Task Scheduling Status (2nd fix on hours calculaion for database uptime)

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (2nd fix on hours calculaion for database uptime)

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0116] To monitor Queue and Task Scheduling Status (3nd fix logic issue related to schedule job checking)

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (3nd fix logic issue related to schedule job checking)

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0116] To monitor Queue and Task Scheduling Status (4th fix logic issue related to schedule job checking)

app/Http/Controllers/Api/SystemStatusController.php
=>  [jp-0116] To monitor Queue and Task Scheduling Status (5th fix logic issue related to schedule job checking)

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (5th fix logic issue related to schedule job checking)

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0116] To monitor Queue and Task Scheduling Status (8th check failure when the database was restarted within 5 mins)

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST) [jp-0116] To monitor Queue and Task Scheduling Status (8th check failure when the database was restarted within 5 mins)

app/Http/Controllers/Admin/BusinessUnitController.php, app/Http/Requests/BusinessUnitRequest.php, app/Models/BusinessUnit.php, database/migrations/2024_04_19_093901_add_acronym_in_business_units.php, resources/views/admin-campaign/business-units/index.blade.php, resources/views/admin-campaign/business-units/partials/model-create.blade.php, resources/views/admin-campaign/business-units/partials/model-edit.blade.php, resources/views/admin-campaign/business-units/partials/model-show.blade.php
Under Administration\Campaign Set up\Foundation tables\Business Units add a column for the organizations acronym. Example: BC Public Service Agency = PSA.
The field would allow for no more than four letters, all caps and no duplication.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/rZTchpgg6k6wUBLNynP0-2UAHP7c?Type=TaskLink&Channel=Link&CreatedTime=638491435490780000)
=> (TEST) [jp-0123] Dev - PECSF Admin: Org Acronyms in foundations table 

app/Http/Controllers/Api/SystemStatusController.php
The program was incorrectly report an failure when the campaign period is closed and the following 2 process only run on Monday, the chkecing for previous job should be on Monday instead of Friday when the campaign period is not yet open.
{
"name": "command:ImportCities",
"cron": "30 2 * * 1-5",
"previous schedule time": "2024-04-19 02:30:00",
"next schedule time": "2024-04-22 02:30:00"
},
{
"name": "command:ImportDepartments",
"cron": "45 2 * * 1-5",
"previous schedule time": "2024-04-19 02:45:00",
"next schedule time": "2024-04-22 02:45:00"
},
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/awWzsysfPk …
=> [jp-0124] Improve the logic in Task Scheduling Status Monitoring

app/Http/Controllers/Api/SystemStatusController.php
The program was incorrectly report an failure when the campaign period is closed and the following 2 process only run on Monday, the chkecing for previous job should be on Monday instead of Friday when the campaign period is not yet open.
{
"name": "command:ImportCities",
"cron": "30 2 * * 1-5",
"previous schedule time": "2024-04-19 02:30:00",
"next schedule time": "2024-04-22 02:30:00"
},
{
"name": "command:ImportDepartments",
"cron": "45 2 * * 1-5",
"previous schedule time": "2024-04-19 02:45:00",
"next schedule time": "2024-04-22 02:45:00"
},
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/awWzsysfPk …
=> (TEST) [jp-0124] Improve the logic in Task Scheduling Status Monitoring

app/Http/Controllers/Api/SystemStatusController.php
The program was incorrectly report an failure when the campaign period is closed and the following 2 process only run on Monday, the chkecing for previous job should be on Monday instead of Friday when the campaign period is not yet open.
{
"name": "command:ImportCities",
"cron": "30 2 * * 1-5",
"previous schedule time": "2024-04-19 02:30:00",
"next schedule time": "2024-04-22 02:30:00"
},
{
"name": "command:ImportDepartments",
"cron": "45 2 * * 1-5",
"previous schedule time": "2024-04-19 02:45:00",
"next schedule time": "2024-04-22 02:45:00"
},
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/awWzsysfPk …
=> (MASTER) [jp-0124] Improve the logic in Task Scheduling Status Monitoring

app/Http/Controllers/Admin/BusinessUnitController.php, app/Http/Requests/BusinessUnitRequest.php, app/Models/BusinessUnit.php, database/migrations/2024_04_19_093901_add_acronym_in_business_units.php, resources/views/admin-campaign/business-units/index.blade.php, resources/views/admin-campaign/business-units/partials/model-create.blade.php, resources/views/admin-campaign/business-units/partials/model-edit.blade.php, resources/views/admin-campaign/business-units/partials/model-show.blade.php
Under Administration\Campaign Set up\Foundation tables\Business Units add a column for the organizations acronym. Example: BC Public Service Agency = PSA.
The field would allow for no more than four letters, all caps and no duplication.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/rZTchpgg6k6wUBLNynP0-2UAHP7c?Type=TaskLink&Channel=Link&CreatedTime=638491435490780000)
=> (MASTER) [jp-0123] Dev - PECSF Admin: Org Acronyms in foundations table

app/Imports/DonationsImportLA.php
To improve the program to handle there is no value or empty cell on column “G”, as before assume as ‘bi-weekly’.  For one-time transaction, please specify the ‘one time’ on column ‘G’
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/PhV7-CZO2kSg_SJg7Sq_-WUAO0x_?Type=TaskLink&Channel=Link&CreatedTime=638502809899470000)
=> [jp-0126] Improve Donation data upload process for LA to handling the exception on column G

app/Imports/DonationsImportLA.php
To improve the program to handle there is no value or empty cell on column “G”, as before assume as ‘bi-weekly’. For one-time transaction, please specify the ‘one time’ on column ‘G’
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/PhV7-CZO2kSg_SJg7Sq_-WUAO0x_?Type=TaskLink&Channel=Link&CreatedTime=638502809899470000)
=> (TEST) [jp-0126] Improve Donation data upload process for LA to handling the exception on column G

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST) [jp-0128] Improve the Task Scheduling Status Monitoring to conditionally skip checking based on the local env configuration

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0128] Improve the Task Scheduling Status Monitoring to conditionally skip checking based on the local env configuration

app/Imports/DonationsImportLA.php
To improve the program to handle there is no value or empty cell on column “G”, as before assume as ‘bi-weekly’. For one-time transaction, please specify the ‘one time’ on column ‘G’
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/PhV7-CZO2kSg_SJg7Sq_-WUAO0x_?Type=TaskLink&Channel=Link&CreatedTime=638502809899470000)
=> (MASTER) [jp-0126] Improve Donation data upload process for LA to handling the exception on column G

app/Http/Controllers/Api/SystemStatusController.php
=> [jp-0128] Improve the Task Scheduling Status Monitoring to conditionally skip checking based on the local env configuration (more enhancement needs)

config/adminlte.php, resources/views/challenge/daily_campaign.blade.php, resources/views/challenge/index.blade.php, resources/views/challenge/org_participation_tracker.blade.php
Challenge Page rename – to “Statistics” (front -end) 
Update Challenge Page references everywhere in front-end App to “Statistics” 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/9w9vDAxIBU6rsYj7Es8HSmUAEOZT?Type=TaskLink&Channel=Link&CreatedTime=638526986762400000)
=> [jp-0127] Challenge Page rename

app/Http/Controllers/Admin/MaintainVolunteerProfileController.php
Remove the GAL option in step 2 of the volunteering registration (image in the document attached). Remove the radial button in front of "Use the following address:" Located: Volunteering > Register tile
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/nnEK4nKIW0KNkGMUEU5k9mUADBKV?Type=TaskLink&Channel=Link&CreatedTime=638526140667890000)
=> [jp-0129] Volunteering Registration - address (remove debug statement)

config/adminlte.php, resources/views/challenge/daily_campaign.blade.php, resources/views/challenge/index.blade.php, resources/views/challenge/org_participation_tracker.blade.php
Challenge Page rename – to “Statistics” (front -end)
Update Challenge Page references everywhere in front-end App to “Statistics”
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/9w9vDAxIBU6rsYj7Es8HSmUAEOZT?Type=TaskLink&Channel=Link&CreatedTime=638526986762400000)
=> (MASTER) [jp-0127] Challenge Page rename

app/Http/Controllers/Api/SystemStatusController.php
=> (MASTER) [jp-0128] Improve the Task Scheduling Status Monitoring to conditionally skip checking based on the local env configuration

app/Models/EmployeeJob.php
The issue was replicated on local database and fix this bug on the method to calculate the total donation amount inside EmployeeJob model.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0l2v7ECXJEqg5ksRsb4n3GUABUYW?Type=TaskLink&Channel=Link&CreatedTime=638526799483380000)
=> (MASTER) [jp-0131] Discrepancy in numbers - Donation history & Dollars donated to date

resources/views/volunteer-profile/wizard.blade.php
The program was updated. When hovering over the navigation bar on the active items (in blue color) while registering, the cursor style changes to 'pointer'.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/91DeBpz4GkuBwL3KlwHu_WUAFG1I?Type=TaskLink&Channel=Link&CreatedTime=638526800049470000)
=> (MASTER) [jp-0132] Register volunteering: Cursor style does not change on hovering over the navigation bar

app/Http/Controllers/AnnualCampaignController.php, resources/views/donations/partials/bi-pledge-detail-modal.blade.php
Issue 2: The name was blank on "Benefitting Charity" field, it was caused by data from BI was difference on columns name1 and vendor_name1. After some data analysis, looks like better to use the column vendor_name1 and vendor_name2 instead of name1 and name2. The program was updated to use the vendor_name1 and vendor_name2.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/krg_x2GtEkaGgDDvIVsFnGUACGXV?Type=TaskLink&Channel=Link&CreatedTime=638526851543530000)
=> (MASTER) [jp-0134] No of charities in view details do not match the list when duplicating pledge

resources/views/donate-now/wizard.blade.php
While donating, the expected result is that only the donation tab in the left hand menu must remain highlighted but instead all other tabs are highlighted too. Please see the screenshot attached for reference
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0H5HvExlLE6l_PYMsSiJl2UAEQbl?Type=TaskLink&Channel=Link&CreatedTime=638533837710230000)
=> (TEST) [jp-0139] Donate now - All tabs in left menu remains highlighted

resources/views/donate-now/wizard.blade.php
While donating, the expected result is that only the donation tab in the left hand menu must remain highlighted but instead all other tabs are highlighted too. Please see the screenshot attached for reference
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0H5HvExlLE6l_PYMsSiJl2UAEQbl?Type=TaskLink&Channel=Link&CreatedTime=638533837710230000)
=> [jp-0139] Donate now - All tabs in left menu remains highlighted

resources/views/volunteer-profile/wizard.blade.php
While registering/editing volunteer profile, the expected result is that only the Volunteering tab in the left hand menu must remain highlighted but instead all other tabs are highlighted too. Please see the screenshot attached for reference
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/gFIlJUrp8kC9WrRy9Z5m1mUAAbpK?Type=TaskLink&Channel=Link&CreatedTime=638533838245030000)
=> [jp-0140] Register/Edit volunteering - All tabs in left menu remains highlighted

resources/views/volunteer-profile/wizard.blade.php
While registering/editing volunteer profile, the expected result is that only the Volunteering tab in the left hand menu must remain highlighted but instead all other tabs are highlighted too. Please see the screenshot attached for reference
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/gFIlJUrp8kC9WrRy9Z5m1mUAAbpK?Type=TaskLink&Channel=Link&CreatedTime=638533838245030000)
=> (TEST) [jp-0140] Register/Edit volunteering - All tabs in left menu remains highlighted

database/seeders/DataFixFor_jp_0142_EE123062.php
June 12 - issue for cheque run identified. CC to take screenshots of affected employee, James to update back end to reflect one-time, PO to test fix, Job to verify change in BI report. (One time 1125)
Campaign Year: 2023 (Calendar Year 2024)
EE 123062
Bi-weekly Amount : NO CHANGE
One-Time Amount: 1125.00
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/OiP1gcjBeEmIg7AbDzU_JGUAIsH_?Type=TaskLink&Channel=Link&CreatedTime=638538152756370000)
=> [jp-0142] EE 123062 Pledge #1837 -- Data Fix one time amount through backend

database/seeders/DataFixFor_jp_0142_EE123062.php
June 12 - issue for cheque run identified. CC to take screenshots of affected employee, James to update back end to reflect one-time, PO to test fix, Job to verify change in BI report. (One time 1125)
Campaign Year: 2023 (Calendar Year 2024)
EE 123062
Bi-weekly Amount : NO CHANGE
One-Time Amount: 1125.00
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/OiP1gcjBeEmIg7AbDzU_JGUAIsH_?Type=TaskLink&Channel=Link&CreatedTime=638538152756370000)
=> (TEST) [jp-0142] EE 123062 Pledge #1837 -- Data Fix one time amount through backend

resources/views/donate-now/wizard.blade.php
While donating, the expected result is that only the donation tab in the left hand menu must remain highlighted but instead all other tabs are highlighted too. Please see the screenshot attached for reference
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0H5HvExlLE6l_PYMsSiJl2UAEQbl?Type=TaskLink&Channel=Link&CreatedTime=638533837710230000)
=> (MASTER) [jp-0139] Donate now - All tabs in left menu remains highlighted

resources/views/volunteer-profile/wizard.blade.php
While registering/editing volunteer profile, the expected result is that only the Volunteering tab in the left hand menu must remain highlighted but instead all other tabs are highlighted too. Please see the screenshot attached for reference
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/gFIlJUrp8kC9WrRy9Z5m1mUAAbpK?Type=TaskLink&Channel=Link&CreatedTime=638533838245030000)
=> (MASTER) [jp-0140] Register/Edit volunteering - All tabs in left menu remains highlighted

database/seeders/DataFixFor_jp_0142_EE123062.php
June 12 - issue for cheque run identified. CC to take screenshots of affected employee, James to update back end to reflect one-time, PO to test fix, Job to verify change in BI report. (One time 1125)
Campaign Year: 2023 (Calendar Year 2024)
EE 123062
Bi-weekly Amount : NO CHANGE
One-Time Amount: 1125.00
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/OiP1gcjBeEmIg7AbDzU_JGUAIsH_?Type=TaskLink&Channel=Link&CreatedTime=638538152756370000)
=> (MASTER) [jp-0142] EE 123062 Pledge #1837 -- Data Fix one time amount through backend

app/Http/Controllers/System/ExportAuditLogController.php, resources/views/system-security/export-audit-log/index.blade.php
June 14 - In Export Audit Log page, no expected result returned when searching by Row ID field. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/0YycVEzpsEm6EXqZiKMcs2UAFcEZ?Type=TaskLink&Channel=Link&CreatedTime=638539780000350000)
=> [jp-0144] Export Audit Log -- search by Row ID doesn't work

app/Http/Controllers/Admin/MaintainVolunteerProfileController.php, app/Http/Controllers/VolunteerProfileController.php, app/Http/Requests/MaintainVolunteerProfileRequest.php, app/Http/Requests/VolunteerProfileRequest.php, app/Models/VolunteerProfile.php, resources/views/admin-volunteering/profile/create-edit.blade.php, resources/views/volunteer-profile/partials/recognition-items.blade.php, resources/views/volunteer-profile/partials/summary.blade.php, resources/views/volunteer-profile/show.blade.php
Steffi: I had noticed this earlier, but thought we still need the address while registering regardless of the selection to the checkbox
AC:
i) If user checks in to the checkbox, the address fields must become optional. The 'Use the following address field must remain hidden under the Recognition section of the 3. Confirmation page and the volunteer profile page
ii) If the user puts the address in the fields, and still checks in to the checkbox, the address fields must become optional and entered data must be neglected. The 'Use the following address field must remain hidden under the Recognition section of the 3. Confirmation page and the volunteer profile page
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/V1vHKJqAb069bDgtn8EwdGUAL9o7?Type=TaskLink&Channel=Link&CreatedT …
=> (TEST) [jp-0141] bug fix Volunteer Reg Programming - Opt out selected, address not required

package-lock.json
Jun 18- 1 HIGH vulnerabilities reported on Github.
https://github.com/bcgov/PECSF/pull/1351   "Bump braces from 3.0.2 to 3.0.3"
> npm audit
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
node_modules/braces
summernote  *
SummerNote Cross Site Scripting Vulnerability - https://github.com/advisories/GHSA-cc55-mvqc-g9mg
fix available via `npm audit fix --force`
Will install admin-lte@4.0.0-beta1, which is a breaking change
node_modules/summernote
admin-lte  3.0.0-alpha - 3.2.0
Depends on vulnerable versions of summernote
node_modules/admin-lte
sweetalert2  >=10.16.10 <11.0.0
sweetalert2 v10.16.10 and above contains hidden functionality - …
=> [jp-0145] Security update required -- 1 HIGH security vulnerability

package-lock.json
Jun 18- 1 HIGH vulnerabilities reported on Github.
https://github.com/bcgov/PECSF/pull/1351 "Bump braces from 3.0.2 to 3.0.3"
npm audit
npm audit report
braces <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via npm audit fix
node_modules/braces
summernote *
SummerNote Cross Site Scripting Vulnerability - https://github.com/advisories/GHSA-cc55-mvqc-g9mg
fix available via npm audit fix --force
Will install admin-lte@4.0.0-beta1, which is a breaking change
node_modules/summernote
admin-lte 3.0.0-alpha - 3.2.0
Depends on vulnerable versions of summernote
node_modules/admin-lte
sweetalert2 >=10.16.10 <11.0.0
sweetalert2 v10.16.10 and above contains hidden functionality - …
=> (TEST) [jp-0145] Security update required -- 1 HIGH security vulnerability

resources/views/volunteer-profile/partials/recognition-items.blade.php
Steffi: I had noticed this earlier, but thought we still need the address while registering regardless of the selection to the checkbox
AC:
i) If user checks in to the checkbox, the address fields must become optional. The 'Use the following address field must remain hidden under the Recognition section of the 3. Confirmation page and the volunteer profile page
ii) If the user puts the address in the fields, and still checks in to the checkbox, the address fields must become optional and entered data must be neglected. The 'Use the following address field must remain hidden under the Recognition section of the 3. Confirmation page and the volunteer profile page
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/V1vHKJqAb069bDgtn8EwdGUAL9o7?Type=TaskLink&Channel=Link&CreatedT …
=> [jp-0141] bug fix Volunteer Reg Programming - Opt out selected, address not required (clear error message if exists)

package-lock.json
Jun 18- 1 HIGH vulnerabilities reported on Github.
https://github.com/bcgov/PECSF/pull/1351 "Bump braces from 3.0.2 to 3.0.3"
npm audit
npm audit report
braces <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via npm audit fix
node_modules/braces
summernote *
SummerNote Cross Site Scripting Vulnerability - https://github.com/advisories/GHSA-cc55-mvqc-g9mg
fix available via npm audit fix --force
Will install admin-lte@4.0.0-beta1, which is a breaking change
node_modules/summernote
admin-lte 3.0.0-alpha - 3.2.0
Depends on vulnerable versions of summernote
node_modules/admin-lte
sweetalert2 >=10.16.10 <11.0.0
sweetalert2 v10.16.10 and above contains hidden functionality - …
=> (MASTER) [jp-0145] Security update required -- 1 HIGH security vulnerability

app/Http/Requests/BusinessUnitRequest.php
Jun 21 - Bug found in the Business Unit page, when update the BU without changing the acronym, the duplicate error "The acronym has already been taken." shown. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/fpg-L2Kt2U2OTLt7ivkFgWUAH-Nt?Type=TaskLink&Channel=Link&CreatedTime=638545870733130000)
=> [jp-0146] Bug in Business Unit page, incorrect 'acronym' duplicate error shown when update

app/Http/Requests/BusinessUnitRequest.php
Jun 21 - Bug found in the Business Unit page, when update the BU without changing the acronym, the duplicate error "The acronym has already been taken." shown.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/fpg-L2Kt2U2OTLt7ivkFgWUAH-Nt?Type=TaskLink&Channel=Link&CreatedTime=638545870733130000)
=> (TEST) [jp-0146] Bug in Business Unit page, incorrect 'acronym' duplicate error shown when update

app/Http/Controllers/ChallengeController.php
Serveral enhancement on Statistic (Challenge) Page:
[jp-0137a] Enhancement - Daily Campaign Stats - Final Stats [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/T_dTCzJqVkuFqO0pzhBQWGUALT5B?Type=TaskLink&Channel=Link&CreatedTime=638533030443900000)
[jp-0137b] Enhancement - Challenge Page Export for end users [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ntd_9k4HD0eXVRmABfNNKGUAJtWa?Type=TaskLink&Channel=Link&CreatedTime=638533030776710000)
[jp-0137c] Enhancement - Org Tracker - availability requirements [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aJ72fFrt1UavEam3ITiNEGUAHxK5?Type=TaskLink&Channel=Link&CreatedTime=638533030953040000)
[jp-0137d] Challenge Page rename – to “Statistics Page Data” (back-end/admin) …
=> [jp-0137b] Enhancement - Challenge Page Export for end users (improve logic to control the display of Download as PDF button)

app/Http/Controllers/ChallengeController.php
Serveral enhancement on Statistic (Challenge) Page:
[jp-0137a] Enhancement - Daily Campaign Stats - Final Stats [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/T_dTCzJqVkuFqO0pzhBQWGUALT5B?Type=TaskLink&Channel=Link&CreatedTime=638533030443900000)
[jp-0137b] Enhancement - Challenge Page Export for end users [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ntd_9k4HD0eXVRmABfNNKGUAJtWa?Type=TaskLink&Channel=Link&CreatedTime=638533030776710000)
[jp-0137c] Enhancement - Org Tracker - availability requirements [Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/aJ72fFrt1UavEam3ITiNEGUAHxK5?Type=TaskLink&Channel=Link&CreatedTime=638533030953040000)
[jp-0137d] Challenge Page rename – to “Statistics Page Data” (back-end/admin) …
=> (TEST) [jp-0137b] Enhancement - Challenge Page Export for end users (improve logic to control the display of Download as PDF button)

app/Http/Controllers/Admin/CampaignPledgeController.php, app/Models/CampaignYear.php, resources/views/admin-pledge/campaign/index.blade.php, resources/views/admin-pledge/campaign/partials/profile.blade.php, resources/views/admin-pledge/campaign/wizard.blade.php
*Requirements:*
- The default calendar year would indicate using the current year when the campaign is not yet open. Once the campaign for the next calendar year, such as 2025, opens, the system will default to calendar year 2025 (campaign year 2024).
- When click on the next step to 2nd page during create a annual campaign pledge, the pop message ask for confirmation of the calendar year choice 
=> [jp-0148] Admin: Annual Campaign Pledge -- Pop-up message to confirm calendar year

app/Http/Controllers/Admin/CampaignPledgeController.php, app/Models/CampaignYear.php, resources/views/admin-pledge/campaign/index.blade.php, resources/views/admin-pledge/campaign/partials/profile.blade.php, resources/views/admin-pledge/campaign/wizard.blade.php
*Requirements:*
- The default calendar year would indicate using the current year when the campaign is not yet open. Once the campaign for the next calendar year, such as 2025, opens, the system will default to calendar year 2025 (campaign year 2024).
- When click on the next step to 2nd page during create a annual campaign pledge, the pop message ask for confirmation of the calendar year choice 
=> (TEST) [jp-0148] Admin: Annual Campaign Pledge -- Pop-up message to confirm calendar year

database/seeders/DataFixFor_jp_0147_update_Plege6185.php
Jun 21 - Per user request, the pledge ID  6185 should be under calendar year 2024 instead of 2025. This was caused by campaign year 2024 setup on the system with the improper default logic.
SQL script:
select * from pledges where id  = 6185 and campaign_year_id = 21;
update pledges set campaign_year_id = 20, updated_at = now()  where id  = 6185 and campaign_year_id = 21;
=> [jp-0147] Fixing the pledge with Tran# 6185, update the calendar year to 2024 from 2025

database/seeders/DataFixFor_jp_0147_update_Plege6185.php
Jun 21 - Per user request, the pledge ID  6185 should be under calendar year 2024 instead of 2025. This was caused by campaign year 2024 setup on the system with the improper default logic.
SQL script:
select * from pledges where id  = 6185 and campaign_year_id = 21;
update pledges set campaign_year_id = 20, updated_at = now()  where id  = 6185 and campaign_year_id = 21;
=> (TEST) [jp-0147] Fixing the pledge with Tran# 6185, update the calendar year to 2024 from 2025

database/seeders/DataFixFor_jp_0147_update_Plege6185.php
Jun 21 - Per user request, the pledge ID 6185 should be under calendar year 2024 instead of 2025. This was caused by campaign year 2024 setup on the system with the improper default logic.
SQL script:
select * from pledges where id = 6185 and campaign_year_id = 21;
update pledges set campaign_year_id = 20, updated_at = now() where id = 6185 and campaign_year_id = 21;
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/vFrNMFdp0EC4wy1-wMIM3WUAKmLO?Type=TaskLink&Channel=Link&CreatedTime=638549256147830000)
=> (MASTER) [jp-0147] Fixing the pledge with Tran# 6185, update the calendar year to 2024 from 2025

resources/views/admin-pledge/campaign/wizard.blade.php
Requirements:
The default calendar year would indicate using the current year when the campaign is not yet open. Once the campaign for the next calendar year, such as 2025, opens, the system will default to calendar year 2025 (campaign year 2024).
When click on the next step to 2nd page during create a annual campaign pledge, the pop message ask for confirmation of the calendar year choice
=>  [jp-0148] Admin: Annual Campaign Pledge -- Pop-up message to confirm calendar year (use javascript confirm instead of sweetalert2)

resources/views/admin-pledge/campaign/wizard.blade.php
Requirements:
The default calendar year would indicate using the current year when the campaign is not yet open. Once the campaign for the next calendar year, such as 2025, opens, the system will default to calendar year 2025 (campaign year 2024).
When click on the next step to 2nd page during create a annual campaign pledge, the pop message ask for confirmation of the calendar year choice
=> (TEST)  [jp-0148] Admin: Annual Campaign Pledge -- Pop-up message to confirm calendar year (use javascript confirm instead of sweetalert2)

resources/views/admin-pledge/campaign/wizard.blade.php
Requirements:
The default calendar year would indicate using the current year when the campaign is not yet open. Once the campaign for the next calendar year, such as 2025, opens, the system will default to calendar year 2025 (campaign year 2024).
When click on the next step to 2nd page during create a annual campaign pledge, the pop message ask for confirmation of the calendar year choice
=> [jp-0148] Admin: Annual Campaign Pledge -- Pop-up message to confirm calendar year (use sweetalert2 and rearrange logic)

app/Http/Requests/BusinessUnitRequest.php
Jun 21 - Bug found in the Business Unit page, when update the BU without changing the acronym, the duplicate error "The acronym has already been taken." shown.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/fpg-L2Kt2U2OTLt7ivkFgWUAH-Nt?Type=TaskLink&Channel=Link&CreatedTime=638545870733130000)
=> (MASTER) [jp-0146] Bug in Business Unit page, incorrect 'acronym' duplicate error shown when update

database/seeders/DataFixFor_jp_0151_Event173.php
Reallocate pledge for LSA Fundraiser event due to inactive charity. (Tran ID 173, PECSF ID F23093). Showing on 40D Reconciliation Report. 
BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY is no longer an active charity and needs to be reallocated to remove from 40D Rec. 
Move current allocation from:
BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY (50%), ALZEIMER SOCIETY OF B.C. (50%)
to
FIRST NATIONS HEALTH FOUNDATION (50%), ALZEIMER SOCIETY OF B.C. (50%)
June 27 - Developed the script for reassign the charity on Event Pledge#173
From 
896694098RR0001 BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY   (9290) 
To 
713653103RR0001   First Nations Health Foundation (133718)
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/6fDO76PWGUeN3CON4dgXFWUAIS8R?Type=TaskLink&Channel=Link&CreatedTim …
=> [jp-0151] Reassign Charity on Event Pledge Tran#173

database/seeders/DataFixFor_jp_0151_Event173.php
Reallocate pledge for LSA Fundraiser event due to inactive charity. (Tran ID 173, PECSF ID F23093). Showing on 40D Reconciliation Report. 
BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY is no longer an active charity and needs to be reallocated to remove from 40D Rec. 
Move current allocation from:
BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY (50%), ALZEIMER SOCIETY OF B.C. (50%)
to
FIRST NATIONS HEALTH FOUNDATION (50%), ALZEIMER SOCIETY OF B.C. (50%)
June 27 - Developed the script for reassign the charity on Event Pledge#173
From 
896694098RR0001 BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY   (9290) 
To 
713653103RR0001   First Nations Health Foundation (133718)
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/6fDO76PWGUeN3CON4dgXFWUAIS8R?Type=TaskLink&Channel=Link&CreatedTim …
=> (TEST) [jp-0151] Reassign Charity on Event Pledge Tran#173

database/seeders/DataFixFor_jp_0151_Event173.php
Reallocate pledge for LSA Fundraiser event due to inactive charity. (Tran ID 173, PECSF ID F23093). Showing on 40D Reconciliation Report. 
BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY is no longer an active charity and needs to be reallocated to remove from 40D Rec. 
Move current allocation from:
BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY (50%), ALZEIMER SOCIETY OF B.C. (50%)
to
FIRST NATIONS HEALTH FOUNDATION (50%), ALZEIMER SOCIETY OF B.C. (50%)
June 27 - Developed the script for reassign the charity on Event Pledge#173
From 
896694098RR0001 BC ABORIGINAL NETWORK ON DISABIITLY SOCIETY   (9290) 
To 
713653103RR0001   First Nations Health Foundation (133718)
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/6fDO76PWGUeN3CON4dgXFWUAIS8R?Type=TaskLink&Channel=Link&CreatedTim …
=> (MASTER) [jp-0151] Reassign Charity on Event Pledge Tran#173

app/Http/Controllers/ChallengeController.php
James have encountered a bug on the statistics page, there are no current campaign year data displayed on statistics page, only the total donors and donation amounts
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/35mTk5emRkubU5S-aY18g2UAB5vX?Type=TaskLink&Channel=Link&CreatedTime=638560934054120000)
=> [jp-0153]  No current campaign year data shows on Statistics Page

app/Http/Controllers/ChallengeController.php
James have encountered a bug on the statistics page, there are no current campaign year data displayed on statistics page, only the total donors and donation amounts
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/35mTk5emRkubU5S-aY18g2UAB5vX?Type=TaskLink&Channel=Link&CreatedTime=638560934054120000)
=> (TEST) [jp-0153]  No current campaign year data shows on Statistics Page

Dockerfile
Jul 4  - we have encountered Production migration failure. The Github Pull request Production deployment action was failed 
Jul 5 - reported to Kunal and start investigation. James has replicate this issue on DEV and TEST and noticed that the same issue. According to Kunal findings and email:
Looks like it is failing to get the php dist or buster
from https://packages.sury.org/php/dists 
403 Forbidden 
The last successful run for this build happened on June 28 where the package was successfully downloaded. 
I guess the difference between the Docker file or PDP and PECSF is that PECSF docker files runs an apt-get update command (where the build is failing) just after the debian buster package is added to the
/etc/apt/sources.list.d/php.list file. When the apt-get update command runs, it …
=> (MASTER) Update base image to php:8.1-apache-bullseye 

database/seeders/DataFixFor_jp_0155_DonateNow117.php
Tran ID 117 - There is a $50.00 Donate Now Pledge going to an inactive Charity, this needs to be updated to one of the pledge donors other chosen charities. If possible can the Donate Now pledge be split 50/50 between her two other charity choices or two Donate Now pledges be created. We are unable to make any adjustments through Greenfield.  
Move from - Sahaara Foundation (Inactive Charity)
Move to - Foundation for Youth Rights to Education Canada (Active Charity)
Asian Canadian Cancer Fellowship Association (Active Charity) 
Update July 10, 2024
Donate Now Pledge can't be split between multiple charities. Please allocate the full amount ($50.00) from Sahaara Foundation to Found for Youth Rights to Education Canada. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mrJUW …
=> [jp-0155] Update Donate Now Pledge (Tran ID 117)

database/seeders/DataFixFor_jp_0155_DonateNow117.php
Tran ID 117 - There is a $50.00 Donate Now Pledge going to an inactive Charity, this needs to be updated to one of the pledge donors other chosen charities. If possible can the Donate Now pledge be split 50/50 between her two other charity choices or two Donate Now pledges be created. We are unable to make any adjustments through Greenfield.
Move from - Sahaara Foundation (Inactive Charity)
Move to - Foundation for Youth Rights to Education Canada (Active Charity)
Asian Canadian Cancer Fellowship Association (Active Charity)
Update July 10, 2024
Donate Now Pledge can't be split between multiple charities. Please allocate the full amount ($50.00) from Sahaara Foundation to Found for Youth Rights to Education Canada.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mrJUWiXxr …
=> (TEST) [jp-0155] Update Donate Now Pledge (Tran ID 117) 

database/seeders/DataFixFor_jp_0155_DonateNow117.php
Tran ID 117 - There is a $50.00 Donate Now Pledge going to an inactive Charity, this needs to be updated to one of the pledge donors other chosen charities. If possible can the Donate Now pledge be split 50/50 between her two other charity choices or two Donate Now pledges be created. We are unable to make any adjustments through Greenfield.
Move from - Sahaara Foundation (Inactive Charity)
Move to - Foundation for Youth Rights to Education Canada (Active Charity)
Asian Canadian Cancer Fellowship Association (Active Charity)
Update July 10, 2024
Donate Now Pledge can't be split between multiple charities. Please allocate the full amount ($50.00) from Sahaara Foundation to Found for Youth Rights to Education Canada.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/mrJUWiXxr …
=> (MASTER) [jp-0155] Update Donate Now Pledge (Tran ID 117)

app/Http/Controllers/ChallengeController.php
The date option field does not display a list of dates under Daily Campaign Update tab (http://localhost:8000/challenge/daily_campaign)
Menu > Statistics 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ann2P5OioEaRotvX-BSyeGUAKAeb?Type=TaskLink&Channel=Link&CreatedTime=638563077095330000)
=> [jp-0156] Daily Campaign Update tab - The date option field does not display a list of dates

app/Http/Controllers/ChallengeController.php
The date option field does not display a list of dates under Daily Campaign Update tab (http://localhost:8000/challenge/daily_campaign)
Menu > Statistics
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ann2P5OioEaRotvX-BSyeGUAKAeb?Type=TaskLink&Channel=Link&CreatedTime=638563077095330000)
=> (TEST) [jp-0156] Daily Campaign Update tab - The date option field does not display a list of dates

resources/views/admin-campaign/eligible-employee-summary/index.blade.php
Issue on Admin -> Campaign setup -> Statistics Setup -> Eligible Employee Summary Maintenance page
If admin tries to enter a new record, the expected outcome is everytime admin clicks on Add a new Record, the form modal that opens must be blank.
Actual: If admin puts details in the modal and creates a new record -> Clicks on the Add new record button again, the previously entered data is not cleared.
If admin puts details in the modal and cancels -> Clicks on the Add new record button again, the previously entered data is not cleared.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/4P_WRMUX60COtG48LbGT4WUABCyS?Type=TaskLink&Channel=Link&CreatedTime=638563088217510000)
=> [jp-0157] Form does not clear when adding a new record on the Eligible Employee Summary Maintenance page

resources/views/admin-campaign/eligible-employee-summary/index.blade.php
Issue on Admin -> Campaign setup -> Statistics Setup -> Eligible Employee Summary Maintenance page
If admin tries to enter a new record, the expected outcome is everytime admin clicks on Add a new Record, the form modal that opens must be blank.
Actual: If admin puts details in the modal and creates a new record -> Clicks on the Add new record button again, the previously entered data is not cleared.
If admin puts details in the modal and cancels -> Clicks on the Add new record button again, the previously entered data is not cleared.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/4P_WRMUX60COtG48LbGT4WUABCyS?Type=TaskLink&Channel=Link&CreatedTime=638563088217510000)
=> (TEST) [jp-0157] Form does not clear when adding a new record on the Eligible Employee Summary Maintenance page

app/Http/Controllers/Admin/EventSubmissionQueueController.php, app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php
148617
110051
Jul 11 - very good finding, the criteria on the sql shouldn't limit to the linked BU only. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/72NGI_hyRUe8o937UTPZY2UAN3kG?Type=TaskLink&Channel=Link&CreatedTime=638563114466450000)
=> [jp-0158] Business unit in event form does not pop up for BC063, BC725

app/Http/Controllers/Admin/EventSubmissionQueueController.php, app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php
148617
110051
Jul 11 - very good finding, the criteria on the sql shouldn't limit to the linked BU only.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/72NGI_hyRUe8o937UTPZY2UAN3kG?Type=TaskLink&Channel=Link&CreatedTime=638563114466450000)
=> (TEST) [jp-0158] Business unit in event form does not pop up for BC063, BC725

app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
Found an SQL error when check the production laravel log file 
[2024-07-05 10:15:36] prod.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'where clause' (Connection: mysql, SQL: select count(*) as aggregate from `special_campaign_pledges` left join `employee_jobs` on `employee_jobs`.`emplid` = `special_campaign_pledges`.`emplid` where ((`employee_jobs`.`empl_rcd` = (select min(J2.empl_rcd) from `employee_jobs` as `J2` where `J2`.`emplid` = `employee_jobs`.`emplid`) or `employee_jobs`.`empl_rcd` is null) and `special_campaign_pledges`.`first_name` like %Nicole% or `special_campaign_pledges`.`first_name` like %Nicole% or `users`.`name` like %Nicole% and `yearcd` = 2024) and `special_campaign_pledges`.`deleted_at` is null) {"userId":33248,"exception":"[object] …
=> [jp-0154] SQL error -- Unknown column users.name in where clause

app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
Found an SQL error when check the production laravel log file 
[2024-07-05 10:15:36] prod.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'where clause' (Connection: mysql, SQL: select count(*) as aggregate from `special_campaign_pledges` left join `employee_jobs` on `employee_jobs`.`emplid` = `special_campaign_pledges`.`emplid` where ((`employee_jobs`.`empl_rcd` = (select min(J2.empl_rcd) from `employee_jobs` as `J2` where `J2`.`emplid` = `employee_jobs`.`emplid`) or `employee_jobs`.`empl_rcd` is null) and `special_campaign_pledges`.`first_name` like %Nicole% or `special_campaign_pledges`.`first_name` like %Nicole% or `users`.`name` like %Nicole% and `yearcd` = 2024) and `special_campaign_pledges`.`deleted_at` is null) {"userId":33248,"exception":"[object] …
=> (TEST) [jp-0154] SQL error -- Unknown column users.name in where clause

app/Http/Controllers/ChallengeController.php
James have encountered a bug on the statistics page, there are no current campaign year data displayed on statistics page, only the total donors and donation amounts
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/35mTk5emRkubU5S-aY18g2UAB5vX?Type=TaskLink&Channel=Link&CreatedTime=638560934054120000)
=> (MASTER) [jp-0153]  No current campaign year data shows on Statistics Page

app/Http/Controllers/Admin/SpecialCampaignPledgeController.php
Found an SQL error when check the production laravel log file
[2024-07-05 10:15:36] prod.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'where clause' (Connection: mysql, SQL: select count() as aggregate from special_campaign_pledges left join employee_jobs on employee_jobs.emplid = special_campaign_pledges.emplid where ((employee_jobs.empl_rcd = (select min(J2.empl_rcd) from employee_jobs as J2 where J2.emplid = employee_jobs.emplid) or employee_jobs.empl_rcd is null) and special_campaign_pledges.first_name like %Nicole% or special_campaign_pledges.first_name like %Nicole% or users.name like %Nicole% and yearcd = 2024) and special_campaign_pledges.deleted_at is null) {"userId":33248,"exception":"[object] (Illuminate\Database\QueryException(code: 42S22): …
=> (MASTER) [jp-0154] SQL error -- Unknown column users.name in where clause

app/Http/Controllers/ChallengeController.php
The date option field does not display a list of dates under Daily Campaign Update tab (http://localhost:8000/challenge/daily_campaign)
Menu > Statistics
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Ann2P5OioEaRotvX-BSyeGUAKAeb?Type=TaskLink&Channel=Link&CreatedTime=638563077095330000)
=> (MASTER) [jp-0156] Daily Campaign Update tab - The date option field does not display a list of dates

app/Http/Controllers/Admin/EventSubmissionQueueController.php, app/Http/Controllers/Admin/MaintainEventPledgeController.php, app/Http/Controllers/BankDepositFormController.php
148617
110051
Jul 11 - very good finding, the criteria on the sql shouldn't limit to the linked BU only.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/72NGI_hyRUe8o937UTPZY2UAN3kG?Type=TaskLink&Channel=Link&CreatedTime=638563114466450000)
=> (MASTER) [jp-0158] Business unit in event form does not pop up for BC063, BC725

app/Http/Controllers/DonationController.php
Test account user Employee 103 has a donation history in which the year 2020 displays 2 Annual pledges. - Bi-weekly and One-time. These 2 pledges should be made to the same number of charities as there is no way to make separate pledges. 
July 25 - Noticed that one entry is a gaming event 
Question: For consistency, do we remove the gaming and fundraising events from the donation history? The numbers are also added to the employee's total amount of donation made.
July 25 - PO response: fundraising and gaming events submitted by employees should not be included in personal donation history (no exceptions). Only "Event pledge" that should be included are cash/cheque donations.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/JXEq5PvVEkyK6eR6sIpodWUAOIxM?Type=TaskLink&Channel …
=> [jp-0163] Historical gaming/fundraiser event appears on employee's donation history

app/Http/Controllers/DonationController.php
Test account user Employee 103 has a donation history in which the year 2020 displays 2 Annual pledges. - Bi-weekly and One-time. These 2 pledges should be made to the same number of charities as there is no way to make separate pledges.
July 25 - Noticed that one entry is a gaming event
Question: For consistency, do we remove the gaming and fundraising events from the donation history? The numbers are also added to the employee's total amount of donation made.
July 25 - PO response: fundraising and gaming events submitted by employees should not be included in personal donation history (no exceptions). Only "Event pledge" that should be included are cash/cheque donations.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/JXEq5PvVEkyK6eR6sIpodWUAOIxM?Type=TaskLink&Channel=L …
=> (TEST) [jp-0163] Historical gaming/fundraiser event appears on employee's donation history

app/Http/Controllers/Admin/ChallengePageDataReportController.php
There are some BU that have 0 donors but still displays in the Statistics Page Data Report and also in the excel sheet when downloaded. Can we remove the one's with 0 entries?
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Dd-PVYgbnUG8U_uxS7T0nmUAGGjP?Type=TaskLink&Channel=Link&CreatedTime=638575373293410000)
=> [jp-0164] Remove the entries displaying 0 from the Statistics Page Data Report

app/Http/Controllers/Admin/ChallengePageDataReportController.php
There are some BU that have 0 donors but still displays in the Statistics Page Data Report and also in the excel sheet when downloaded. Can we remove the one's with 0 entries?
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Dd-PVYgbnUG8U_uxS7T0nmUAGGjP?Type=TaskLink&Channel=Link&CreatedTime=638575373293410000)
=> (TEST) [jp-0164] Remove the entries displaying 0 from the Statistics Page Data Report 

app/Http/Controllers/ChallengeController.php
Issue:
Once the challenge finalize date is updated for the next campaign year, the previously finalized statistics data will no longer be displayed on the statistics page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/HMC0wouchkuuj6uLIX3BpmUAAXDz?Type=TaskLink&Channel=Link&CreatedTime=638579681952110000)
=> (TEST) [jp-0166] Previous finalized statistics data can't display on statistics Page

app/Http/Controllers/ChallengeController.php
Issue: 
Once the challenge finalize date is updated for the next campaign year, the previously finalized statistics data will no longer be displayed on the statistics page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/HMC0wouchkuuj6uLIX3BpmUAAXDz?Type=TaskLink&Channel=Link&CreatedTime=638579681952110000)
=> [jp-0166] Previous finalized statistics data can't display on statistics Page

app/Http/Controllers/DonationController.php
Test account user Employee 103 has a donation history in which the year 2020 displays 2 Annual pledges. - Bi-weekly and One-time. These 2 pledges should be made to the same number of charities as there is no way to make separate pledges.
July 25 - Noticed that one entry is a gaming event
Question: For consistency, do we remove the gaming and fundraising events from the donation history? The numbers are also added to the employee's total amount of donation made.
July 25 - PO response: fundraising and gaming events submitted by employees should not be included in personal donation history (no exceptions). Only "Event pledge" that should be included are cash/cheque donations.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/JXEq5PvVEkyK6eR6sIpodWUAOIxM?Type=TaskLink&Channel=L …
=> (MASTER)  [jp-0163] Historical gaming/fundraiser event appears on employee's donation history

app/Http/Controllers/Admin/ChallengePageDataReportController.php
There are some BU that have 0 donors but still displays in the Statistics Page Data Report and also in the excel sheet when downloaded. Can we remove the one's with 0 entries?
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Dd-PVYgbnUG8U_uxS7T0nmUAGGjP?Type=TaskLink&Channel=Link&CreatedTime=638575373293410000)
=> (MASTER) [jp-0164] Remove the entries displaying 0 from the Statistics Page Data Report

app/Http/Controllers/ChallengeController.php
Issue:
Once the challenge finalize date is updated for the next campaign year, the previously finalized statistics data will no longer be displayed on the statistics page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/HMC0wouchkuuj6uLIX3BpmUAAXDz?Type=TaskLink&Channel=Link&CreatedTime=638579681952110000)
=> (MASTER) [jp-0166] Previous finalized statistics data can't display on statistics Page

database/seeders/DataFixFor_jp_0167_EE185747.php
Add a one-time pledge of $73.84 for EE 185747 (P. Osborn) to Okanagan Central Christadelphian Ecclesia. Through the backend and not through Peoplesoft, the deduction has already occurred. 
This is needed to clear the No-Pledge showing in the 40D Reconciliation report. 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/n96qPKT9AEKFxsYLcFyujGUAC_l2?Type=TaskLink&Channel=Link&CreatedTime=638580462848670000)
=> [jp-0167] Pledge# 6184 -- Create One-Time amount through backend

database/seeders/DataFixFor_jp_0167_EE185747.php
Add a one-time pledge of $73.84 for EE 185747 (P. Osborn) to Okanagan Central Christadelphian Ecclesia. Through the backend and not through Peoplesoft, the deduction has already occurred.
This is needed to clear the No-Pledge showing in the 40D Reconciliation report.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/n96qPKT9AEKFxsYLcFyujGUAC_l2?Type=TaskLink&Channel=Link&CreatedTime=638580462848670000)
=> (TEST) [jp-0167] Pledge# 6184 -- Create One-Time amount through backend

database/seeders/DataFixFor_jp_0167_EE185747.php
Add a one-time pledge of $73.84 for EE 185747 (P. Osborn) to Okanagan Central Christadelphian Ecclesia. Through the backend and not through Peoplesoft, the deduction has already occurred.
This is needed to clear the No-Pledge showing in the 40D Reconciliation report.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/n96qPKT9AEKFxsYLcFyujGUAC_l2?Type=TaskLink&Channel=Link&CreatedTime=638580462848670000)
=> (MASTER) [jp-0167] Pledge# 6184 -- Create One-Time amount through backend

app/Console/Commands/UpdateEligibleEmployeeSnapshot.php, app/Http/Controllers/Admin/ChallengeSettingsController.php, app/Http/Controllers/ChallengeController.php, app/Models/Setting.php, database/migrations/2024_08_01_101435_add_snap_shot_date_in_settings_table.php, resources/views/admin-campaign/challenge/index.blade.php, resources/views/challenge/partials/tabs.blade.php
Add new fields for Eligible Employee Snapshot date 1 and date 2 added. Those fields will be used for determine when generate Eligible Employee snapshot and make the Org Participation Tracker report availability.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/1sJEqPKXAk-oFMOCHAEUkWUAFmwH?Type=TaskLink&Channel=Link&CreatedTime=638581416337480000)
=> [jp-0168] Organization Participation Tracker must function on custom dates

app/Console/Commands/UpdateEligibleEmployeeSnapshot.php, app/Http/Controllers/Admin/ChallengeSettingsController.php, app/Http/Controllers/ChallengeController.php, app/Models/Setting.php, database/migrations/2024_08_01_101435_add_snap_shot_date_in_settings_table.php, resources/views/admin-campaign/challenge/index.blade.php, resources/views/challenge/partials/tabs.blade.php
Add new fields for Eligible Employee Snapshot date 1 and date 2 added. Those fields will be used for determine when generate Eligible Employee snapshot and make the Org Participation Tracker report availability.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/1sJEqPKXAk-oFMOCHAEUkWUAFmwH?Type=TaskLink&Channel=Link&CreatedTime=638581416337480000)
=> (TEST) [jp-0168] Organization Participation Tracker must function on custom dates

resources/views/admin-pledge/donate-now/create-edit.blade.php
Business requirement:
Administrators need to update user charity choices due to the charities being inactive on the CRA listing.
Add a new function for administrators to modify the selected charities for the Donate Now Pledge that transfers to PeopleSoft.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/7H1v1YYLekecFT4OyuEl8mUAAKm_?Type=TaskLink&Channel=Link&CreatedTime=638567496540340000)
=> [jp-0159] Admin -- Enable administrators to modify the selected charities for the Donate Now pledge that transfers to PeopleSoft (fix bug)

database/seeders/DataFixFor_jp_0169_DonateNowPledges1_to_6.php
The Donate Now Pledge (PECADD) for 3 Gov EEs’ deduct from pay dates do not match the actual deduction check dates. Greenfield shows the Deduction Pay as 2024-01-05, the actual deduction Pay should be 2024-01-19.
Please update the Deduct Pay date in Greenfield for the three EEs below to the correct date.
EE Deduct Pay Actual Deduct Pay Date
010058 2024-01-05 2024-01-19
064306 2024-01-05 2024-01-19
160588 2024-01-05 2024-01-19
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/z1g9uyBIjUyXw2k7eoewTmUAHe6G?Type=TaskLink&Channel=Link&CreatedTime=638590857585870000)
=> [jp-0169] Correct Deduct Pay dates in Donate Now

database/seeders/DataFixFor_jp_0169_DonateNowPledges1_to_6.php
The Donate Now Pledge (PECADD) for 3 Gov EEs’ deduct from pay dates do not match the actual deduction check dates. Greenfield shows the Deduction Pay as 2024-01-05, the actual deduction Pay should be 2024-01-19.  
Please update the Deduct Pay date in Greenfield for the three EEs below to the correct date. 
EE                    Deduct Pay      Actual Deduct Pay Date  
010058                2024-01-05       2024-01-19 
064306                2024-01-05       2024-01-19 
160588                2024-01-05       2024-01-19 
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/z1g9uyBIjUyXw2k7eoewTmUAHe6G?Type=TaskLink&Channel=Link&CreatedTime=638590857585870000)
=> (TEST) [jp-0169] Correct Deduct Pay dates in Donate Now

database/seeders/DataFixFor_jp_0170_EE080753.php
BCSC EE 080753 shows in Greenfield is incorrectly showing as having a bi-weekly payroll deduction of $800.00. It should show as a One-time payroll deduction.
Transaction ID: 5710
From $800.00 Bi-weekly payroll deduction
To $800.00 One-time payroll deduction
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/zX8vQMNS_kORRCeArHUNA2UAKQaz?Type=TaskLink&Channel=Link&CreatedTime=638590856700440000)
=> (TEST) [jp-0170] Campiagn Pledge 5710 -- Correct BCSC EE Deduction Type

database/seeders/DataFixFor_jp_0170_EE080753.php
BCSC EE 080753 shows in Greenfield is incorrectly showing as having a bi-weekly payroll deduction of $800.00. It should show as a One-time payroll deduction.
Transaction ID: 5710
From $800.00 Bi-weekly payroll deduction
To $800.00 One-time payroll deduction
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/zX8vQMNS_kORRCeArHUNA2UAKQaz?Type=TaskLink&Channel=Link&CreatedTime=638590856700440000)
=> [jp-0170] Campaign Pledge 5710 -- Correct BCSC EE Deduction Type

resources/views/admin-campaign/challenge/index.blade.php
Add new fields for Eligible Employee Snapshot date 1 and date 2 added. Those fields will be used for determine when generate Eligible Employee snapshot and make the Org Participation Tracker report availability.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/1sJEqPKXAk-oFMOCHAEUkWUAFmwH?Type=TaskLink&Channel=Link&CreatedTime=638581416337480000)
=> [jp-0168] Organization Participation Tracker must function on custom dates (fine tune wordings)

database/seeders/DataFixFor_jp_0169_DonateNowPledges1_to_6.php
The Donate Now Pledge (PECADD) for 3 Gov EEs’ deduct from pay dates do not match the actual deduction check dates. Greenfield shows the Deduction Pay as 2024-01-05, the actual deduction Pay should be 2024-01-19.
Please update the Deduct Pay date in Greenfield for the three EEs below to the correct date.
EE Deduct Pay Actual Deduct Pay Date
010058 2024-01-05 2024-01-19
064306 2024-01-05 2024-01-19
160588 2024-01-05 2024-01-19
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/z1g9uyBIjUyXw2k7eoewTmUAHe6G?Type=TaskLink&Channel=Link&CreatedTime=638590857585870000)
=> (MASTER) [jp-0169] Correct Deduct Pay dates in Donate Now

database/seeders/DataFixFor_jp_0170_EE080753.php
BCSC EE 080753 shows in Greenfield is incorrectly showing as having a bi-weekly payroll deduction of $800.00. It should show as a One-time payroll deduction.
Transaction ID: 5710
From $800.00 Bi-weekly payroll deduction
To $800.00 One-time payroll deduction
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/zX8vQMNS_kORRCeArHUNA2UAKQaz?Type=TaskLink&Channel=Link&CreatedTime=638590856700440000)
=> (MASTER) [jp-0170] Campiagn Pledge 5710 -- Correct BCSC EE Deduction Type

package-lock.json
Aug 13- 1 HIGH vulnerabilities reported on Github.
Server-Side Request Forgery in axios
https://github.com/bcgov/PECSF/security/dependabot/93
Required to "Upgrade axios to fix 1 Dependabot alert in package-lock.json"
Package                 Affected versions            Patched version    
axios (npm)          >= 1.3.2, <= 1.7.3           1.7.4       
axios 1.7.2 allows SSRF via unexpected behavior where requests for path relative URLs get processed as protocol relative URLs.
Action:
====
> npm audit 
axios  1.3.2 - 1.7.3
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
8 vulnerabilities (2 low, 5 moderate, 1 high)
> npm audit fix
6 vulnerabilities (1 low, 5 moderate) …
=> [jp-0171] Security update required -- 1 HIGH security vulnerability

package-lock.json
Aug 13- 1 HIGH vulnerabilities reported on Github.
Server-Side Request Forgery in axios
https://github.com/bcgov/PECSF/security/dependabot/93
Required to "Upgrade axios to fix 1 Dependabot alert in package-lock.json"
Package                 Affected versions            Patched version    
axios (npm)          >= 1.3.2, <= 1.7.3           1.7.4       
axios 1.7.2 allows SSRF via unexpected behavior where requests for path relative URLs get processed as protocol relative URLs.
Action:
====
> npm audit 
axios  1.3.2 - 1.7.3
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
8 vulnerabilities (2 low, 5 moderate, 1 high)
> npm audit fix
6 vulnerabilities (1 low, 5 moderate) …
=> (MASTER) [jp-0171] Security update required -- 1 HIGH security vulnerability

app/Http/Controllers/BankDepositFormController.php, app/Models/BankDepositForm.php, app/Models/BusinessUnit.php, app/Models/EmployeeJob.php, app/Models/Pledge.php, tests/Feature/AdminBankDepositFormTest.php, tests/Feature/AdminCampaignPledgeTest.php, tests/Feature/AdminSubmissionQueueTest.php, tests/Feature/AdminVolunteerProfileTest.php, tests/Feature/AnnualCampaignTest.php, tests/Feature/BankDepositFormTest.php, tests/Feature/ChallengePageTest.php, tests/Feature/ChallengeSettingsTest.php
Issue:
148617
110051
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/yR-kl2f26EuJ5YKGmdXz0mUALE54?Type=TaskLink&Channel=Link&CreatedTime=638603689656190000)
=> (TEST) [jp-0172] eForm - Default Business Unit not assigned

resources/views/donations/index.blade.php
1) For text outside of campaign
Enhancement on the My Donations page. Can we change the text :
Since you started giving through PECSF, you've donated $0, as BC Public Servant.
reflects pledge totals from 2005 onwards
To
Since you began donating through PECSF, your total contributions as a BC Public Servant amount to $0.
The donation history below reflects pledge totals from 2005 onwards.
2) For text in campaaign:
Can we change the text : 
To make a pledge click the Donate button, copy a prior year's choices from your Donation History. 
To 
To make a pledge, click the Donate button or copy a prior year's choice from your Donation History.
[Ticket ](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/JDGrijxwFEKfCSkg3pvKf2UACHX0?Type=TaskLink&Channel=Link&CreatedTime=638603765130840000 …
=> [jp-0173] Content change on My Donations page

app/Http/Controllers/BankDepositFormController.php, app/Models/BankDepositForm.php, app/Models/BusinessUnit.php, app/Models/EmployeeJob.php, app/Models/Pledge.php, tests/Feature/AdminBankDepositFormTest.php, tests/Feature/AdminCampaignPledgeTest.php, tests/Feature/AdminSubmissionQueueTest.php, tests/Feature/AdminVolunteerProfileTest.php, tests/Feature/AnnualCampaignTest.php, tests/Feature/BankDepositFormTest.php, tests/Feature/ChallengePageTest.php, tests/Feature/ChallengeSettingsTest.php
Issue:
148617
110051
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/yR-kl2f26EuJ5YKGmdXz0mUALE54?Type=TaskLink&Channel=Link&CreatedTime=638603689656190000)
=> [jp-0172] eForm - Default Business Unit not assigned

resources/views/donations/index.blade.php
When not in an active campaign, the text displayed in the blue banner on the My donations page is incorrect.
The text says 'Click the “Details” button below to see your campaign pledge.'
There is no details button on the page now, so can we please remove this line?
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ezvXYHFZd0-PnZW8hi12omUADxJ2?Type=TaskLink&Channel=Link&CreatedTime=638603818208280000)
=> (TEST) [jp-0175] Correct the text displayed in the blue banner on My Donations

resources/views/donations/index.blade.php
When not in an active campaign, the text displayed in the blue banner on the My donations page is incorrect. 
The text says 'Click the “Details” button below to see your campaign pledge.' 
There is no details button on the page now, so can we please remove this line? 
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ezvXYHFZd0-PnZW8hi12omUADxJ2?Type=TaskLink&Channel=Link&CreatedTime=638603818208280000)
=> [jp-0175] Correct the text displayed in the blue banner on My Donations

resources/views/donations/index.blade.php
For text outside of campaign
Enhancement on the My Donations page. Can we change the text :
Since you started giving through PECSF, you've donated $0, as BC Public Servant.
reflects pledge totals from 2005 onwards
To
Since you began donating through PECSF, your total contributions as a BC Public Servant amount to $0.
The donation history below reflects pledge totals from 2005 onwards.
For text in campaaign:
Can we change the text :
To make a pledge click the Donate button, copy a prior year's choices from your Donation History.
To
To make a pledge, click the Donate button or copy a prior year's choice from your Donation History.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/JDGrijxwFEKfCSkg3pvKf2UACHX0?Type=TaskLink&Channel=Link&CreatedTime=638603765130840000)
=> (MASTER) [jp-0173] Content change on My Donations page

resources/views/donations/index.blade.php
When not in an active campaign, the text displayed in the blue banner on the My donations page is incorrect.
The text says 'Click the “Details” button below to see your campaign pledge.'
There is no details button on the page now, so can we please remove this line?
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/ezvXYHFZd0-PnZW8hi12omUADxJ2?Type=TaskLink&Channel=Link&CreatedTime=638603818208280000)
=> (MASTER) [jp-0175] Correct the text displayed in the blue banner on My Donations

app/Http/Controllers/AnnualCampaignController.php
Issue
In an active campaign, user made a donation and landed on the Thank you page. Insisted on clicking on view donation history, if user clicks on the refresh page, a 403 error is received.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/hugrTmeHT0eZBnTH8EyL4mUAA7Jj?Type=TaskLink&Channel=Link&CreatedTime=638604634520530000)
=> [jp-0176] Refreshing the Thank You page in the donations throws a 403 error

app/Http/Controllers/BankDepositFormController.php, app/Http/Controllers/ContactFaqController.php, app/Models/BankDepositForm.php, app/Models/BusinessUnit.php, app/Models/EmployeeJob.php, app/Models/Pledge.php, resources/views/annual-campaign/partials/amount-distribution.blade.php, resources/views/annual-campaign/wizard.blade.php, resources/views/challenge/index.blade.php, resources/views/contact/index.blade.php, resources/views/donations/index.blade.php, tests/Feature/AdminBankDepositFormTest.php, tests/Feature/AdminCampaignPledgeTest.php, tests/Feature/AdminSubmissionQueueTest.php, tests/Feature/AdminVolunteerProfileTest.php, tests/Feature/AnnualCampaignTest.php, tests/Feature/BankDepositFormTest.php, tests/Feature/ChallengePageTest.php, tests/Feature/ChallengeSettingsTest.php
1)Issue only for in campaign. The 'Distribute evenly' on the Amount Distribution page of the donations must appear as link. Maybe an underline may work too. Currently the text highlights and has a border when hovered which is good. 
Example for reference is the PECSF email link in the blue banner text
2) Same issue as 1 at the page Statistics -> Leadership -> PECSF@gov.bc.ca
3) FAQ page -> PECSF@gov.bc.ca
4) FAQ -> Volunteering -> Volunteer Section
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2E0P_58MSkeTcmiVaKkiSWUAMNtu?Type=TaskLink&Channel=Link&CreatedTime=638604634992310000)
=> [jp-0177] Distribute evenly and PECSF email does not appear as link

app/Http/Controllers/AnnualCampaignController.php
Issue
In an active campaign, user made a donation and landed on the Thank you page. Insisted on clicking on view donation history, if user clicks on the refresh page, a 403 error is received.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/hugrTmeHT0eZBnTH8EyL4mUAA7Jj?Type=TaskLink&Channel=Link&CreatedTime=638604634520530000)
=> (TEST) [jp-0176] Refreshing the Thank You page in the donations throws a 403 error

app/Http/Controllers/BankDepositFormController.php, app/Http/Controllers/ContactFaqController.php, app/Models/BankDepositForm.php, app/Models/BusinessUnit.php, app/Models/EmployeeJob.php, app/Models/Pledge.php, resources/views/annual-campaign/partials/amount-distribution.blade.php, resources/views/annual-campaign/wizard.blade.php, resources/views/challenge/index.blade.php, resources/views/contact/index.blade.php, resources/views/donations/index.blade.php, tests/Feature/AdminBankDepositFormTest.php, tests/Feature/AdminCampaignPledgeTest.php, tests/Feature/AdminSubmissionQueueTest.php, tests/Feature/AdminVolunteerProfileTest.php, tests/Feature/AnnualCampaignTest.php, tests/Feature/BankDepositFormTest.php, tests/Feature/ChallengePageTest.php, tests/Feature/ChallengeSettingsTest.php
1)Issue only for in campaign. The 'Distribute evenly' on the Amount Distribution page of the donations must appear as link. Maybe an underline may work too. Currently the text highlights and has a border when hovered which is good.
Example for reference is the PECSF email link in the blue banner text
2) Same issue as 1 at the page Statistics -> Leadership -> [PECSF@gov.bc.ca](mailto:PECSF@gov.bc.ca)
3) FAQ page -> [PECSF@gov.bc.ca](mailto:PECSF@gov.bc.ca)
4) FAQ -> Volunteering -> Volunteer Section
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/2E0P_58MSkeTcmiVaKkiSWUAMNtu?Type=TaskLink&Channel=Link&CreatedTime=638604634992310000)
=> (TEST) [jp-0177] Distribute evenly and PECSF email does not appear as link

app/Http/Controllers/AnnualCampaignController.php
Issue
In an active campaign, user made a donation and landed on the Thank you page. Insisted on clicking on view donation history, if user clicks on the refresh page, a 403 error is received.
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/hugrTmeHT0eZBnTH8EyL4mUAA7Jj?Type=TaskLink&Channel=Link&CreatedTime=638604634520530000)
=> (MASTER) [jp-0176] Refreshing the Thank You page in the donations throws a 403 error

app/Models/EmployeeJob.php
Employee103 - emp id 013238 had a 2025 annual pledge, which admin cancelled. The amounts on the donation history page and the volunteer profile page now differ. Not able to find the root cause.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/rVjfXqgFzEarpWXxUXV7UGUAMLSK?Type=TaskLink&Channel=Link&CreatedTime=638604641010020000)
=> (MASTER) [jp-0179] Inconsistency in the numbers on the volunteer profile and donation history page

resources/views/home.blade.php
As discussed with James, this text is marked as h3 and also overridden by the font-size: 4rem
Can we remove the overridden property and adjust the font size. Since its not a heading we want to remove the h3 tag too and add a bigger font size to the text.
Also, match the text colour with the text on the Volunteering dashboard
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Tzo1l4Unv0e1fmmBe0AGcGUAPgUQ?Type=TaskLink&Channel=Link&CreatedTime=638610775182950000)
=> [jp-0182] Remove the overriden properties from text - Generosity in Action on home page

resources/views/home.blade.php
As discussed with James, this text is marked as h3 and also overridden by the font-size: 4rem
Can we remove the overridden property and adjust the font size. Since its not a heading we want to remove the h3 tag too and add a bigger font size to the text.
Also, match the text colour with the text on the Volunteering dashboard
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Tzo1l4Unv0e1fmmBe0AGcGUAPgUQ?Type=TaskLink&Channel=Link&CreatedTime=638610775182950000)
=> (TEST) [jp-0182] Remove the overriden properties from text - Generosity in Action on home page

app/Http/Requests/VolunteerProfileRequest.php
We need to Add a character limit to the Street Address field on step 2 of volunteer registration
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/J2myHbw4vk6oCztFgJOjaGUAEeqj?Type=TaskLink&Channel=Link&CreatedTime=638610782559820000)
=> [jp-0183] Volunteer Registration: Add a character limit to the Street Address field

app/Http/Requests/VolunteerProfileRequest.php
We need to Add a character limit to the Street Address field on step 2 of volunteer registration
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/J2myHbw4vk6oCztFgJOjaGUAEeqj?Type=TaskLink&Channel=Link&CreatedTime=638610782559820000)
=> (TEST) [jp-0183] Volunteer Registration: Add a character limit to the Street Address field

resources/views/annual-campaign/partials/amount.blade.php, tests/Feature/ChallengePageTest.php
Expected: Can we add a $ sign to the text box. Reference is the Dollar Amount field on the amount distribution page. 
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/qzS4CV_8nka-Ts0kgWAkvGUAAVSo?Type=TaskLink&Channel=Link&CreatedTime=638610786649270000)
=> [jp-0184] Prepopulate a $ sign in the custom amount field of the donation

resources/views/annual-campaign/partials/amount.blade.php, tests/Feature/ChallengePageTest.php
Expected: Can we add a $ sign to the text box. Reference is the Dollar Amount field on the amount distribution page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/qzS4CV_8nka-Ts0kgWAkvGUAAVSo?Type=TaskLink&Channel=Link&CreatedTime=638610786649270000)
=> (TEST) [jp-0184] Prepopulate a $ sign in the custom amount field of the donation

app/Exports/PledgesExport.php
Issue:
The annual campaign pledge was created without emplid (special iDIR account) and cause the PledgeExport process was failed with the following error message 
ErrorException: Attempt to read property "linked_bu_code" on null in /var/www/html/app/Exports/PledgesExport.php:370
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Attempt to read...', '/var/www/html/a...', 370)
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/-k2Gv2kLfEmOl5VhRO84f2UAJk54?Type=TaskLink&Channel=Link&CreatedTime=638611580191850000)
=> [jp-0185] PledgeExport process was failed on attempt to read property on null

app/Exports/PledgesExport.php
Issue:
The annual campaign pledge was created without emplid (special iDIR account) and cause the PledgeExport process was failed with the following error message
ErrorException: Attempt to read property "linked_bu_code" on null in /var/www/html/app/Exports/PledgesExport.php:370
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Attempt to read...', '/var/www/html/a...', 370)
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/-k2Gv2kLfEmOl5VhRO84f2UAJk54?Type=TaskLink&Channel=Link&CreatedTime=638611580191850000)
=> (TEST) [jp-0185] PledgeExport process was failed on attempt to read property on null

composer.lock, package-lock.json
Sept 4 - 1 HIGH vulnerabilities reported on Github.
XXE in PHPSpreadsheet encoding is returned
https://github.com/bcgov/PECSF/security/dependabot/98
Summary
Bypassing the filter allows a XXE-attack. Which is turn allows attacker to obtain contents of local files, even if error reporting muted by @ symbol. (LFI-attack)
Details
Check  $pattern = '/encoding="(.*?)"/'; easy to bypass. Just use a single quote symbol '. So payload looks like this:
<?xml version="1.0" encoding='UTF-7' standalone="yes"?>
+ADw-!DOCTYPE xxe [+ADw-!ENTITY % xxe SYSTEM "http://example.com/file.dtd"> %xxe;]>
If you add this header to any XML file into xlsx-formatted file, such as sharedStrings.xml file, then xxe will execute.
Action
Package                                                       Affected versions …
=> (MASTER) [jp-0181] Security update required -- 1 HIGH security vulnerability

resources/views/home.blade.php
As discussed with James, this text is marked as h3 and also overridden by the font-size: 4rem
Can we remove the overridden property and adjust the font size. Since its not a heading we want to remove the h3 tag too and add a bigger font size to the text.
Also, match the text colour with the text on the Volunteering dashboard
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/Tzo1l4Unv0e1fmmBe0AGcGUAPgUQ?Type=TaskLink&Channel=Link&CreatedTime=638610775182950000)
=> (MASTER) [jp-0182] Remove the overriden properties from text - Generosity in Action on home page

app/Http/Requests/VolunteerProfileRequest.php
We need to Add a character limit to the Street Address field on step 2 of volunteer registration
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/J2myHbw4vk6oCztFgJOjaGUAEeqj?Type=TaskLink&Channel=Link&CreatedTime=638610782559820000)
=> (MASTER)  [jp-0183] Volunteer Registration: Add a character limit to the Street Address field 

resources/views/annual-campaign/partials/amount.blade.php, tests/Feature/ChallengePageTest.php
Expected: Can we add a $ sign to the text box. Reference is the Dollar Amount field on the amount distribution page.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/qzS4CV_8nka-Ts0kgWAkvGUAAVSo?Type=TaskLink&Channel=Link&CreatedTime=638610786649270000)
=> (MASTER)  [jp-0184] Prepopulate a $ sign in the custom amount field of the donation

app/Exports/PledgesExport.php
Issue:
The annual campaign pledge was created without emplid (special iDIR account) and cause the PledgeExport process was failed with the following error message
ErrorException: Attempt to read property "linked_bu_code" on null in /var/www/html/app/Exports/PledgesExport.php:370
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Attempt to read...', '/var/www/html/a...', 370)
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/-k2Gv2kLfEmOl5VhRO84f2UAJk54?Type=TaskLink&Channel=Link&CreatedTime=638611580191850000)
=> (MASTER) [jp-0185] PledgeExport process was failed on attempt to read property on null

package-lock.json
Sept 16 - 3 HIGH vulnerabilities reported npm audit:
> npm audit
body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
node_modules/body-parser
express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of body-parser
Depends on vulnerable versions of path-to-regexp
Depends on vulnerable versions of send
Depends on vulnerable versions of serve-static
path-to-regexp  <0.1.10
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
node_modules/path-to-regexp
11 vulnerabilities (1 low, 7 moderate, 3 high)
Action …
=> [jp-0190] Security update required -- 3 HIGH security vulnerability

package-lock.json
Sept 16 - 3 HIGH vulnerabilities reported npm audit:
> npm audit
body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
node_modules/body-parser
express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of body-parser
Depends on vulnerable versions of path-to-regexp
Depends on vulnerable versions of send
Depends on vulnerable versions of serve-static
path-to-regexp  <0.1.10
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
node_modules/path-to-regexp
11 vulnerabilities (1 low, 7 moderate, 3 high)
Action …
=> (TEST) [jp-0190] Security update required -- 3 HIGH security vulnerability

resources/views/donate-now/partials/amount.blade.php
We fixed this issue for in-campaign but didn't fix it for the field outside of the campaign.
Expected: Can we add a $ sign to the text box. Reference is the Dollar Amount field on the amount distribution page. 
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/_cUd01RlAEO2XTWrsMKVl2UAKcWl?Type=TaskLink&Channel=Link&CreatedTime=638621602374220000)
=> [jp-0191] Outside of campaign: Prepopulate a $ sign in the custom amount field of the donation

resources/views/donate-now/partials/amount.blade.php
We fixed this issue for in-campaign but didn't fix it for the field outside of the campaign.
Expected: Can we add a $ sign to the text box. Reference is the Dollar Amount field on the amount distribution page.
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/_cUd01RlAEO2XTWrsMKVl2UAKcWl?Type=TaskLink&Channel=Link&CreatedTime=638621602374220000)
=> (TEST) [jp-0191] Outside of campaign: Prepopulate a $ sign in the custom amount field of the donation

resources/views/donations/index.blade.php
Issue for both outside and in campaign. The 'Learn more about donating to PECSF' below the Donate to PECSF button must appear as link. Maybe an underline may work too. Currently the text highlights and has a border when hovered which is good.
Example for reference is the PECSF email link in the blue banner text
[Ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/k_-cbRY3sUybPEzcuEkIvWUAELBa?Type=TaskLink&Channel=Link&CreatedTime=638612393770580000)
=> (MASTER)  [jp-0186] Learn more about donating to PECSF does not appear as link 

resources/views/admin-pledge/campaign/index.blade.php
The 'Status' column on the page Maintain EE Pledges, is missing a sort icon as well as the sort functionality for the column
The sort icon besides the column header must appear
The admin must be able to click on the header to sort the column. Sorting must function throughout the table
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/AhgJ1sWdVEyhCBzs_wM-WGUACa0q?Type=TaskLink&Channel=Link&CreatedTime=638612394279750000)
=> (MASTER) [jp-0187] Missing sort feature on Status column on Maintain EE Pledge page

resources/views/volunteer-profile/partials/recognition-items.blade.php
When we hover over the checkbox, the mouse cursor must change to hand from arrow.
[ticket](https://tasks.office.com/bcgov.onmicrosoft.com/Home/Task/UCdIXnl8OUKzhIxhmUWK52UALMpa?Type=TaskLink&Channel=Link&CreatedTime=638612394930970000)
=> (MASTER)  [jp-0188] Mouse cursor does not change on hovering over the Opt-out checkbox in Registering as volunteer

package-lock.json
Sept 16 - 3 HIGH vulnerabilities reported npm audit:
> npm audit
body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
node_modules/body-parser
express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of body-parser
Depends on vulnerable versions of path-to-regexp
Depends on vulnerable versions of send
Depends on vulnerable versions of serve-static
path-to-regexp  <0.1.10
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
node_modules/path-to-regexp
11 vulnerabilities (1 low, 7 moderate, 3 high)
Action …
=> (MASTER) [jp-0190] Security update required -- 3 HIGH security vulnerability

resources/views/donate-now/partials/amount.blade.php
We fixed this issue for in-campaign but didn't fix it for the field outside of the campaign.
Expected: Can we add a $ sign to the text box. Reference is the Dollar Amount field on the amount distribution page.
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/_cUd01RlAEO2XTWrsMKVl2UAKcWl?Type=TaskLink&Channel=Link&CreatedTime=638621602374220000)
=> (MASTER) [jp-0191] Outside of campaign: Prepopulate a $ sign in the custom amount field of the donation 

package-lock.json
Oct 2 - 1 HIGH vulnerabilities reported npm audit:
uPlot Prototype Pollution vulnerability
Bump uplot from 1.6.28 to 1.6.31
Package               Affected versions              Patched version
uplot (npm)         < 1.6.31                             1.6.31
Versions of the package uplot before 1.6.31 are vulnerable to Prototype Pollution via the uplot.assign function due to missing check if the attribute resolves to the object prototype.
> npm audit
uplot  <1.6.31
Severity: high
uPlot Prototype Pollution vulnerability - https://github.com/advisories/GHSA-34q8-jcq6-mc37
node_modules/uplot
vue-template-compiler vulnerable to client-side Cross-Site Scripting (XSS) - https://github.com/advisories/GHSA-g3ch-rx76-35fx
fix available via `npm …
=> (TEST) [jp-0197] Security update required -- 1 HIGH security vulnerability

composer.lock
Creating a security update for phpoffice/phpspreadsheet
Dependabot is creating a security update to fix [4 Dependabot alerts](https://github.com/bcgov/PECSF/security/dependabot?q=is%3Aopen+package%3Aphpoffice%2Fphpspreadsheet+manifest%3Acomposer.lock+has%3Apatch) on phpoffice/phpspreadsheet in [composer.lock](https://github.com/bcgov/PECSF/blob/-/composer.lock).
Or, manually upgrade phpoffice/phpspreadsheet to version 1.29.2 or later. For example:
"require": {
"phpoffice/phpspreadsheet": "1.29.2"
}
Package
Affected versions                   Patched version                    
phpoffice/phpspreadsheet (Composer)       < 1.29.2                                  1.29.2
=> [jp-0197] Security update required -- 1 HIGH security vulnerability (Composer update phpoffice/phpspreadsheet)

composer.lock
Creating a security update for phpoffice/phpspreadsheet
Dependabot is creating a security update to fix [4 Dependabot alerts](https://github.com/bcgov/PECSF/security/dependabot?q=is%3Aopen+package%3Aphpoffice%2Fphpspreadsheet+manifest%3Acomposer.lock+has%3Apatch) on phpoffice/phpspreadsheet in [composer.lock](https://github.com/bcgov/PECSF/blob/-/composer.lock).
Or, manually upgrade phpoffice/phpspreadsheet to version 1.29.2 or later. For example:
"require": {
"phpoffice/phpspreadsheet": "1.29.2"
}
Package                                                   Affected versions                    Patched version
phpoffice/phpspreadsheet (Composer)  < 1.29.2                                  1.29.2
=> (TEST) [jp-0197] Security update required -- 1 HIGH security vulnerability (Composer update phpoffice/phpspreadsheet)

app/Http/Controllers/BankDepositFormController.php
The eForm - Postal code field had a validation that only accepted postal code in the format X0X 0X0 and would throw an error displaying the format. This validation is not there on the field anymore.
Currently, field accepts any text. For reference check the event pledge with transaction id 293
[ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/_jWVgfflgU6Xfof1dJPjE2UAPOSe?Type=TaskLink&Channel=Link&CreatedTime=638624696021130000)
=> [jp-0196] eForm: Postal code format validation doesn't exit (addition changes)

composer.lock, package-lock.json
Oct 2 - 1 HIGH vulnerabilities reported npm audit:
uPlot Prototype Pollution vulnerability
Bump uplot from 1.6.28 to 1.6.31
Package               Affected versions              Patched version
uplot (npm)         < 1.6.31                             1.6.31
Versions of the package uplot before 1.6.31 are vulnerable to Prototype Pollution via the uplot.assign function due to missing check if the attribute resolves to the object prototype.
> npm audit
uplot  <1.6.31
Severity: high
uPlot Prototype Pollution vulnerability - https://github.com/advisories/GHSA-34q8-jcq6-mc37
node_modules/uplot
vue-template-compiler vulnerable to client-side Cross-Site Scripting (XSS) - https://github.com/advisories/GHSA-g3ch-rx76-35fx
fix available via `npm …
=> (MASTER) [jp-0197] Security update required -- 1 HIGH security vulnerability

app/Console/Commands/ExportDatabaseToBI.php
Scenario
1. Try to re-export all data from Greenfield to BI via ODS 
Table 'bank_deposit_form_organizations' data to BI sent completed on 2024-10-10 10:36:27
=========================================================================
Table 'bank_deposit_form_attachments' Detail to BI (Datawarehouse) start on 2024-10-10 10:36:27
Table Name                   : 'bank_deposit_form_attachments'
The Last send completed time : 2000-01-01
The schedule Job id          : 8135
The command name             : command:ExportDatabaseToBI:bank_deposit_form_attachments
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1085440 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 430
Symfony\Component\ErrorHandler\Error\FatalError …
=> (TEST) [jp-0198] Command: ExportDatabaseToBI encountered an error while re-exporting all data

app/Console/Commands/ExportDatabaseToBI.php
Scenario
1. Try to re-export all data from Greenfield to BI via ODS 
Table 'bank_deposit_form_organizations' data to BI sent completed on 2024-10-10 10:36:27
=========================================================================
Table 'bank_deposit_form_attachments' Detail to BI (Datawarehouse) start on 2024-10-10 10:36:27
Table Name                   : 'bank_deposit_form_attachments'
The Last send completed time : 2000-01-01
The schedule Job id          : 8135
The command name             : command:ExportDatabaseToBI:bank_deposit_form_attachments
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1085440 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 430
Symfony\Component\ErrorHandler\Error\FatalError …
=>  [jp-0198] Command: ExportDatabaseToBI encountered an error while re-exporting all data

app/Console/Kernel.php
=>  [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error (update schedule time)

app/Console/Kernel.php
=> (MASTER) [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error (update schedule time)

app/Console/Commands/ExportDatabaseToBI.php
Scenario
1. Try to re-export all data from Greenfield to BI via ODS 
Table 'bank_deposit_form_organizations' data to BI sent completed on 2024-10-10 10:36:27
=========================================================================
Table 'bank_deposit_form_attachments' Detail to BI (Datawarehouse) start on 2024-10-10 10:36:27
Table Name                   : 'bank_deposit_form_attachments'
The Last send completed time : 2000-01-01
The schedule Job id          : 8135
The command name             : command:ExportDatabaseToBI:bank_deposit_form_attachments
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1085440 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 430
Symfony\Component\ErrorHandler\Error\FatalError …
=> (MASTER) [jp-0198] Command: ExportDatabaseToBI encountered an error while re-exporting all data

resources/views/contact/index.blade.php
Follow the following steps to reproduce:
- Go to the FAQ page
- Expand the first question
- Expand the second question and notice the collapse(-) button for the first question is highlighted with a border for a second on the click event
- Same thing happens if we collapse the buttons 
- Only the current button must highlight
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/OM-K1_9IoEGfG0WxoL9EzmUAMeoK?Type=TaskLink&Channel=Link&CreatedTime=638651268274410000)
=> [jp-0201] FAQ: Expand/collapsing one question highlights the button for the previously expanded/collapsed question

resources/views/contact/index.blade.php
Follow the following steps to reproduce:
- Go to the FAQ page
- Expand the first question
- Expand the second question and notice the collapse(-) button for the first question is highlighted with a border for a second on the click event
- Same thing happens if we collapse the buttons 
- Only the current button must highlight
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/OM-K1_9IoEGfG0WxoL9EzmUAMeoK?Type=TaskLink&Channel=Link&CreatedTime=638651268274410000)
=> (TEST) [jp-0201] FAQ: Expand/collapsing one question highlights the button for the previously expanded/collapsed question

app/Console/Kernel.php
Root Cause:
Important: noticed that the ImportJobData is taking longer (more than 20 mins) in Production, need to adjust the start time of some tasks. 
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/MCn4Pv0iPkypbAL5wgjvP2UAAFHP?Type=TaskLink&Channel=Link&CreatedTime=638658992156280000)
=> [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error & reschedule some tasks

app/Console/Kernel.php
Root Cause:
Important: noticed that the ImportJobData is taking longer (more than 20 mins) in Production, need to adjust the start time of some tasks.
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/MCn4Pv0iPkypbAL5wgjvP2UAAFHP?Type=TaskLink&Channel=Link&CreatedTime=638658992156280000)
=> (TEST) [jp-0200] BI export processes encountered a failure in lower regions due to a 502 Bad Gateway error & reschedule some tasks

app/Http/Controllers/AnnualCampaignController.php
Per system log, there are couple of error were logged
[2024-10-07 11:46:26] prod.ERROR: Attempt to read property "id" on null {"userId":53990,"exception":"[object] (ErrorException(code: 0): Attempt to read property "id" on null at /var/www/html/app/Http/Controllers/AnnualCampaignController.php:526)
[stacktrace]
Root cause
The code doesn't handle the bad data when user directly visit this link
https:///annual-campaign/thank-you without go through the annual campaign wizard
Solution
Enhance the code to handle the bad data without fire the error message on the log file.
[ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/LuyLRuX0ikiN7gPUxJfX-WUAOGCF?Type=TaskLink&Channel=Link&CreatedTime=638664214307470000)
=> (TEST) [jp-0204] Annual Campaign - Attempt to read property 'id' on null

app/Http/Controllers/AnnualCampaignController.php
Per system log, there are couple of error were logged
[2024-10-07 11:46:26] prod.ERROR: Attempt to read property "id" on null {"userId":53990,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /var/www/html/app/Http/Controllers/AnnualCampaignController.php:526)
[stacktrace]
Root cause 
The code doesn't handle the bad data when user directly visit this link 
https://<host>/annual-campaign/thank-you without go through the annual campaign wizard
Solution
Enhance the code to handle the bad data without fire the error message on the log file.
[ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/LuyLRuX0ikiN7gPUxJfX-WUAOGCF?Type=TaskLink&Channel=Link&CreatedTime=638664214307470000)
=> [jp-0204] Annual Campaign -  Attempt to read property 'id' on null

resources/views/contact/index.blade.php
Follow the following steps to reproduce:
- Go to the FAQ page
- Expand the first question
- Expand the second question and notice the collapse(-) button for the first question is highlighted with a border for a second on the click event
- Same thing happens if we collapse the buttons 
- Only the current button must highlight
[Ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/OM-K1_9IoEGfG0WxoL9EzmUAMeoK?Type=TaskLink&Channel=Link&CreatedTime=638651268274410000)
=> (MASTER) [jp-0201] FAQ: Expand/collapsing one question highlights the button for the previously expanded/collapsed question

Dockerfile, composer.json, server_files/php.ini
Dependabot alerts (Github) reported HIGH vulnerabilities. Run composer audit and npm audit, a couple of packages required update:
[ticket](https://planner.cloud.microsoft/bcgov.onmicrosoft.com/Home/Task/PLvpkEk1NkWbbNmfV_P6MWUAANE2?Type=TaskLink&Channel=Link&CreatedTime=638665269908590000)
=> [jp-0205] Security update required -- HIGH security vulnerability (Rollback upgrade PHP 8.3 changes)

Dockerfile, app/Http/Kernel.php, composer.json, composer.lock, package-lock.json, phpunit.xml, server_files/php.ini
=> [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (include all changes for both laravel & php)

app/Console/Commands/ExportDatabaseToBI.php
Issue
The created_at and updated_at timestamp fields in each table on the OpenShift platform store values in UTC time, which are assigned by the system during create or update operations. However, the field used to compare values and determine which data is sent to the BI system is based on the PDT time zone. This creates an 8- or 9-hour time difference. If data changes within this time gap, it is possible that the changes may never be sent to the BI system.
Action
Use the updated_at value from the schedule_job_audits table for comparison, ensuring that the same time zone is used for accurate synchronization
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/s0ZdUDYmzkWIXGYDoggWrGUADtTQ?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (TEST) [jp-0207] Time Zone Discrepancy Between UTC and PDT May Cause Data Sync Issues to BI System

app/Console/Commands/ExportDatabaseToBI.php
Issue
The created_at and updated_at timestamp fields in each table on the OpenShift platform store values in UTC time, which are assigned by the system during create or update operations. However, the field used to compare values and determine which data is sent to the BI system is based on the PDT time zone. This creates an 8- or 9-hour time difference. If data changes within this time gap, it is possible that the changes may never be sent to the BI system.
Action 
Use the updated_at value from the schedule_job_audits table for comparison, ensuring that the same time zone is used for accurate synchronization  
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/s0ZdUDYmzkWIXGYDoggWrGUADtTQ?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> [jp-0207] Time Zone Discrepancy Between UTC and PDT May Cause Data Sync Issues to BI System

app/Console/Commands/ExportDatabaseToBI.php
ROLLBACK LAST CHANGES -- No Issue on OpenShift platform
Issue
The created_at and updated_at timestamp fields in each table on the OpenShift platform store values in UTC time, which are assigned by the system during create or update operations. However, the field used to compare values and determine which data is sent to the BI system is based on the PDT time zone. This creates an 8- or 9-hour time difference. If data changes within this time gap, it is possible that the changes may never be sent to the BI system.
Action
Use the updated_at value from the schedule_job_audits table for comparison, ensuring that the same time zone is used for accurate synchronization
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/s0ZdUDYmzkWIXGYDoggWrGUADtTQ …
=> [jp-0207] Time Zone Discrepancy Between UTC and PDT May Cause Data Sync Issues to BI System (ROLLBACK)

app/Console/Commands/ExportDatabaseToBI.php
ROLLBACK LAST CHANGES -- No Issue on OpenShift platform
Issue
The created_at and updated_at timestamp fields in each table on the OpenShift platform store values in UTC time, which are assigned by the system during create or update operations. However, the field used to compare values and determine which data is sent to the BI system is based on the PDT time zone. This creates an 8- or 9-hour time difference. If data changes within this time gap, it is possible that the changes may never be sent to the BI system.
Action
Use the updated_at value from the schedule_job_audits table for comparison, ensuring that the same time zone is used for accurate synchronization
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/s0ZdUDYmzkWIXGYDoggWrGUADtTQ …
=> [jp-0207] Time Zone Discrepancy Between UTC and PDT May Cause Data Sync Issues to BI System (ROLLBACK last change)

app/Http/Controllers/System/LogViewerController.php, composer.json, composer.lock, tests/Browser/ExampleTest.php, tests/Browser/LoginTest.php, tests/Browser/Pages/HomePage.php, tests/Browser/Pages/Page.php, tests/Browser/console/.gitignore, tests/Browser/screenshots/.gitignore, tests/Browser/source/.gitignore, tests/DuskTestCase.php, tests/Feature/ChallengePageTest.php, tests/Feature/ExampleTest.php, tests/Pest.php, tests/Unit/ExampleTest.php
=> (TEST) [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (installed PEST & DUSK)

composer.lock, package-lock.json
=> [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (UPDATE package league/commonmark)

composer.lock, package-lock.json
=> (TEST) [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (UPDATE package league/commonmark)

database/seeders/DataFixFor_jp_0208_DonateNowPledges_242_243.php
**Issue**
Registration no. 769912676 RR 0001
Registration no. 888441995 RR 0001
**Action:** …
=> (TEST) [jp-0208] Donate Now Pledge 242 and 243-- Correct Calendar Year and Pay deduct date

database/seeders/DataFixFor_jp_0208_DonateNowPledges_242_243.php
**Issue**
Registration no.  769912676 RR 0001
Registration no.  888441995 RR 0001
**Action:**
Please make the adjustment on the backend and update the payroll deduction:  …
=> [jp-0208] Donate Now Pledge 242 and 243-- Correct Calendar Year and Pay deduct date

database/seeders/DataFixFor_jp_0208_DonateNowPledges_242_243.php
**Issue**
Registration no. 769912676 RR 0001
Registration no. 888441995 RR 0001
**Action:** …
=> (MASTER) [jp-0208] Donate Now Pledge 242 and 243-- Correct Calendar Year and Pay deduct date

.github/workflows/deploy.yml
Issue:
Failed to deploy changes on DEV, TEST and Production with the following error message
Run oc login --token=*** --server=https://api.silver.devops.gov.bc.ca:6443/
10 /home/runner/work/_temp/deaa6f60-5e9c-4171-9e95-e8dec1c8239c.sh: line 1: oc: command not found
11 Error: Process completed with exit code 127.
Action:
If you update the workflow “runs-on” image to “ubuntu-22.04” or add the additional installation step that Kunal shared it should get the deployment working again. 
In this case, the file is: /.github/workflows/deploy.yml 
You can just change: 
runs-on: ubuntu-latest 
to: 
runs-on: ubuntu-22.04 
https://github.com/bcgov/performance/blob/d96c86a9a00f944c08afafecb399e1493e8ca432/.github/workflows/deploy.yml#L30
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcak …
=> [jp-0208] Deployment error on openshift - 'oc: command not found'

.github/workflows/deploy.yml
Issue
Registration no. 769912676 RR 0001
Registration no. 888441995 RR 0001
Action: …
=> [jp-0208] Donate Now Pledge 242 and 243-- Correct Calendar Year and Pay deduct date (Merge branch 'jp-0209' into jp-0208)

.github/workflows/deploy.yml
Issue
Registration no. 769912676 RR 0001
Registration no. 888441995 RR 0001
Action: …
=> (TEST) [jp-0208] Donate Now Pledge 242 and 243-- Correct Calendar Year and Pay deduct date (Merge branch 'jp-0209' into jp-0208)

.github/workflows/deploy.yml
Issue:
Failed to deploy changes on DEV, TEST and Production with the following error message
Run oc login --token=*** --server=https://api.silver.devops.gov.bc.ca:6443/
10 /home/runner/work/_temp/deaa6f60-5e9c-4171-9e95-e8dec1c8239c.sh: line 1: oc: command not found
11 Error: Process completed with exit code 127.
Action:
If you update the workflow “runs-on” image to “ubuntu-22.04” or add the additional installation step that Kunal shared it should get the deployment working again.
In this case, the file is: /.github/workflows/deploy.yml
You can just change:
runs-on: ubuntu-latest
to:
runs-on: ubuntu-22.04
https://github.com/bcgov/performance/blob/d96c86a9a00f944c08afafecb399e1493e8ca432/.github/workflows/deploy.yml#L30
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2 …
=> (MASTER) [jp-0209] Deployment error on openshift - 'oc: command not found'

database/seeders/DataFixFor_jp_0210_DonateNowPledges_245_246.php
Issue
Both Donate Now (245 and 246) for Phelan,Michelle (EE#168370) in PeopleSoft were created for the 2024 calendar year, with the pay date of December 14, 2024. However, it is not possible to backdate to December 2024 in Greenfield.
$75 one time to
KAMLOOPS SEXUAL ASSAULT COUNSELLING CENTRE SOCIETY
$75 one time to
BRITISH COLUMBIA SOCIETY FOR THE PREVENTION OF CRUELTY TO ANIMALS
Action:
Both Transaction ID: 245 and 246
Please make the adjustment on the backend and update the payroll deduction: 
payroll deduction date : Nov 14, 2024
[ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakW …
=> [jp-0210] Donate Now Pledge 245 and 246-- Correct Calendar Year and Pay deduct date

database/seeders/DataFixFor_jp_0210_DonateNowPledges_245_246.php
Issue
Both Donate Now (245 and 246) for Phelan,Michelle (EE#168370) in PeopleSoft were created for the 2024 calendar year, with the pay date of December 14, 2024. However, it is not possible to backdate to December 2024 in Greenfield.
$75 one time to
KAMLOOPS SEXUAL ASSAULT COUNSELLING CENTRE SOCIETY
$75 one time to
BRITISH COLUMBIA SOCIETY FOR THE PREVENTION OF CRUELTY TO ANIMALS
Action:
Both Transaction ID: 245 and 246
payroll deduction date : Nov 14, 2024
[ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu …
=> (TEST) [jp-0210] Donate Now Pledge 245 and 246-- Correct Calendar Year and Pay deduct date

database/seeders/DataFixFor_jp_0210_DonateNowPledges_245_246.php
Issue
Both Donate Now (245 and 246) for Phelan,Michelle (EE#168370) in PeopleSoft were created for the 2024 calendar year, with the pay date of December 14, 2024. However, it is not possible to backdate to December 2024 in Greenfield.
$75 one time to
KAMLOOPS SEXUAL ASSAULT COUNSELLING CENTRE SOCIETY
$75 one time to
BRITISH COLUMBIA SOCIETY FOR THE PREVENTION OF CRUELTY TO ANIMALS
Action:
Both Transaction ID: 245 and 246
Please make the adjustment on the backend and update the payroll deduction: 
payroll deduction date : Nov 14, 2024
[ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakW …
=> (MASTER) [jp-0210] Donate Now Pledge 245 and 246-- Correct Calendar Year and Pay deduct date

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST) [jp-0211] Improve the Task Scheduling Status Monitoring for lower regions

app/Http/Controllers/Api/SystemStatusController.php
=>  [jp-0211] Improve the Task Scheduling Status Monitoring for lower regions (Additional changes)

app/Http/Controllers/Api/SystemStatusController.php
=>  [jp-0211] Improve the Task Scheduling Status Monitoring for lower regions (Additional 2nd changes)

app/Http/Controllers/Api/SystemStatusController.php
=> (TEST)  [jp-0211] Improve the Task Scheduling Status Monitoring for lower regions (Additional changes)

composer.lock, database/migrations/2024_04_30_083317_add_region_in_volunteer_profiles_table.php, package-lock.json
=> [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (UPDATE package phpoffice/phpspreadsheet)

composer.lock, database/migrations/2024_04_30_083317_add_region_in_volunteer_profiles_table.php, package-lock.json
=> (TEST) [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (UPDATE package phpoffice/phpspreadsheet)

openshift/app/pecsf-dc.yml
Removed restartPolicy due to deprecation for non-init containers in OpenShift 4.16
=> Update pecsf-dc.yml to remove deprecated restartPolicy

openshift/app/pecsf-dc.yml
Removed restartPolicy due to deprecation for non-init containers in OpenShift 4.16
=> (TEST) Update pecsf-dc.yml to remove deprecated restartPolicy

database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "136016"
=> [jp-0212] Non-gov Pledge Updates (BCS 080964 / LA135016 )

database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "136016"
=> (TEST) [jp-0212] Non-gov Pledge Updates (BCS 080964 / LA135016 )

database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "136016"
=> [jp-0212] Non-gov Pledge Updates (BCS 080964 / LA135016) additional change

database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "136016"
=> (TEST) [jp-0212] Non-gov Pledge Updates (BCS 080964 / LA135016) additional change

database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "135016"
=> (TEST) [jp-0212] Non-gov Pledge Updates (BCS 081027/ LA135016) 2nd revised 

resources/views/volunteering/partials/learn-more-modal.blade.php
At the end of the "Learn" tile in the volunteering section of the application on slide 8.  The text in the bottom right corner of the slide "I'm ready to volunteer!" when selected it goes back to the home page.  During registration (June to September) this would take you to the register or renew function on the home page.  Outside of registration, it should have a static message and refer volunteers to PECSF.  If not that then "hide" the button.  
Action 
Update label on the button
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/M-rMRBHNckqtUGHwOlADW2UAJLm-?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> [jp-0214] Volunteering - Learn tile Improvement

resources/views/volunteering/partials/learn-more-modal.blade.php
At the end of the "Learn" tile in the volunteering section of the application on slide 8. The text in the bottom right corner of the slide "I'm ready to volunteer!" when selected it goes back to the home page. During registration (June to September) this would take you to the register or renew function on the home page. Outside of registration, it should have a static message and refer volunteers to PECSF. If not that then "hide" the button.
Action
Update label on the button
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/M-rMRBHNckqtUGHwOlADW2UAJLm-?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (TEST) [jp-0214] Volunteering - Learn tile Improvement

app/Http/Controllers/Api/SystemStatusController.php
=> (MASTER) [jp-0211] Improve the Task Scheduling Status Monitoring for lower regions

database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php
Employee PECSF ID should be "135016"
=> (MASTER) [jp-0212] Non-gov Pledge Updates (BCS 081027/ LA135016) 

openshift/app/pecsf-dc.yml
**Issue**
Encountered the following error message when deploying project on openshit
The DeploymentConfig "pecsf-new" is invalid: spec.template.spec.containers[0].restartPolicy: Forbidden: may not be set for non-init containers
**Action Required**
Removed restartPolicy due to deprecation for non-init containers in OpenShift 4.16
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/InIDmG0_vk2vFLR9wnPid2UAFW6P?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (MASTER) [jp-0213] Update pecsf-dc.yml to remove deprecated restartPolicy

.gitignore, app/Http/Controllers/Api/SystemStatusController.php, app/Providers/AppServiceProvider.php, composer.lock, database/factories/BusinessUnitFactory.php, database/factories/OrganizationFactory.php, database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php, database/seeders/UserTableSeeder.php, openshift/app/pecsf-dc.yml, phpunit.dusk.xml, tests/Browser/BusinessUnitTest.php, tests/Browser/ExampleTest.php, tests/Browser/LoginTest.php, tests/Browser/OrganizationTest.php
=> [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (Update Dusk Test Cases)

.gitignore, app/Http/Controllers/Api/SystemStatusController.php, app/Providers/AppServiceProvider.php, composer.lock, database/factories/BusinessUnitFactory.php, database/factories/OrganizationFactory.php, database/seeders/DataFixFor_jp_0212_CampaignPledge_5981_12581.php, database/seeders/UserTableSeeder.php, openshift/app/pecsf-dc.yml, phpunit.dusk.xml, tests/Browser/BusinessUnitTest.php, tests/Browser/ExampleTest.php, tests/Browser/LoginTest.php, tests/Browser/OrganizationTest.php
=> (TEST) [upgrade_10_to_11] Dev - Upgrade Laravel version 10 to 11 and PHP version 8.1 to 8.3 (Update Dusk Test Cases)

resources/views/volunteering/partials/learn-more-modal.blade.php
At the end of the "Learn" tile in the volunteering section of the application on slide 8. The text in the bottom right corner of the slide "I'm ready to volunteer!" when selected it goes back to the home page. During registration (June to September) this would take you to the register or renew function on the home page. Outside of registration, it should have a static message and refer volunteers to PECSF. If not that then "hide" the button.
Action
Update label on the button
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/M-rMRBHNckqtUGHwOlADW2UAJLm-?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (MASTER) [jp-0214] Volunteering - Learn tile Improvement 

Dockerfile
To add a flag --no-check-certificate on wget command to resolve 
=> Fix error Resolving packages.sury.org (packages.sury.org)... failed: Temporary failure in name resolution.

Dockerfile
=> Fix error Resolving packages.sury.org (packages.sury.org)... failed: …Temporary failure in name resolution.(additional change

Dockerfile
Issue
Error when deployment package on Production region
[2/2] STEP 9/33: RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
/etc/apt/trusted.gpg.d/php.gpg: Scheme missing.
--2025-02-08 23:44:29--  https://packages.sury.org/php/apt.gpg
error: build error: building at STEP "RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg": while running runtime: exit status 4
Action
Resolving packages.sury.org …
=> jp-0217 Fix error Resolving packages.sury.org (packages.sury.org)…failed: Temporary failure in name resolution.(comment the line in docker file)

Dockerfile
Issue
Error when deployment package on Production region
[2/2] STEP 9/33: RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
/etc/apt/trusted.gpg.d/php.gpg: Scheme missing.
--2025-02-08 23:44:29-- https://packages.sury.org/php/apt.gpg
error: build error: building at STEP "RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg": while running runtime: exit status 4
Action
Resolving packages.sury.org …
=> (TEST) [jp-0217] Fix Production Deployment error -- unable to resolve host address 'packages.sury.org' 

Dockerfile
Issue
Error when deployment package on Production region
[2/2] STEP 9/33: RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
/etc/apt/trusted.gpg.d/php.gpg: Scheme missing.
--2025-02-08 23:44:29-- https://packages.sury.org/php/apt.gpg
error: build error: building at STEP "RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg": while running runtime: exit status 4
Action
Resolving packages.sury.org …
=> (MASTER) [jp-0217] Fix Production Deployment error -- unable to resolve host address 'packages.sury.org' 

Dockerfile
Issue
Error when deployment package on Production region
[2/2] STEP 9/33: RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
/etc/apt/trusted.gpg.d/php.gpg: Scheme missing.
--2025-02-08 23:44:29-- https://packages.sury.org/php/apt.gpg
error: build error: building at STEP "RUN wget -O --no-check-certificate /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg": while running runtime: exit status 4
Action
Resolving packages.sury.org …
=> (MASTER) jp-0217 Fix error Resolving packages.sury.org (packages.sury.org)... failed: Temporary failure in name resolution.(use 8.1-apache instead)

app/Models/EmployeeJob.php
Issue: Incorrect figure on Years of BC Government Service under Volunteer Profile Page
For example: Employee A on Volunteer Profile page
-18.712328767123
Year of BC Government Service
[ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/plCCgcTSRk2RHFdy-8WAZGUAHVUa?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> [jp-0219] Volunteer Profile -- Incorrect figure on Years of BC Government Service

app/Models/EmployeeJob.php
Issue: Incorrect figure on Years of BC Government Service under Volunteer Profile Page
For example: Employee A on Volunteer Profile page
-18.712328767123
Year of BC Government Service
[ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/plCCgcTSRk2RHFdy-8WAZGUAHVUa?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (TEST) [jp-0219] Volunteer Profile -- Incorrect figure on Years of BC Government Service

app/Models/EmployeeJob.php
Issue: Incorrect figure on Years of BC Government Service under Volunteer Profile Page
For example: Employee A on Volunteer Profile page
-18.712328767123
Year of BC Government Service
[ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/plCCgcTSRk2RHFdy-8WAZGUAHVUa?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (MASTER) [jp-0219] [jp-0219] Volunteer Profile -- Incorrect figure on Years of BC Government Service

app/Http/Controllers/Auth/KeycloakLoginController.php
=> (TEST) [jp-0222] Keycloak 26 upgrade -- legacy redirect_url parameter is no longer supported

app/Http/Controllers/Auth/KeycloakLoginController.php
=> (TEST) [jp-0222] Keycloak 26 upgrade -- legacy redirect_url parameter is no longer supported (solve invalid redirect uri issue)

app/Http/Controllers/Auth/KeycloakLoginController.php
=> (TEST) [jp-0222] Keycloak 26 upgrade -- legacy redirect_url parameter is no longer supported (Invalid redirect uri)

app/Listeners/LogFailedLogin.php, app/Providers/EventServiceProvider.php
Enhancement
Logging failed login attempts helps enhance security by detecting potential brute force attacks and unauthorized access attempts, while also improving troubleshooting, user support, and compliance with security standards. It provides an audit trail for monitoring suspicious activity and helps refine security measures like rate limiting and account lockouts.
In Laravel 11, to log a message when a user fails to log in, you can make use of the built-in authentication events and logging capabilities.
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/qLQvnrn-AESkXa02kIJ4-2UAIYg8?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> [jp-0223] Logging failed login attempts

app/Http/Controllers/Auth/KeycloakLoginController.php
=> (MASTER) [jp-0222] Keycloak 26 upgrade -- legacy redirect_url parameter is no longer supported

app/Listeners/LogFailedLogin.php, app/Providers/EventServiceProvider.php
Enhancement
Logging failed login attempts helps enhance security by detecting potential brute force attacks and unauthorized access attempts, while also improving troubleshooting, user support, and compliance with security standards. It provides an audit trail for monitoring suspicious activity and helps refine security measures like rate limiting and account lockouts.
In Laravel 11, to log a message when a user fails to log in, you can make use of the built-in authentication events and logging capabilities.
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/qLQvnrn-AESkXa02kIJ4-2UAIYg8?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (MASTER) [jp-0223] Logging failed login attempts

app/Console/Kernel.php
**Issue**
On Production, the ImportEmployeeJob wasn't triggered couple of time without any issue. would like to try difference time to see any improvement. 
"name": "command:ImportEmployeeJob",
"cron": "0 4 * * 1-5",
"previous schedule time": "2025-03-25 04:00:00",
"last completed start time": "2025-03-24 04:00:27",
"last completed end time": "2025-03-24 04:10:58",
"next schedule time": "2025-03-26 04:00:00"
**Action**
Reschedule ImportEmployeeJob from 4:00am to 4:05am
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/JGj5EDIuqEu_kasUhEOuMWUAAHki?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (MASTER) [jp-0224]  Reschedule ImportEmployeeJob from 4:00am to 4:05am

app/Http/Controllers/System/UserActivityController.php, resources/views/system-security/user-activity/transaction_timings.blade.php
Need to create an area in the administrative side of the PECSF application to view donor and volunteer analytics.
For example:
How many users access the application?
How many users set up a pledge?
How long did it take to set up a donation?
How many users visit the volunteering section?
What is the traffic on each volunteering page?
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/YduahGL_R02M1OR4rYu4E2UAOwGI?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (TEST) [jp-0221] Donor and Volunteer Analytics

Dockerfile, app/Console/Kernel.php, database/migrations/2025_04_28_150431_create_cache_table.php, server_files/laravel-schedule.sh
To replace OpenShift cronjob by using Laravel Task Scheduling for running schedule on servers.
[Ticket ](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/DxHPN5m3bEyKbN4SDMhG2GUALFgk?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> [jp-0225] Running Laravel schedule:run Across Multiple Pods Using the Native onOneServer() Method

app/Console/Kernel.php
To replace OpenShift cronjob by using Laravel Task Scheduling for running schedule on servers.
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/DxHPN5m3bEyKbN4SDMhG2GUALFgk?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> [jp-0225] Running Laravel schedule:run Across Multiple Pods Using the Native onOneServer() Method 

openshift/app/pecsf-dc.yml
**Issue**
Platform Services team
We've noticed that there are frequent cronjobs in your project set that run every 5 min and use a PVC. This is using a lot of resources from Trident (the storage service on OpenShift) to mount/unmount these volumes over and over. As a result, this is causing pods in the Silver cluster to take a while to start as they have to wait for Trident to finish a long queue of jobs before getting to them.
To sustain the normal functioning of Trident on Silver, we ask you to change the frequent cronjobs with PVC mounts to a deployment instead. This will not only benefit all the teams on the platform, but also help you to reduce the overhead resource consumption of frequent pod restarts in your namespace.
Following is the list of cronjobs that we highly recommend you …
=> [jp-0225] Running Laravel schedule:run Across Multiple Pods Using the Native onOneServer() Method (update pecsf-dc.yml)

Dockerfile, app/Console/Kernel.php, database/migrations/2025_04_28_150431_create_cache_table.php, openshift/app/pecsf-dc.yml, server_files/laravel-schedule.sh
**Issue**
Platform Services team
We've noticed that there are frequent cronjobs in your project set that run every 5 min and use a PVC. This is using a lot of resources from Trident (the storage service on OpenShift) to mount/unmount these volumes over and over. As a result, this is causing pods in the Silver cluster to take a while to start as they have to wait for Trident to finish a long queue of jobs before getting to them.
To sustain the normal functioning of Trident on Silver, we ask you to change the frequent cronjobs with PVC mounts to a deployment instead. This will not only benefit all the teams on the platform, but also help you to reduce the overhead resource consumption of frequent pod restarts in your namespace.
Following is the list of cronjobs that we highly recommend you …
=> (TEST) [jp-0225] Running Laravel schedule:run Across Multiple Pods Using the Native onOneServer() Method

app/Console/Kernel.php
**Issue**
Platform Services team
We've noticed that there are frequent cronjobs in your project set that run every 5 min and use a PVC. This is using a lot of resources from Trident (the storage service on OpenShift) to mount/unmount these volumes over and over. As a result, this is causing pods in the Silver cluster to take a while to start as they have to wait for Trident to finish a long queue of jobs before getting to them.
To sustain the normal functioning of Trident on Silver, we ask you to change the frequent cronjobs with PVC mounts to a deployment instead. This will not only benefit all the teams on the platform, but also help you to reduce the overhead resource consumption of frequent pod restarts in your namespace.
Following is the list of cronjobs that we highly recommend you …
=> [jp-0225] Running Laravel schedule:run Across Multiple Pods Using the Native onOneServer() Method (now set to 15 mins on the testing task)

app/Console/Kernel.php
**Issue**
Platform Services team
We've noticed that there are frequent cronjobs in your project set that run every 5 min and use a PVC. This is using a lot of resources from Trident (the storage service on OpenShift) to mount/unmount these volumes over and over. As a result, this is causing pods in the Silver cluster to take a while to start as they have to wait for Trident to finish a long queue of jobs before getting to them.
To sustain the normal functioning of Trident on Silver, we ask you to change the frequent cronjobs with PVC mounts to a deployment instead. This will not only benefit all the teams on the platform, but also help you to reduce the overhead resource consumption of frequent pod restarts in your namespace.
Following is the list of cronjobs that we highly recommend you …
=> (TEST) [jp-0225] Running Laravel schedule:run Across Multiple Pods Using the Native onOneServer() Method (adjust the schedule time)

Dockerfile
**Issue**
**Action**
_Workaround_
If this is during a Dockerfile RUN step (e.g. apt-get install), try adding:
RUN …
=> (TEST) [jp-0230] To avoid the Intermittent error 'wget: unable to resolve host address' during the deployment

Dockerfile
**Issue**
**Action**
_Workaround_
If this is during a Dockerfile RUN step (e.g. apt-get install), try adding:
RUN …
=> [jp-0230] To avoid the Intermittent error 'wget: unable to resolve host address' during the deployment

app/Imports/CharitiesImport.php
**As a FMO administrator processing charity information,**
I want the system to automatically clear the "Use Alternative Address" flag when the Original Mailing Address and Alternative Address fields contain identical information,
So that we don't override freshly updated CRA addresses with obsolete ones, reducing returned mail, reprocessing time, and improving charity experience.
(it is expected that some cheques will still be returned)
**Rational:**
To help reduce incorrect address cheque returns,
Proposed change: If the Original Mailing Address and the Alternative Address fields are identical, automatically clear the Use Alternative Address flag.
Benefit: This prevents us from overriding a freshly updated CRA address with an obsolete one that was entered earlier, without requiring …
=> [jp-0226] CRA Charity List upload - Alternative Address

app/Imports/CharitiesImport.php
**As a FMO administrator processing charity information,**
I want the system to automatically clear the "Use Alternative Address" flag when the Original Mailing Address and Alternative Address fields contain identical information,
So that we don't override freshly updated CRA addresses with obsolete ones, reducing returned mail, reprocessing time, and improving charity experience.
(it is expected that some cheques will still be returned)
**Rational:**
To help reduce incorrect address cheque returns,
Proposed change: If the Original Mailing Address and the Alternative Address fields are identical, automatically clear the Use Alternative Address flag.
Benefit: This prevents us from overriding a freshly updated CRA address with an obsolete one that was entered earlier, without requiring …
=> (TEST) [jp-0226] CRA Charity List upload - Alternative Address

Dockerfile
**Issue**
**Action**
_Workaround_
1. If this is during a Dockerfile RUN step (e.g. apt-get install), try adding: …
=> (TEST) [jp-0230] To avoid the Intermittent error 'wget: unable to resolve host address' during the deployment (Forces wget to use IPv4.) 

Dockerfile
**Issue**
**Action**
_Workaround_
1. If this is during a Dockerfile RUN step (e.g. apt-get install), try adding: …
=> [jp-0230] To avoid the Intermittent error 'wget: unable to resolve host address' during the deployment (Forces wget to use IPv4.)

Dockerfile
**Issue**
**Action**
_Workaround_
1. If this is during a Dockerfile RUN step (e.g. apt-get install), try adding: …
=>  [jp-0230] To avoid the Intermittent error 'wget: unable to resolve host address' during the deployment (Approach 3: Try using curl instead of wget)

database/seeders/DataFixFor_jp_0232_Pledge_12799.php
Bi weekly pledge for E# 136279 showing up on 40D report but was not in PECSF application ("no pledge")
June 5 - Ashley and Job have added pledge in system but it will only allow us to enter as 2026.
James can you please adjust transaction ID 12799 so it reflects 2025?
This would need to be fixed ahead of the next cheque run. Please let us know if you need more info!
[Ticket](https://planner.cloud.microsoft/webui/v1/plan/ZOb3bFXcakWu8Gl2Zd_PuGUAFIJt/view/board/task/2tlncXSSskqGmx17YRwuoGUAMHQP?tid=6fdb5200-3d0d-4a8a-b036-d3685e359adc)
=> (MASTER) [jp-0232] Backdate deduction for Transaction ID 12799 to 2025

app/Console/Kernel.php
Alert: "PECSF [prod] -- The Process (13778 - command:ImportEmployeeJob) was failed to complete."
Process ID : 13778
Process Name : command:ImportEmployeeJob
Failed at : 2025-08-05 04:07:58
The process was failed with the following error message:
cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://analytics-api.psa.gov.bc.ca/apiserver/api.rsc/Datamart_PECSF_peoplesoft_employee_demographic?$top=1000&$skip=26000&$filter=&$orderBy=EMPLID%20asc,%20EMPL_RCD%20asc,%20EFFDT%20desc,%20EFFSEQ%20desc,%20date_updated%20desc
**Root Cause:** Timeout errors are occurring on both our side and the BI side. Analysis shows heavy API usage from other consumers between 3:00-4:00 AM, potentially compounded by …
=> (TEST) [jp-0238b] Schedule adjustment required for Job 'ImportEmployeeJob' due to peak traffic

app/Exports/DonationDataReportExport.php
**Issue Description**
Error encountered when executing "Export Donation Data" function in Test region:
ErrorException: Attempt to read property "name" on null in /var/www/html/app/Exports/DonationDataReportExport.php:115
**Root Cause Analysis**
The error is caused by data integrity issues resulting from:
Data restoration from Production backup to Test environment
Cleanup operations performed on the process history table
Missing or null references in the process history data that the export function expects to be present
**Proposed Solution**
Implement a null-check validation before accessing the "name" property in the DonationDataReportExport.php file at line 115. This will involve:
1. Adding conditional logic to verify that the process history object exists and is not null
2. …
=> [jp-0242] Error on DonationDataReportExport process (additional change)

app/Exports/DonationDataReportExport.php
**Issue Description**
Error encountered when executing "Export Donation Data" function in Test region:
ErrorException: Attempt to read property "name" on null in /var/www/html/app/Exports/DonationDataReportExport.php:115
**Root Cause Analysis**
The error is caused by data integrity issues resulting from:
Data restoration from Production backup to Test environment
Cleanup operations performed on the process history table
Missing or null references in the process history data that the export function expects to be present
**Proposed Solution**
Implement a null-check validation before accessing the "name" property in the DonationDataReportExport.php file at line 115. This will involve:
1. Adding conditional logic to verify that the process history object exists and is not null
2. …
=> (TEST) [jp-0242] Error on DonationDataReportExport process (additional change)

composer.lock, package-lock.json, tests/Feature/ChallengePageTest.php
1. sha.js is missing type checks leading to hash rewind and passing on crafted data
Package                             Affected versions       Patched version
sha.js (npm)                  <= 2.4.11                     2.4.12
This is the same as GHSA-cpq7-6gpm-g9rc but just for sha.js, as it has its own implementation.
Missing input type checks can allow types other than a well-formed Buffer or string,
resulting in invalid values, hanging and rewinding the hash state (including turning a tagged hash into an untagged hash),
or other generally undefined behaviour.
2. PhpSpreadsheet vulnerable to SSRF when reading and displaying a processed HTML document in the browser
Package                                                     Affected versions             Patched …
=> (MASTER) [jp-0241] Security update required -- 1 CRITICAL and 1 high vulnerability

app/Exports/DonationDataReportExport.php
**Issue Description**
Error encountered when executing "Export Donation Data" function in Test region:
ErrorException: Attempt to read property "name" on null in /var/www/html/app/Exports/DonationDataReportExport.php:115
**Root Cause Analysis**
The error is caused by data integrity issues resulting from:
Data restoration from Production backup to Test environment
Cleanup operations performed on the process history table
Missing or null references in the process history data that the export function expects to be present
**Proposed Solution**
Implement a null-check validation before accessing the "name" property in the DonationDataReportExport.php file at line 115. This will involve:
1. Adding conditional logic to verify that the process history object exists and is not null
2. …
=> (MASTER) [jp-0242] Error on DonationDataReportExport process 
